fix(core): ignore @nrwl packages from move and remove generators
nrwl/nx pull request #10063
Opened 2022-04-29 13:35 UTC by mandarini

# # Current Behavior
For any project where this combination is the following:
```
    "storybook": {
         "executor": "@nrwl/storybook:storybook",
```
That is, `@nrwl/*` package name is the same as a `target` name.

The result is that when a workspace has a project named `storybook`, and another project that uses `@nrwl/storybook`, if a user tries to `move` or `remove` the `storybook` project the following will happen:

### In the case of `move`

The `storybook` target executors across the workspace will be changed. If the new project name is, for example, `new-name` the changes will be:

```
-      "executor": "@nrwl/storybook:storybook",
+      "executor": "@nrwl/new-name:storybook",
```

### In the case of `remove`

Nx will get confused, and it will think that the project `storybook` is used by other projects in the workspace, whereas the other projects would just be using `@nrwl/storybook`, resulting in the following error, and not letting the user remove the `storybook` project:

```
$ nx g @nrwl/workspace:remove jest
storybook is still targeted by some projects:

"storybook:storybook" is used by "some-other-project"
```

## Expected Behavior
`move` and `remove` generators should work, regardless of the name of the project.

## Thoughts
My first thought (and I've had this thought in the past, as well) was to protect some keywords from being used as project names. However, this may create some negative experience to our users, who are used to naming projects `storybook` however confusing that may be in some cases (to Nx).

2022-04-29 14:04 UTC, AgentEnder requested changes
I think this should probably be generalized a bit more, considering the same match ups could happen with community plugin executors or local plugin executors. 

For example, imagine nx-dotnet had an executor: `@nx-dotnet/core:test`. Projects named test would then exhibit this same behavior, even after the fix.

Additionally, I think this may be able to be simplified a bit because of this. Instead of updating the regex, we could do something like
```typescript
  let {executor, ...configuration} = targetConfig
  const configString = JSON.stringify(targetConfig)
  
  // In a local plugin, if it uses an executor provided by
  // itself, that executor would still need to be updated
  // if the import path from the plugin changed
  if (executorIsFromThisPackage) {
    executor = executor.replace(/.*:/, newImportPath)
  }

  configString = configString.replace(
    new RegExp(`${schema.projectName}:`, 'g'),
      `${schema.newProjectName}:`
     )
  );
  projectConfig.targets[target] = {
    executor,
    ...JSON.parse(configString)
  }
```

2022-04-29 15:30 UTC, jaysoo approved these changes

2022-04-29 15:33 UTC, nartc approved these changes

2022-04-29 15:58 UTC, AgentEnder requested changes
Small nit, otherwise lgtm

2022-04-29 15:58 UTC, AgentEnder commented on packages/workspace/src/generators/move/lib/update-build-targets.ts
> +          const [project, target, configuration] = value.split(':');
There's a util for this, I think it's called parseTargetString

2022-04-29 15:58 UTC, AgentEnder commented on packages/workspace/src/generators/remove/lib/check-targets.ts
> +function checkIfProjectIsUsed(
Out of scope of this PR, but we should update this to check if it's a local plugin in use

2022-04-29 16:15 UTC, merged

2022-05-06 12:55 UTC, gioragutt commented
Thanks @mandarini for taking care of that, I stumbled upon it a couple of weeks ago, glad to see people taking action and fixing it ❤️