fix(format.ts): add filtering of deleted files
nrwl/nx pull request #1087
Opened 2019-02-17 20:22 UTC by ZachJW34

Formatting of uncommitted files errors when the only change is the deletion of files. Checking if
the file exists before writing solves this issue.

#1036

_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-pr)_

## Current Behavior (This is the behavior we have today, before the PR is merged)

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

## Issue

2019-02-17 20:43 UTC, ZachJW34 commented
I also considered adding the paramater `--diff-filter=d` to the git command `getUncommittedFiles()` (`packages/schematics/src/command-line/shared.ts`) but I didn't want to cause issues if their was a need to obtain deleted files from the diff. A flag could be created to choose between obtaining all file changes or only non-deleted file changes, so let me know if this is a solution that would be cleaner rather than manually checking if `fileExists()`.

2019-02-18 17:06 UTC, FrozenPandaz reviewed
Can you also change your commit to something like:

`fix(nx): filter non-existing files during format`

2019-02-18 17:06 UTC, FrozenPandaz commented on packages/schematics/src/command-line/format.ts
> +    let patterns = files.filter(f =>
You can chain the `filter`s instead of creating an otherwise unused variable.

2019-02-18 17:06 UTC, FrozenPandaz requested changes
Thanks for the contribution!

Only have some minor changes to request

2019-02-18 20:44 UTC, ZachJW34 commented
@FrozenPandaz Updated!

2019-02-19 17:40 UTC, FrozenPandaz commented
Thank you!

LGTM!

2019-02-19 17:40 UTC, merged