fix(nx): Ignore the debugger attached message in node
nrwl/nx pull request #11131
Opened 2022-07-13 16:28 UTC by jean343

## Current Behavior
Node will print out `Debugger attached.` to stderr when a debugger is attached, thus marking the build as failed.

## Expected Behavior
The message should be ignored.

## Related Issue(s)

Fixes #11130

2022-07-13 18:59 UTC, AgentEnder commented on packages/js/src/utils/swc/compile-swc.ts
>          process.stderr.write(err);
We should still log the Debugger attached message, so it should probably be reordered:

```suggestion
        process.stderr.write(err);
        if(err.includes("Debugger attached.")) {
          return;
        }
```

2022-07-13 18:59 UTC, AgentEnder requested changes
Looks good, just a minor change:

2022-07-13 19:01 UTC, jean343 commented
> Looks good, just a minor change:

Love it, thank you!

2022-07-23 02:42 UTC, nartc commented
@jean343 can you rebase and push real quick?

2022-07-23 03:08 UTC, jean343 commented
@nartc I have rebased the branch and formatted the source code appropriately.
cheers

2022-07-23 03:21 UTC, nartc commented
@jean343 thank you. I'll check the failed CI after it finishes running.

2022-08-02 02:31 UTC, merged