fix(testing): handle more complex projects for react component testing
nrwl/nx pull request #11725
Opened 2022-08-25 19:18 UTC by barbados-clemens

This change will now use `@nrwl/web:webpack` utilities and requires a build target to be provided in the `@nrwl/cypress:cypress` executor options. Using `nxComponentTestingPreset` will load the `@nrwl/web:webpack` executor options from the provided build target in order to create the webpack configuration for cypress dev server. As of right now, if it's unable to build the webpack configuration, it will fallback to the default configuration that was there before. Which will handle simple cases/can be extended as needed.

When generating a new component testing configuration, a new option for --build-target is available. this allows for manually specifying the target to use for component testing. If one isn't provided the project graph is used to try to find an existing valid build configuration by looking for parent projects that use `@nrwl/web:webpack` (i.e. a React App)

## Potential issues
if working in a workspace without a project using `@nrwl/web:webpack` i.e. a publishable react lib without apps. 2 options.
1. Allow for `@nrwl/cypress:cypress` to accept a full configuration for `@nrwl/web:webpack` / make a new component testing executor that has these options (might not be ideal as new frameworks might have different needs i.e. angular)
2. generate a target that has uses `@nrwl/web:webpack` and pass to the component testing options. i.e. make a dummy app or add a custom `ct-build` target with `@nrwl/web:webpack` in the current project.

## Current Behavior
the default webpack configuration used for cypress component testing (in react) fails when having more "complex" set ups i.e. tailwinds via setup-tailwinds generator.

## Expected Behavior
things automagically work.

## Related Issue(s)

Fixes #11372 #11509

2022-08-29 20:24 UTC, barbados-clemens commented on packages/react/plugins/component-testing/index.ts
> +  options.compiler = options.compiler || 'babel';
use `||=`

2022-08-29 20:24 UTC, barbados-clemens commented on packages/react/plugins/component-testing/index.ts
> +  options.compiler = options.compiler || 'babel';
or `??=`

2022-08-29 20:24 UTC, barbados-clemens commented on packages/react/plugins/component-testing/index.ts
> +    : target.options;
readTargetOptions() will need to build an executor context :(

2022-08-29 20:24 UTC, barbados-clemens commented on packages/react/plugins/component-testing/index.ts
> +  ).replace(extname(configPath), '');
what if dir has `.` in it?

2022-08-29 20:24 UTC, barbados-clemens commented on packages/react/plugins/component-testing/index.ts
> +    const mergedOptions = targets[targetName].defaultConfiguration
look at readTargetOptions

2022-08-29 20:24 UTC, barbados-clemens commented on packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.ts
>    updateTsConfig(tree, projectConfig);
add to cacheable operations

2022-08-29 20:24 UTC, barbados-clemens commented on packages/react/src/generators/cypress-component-configuration/schema.json
> +      "pattern": "^[^:\\s]+:[^:\\s]+(:\\S+)?$"
idea for console? be able to pick a target?

2022-08-30 14:37 UTC, barbados-clemens commented on packages/cypress/src/utils/find-target-options.ts
> +      if (maybeBuildTarget && maybeTargetConfig) {
decided to log if multiple projects found and mention using --build-target can be used to specify the desired target

2022-08-30 14:53 UTC, barbados-clemens commented on packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.ts
>    updateTsConfig(tree, projectConfig);
it's in the base generator from @nrwl/cypress 🤦

2022-08-30 14:54 UTC, barbados-clemens commented on packages/react/src/generators/cypress-component-configuration/schema.json
> +      "pattern": "^[^:\\s]+:[^:\\s]+(:\\S+)?$"
jon is already on it 🔥

2022-08-30 15:18 UTC, AgentEnder requested changes

2022-08-30 15:18 UTC, AgentEnder commented on packages/cypress/src/utils/find-target-options.ts
>    };
Can this use readTargetOptions? e.g. `readTargetOptions({project, target configuration})`

2022-08-30 15:18 UTC, AgentEnder commented on packages/cypress/src/utils/find-target-options.ts
>    };
If not, you can remove the `|| {}`

2022-08-30 15:18 UTC, AgentEnder commented on packages/cypress/src/utils/find-target-options.ts
>          : targetConfig.options;
`readTargetOptions({project: projectName, target: targetName})`

2022-08-30 15:18 UTC, AgentEnder commented on packages/react/plugins/component-testing/index.ts
> +    }, {});
Use `readProjectsConfigurationFromProjectGraph` in `packages/nx/src/project-graph/project-graph.ts`

2022-08-30 15:39 UTC, AgentEnder approved these changes

2022-08-30 16:42 UTC, merged