feat(core): add yarn parser WIP
nrwl/nx pull request #11953
Opened 2022-09-09 13:36 UTC by meeroslav

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2022-09-13 10:22 UTC, meeroslav commented on scripts/check-lock-files.js
> +      'yarn lockfile-lint -s -p yarn.lock -a hosts yarn npm',
We disable this explicitly, because of `pnpm`'s package name hacks.

2022-09-18 17:41 UTC, vsavkin commented
I think the pair of parseLockFIle/writeLockFile is a good interface. 

Some notes and questions:

1. Should parseLockFIle be generic?
LockFileData is generic, but that type parameter is not used in the parseLockFile/writeLockFile functions, and I don't think we would use it.

After all, we want to write lock-file-oriented code in a polymorphic way. E.g., if we want to prune the lock file, we would want to write that code without any specific yarn, npm etc stuff. If it is possible, the parse/write functions cannot be generic. If it is not possible, then I don't think hose functions are needed because the if statement you have inside will have to outside. Does it make sense?

We use generics in the same way when creating a project graph. The generic parameter there is not used.

2. Should parseLockFIle take parameters?
 
 I don't think it should cause I imagine all the unit testing will be done around package-specific functions (you will test npm,yarn,pnpm versions directly).

3. I don't think the tests should be in the lockfile-test folder. All unit tests should be based on parsing and serializing strings. We need at least some unit tests for each package manager.

2022-09-18 17:42 UTC, vsavkin requested changes
Left some comments.

2022-09-18 18:05 UTC, meeroslav commented
Thank you for checking the PR.

I'll check if we can get rid of generics without making code too messy. But generally, all callers of parse, stringify (and future prune) should be agnostic of package manager (and lock file generic type).

Regarding the lock files in script folder, all of that will be gone. It was more convenient while debugging, but I'll drop that entire folder and add tests with fixtures. This would also make the working directory param obsolete.

Once I add tests, the PR will be ready for full review.

2022-09-20 18:47 UTC, merged

2022-10-20 07:54 UTC, Nikamura commented
Hey guys, why was `@zkochan/js-yaml` added as dependency instead of using `js-yaml` ?

https://www.npmjs.com/package/@zkochan/js-yaml/v/0.0.6
https://www.npmjs.com/package/js-yaml

2022-12-16 14:30 UTC, meeroslav commented
@Nikamura  Because of the lock file pruning. The `@zkochan/js-yaml` adds additional functionality on top of `js-yaml`, which unfortunately is necessary to properly construct `pnpm-lock.yaml`.