feat(testing): add reporters cli param support for jest
nrwl/nx pull request #1203
Opened 2019-03-24 17:03 UTC by jefvanhoyweghen

Add the reporters cli option to the jest config. Support for either string or json.

_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-pr)_

## Current Behavior (This is the behavior we have today, before the PR is merged)
No support for jest `--reporters` cli option

## Expected Behavior (This is the new behavior we can expect after the PR is merged)
Added support for jest `--reporters` cli option, supporting both string and json

## Issue

2019-04-03 20:11 UTC, vsavkin commented
@FrozenPandaz could you take a look?

2019-04-04 16:31 UTC, FrozenPandaz requested changes
Thank you for your contribution!

Left some comments.

2019-04-04 16:31 UTC, FrozenPandaz commented on packages/builders/src/jest/schema.json
> +      "type": "string|json",
This syntax is invalid. Also, I think it should be `string` or `Array<string>`.

You can use `oneOf`:

Example: https://github.com/nrwl/nx/blob/master/packages/builders/src/web/build/schema.json#L41

2019-06-04 20:41 UTC, vsavkin commented
I'm closing this PR due to inactivity. Sorry about that.

2019-06-04 20:41 UTC, closed without merging