feat(nx-plugin): allow skipping the creation of an e2e project
nrwl/nx pull request #12129
Opened 2022-09-20 16:28 UTC by ashley-hunter

## Current Behavior

Currently there is no option to skip the creation of an E2E project when generating an Nx Plugin.

## Expected Behavior

Ideally the creation of an e2e project should be optional.

## Related Issue(s)

N/A

2022-09-22 22:15 UTC, AgentEnder commented
Hey, thanks for the contribution. Lets make this consistent with several of our other generators, and use `e2eTestRunner` as the property, with options "jest", and "none".

Here's a fragment of the next app generator's schema.json as an example:
```json
{
  "properties": {
    "e2eTestRunner": {
      "type": "string",
      "enum": ["cypress", "none"],
      "description": "Test runner to use for end to end (E2E) tests.",
      "default": "cypress"
    }
  }
}
```

2022-09-22 22:16 UTC, AgentEnder requested changes
See comment (`--skipE2eProject` -> `--e2eTestRunner none`)

2022-09-22 22:45 UTC, ashley-hunter commented
@AgentEnder thanks very much for the feedback, I have made the suggested changes.

2022-09-23 00:10 UTC, AgentEnder approved these changes

2022-09-23 00:11 UTC, merged