docs: add troubleshoot in bitbutcket-pipelines.yml
nrwl/nx pull request #12202
Opened 2022-09-23 07:10 UTC by r17x

## Current Behavior

NX can resolved base branch in `bitbutcket-pipeline.yml`.

## Expected Behavior

## Related Issue(s)

Fixes #

2022-10-11 22:23 UTC, meeroslav commented
Hi @r17x,

Can you provide a bit more explanation on what is your PR solving? I need a bit more information about the bitbucket issue and how is this additional info helping.

2022-10-28 12:41 UTC, johannesschobel requested changes

2022-10-28 12:41 UTC, johannesschobel commented on docs/shared/monorepo-ci-bitbucket-pipelines.md
> +If you found this issue in bitbucket pipelines, maybe you `bitbucket-pielines.yml` can defined like this:
```suggestion
If you found this issue in bitbucket pipelines, maybe you `bitbucket-pipelines.yml` can defined like this:
```

2022-11-03 09:53 UTC, meeroslav commented
This PR seems to be inactive, so I will close it.

2022-11-03 09:53 UTC, closed without merging