feat(core): warn when falling back to angular cli for misc commands
nrwl/nx pull request #12401
Opened 2022-10-04 15:17 UTC by AgentEnder

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2022-10-04 15:20 UTC, juristr commented on packages/nx/bin/init-local.ts
> +      `${NX_PREFIX} If this is not the desired behaviour, try: \`nx run  ${project}:${command}`
there's a blank too much in between `run` and `${project}:${command}`

2022-10-05 19:18 UTC, FrozenPandaz requested changes

2022-10-05 19:40 UTC, AgentEnder commented on packages/nx/bin/init-local.ts
> +      `${NX_PREFIX} Falling back to \`ng ${command} ${project} ${args.join(
If worried about `ng completion` in particular, we could hide the warning for it specifically?

2022-10-11 21:11 UTC, FrozenPandaz approved these changes

2022-10-11 21:12 UTC, merged