feat(graph): toggle visibility of all projects in a folder
nrwl/nx pull request #12641
Opened 2022-10-15 14:18 UTC by alexciesielski

Adds a button next to the folder label to quickly show/hide all projects of that folder.
ISSUES CLOSED: 12640

## Related Issue(s)

Fixes #12640

2022-10-24 21:16 UTC, philipjfulcher requested changes
Thanks for your contribution! I especially appreciate the added e2e tests. 

I like this addition. After talking with some other folks, we think the behavior for clicking the toggle button for a folder when some of the projects are already selected should change. It should add the rest of the projects, rather than deselect the currently selected projects.

I think your failing e2e task should pass after a rebase on master.

Let me know if you need any help. 😄

2022-11-01 20:57 UTC, philipjfulcher approved these changes

2022-11-01 20:58 UTC, philipjfulcher commented
I had some time today, so I made the change myself. Thanks again for your work!

2022-11-02 04:32 UTC, merged

2022-11-03 06:53 UTC, alexciesielski commented
Hey, I was on vacation last week. Thanks for taking the time to finish this, much appreciated!