feat(core): add generator to migrate workspace generators to a local plugin
nrwl/nx pull request #12700
Opened 2022-10-18 21:10 UTC by AgentEnder

## Current Behavior
You have to manually create a plugin and move workspace-generators manually.

## Expected Behavior
You can run a generator to handle this. `nx g @nrwl/nx-plugin:local-plugin-from-tools`.

## Related Issue(s)

Fixes #

2022-10-18 21:14 UTC, AgentEnder commented on packages/nx-plugin/.eslintrc.json
> -          "@nrwl/workspace"
We are using the workspace generator generator for tests, as well as the move generator

2022-10-18 21:14 UTC, AgentEnder commented on packages/nx-plugin/src/generators/local-plugin-from-tools/generator.ts
> +  if (config.root !== options.toolsProjectRoot) {
Trying to call move generator without actually moving files errors

2023-02-24 19:51 UTC, FrozenPandaz approved these changes

2023-02-24 19:51 UTC, FrozenPandaz commented on docs/generated/packages/workspace/generators/move.json
> +      "newProjectName": {
Remove from schema, keep in types

2023-02-24 19:51 UTC, FrozenPandaz commented on packages/devkit/testing-pre16.ts
> +export function uniq(prefix: string): string {
remove

2023-02-24 19:51 UTC, FrozenPandaz commented on packages/nx-plugin/src/generators/local-plugin-from-tools/generator.ts
> +function moveFolder(tree: Tree, source: string, destination: string) {
Can we use `Tree.rename`?

2023-02-24 19:51 UTC, FrozenPandaz commented on packages/nx-plugin/src/generators/local-plugin-from-tools/generator.ts
> +export default async function (
This is great. Let's make this a migration in `workspace`

2023-02-27 19:55 UTC, isaacplmann approved these changes

2023-02-27 21:26 UTC, FrozenPandaz requested changes

2023-02-27 21:26 UTC, FrozenPandaz commented on packages/nx-plugin/src/generators/local-plugin-from-tools/schema.json
> +{
rm

2023-02-27 21:26 UTC, FrozenPandaz commented on packages/nx/src/command-line/nx-commands.ts
> +    deprecated: true,
This should be a string

2023-02-27 21:26 UTC, FrozenPandaz commented on packages/nx/src/command-line/nx-commands.ts
> +    describe:
Leave it the same

2023-02-27 21:26 UTC, FrozenPandaz commented on scripts/depcheck/missing.ts
> +  console.log(missing['@nrwl/nx-plugin']);
rm

2023-04-06 16:38 UTC, FrozenPandaz requested changes

2023-04-06 16:38 UTC, FrozenPandaz commented on packages/workspace/src/generators/workspace-generator/workspace-generator.ts
> +    started, install @nrwl/nx-plugin and run \`nx g plugin\`.
We need to make `nx g plugin` fit the mold for this.

Currently, it generates e2e tests, and placeholder executors and generators.

2023-04-19 18:02 UTC, FrozenPandaz approved these changes

2023-04-19 18:03 UTC, merged