fix(core): fix custom workspace-generator options
nrwl/nx pull request #12821
Opened 2022-10-25 20:53 UTC by Roozenboom

After PR 12258 the custom options for local workspace-generators did not work anymore because if any
options are defined in the schema it added (options) to the command and if no properties were
defined it also throwed an error

ISSUES CLOSED: 12677

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2022-10-25 22:58 UTC, AgentEnder requested changes

2022-10-25 22:58 UTC, AgentEnder commented on packages/nx/src/command-line/nx-commands.ts
> +    Object.entries(schema.properties as WorkspaceGeneratorProperties).forEach(
Rather than wrapping whole block in if statement, can we do `schema.properties ?? {}`?

2022-11-07 15:37 UTC, AgentEnder commented
Since #12955 included most of the fix, can this PR be updated to only add the null safety?

2022-11-07 20:33 UTC, Roozenboom commented
PR is updated to only add the null safety, because if prettier the change looks bigger than it actually is :)

2022-11-07 21:08 UTC, AgentEnder approved these changes

2022-11-07 21:09 UTC, merged