docs(core): add info on NX_TARGET_TASK_PROJECT
nrwl/nx pull request #12957
Opened 2022-11-03 00:01 UTC by dan-cooke

Just adding some documentation on the elusive `NX_TARGET_TASK_PROJECT` feature that has been apparently in the framework for 16 months.

I was actually attempting to add a similar feature when I discovered it by digging through the source code.

2022-11-07 15:54 UTC, AgentEnder requested changes
It seems like CircleCI picked up some weird issue. Can you rebase?

2022-11-07 15:54 UTC, AgentEnder commented on packages/nx/src/tasks-runner/run-command.ts
> +  console.log(projectsToRun, projectGraph);
This needs to be removed

2022-11-07 16:06 UTC, dan-cooke commented on packages/nx/src/tasks-runner/run-command.ts
> +  console.log(projectsToRun, projectGraph);
Removed, and rebased

2022-11-18 20:27 UTC, closed without merging

2022-11-18 20:28 UTC, isaacplmann commented
@dan-cooke , I put your commit on a PR that I opened up and the CI passed.

2022-11-18 21:58 UTC, AgentEnder commented
Thanks @isaacplmann

2022-11-18 22:09 UTC, dan-cooke commented
@isaacplmann thank you!