feat(frontend): add differential loading for web apps
nrwl/nx pull request #1344
Opened 2019-05-14 15:34 UTC by FrozenPandaz

_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-pr)_

## Current Behavior (This is the behavior we have today, before the PR is merged)

The web builder does not utilize differential loading:

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

The web builder utilizes differential loading.

It is enabled by default.

2 sets of bundles are produced: 1 for evergreen browsers (ones that support es2015) and 1 for older browsers.

## Issue

2019-05-18 00:06 UTC, vsavkin requested changes
I'm a bit concerned that we depend on angular-devkit/build-angular here. How hard would it be not to?

2019-05-18 00:06 UTC, vsavkin commented on packages/web/src/builders/build/build.impl.ts
> +        mergeScan(
would not forkJin work better here? I might be misunderstanding what you are trying to do

2019-05-18 00:06 UTC, vsavkin commented on packages/web/src/utils/web.config.ts
> +import { ScriptTarget } from '@schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript';
we import it from 'typescript' in another file. why?

2019-05-20 16:21 UTC, Jordan-Hall commented
@mbinic are you able to make this change or do you mind if I jump on the PR and make the change required?

2019-05-23 15:09 UTC, FrozenPandaz commented on packages/web/src/builders/build/build.impl.spec.ts
> +import * as indexHtmlUtils from '@angular-devkit/build-angular/src/angular-cli-files/utilities/index-file/write-index-html';
There is a way. But for time, can we address this in a future release/PR?

2019-05-23 15:57 UTC, merged