docs(core): update angular to nx guide
nrwl/nx pull request #13519
Opened 2022-11-30 20:18 UTC by isaacplmann

Updates the angular cli to Nx guide

2022-11-30 21:27 UTC, FrozenPandaz commented on docs/shared/migration/migration-angular.md
> +├── .eslintrc.<app name>.json
This should be `.eslintrc.base.json`

2022-11-30 21:27 UTC, FrozenPandaz commented on docs/shared/migration/migration-angular.md
>        "executor": "@angular-devkit/build-angular:tslint",
Is this still valid?

2022-11-30 21:27 UTC, FrozenPandaz commented on docs/shared/migration/migration-angular.md
>  When prompted for the `application name`, enter the _project name_ from your current `angular.json` file.
Above this, it says to use `--preset angular`, it should now be `--preset angular-standalone`.

Or honestly.. maybe `--preset empty`?

2022-12-01 15:47 UTC, FrozenPandaz requested changes

2022-12-01 15:47 UTC, FrozenPandaz commented on docs/shared/migration/migration-angular.md
> +- Copy any project-specific configuration files, such as `browserslist`, or service worker configuration files into their relative path in the root of the repo.
This should say to move it to the `src` in the root or something.

2022-12-01 15:47 UTC, FrozenPandaz commented on docs/shared/migration/migration-angular.md
>  - Update the `test` target file paths to be relative to `apps/<app name>`.
This line isn't needed anymore.

2022-12-01 15:47 UTC, FrozenPandaz commented on docs/shared/migration/migration-angular.md
> +```jsonc {% fileName="project.json" %}
It's a lot more 1:1 now.. I'd say it's not worth showing this example.

The one thing I would say to do is to change `builder => executor`...

2022-12-01 15:47 UTC, FrozenPandaz commented on docs/shared/migration/migration-angular.md
>  - Rename the `e2e` folder to `<app name>-e2e`.
This line can be removed.

2022-12-01 15:47 UTC, FrozenPandaz commented on docs/shared/migration/migration-angular.md
> +```json {% fileName="e2e/project.json" %}
Again this should be more 1:1 now.

I would just mention to change `architect => targets` and `builder => executor`

2022-12-01 15:47 UTC, FrozenPandaz commented on docs/shared/migration/migration-angular.md
> +Create a `tsconfig.e2e.json` file under `e2e` folder:
We could call this `tsconfig.json`?

2022-12-02 11:30 UTC, leosvelperez reviewed
The section about `--preserve-angular-cli-layout` (https://github.com/nrwl/nx/blob/master/docs/shared/migration/migration-angular.md?plain=1#L14-L36) probably needs to be amended as well.

Starting in Nx v15.3.0, the changes made to an Angular v15 workspace are different from what is currently listed in that section:

- It'll generate a `project.json`
- The `angular.json` is removed
- `prettier` is installed

Note that those changes only happen for Angular CLI v15 workspaces using `@nrwl/angular@15.3.0`. For Angular CLI v14 workspaces migrating with an older version of the `@nrwl/angular` plugin, the changes will be the ones that are listed today.

2022-12-06 09:15 UTC, leosvelperez commented on docs/shared/migration/migration-angular.md
>  | >= 13.10.0          | `@nrwl/angular`   | `--preserve-angular-cli-layout` | `ng add @nrwl/angular@13.10.0 --preserve-angular-cli-layout`  |
Probably we want to add the max in the range for the Nx version here to clearly state up to which version they need to use this. It should be `>= 13.10.0 < 15.3.0`.

2022-12-06 09:15 UTC, leosvelperez commented on docs/shared/migration/migration-angular.md
> +- A `decorate-angular-cli.js` file will be added to the root of your workspace, and a `postinstall` script will be added to your `package.json` to run this script when your dependencies are updated.
We also install `prettier` and split the `angular.json` file into `project.json` files.

2022-12-06 09:15 UTC, leosvelperez commented on docs/shared/migration/migration-angular.md
> +- A `decorate-angular-cli.js` file will be added to the root of your workspace, and a `postinstall` script will be added to your `package.json` to run this script when your dependencies are updated.
Should we also add a note clarifying these changes will be slightly different for legacy versions?

2022-12-06 13:44 UTC, leosvelperez approved these changes
LGTM!

2022-12-06 14:50 UTC, FrozenPandaz approved these changes

2022-12-06 14:50 UTC, merged