fix(vite): Support fileReplacements for devServer
nrwl/nx pull request #13761
Opened 2022-12-12 10:23 UTC by nodegin

## Current Behavior

The `fileReplacements` option does not work with `@nrwl/vite:dev-server` executor

Existing solution using `resolveId` only works when building but not local dev

## Expected Behavior

When also passing `fileReplacements` in the "serve" section for the dev server,

It should also do the replacement

## Related Issue(s)

Fixes #13758

2022-12-12 14:15 UTC, mandarini commented
Hello! Thanks for the PR! Do you want to check your errors and fix them? Then I can approve! Have you tested it, does it work properly in all scenarios?

2022-12-12 14:16 UTC, mandarini commented
I think format check failed (maybe??). Can you try also `nx format`?

2022-12-12 14:35 UTC, mandarini requested changes

2022-12-12 14:35 UTC, mandarini commented on packages/vite/plugins/rollup-replace-files.plugin.ts
> +import fs from 'fs';
You can try `import * as fs from 'fs'`

2022-12-13 08:19 UTC, nodegin reviewed
@mandarini  I have amended the `fs` import

2022-12-13 09:18 UTC, mandarini commented
@nodegin thanks! Did you also run `nx format`? Can you force-push again, in any case, because CI is stuck?

2022-12-13 09:45 UTC, nodegin commented
@mandarini  Sorry I updated again to format the code.

2022-12-13 10:11 UTC, mandarini approved these changes

2022-12-13 10:11 UTC, merged

2023-01-03 10:51 UTC, mandarini commented
@nodegin  I reverted your PR because it was causing issues with the source maps. Let me know if you can look into it more, since I guess reverting your PR brings back the devserver issue you had observed.

2023-01-06 16:34 UTC, KayhanB commented
in version 15.4.4  fileReplacements are not working, i downgraded nx to 15.4.2 and now working

2023-01-09 09:53 UTC, mandarini commented
Are you referring to the build fileReplacements, or the devServer fileReplacements? @KayhanB

2023-01-11 21:16 UTC, KayhanB commented
build is working but devServer is not @mandarini

2023-01-12 08:53 UTC, mandarini commented
Linking [this here](https://github.com/nrwl/nx/issues/14256)

Will take a look at that some time next week.

2023-01-20 14:31 UTC, mandarini commented
@KayhanB @nodegin  I'll see how I can fix this so that both build and dev-server work. However, we do suggest [this](https://github.com/nrwl/nx/issues/14256#issuecomment-1380393263), using `import.meta.env.VITE_*`, see [these docs](https://vitejs.dev/guide/env-and-mode.html)

Please let me know if there's a reason why you prefer the `fileReplacements` solution over this.

2023-01-20 15:40 UTC, pgsteven commented
@mandarini I think for some case we might want to replace some files (e.g. some code logic to execute?) in different environments instead of just configurations

2023-01-28 22:10 UTC, nodegin commented
@mandarini Sorry do you still remember what issue my PR having with source maps?

2023-01-30 15:20 UTC, mandarini commented
@nodegin  @KayhanB @pgsteven 

Hey, people!

So, we decided that this is not in our immediate plans at the moment, after all.

That being said, if any one of you can spend some time putting together a pull request to make this work, I'll be more than happy to test it out, make sure it works, and merge it.

At the same time, if one wants this functionality for Nx, what they can do, is write their own plugin in their workspace, and just add it in the `plugins` array of their `vite.config.js` file. I mean, without the plugin needing to be an actual part of Nx. Here's the [Plugins API](https://vitejs.dev/guide/api-plugin.html) for Vite.

As an alternative, please consider using `import.meta.env.VITE_*` for variable values, or [resolve-alias](https://vitejs.dev/config/shared-options.html#resolve-alias). I know these do not cover the actual file replacing functionality that you all need for dev server, but they could offer an alternative.

Just as a reminder, fileReplacement does work for the prod builder!

2023-02-02 14:18 UTC, KayhanB commented
hi @mandarini  
vite's import.meta.env feature solves my problem perfectly, I didn't know about this feature before you suggested it. I implemented this solution and got a much cleaner result than fileReplacement. for now i don't have a situation where i need to use fileReplacement. If there is, I will inform you.
thank you for attention