fix(core): fix lock file pruning optional dependencies
nrwl/nx pull request #13830
Opened 2022-12-14 19:58 UTC by skrtheboss

## Current Behavior

Optional dependencies are omitted from the pruned .lock file.

## Expected Behavior

Optional dependencies should be included in the .lock file 

## Related Issue(s)

Fixes #

2022-12-14 20:22 UTC, skrtheboss commented
@meeroslav as far as I understood, you have implemented this functionality, so may I ask you to have a look at this? 
Thank you.

2022-12-14 23:02 UTC, meeroslav requested changes
Thank you for the PR. Please add test for npm V1 or V2 to ensure all three variants of npm lock file are working (v2 is backward compatible and contains both V1 and V3 formats).

The rest looks good to me!

2022-12-14 23:02 UTC, meeroslav commented on packages/nx/src/lock-file/npm.spec.ts
>    describe('v3', () => {
Can you please also add a test for V1, or at least replace the V3 with backward-compatible V2?

2022-12-15 08:28 UTC, skrtheboss commented
Hi @meeroslav, i have added the missing lock file tests:
* npm v1 and v3
* yarn berry

Let me know if i should add/change something else

2022-12-15 09:48 UTC, meeroslav approved these changes

2022-12-15 09:48 UTC, meeroslav commented
Amazing work, @skrtheboss, thank you!

2022-12-15 09:49 UTC, merged