fix(vite): set mode in configuration
nrwl/nx pull request #13856
Opened 2022-12-15 19:02 UTC by mandarini

Set the mode under the configuration settings for `vite` projects, so that when someone passes the configuration through Nx, then we will also pass the vite mode.

eg. `nx build --prod` or `nx build --configuration=development` will also set the `mode` for the Vite builder.

2022-12-15 19:06 UTC, jaysoo approved these changes

2022-12-15 19:06 UTC, jaysoo commented on packages/vite/src/migrations/update-15-3-4/set-mode-in-configuration.ts
> +        projectConfiguration.targets[targetName].configurations[
short form

```
projectConfiguration.targets[targetName].configurations[
          configurationName
        ].mode ??= configurationName;
```

2022-12-15 19:09 UTC, mandarini commented on packages/vite/src/migrations/update-15-3-4/set-mode-in-configuration.ts
> +        projectConfiguration.targets[targetName].configurations[
Done

2022-12-15 19:10 UTC, FrozenPandaz requested changes

2022-12-15 19:10 UTC, FrozenPandaz commented on packages/vite/src/migrations/update-15-3-4/set-mode-in-configuration.ts
> +    (_options, projectName, targetName) => {
This callback also gets the `configuration` name. And each configuration setting. So you can use that to make the adjustments.

2022-12-15 19:13 UTC, FrozenPandaz commented on packages/vite/src/migrations/update-15-3-4/set-mode-in-configuration.ts
> +      for (const configurationName in projectConfiguration.targets[targetName]
It should look something like:

```

    (_options, projectName, targetName, configuration) => {
      const projectConfiguration = readProjectConfiguration(tree, projectName);

      if (configuration && !_options.hasOwnProperty('mode')) {
        projectConfiguration.targets[targetName].configurations[configuration].mode = configuration;

        updateProjectConfiguration(tree, projectName, {
          ...projectConfiguration,
        });
      }
    }
```

2022-12-15 19:15 UTC, FrozenPandaz commented on packages/vite/src/migrations/update-15-3-4/set-mode-in-configuration.ts
> +      for (const configurationName in projectConfiguration.targets[targetName]
Better yet:

```ts
    (_options, projectName, targetName, configuration) => {
      if (!configuration) {
        return;
      }
      
      const projectConfiguration = readProjectConfiguration(tree, projectName);
      projectConfiguration.targets[targetName].configurations[configuration].mode ??= configuration;

      updateProjectConfiguration(tree, projectName, {
        ...projectConfiguration,
      });
    }
```

2022-12-15 22:13 UTC, FrozenPandaz approved these changes

2022-12-15 22:44 UTC, merged

2022-12-16 08:53 UTC, mandarini commented on packages/vite/src/migrations/update-15-3-4/set-mode-in-configuration.ts
> +      for (const configurationName in projectConfiguration.targets[targetName]
Ohhhhhh cool I'll push that fix now!

2022-12-16 09:34 UTC, mandarini commented on packages/vite/src/migrations/update-15-3-4/set-mode-in-configuration.ts
> +      for (const configurationName in projectConfiguration.targets[targetName]
Ohh it's already pushed, nevermind!