docs: fix links to devkit index page
nrwl/nx pull request #14034
Opened 2022-12-27 20:39 UTC by felipeplets

## Current Behavior

Documentation link on the sidebar menu to the DevKit package is broken.

## Expected Behavior

Documentation link is fixed.

## Related Issue(s)

Fixes #14033

2023-01-03 15:27 UTC, bcabanes requested changes
Thank you for the time and the contribution, I only have a minor change and it should be good to go 👍

2023-01-03 15:27 UTC, bcabanes commented on docs/map.json
> +              "path": "/packages/devkit",
Could you change this to:
```suggestion
            "path": "/packages/devkit/documents/index",
```

So we can keep the same intent?

2023-01-03 18:36 UTC, felipeplets commented
> Thank you for the time and the contribution, I only have a minor change and it should be good to go 👍

Done. Thank you for the review @bcabanes

2023-01-03 18:44 UTC, bcabanes commented
You will have to run `yarn documentation` again and commit the files to make the CI pass and propagate the changes to the generated documentation.

2023-01-04 18:59 UTC, felipeplets commented
@bcabanes done.

2023-01-04 19:04 UTC, bcabanes approved these changes
Perfect thank you!

2023-01-04 19:04 UTC, merged