docs(testing): add x-priority to jest schema
nrwl/nx pull request #14252
Opened 2023-01-10 16:54 UTC by barbados-clemens

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-01-10 16:57 UTC, barbados-clemens commented
Forgot to do the generators. adding now

2023-01-16 11:58 UTC, MaxKless requested changes

2023-01-16 11:58 UTC, MaxKless commented on docs/generated/packages/jest/executors/jest.json
> +        "x-priority": "important"
Is this really something folks will want to set almost all of the time they use this executor? 
To me it seems like `passWithNoTests` gets enabled as soon as there happens to be no tests which isn't that often, right? Most generators scaffold sample tests

2023-01-16 11:58 UTC, MaxKless commented on docs/generated/packages/jest/executors/jest.json
>        "updateSnapshot": {
Same here. Obviously you're the expert so I'll trust your judgement. But I would think that folks would rather use `-u` when they want to update snapshots and not set it every time...

2023-01-16 11:58 UTC, MaxKless commented on docs/generated/packages/jest/executors/jest.json
> +        "type": "boolean",
See the guidelines that say `watch` shouldn't be `important`

2023-01-23 14:27 UTC, MaxKless commented on docs/generated/packages/jest/executors/jest.json
> +        "x-priority": "important"
unless there's some specific reason here, I think `ci` shouldn't be `important` either. it is set by default and kind of a generic option.

2023-01-23 15:10 UTC, MaxKless approved these changes

2023-01-23 15:29 UTC, merged