feat(nx-cloud): display current token for connect-to-nx-cloud
nrwl/nx pull request #14315
Opened 2023-01-12 17:18 UTC by bcabanes

It displays the current token the runner uses when a workspace is already connected to Nx Cloud.

This will allow developers not to have to look for the access token themselves when they manually want to claim a workspace.

2023-01-12 21:56 UTC, FrozenPandaz requested changes

2023-01-12 21:56 UTC, FrozenPandaz commented on packages/nx/src/command-line/connect.ts
> +        'Here is the token currently used by this workspace to connect to Nx CLoud:',
```suggestion
        'Here is the token currently used by this workspace to connect to Nx Cloud:',
```

2023-01-13 17:06 UTC, jaysoo approved these changes

2023-01-13 17:19 UTC, FrozenPandaz requested changes

2023-01-13 17:19 UTC, FrozenPandaz commented on packages/nx/src/command-line/connect.ts
> +        'This means your workspace can use computation caching and distributed task execution, and show you run analytics.',
```suggestion
        'This means your workspace can use computation caching, distributed task execution, and show you run analytics.',
```

2023-01-13 17:19 UTC, FrozenPandaz commented on packages/nx/src/command-line/connect.ts
> +        'Here is the token currently used by this workspace:',
I don't think normal users will know what to do with this information.

We should show a link that they can click to claim just like when we initially connect.

And we should also make an API call to see if the workspace is indeed unclaimed. 

I think this should be a separate warning.

2023-01-13 18:57 UTC, FrozenPandaz approved these changes

2023-01-13 19:03 UTC, merged