feat(misc): new flag for migrate to succeed if no migrations.json
nrwl/nx pull request #14578
Opened 2023-01-24 13:43 UTC by samuelfernandez

## Current Behavior

Running `nx migrate --run-migrations` fails if `migrations.json` does not exist. This is not suitable for CI environment as Renovate

## Expected Behavior

With a new flag `--if-present`, the command can succeed if the file doesn't exist.

## Related Issue(s)

Fixes #14131

2023-01-24 14:05 UTC, samuelfernandez commented
@AgentEnder This will need an empty commit from your side to let the CI run

2023-01-24 16:42 UTC, AgentEnder requested changes

2023-01-24 16:42 UTC, AgentEnder commented on packages/nx/src/command-line/nx-commands.ts
>        linkToNxDevAndExamples(withMigrationOptions(yargs), 'migrate'),
The option needs to be added in to the `withMigrationOptions` helper, the yargs builder object is what scopes out the --help text and similar.

2023-01-24 16:42 UTC, AgentEnder commented
There are also some docs changes, run `yarn documentation` and push them up.

2023-01-24 17:28 UTC, samuelfernandez commented
> There are also some docs changes, run `yarn documentation` and push them up.

@AgentEnder should be fixed now! Can't do local dev because I use Windows, currently it is blocked. Did the changes manually. This would need another empty commit for the pipeline to run :shrug: Thanks for the time to review! 😄

2023-01-24 17:40 UTC, AgentEnder commented
> Can't do local dev because I use Windows

FWIW I use windows for 95% of my work, the repo works perfectly **_under WSL_** if you are on win 10/11. Outside of WSL yeah, there are some errors. I'll push up a new commit to kick off CI and include any docs changes

2023-01-24 17:55 UTC, samuelfernandez commented
> > Can't do local dev because I use Windows
> 
> 
> 
> FWIW I use windows for 95% of my work, the repo works perfectly **_under WSL_** if you are on win 10/11. Outside of WSL yeah, there are some errors. I'll push up a new commit to kick off CI and include any docs changes

Good to know! I tried with WSL, but hit this bug https://github.com/nrwl/nx/issues/14403 Anyway, thanks for the follow up 😀

2023-01-24 19:15 UTC, samuelfernandez commented on packages/nx/src/command-line/migrate.spec.ts
> +        ifExists: '',
```suggestion
        ifExists: true,
```

2023-01-30 11:09 UTC, samuelfernandez commented
@AgentEnder requested changes should be applied 😄

2023-02-21 17:29 UTC, AgentEnder approved these changes

2023-02-21 18:24 UTC, merged