fix(core): reintroduce misaligned packages check
nrwl/nx pull request #14648
Opened 2023-01-26 18:42 UTC by AgentEnder

## Current Behavior
This PR addresses the following behavior's:

1. Prior to version 15.6, `nx workspace-lint` would list packages that were misaligned. Since `workspace-lint` has now been deprecated, this would no longer be the case.
2. `nx report` contained empty sections for community plugins and local plugins if there were none present
3. `nx report`'s output was growing quite a bit as we add more first party plugins and more folks use community plugins

## Expected Behavior
The corresponding new behavior's: 

1. `nx report` shows any misalignment in new sections at the bottom, with remediation instructions
2. `nx report` hides empty sections for community plugins and local plugins if there were none present
3. `nx report`' hides uninstalled plugins, even if we care about them

## Related Issue(s)

Fixes #

2023-01-27 23:00 UTC, FrozenPandaz requested changes

2023-01-27 23:00 UTC, FrozenPandaz commented on packages/nx/src/command-line/report.ts
> +    ...communityPlugins,
Let's only do this for `nx`

2023-02-07 18:35 UTC, AgentEnder commented on packages/nx/src/command-line/report.ts
> +    bodyLines.push('⚠️ Unable to construct project graph.');
Good point! Fixed in latest.

2023-02-07 18:36 UTC, AgentEnder commented on packages/nx/src/command-line/report.ts
> +      );
Nice catch!

2023-02-07 19:28 UTC, leosvelperez approved these changes

2023-02-07 23:32 UTC, FrozenPandaz approved these changes

2023-02-07 23:32 UTC, merged