chore(repo): add CODEOWNERS
nrwl/nx pull request #14671
Opened 2023-01-27 18:32 UTC by AgentEnder

## Current Behavior
PRs sit for some time before triage assigns reviewers or they are otherwise noticed

## Expected Behavior
PRs are auto-assigned designated reviewers

## Related Issue(s)

Fixes #

2023-01-27 22:35 UTC, FrozenPandaz requested changes

2023-01-27 22:35 UTC, FrozenPandaz commented on CODEOWNERS
> +/packages/cra-to-nx/** @jaysoo @xiongemi
```suggestion
/packages/cra-to-nx/** @jaysoo @xiongemi @mandarini
```

2023-01-27 22:35 UTC, FrozenPandaz commented on CODEOWNERS
> +/packages/cypress/** @barbados-clemens
```suggestion
/packages/cypress/** @barbados-clemens @FrozenPandaz
```

2023-01-27 22:35 UTC, FrozenPandaz commented on CODEOWNERS
> +/packages/detox/** @xiongemi
```suggestion
/packages/detox/** @xiongemi @jaysoo 
```

2023-01-27 22:35 UTC, FrozenPandaz commented on CODEOWNERS
> +/packages/devkit/index.ts @FrozenPandaz
```suggestion
/packages/devkit/index.ts @FrozenPandaz @vsavkin
```

2023-01-27 22:35 UTC, FrozenPandaz commented on CODEOWNERS
> +/packages/eslint-plugin-nx/** @meeroslav
```suggestion
/packages/eslint-plugin-nx/** @meeroslav @FrozenPandaz 
```

2023-01-30 23:11 UTC, bcabanes commented on CODEOWNERS
> +/docs/nx-cloud @StalkAltan @rarmatei @isaacplmann @juristr
```suggestion
/docs/nx-cloud @StalkAltan @rarmatei @isaacplmann @juristr @bcabanes 
```

2023-02-06 22:46 UTC, FrozenPandaz approved these changes

2023-02-06 22:46 UTC, merged