fix(linter): add node_modules to linter ignore patterns
nrwl/nx pull request #14980
Opened 2023-02-14 09:08 UTC by meeroslav

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #13611

2023-02-14 11:44 UTC, Coly010 approved these changes

2023-02-14 12:41 UTC, mandarini approved these changes

2023-02-14 13:00 UTC, nartc approved these changes

2023-02-14 14:51 UTC, AgentEnder approved these changes

2023-02-14 16:52 UTC, FrozenPandaz requested changes
Instead of adding this line to every project, can we create a `.eslintignore` file in the root of the workspace with ` node_modules` in it?

2023-02-14 20:33 UTC, barbados-clemens approved these changes

2023-02-15 22:06 UTC, FrozenPandaz approved these changes

2023-02-15 22:06 UTC, merged