feat(core): add interactive env var
nrwl/nx pull request #14994
Opened 2023-02-14 18:00 UTC by Coly010

Add a `NX_INTERACTIVE` env var that can be used from generators to determine if they can run interactive logic such as handling prompts.
Move the setting of `NX_DRY_RUN` to the yargs handler of the `generate` command so it is as visible as possible.

2023-02-14 18:03 UTC, AgentEnder commented
I really think some of this may make sense in a GeneratorContext object, but I know @FrozenPandaz has been against that in the past.

I imagine something like

```typescript 
export interface GeneratorContext {
  projectGraphSnapshot: ProjectGraph
  dryRun: boolean
  interactive: boolean
}
```

2023-02-14 18:09 UTC, FrozenPandaz submitted a review, later dismissed

2023-02-14 18:09 UTC, FrozenPandaz commented on packages/nx/src/command-line/nx-commands.ts
> +      process.env.NX_DRY_RUN = process.env.NX_DRY_RUN ?? `${args.dryRun}`;
I think you can move these to a `.middleware()` call in `withGenerateOptions`. Also set `args.interactive` to `true` when `process.env.NX_INTERACTIVE !== 'false'`

2023-02-15 15:54 UTC, AgentEnder requested changes

2023-02-15 16:16 UTC, AgentEnder approved these changes

2023-02-16 09:37 UTC, juristr approved these changes

2023-02-16 13:55 UTC, merged