feat(core): allow loading env vars by target and configuration
nrwl/nx pull request #14998
Opened 2023-02-14 20:55 UTC by AgentEnder

## Current Behavior
Nx can load env vars by target name

## Expected Behavior
Nx can load env vars by target name combined with configuration

## Related Issue(s)

Fixes #14931

2023-02-14 21:20 UTC, FrozenPandaz requested changes
Double Triple check the order in the code and the docs.

2023-02-14 21:47 UTC, FrozenPandaz approved these changes

2023-02-14 22:09 UTC, bcabanes approved these changes

2023-02-14 22:24 UTC, merged

2023-02-15 11:00 UTC, the-ult commented
Great PR. Thanks.

Are the docs gonna be updated as well?

2023-02-15 15:55 UTC, AgentEnder commented
The docs updates are in this PR

2023-02-15 16:08 UTC, the-ult commented
> The docs updates are in this PR

Ow.. You're right. Thought it where the tests. My bad.

Thanks again 👍

2023-02-26 17:01 UTC, mathura333 commented
@AgentEnder Shouldn't we also load `apps/my-app/.env.[configuration-name]`, `apps/my-app/.[configuration-name].env`, , `.env.[configuration-name]` , `.[configuration-name].env`?

This is a very common requirement