fix(webpack): add babelUpwardRootMode
nrwl/nx pull request #15061
Opened 2023-02-16 15:59 UTC by mandarini

## Current Behavior
If you try to import a js library in a `@nrwl/webpack:webpack` project, then the build fails, unless your library contains a `.babelrc` file. This is due to the `rootmode: 'upward'` setting that's used in the webpack executor.

## Expected Behavior
Libraries that don't specifically need a `.babelrc`, should not require one.

In this PR, we are adding a flag to allow users to set `rootmode: 'upward'` if they need to, and only in that case we are using `rootmode: 'upward'` in the webpack executor. In the other cases, we are setting the `.babelrc` path to be that of the parent app we are building, so that the executor will not look elsewhere for a `.babelrc` file.

## Related Issue(s)

Fixes #14807

2023-02-16 16:02 UTC, jaysoo approved these changes

2023-02-16 17:49 UTC, nartc requested changes
This breaks the following flow:

```shell
npx nx g @nrwl/react:app my-react-app
npx nx build my-react-app # fails due to .babelrc is missing in src/.babelrc (generated .babelrc is in project root rather than source root)
```

-> Fix: turn on `babelUpwardRootMode: true` in `build` target

The `@nrwl/js` code (that gets deleted) might need to readjust but I think it still needs to be there. The following flow fails:

```shell
npx nx g @nrwl/js:lib my-js-lib
```

use `myJsLib()` in `my-react-app`

```shell
npx nx build my-react-app # fails due to my-js-lib is missing babelrc
```

--> Fix: add `.babelrc` manually or generate a lib with `--include-babel-rc`

2023-02-17 13:08 UTC, mandarini commented
@nartc thanks for the review. It was a stupid typo on my end, instead of project root, I used src root to specify the location of the project's `.babelrc` file. So, it didn't find it. Now that it finds it, then all else works as expected.

The reason behind this PR is to remove `.babelrc` from `js` libs, since it's not really needed.

2023-02-17 13:34 UTC, nartc approved these changes

2023-02-17 17:09 UTC, merged