Ensure package2
nrwl/nx pull request #15074
Opened 2023-02-16 22:04 UTC by FrozenPandaz

## Current Behavior

`ensurePackage` does not work with `pnpm` as the files that are currently executing may get moved entirely.

`ensurePackage` does more of its fair share:
1. Installs the package into the workspace
2. Allows requiring later on
3. Doesn't update the `Tree` with the updated `package.json` yet appears after the generate command.

## Expected Behavior

`ensurePackage` will work with `pnpm`.

1. Installs the package into a tmp directory
2. Allows requiring later on
3. Will not accept a Tree anymore
4. Will not update the Tree. That should be done via `addDependenciesToPackageJson`

## Related Issue(s)

Fixes #

2023-02-16 22:20 UTC, AgentEnder submitted a review, later dismissed

2023-02-16 22:20 UTC, AgentEnder commented on packages/devkit/src/utils/package-json.ts
> +  }
Do we still need this? It  seems like this part should actually work in dry run with the new mode since its not installing in the repo.

2023-02-16 22:20 UTC, AgentEnder commented on packages/devkit/src/utils/package-json.ts
> +  console.log('Installing', pkg);
Remove

2023-02-16 22:20 UTC, AgentEnder commented on packages/devkit/src/utils/package-json.ts
> +  console.log('after install');
Remove

2023-02-16 22:20 UTC, AgentEnder commented on packages/devkit/src/utils/package-json.ts
>   * When running with --dryRun, the function will throw when dependencies are missing.
I don't think this part has to be true anymore.

2023-02-16 22:20 UTC, AgentEnder commented on packages/nx/src/utils/nx-plugin.ts
> +import { ensureTypescript } from '@nrwl/js/src/utils/typescript/ensure-typescript';
This probably needs to actually be used, or removed more likely. nx shouldn't import from @nrwl/js right?

2023-02-16 22:27 UTC, nartc approved these changes
LGTM on `nrwl/js` side

2023-02-17 09:36 UTC, leosvelperez requested changes

2023-02-17 09:36 UTC, leosvelperez commented on packages/angular/src/generators/change-storybook-targets/change-storybook-targets.ts
> +  );
I'm unsure whether it is an issue, but better to leave formatting as the last thing to do. We don't have to double-guess or rely on whether the `addDependenciesToPackageJson` make changes with the right formatting:
```suggestion
  const installTask = addDependenciesToPackageJson(
    tree,
    {},
    { '@nrwl/storybook': nxVersion }
  );

  if (!schema.skipFormat) {
    await formatFiles(tree);
  }

  return installTask;
```

2023-02-17 09:36 UTC, leosvelperez commented on packages/angular/src/generators/init/angular-v14/init.ts
> +          addDependenciesToPackageJson(host, {}, { pkg: devkitVersion })
```suggestion
          addDependenciesToPackageJson(host, {}, { [pkg]: devkitVersion })
```

2023-02-17 09:36 UTC, leosvelperez commented on packages/angular/src/generators/init/init.ts
> +          addDependenciesToPackageJson(tree, {}, { pkg: devkitVersion })
```suggestion
          addDependenciesToPackageJson(tree, {}, { [pkg]: devkitVersion })
```

2023-02-17 09:36 UTC, leosvelperez commented on packages/angular/src/generators/init/angular-v14/init.ts
> +        // @schematics/angular cannot be required so this fails but that's we will still be ble to wrap the schematic later on
nit:
```suggestion
        // @schematics/angular cannot be required so this fails but this will still allow us to wrap the schematic later on
```

2023-02-17 09:36 UTC, leosvelperez commented on packages/angular/src/generators/init/init.ts
> +        // @schematics/angular cannot be required so this fails but that's we will still be ble to wrap the schematic later on
nit:
```suggestion
        // @schematics/angular cannot be required so this fails but this will still allow us to wrap the schematic later on
```

2023-02-17 11:32 UTC, mandarini approved these changes

2023-02-17 14:54 UTC, barbados-clemens approved these changes
Looks good from jest/cypress side

2023-02-17 19:33 UTC, xiongemi approved these changes

2023-02-20 09:04 UTC, leosvelperez approved these changes

2023-02-22 11:51 UTC, meeroslav approved these changes
Linter part looks good!

2023-02-22 14:01 UTC, barbados-clemens approved these changes
cypress/jest look fine. just had a non-blocking question on if jest/cypress really need to call the jsInitGenerator.

2023-02-22 14:01 UTC, barbados-clemens commented on packages/cypress/src/generators/init/schema.d.ts
> +
nitpick: extra space. nx format will probably catch it.

2023-02-22 23:11 UTC, FrozenPandaz commented on packages/jest/src/generators/init/init.ts
> +    })
Okay, we can investigate removing it.

I think jest needs it for `tsconfig.spec.json`?

2023-02-22 23:13 UTC, AgentEnder approved these changes

2023-02-22 23:47 UTC, merged