feat(core): use the native hasher by default
nrwl/nx pull request #15071
Opened 2023-02-16 19:51 UTC by Cammisuli

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-02-16 22:06 UTC, FrozenPandaz requested changes
Slow down there. Let's make it default and allow people to opt out. Keep the other code.

2023-02-17 15:17 UTC, AgentEnder approved these changes

2023-02-17 15:48 UTC, AgentEnder commented on packages/nx/src/utils/testing/temp-fs.ts
> +export class TempFs {
My presumption is that memfs doesn't work with rust's fs access calls. I could be wrong though 🤷. Lets let @Cammisuli respond.

2023-02-17 16:03 UTC, Cammisuli commented on packages/nx/src/utils/testing/temp-fs.ts
> +export class TempFs {
@AgentEnder is correct.

2023-02-17 22:16 UTC, FrozenPandaz approved these changes

2023-02-17 22:17 UTC, merged

2023-03-02 14:32 UTC, LongLiveCHIEF commented
@Cammisuli @FrozenPandaz I think this should be reverted, or logic should be inverted. Many development teams are cross-platform, and additionally, CI environments are on Linux.  A common practice is to freeze dependencies for scanning and change control auditing purposes in release builds.  This means teams will have failures in pipelines/builds that are in different environments than the one yarn/npm was initially run on.

2023-03-02 14:32 UTC, LongLiveCHIEF commented
Also, there was no documentation added for this as far as I can see.