fix(core): skip dev files dependencies on create-package-json
nrwl/nx pull request #15122
Opened 2023-02-20 10:20 UTC by meeroslav

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #14981

2023-02-20 11:34 UTC, skrtheboss commented
Hi, another solution would be the one i have implemented in #13966. Maybe you should have a look.

2023-02-20 16:35 UTC, AgentEnder requested changes

2023-02-20 16:35 UTC, AgentEnder commented on packages/nx/src/utils/create-package-json.ts
> +];
Can we read the supported patterns from inputs and exclude files that don't match instead of hard coding this?

2023-02-21 12:37 UTC, meeroslav commented
@skrtheboss, thank you. I was not aware of your PR. Good job!

Some things should be improved. I'll look to see if it's easier to apply modifications to your PR or mine.

2023-03-06 10:51 UTC, meeroslav commented
Closing in favor of https://github.com/nrwl/nx/pull/13966

2023-03-06 10:51 UTC, closed without merging