feat(storybook): version 7 automigrate integration
nrwl/nx pull request #15136
Opened 2023-02-20 17:52 UTC by mandarini

Integration with `automigrate` from Storybook.

2023-02-24 15:01 UTC, Coly010 approved these changes

2023-02-24 15:31 UTC, jaysoo approved these changes

2023-02-24 15:41 UTC, bcabanes approved these changes

2023-02-28 16:24 UTC, FrozenPandaz requested changes

2023-02-28 16:24 UTC, FrozenPandaz commented on packages/storybook/src/generators/migrate-7/helper-functions.ts
> +## Final adjustments
Move this to an ejs template

2023-03-01 18:41 UTC, FrozenPandaz approved these changes

2023-03-01 18:41 UTC, merged