docs(testing): clarify apps & libs can be component tested
nrwl/nx pull request #15261
Opened 2023-02-25 03:29 UTC by barbados-clemens

## Current Behavior

unsure what I can CT
## Expected Behavior

explain both apps and libs should work

## Related Issue(s)

Fixes #12960

2023-02-25 16:35 UTC, bcabanes approved these changes

2023-02-26 02:48 UTC, isaacplmann requested changes
typo

2023-02-26 02:48 UTC, isaacplmann commented on docs/generated/packages/cypress/documents/cypress-component-testing.md
> +The configuration generators support both application and library types, so while a `--build-target` flag might be needed, it does not need to the build target of the same project you are trying to a
```suggestion
The configuration generators support both application and library types, so while a `--build-target` flag might be needed, it does not need to be the build target of the same project you are trying to add component testing too.
```

2023-02-26 02:48 UTC, isaacplmann commented on docs/shared/packages/cypress/cypress-component-testing.md
> +The configuration generators support both application and library types, so while a `--build-target` flag might be needed, it does not need to the build target of the same project you are trying to a
```suggestion
The configuration generators support both application and library types, so while a `--build-target` flag might be needed, it does not need to be the build target of the same project you are trying to add component testing too.
```

2023-02-27 14:28 UTC, isaacplmann approved these changes

2023-02-28 21:28 UTC, FrozenPandaz requested changes

2023-02-28 21:28 UTC, FrozenPandaz commented on docs/generated/packages/cypress/documents/cypress-component-testing.md
> +The configuration generators support both application and library types, so while a `--build-target` flag might be needed, it does not need to be the build target of the same project you are trying t
```suggestion
Component testing supports both applications and libraries. By default, the generator attempts to find the build target for you based on the project's dependent apps. But you can manually specify the build target to use via the `--build-target` option. Note, in most cases, the build target will be from a different project than the one being configured. The only case where the build targets are from the same project is when the component tests are being added to an application.
```

2023-02-28 21:34 UTC, FrozenPandaz approved these changes

2023-02-28 21:43 UTC, merged