feat(web): add a generator to add @nrwl/web:file-server target
nrwl/nx pull request #15434
Opened 2023-03-03 21:18 UTC by barbados-clemens

## Current Behavior

no automated way to setup @nrwl/web:file-server to serve my static files contents 

## Expected Behavior

generator to setup a 'serve-static' (configurable) target for my project

## Related Issue(s)

this is the start of making feature based testing easier/more robust with nx.

2023-03-03 21:38 UTC, barbados-clemens commented on packages/web/generators.json
> +    "static-config": {
Unsure what we want to name this, but figured I'd start here

2023-03-03 21:42 UTC, barbados-clemens commented on packages/web/src/generators/static-serve/static-serve-configuration.ts
> +    }
unsure if we want to do this, but figured trying to find the output if the target doesn't have 'outputPath' would be helpful for those setting up the static target

2023-03-03 23:43 UTC, isaacplmann requested changes

2023-03-03 23:43 UTC, isaacplmann commented on docs/generated/packages/web/generators/static-config.json
> +        "description": "Path to the directory of the built files. This is only optional if buildTarget doesn't specify an outputPath executor option."
```suggestion
        "description": "Path to the directory of the built files. This is only needed if buildTarget doesn't specify an outputPath executor option."
```

2023-03-03 23:43 UTC, isaacplmann commented on packages/web/src/generators/static-serve/schema.json
> +      "description": "Path to the directory of the built files. This is only optional if buildTarget doesn't specify an outputPath executor option."
```suggestion
      "description": "Path to the directory of the built files. This is only needed if buildTarget doesn't specify an outputPath executor option."
```

2023-03-06 09:51 UTC, mandarini approved these changes

2023-03-07 13:30 UTC, isaacplmann approved these changes

2023-03-07 19:09 UTC, merged