cleanup(misc): remove add-nx-to-monorepo package
nrwl/nx pull request #15498
Opened 2023-03-07 11:34 UTC by leosvelperez

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-03-07 23:21 UTC, FrozenPandaz requested changes
Before we actually stop publishing `add-nx-to-monorepo` could we publish a final version where it redirects `npx nx@latest init`?

2023-04-06 14:00 UTC, barbados-clemens approved these changes

2023-04-06 14:18 UTC, meeroslav approved these changes

2023-04-06 14:31 UTC, AgentEnder approved these changes

2023-04-11 15:53 UTC, FrozenPandaz approved these changes

2023-04-12 15:37 UTC, isaacplmann approved these changes

2023-04-12 15:41 UTC, merged