feat(core): move replaceAppNameWithPath to Devkit
nrwl/nx pull request #15493
Opened 2023-03-07 10:04 UTC by Coly010

## Current Behavior

replaceAppNameWithPath is used in multiple plugins via a deep import to @nrwl/workspace

## Expected Behavior

Move the function to Devkit as it is related to devkit-logic
Deprecate the existing fuction in @nrwl/workspace to allow plugin authors time to migrate.

## Related Issue(s)

Fixes #

2023-03-07 11:46 UTC, leosvelperez reviewed
I have my doubts about making this function part of the DevKit public API. It's probably not something generic enough to make it available for everyone. The logic is Angular-specific and it's only used on the Angular plugin. I would inline it in the Angular plugin utils.

2023-03-07 14:00 UTC, leosvelperez requested changes

2023-03-07 14:00 UTC, leosvelperez commented on packages/angular/src/generators/application/lib/update-config-files.ts
> +
Remove blank line

2023-03-07 14:00 UTC, leosvelperez commented on packages/angular/src/generators/application/angular-v14/lib/update-config-files.ts
> +
Let's remove this blank line, it's not a needed change.

2023-03-07 14:00 UTC, leosvelperez commented on packages/angular/src/utils/cli-config-utils.spec.ts
> +    describe('and appName is `app`', () => {
Too many `describe`s, we can simplify this.

2023-03-07 14:00 UTC, leosvelperez commented on packages/angular/src/utils/cli-config-utils.spec.ts
> +    describe('and appName is `lib`', () => {
Same as previous.

2023-03-07 14:00 UTC, leosvelperez commented on packages/angular/src/utils/cli-config-utils.ts
> +      'browserTarget',
I know this is a copy and paste from existing functionality and not an issue introduced by this PR, but we also have a `buildTarget` property in some of our builders that is similar to `browserTarget`. We should probably include it in this list as well.

2023-03-07 15:25 UTC, mandarini approved these changes

2023-03-07 15:51 UTC, leosvelperez approved these changes

2023-03-07 23:22 UTC, FrozenPandaz requested changes

2023-03-07 23:22 UTC, FrozenPandaz commented on packages/workspace/src/utils/cli-config-utils.ts
>  export function replaceAppNameWithPath(
I don't think anyone is using this:

https://grep.app/search?q=replaceAppNameWithPath&case=true&filter[lang][0]=TypeScript

Let's remove it.

2023-03-08 18:05 UTC, AgentEnder approved these changes

2023-03-08 23:28 UTC, FrozenPandaz approved these changes

2023-03-08 23:28 UTC, merged