feat(angular): remove protractor
nrwl/nx pull request #15627
Opened 2023-03-13 11:55 UTC by Coly010

## Current Behavior

We currently still offer ways to use protractor

## Expected Behavior

We should not offer methods to use protractor unless user has migrated a workspace with an existing setup

## Related Issue(s)

Fixes #

2023-03-13 16:02 UTC, leosvelperez requested changes

2023-03-13 16:02 UTC, leosvelperez commented on packages/angular/src/utils/versions.ts
> -export const protractorVersion = '~7.0.0';
Please check other package versions here that were only needed for Protractor and remove them as well.

2023-03-13 16:02 UTC, leosvelperez commented on packages/angular/src/utils/backward-compatible-versions.ts
> -    protractorVersion: '~7.0.0',
Please check other package versions here that were only needed for Protractor and remove them as well.

2023-03-13 18:01 UTC, bcabanes approved these changes

2023-03-14 09:48 UTC, leosvelperez approved these changes

2023-03-16 16:37 UTC, FrozenPandaz approved these changes

2023-03-16 16:38 UTC, merged