cleanup(angular): replace usage of wrapAngularDevkitSchematics for application
nrwl/nx pull request #15698
Opened 2023-03-15 16:06 UTC by Coly010

## Current Behavior

We currently rely on running the Angular Application Generator from @schematics/angular first before we modify the output to suit Nx.

## Expected Behavior

We should generate what we need ourselves

## Related Issue(s)

Fixes #

2023-03-16 10:46 UTC, leosvelperez requested changes

2023-03-16 10:46 UTC, leosvelperez commented on packages/angular/src/generators/application/files/ng-module/src/app/app.component.spec.ts__tpl__
> +  <% } %>
Let's remove the useless `should create the app` test case and rearrange the rest based on proposed changes to the component generation:
```suggestion
  it('should render title', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.nativeElement as HTMLElement;
    expect(compiled.querySelector('h1')?.textContent).toContain('Welcome <%= appName %>');
  });<% if(!minimal) { %>

  it(`should have as title '<%= appName %>'`, () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app.title).toEqual('<%= appName %>');
  });<% } %>
```

2023-03-16 10:46 UTC, leosvelperez commented on packages/angular/src/generators/application/files/ng-module/src/app/app.component.ts__tpl__
> +}
Let's remove the `title` variable for `minimal`:
```suggestion
export class AppComponent {<% if(!minimal) { %>
  title = '<%= appName %>';
<% } %>}
```

2023-03-16 10:46 UTC, leosvelperez commented on packages/angular/src/generators/application/files/standalone-components/src/app/app.component.spec.ts__tpl__
> +  <% } %>
```suggestion
  it('should render title', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.nativeElement as HTMLElement;
    expect(compiled.querySelector('h1')?.textContent).toContain('Welcome <%= appName %>');
  });<% if(!minimal) { %>
  it(`should have as title '<%= appName %>'`, () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app.title).toEqual('<%= appName %>');
  });<% } %>
```

2023-03-16 10:46 UTC, leosvelperez commented on packages/angular/src/generators/application/files/standalone-components/src/app/app.component.ts__tpl__
> +}
```suggestion
export class AppComponent {<% if(!minimal) { %>
  title = '<%= appName %>';
<% } %>}
```

2023-03-16 10:46 UTC, leosvelperez commented on packages/angular/src/generators/application/files/ng-module/src/app/nx-welcome.component.ts__tpl__
> +      #nx-console:hover {
Let's avoid changes to the existing template, aside from formatting.

2023-03-16 10:46 UTC, leosvelperez commented on packages/angular/src/generators/application/files/standalone-components/src/app/nx-welcome.component.ts__tpl__
Check this as well.

2023-03-16 10:46 UTC, leosvelperez commented on packages/angular/src/generators/application/lib/create-project.ts
> +        },
```suggestion
        options: options.port
          ? {
            port: options.port,
          }
          : undefined,
```

2023-03-16 10:56 UTC, Coly010 commented on packages/angular/src/generators/application/files/base/tsconfig.app.json__tpl__
> +  "exclude": ["jest.config.ts", "src/**/*.test.ts", "src/**/*.spec.ts"]
This is existing behaviour so we can address this in a future PR

2023-03-16 11:46 UTC, leosvelperez requested changes
Some few minor things left

2023-03-16 11:46 UTC, leosvelperez commented on packages/angular/src/generators/application/files/ng-module/src/app/app.component.spec.ts__tpl__
> +  it(`should have as title '<%= appName %>'`, () => {
```suggestion
  });<% if(!minimal) { %>

  it(`should have as title '<%= appName %>'`, () => {
```

2023-03-16 11:46 UTC, leosvelperez commented on packages/angular/src/generators/application/files/ng-module/src/main.ts__tpl__
> +import { AppModule } from './app/app.module';
This change is still missing

2023-03-16 11:46 UTC, leosvelperez commented on packages/angular/src/generators/application/files/standalone-components/src/app/app.component.spec.ts__tpl__
> +  it(`should have as title '<%= appName %>'`, () => {
```suggestion
  });<% if(!minimal) { %>

  it(`should have as title '<%= appName %>'`, () => {
```

2023-03-16 11:46 UTC, leosvelperez commented on packages/angular/src/generators/application/files/standalone-components/src/app/app.component.spec.ts__tpl__
> +  it(`should have as title '<%= appName %>'`, () => {
```suggestion
  });<% if(!minimal) { %>

  it(`should have as title '<%= appName %>'`, () => {
```

2023-03-16 11:46 UTC, leosvelperez commented on packages/angular/src/generators/application/files/standalone-components/src/app/nx-welcome.component.ts__tpl__
> +/* eslint-disable */
Remove

2023-03-17 08:34 UTC, leosvelperez approved these changes

2023-03-17 08:34 UTC, merged