cleanup(angular): replace wrapAngularDevkitSchematics in library generator
nrwl/nx pull request #15714
Opened 2023-03-16 15:11 UTC by Coly010

## Current Behavior

We use wrapAngularDevkitSchematics when we create Angular libraries.

## Expected Behavior

Generate the files ourselves

## Related Issue(s)

Fixes #

2023-03-17 09:49 UTC, leosvelperez requested changes

2023-03-17 09:49 UTC, leosvelperez commented on packages/angular/src/generators/library/files/base/tsconfig.json__tpl__
> +    }<% } %>
I just realized we shouldn't handle any test-related config & files (except spec files) in the `library` generator. We invoke the `jestProject` generator and that one sets up any file and config needed for a project. It handles this change and others we're doing in this PR.

The same applies to what we already did in the `application` generator. We need to amend that.

2023-03-17 09:49 UTC, leosvelperez commented on packages/angular/src/generators/library/files/base/tsconfig.spec.json__tpl__
Remove this file

2023-03-17 09:49 UTC, leosvelperez commented on packages/angular/src/generators/library/files/base/package.json__tpl__
> +  "name": "<%= npmScope %><%= libFileName %>",
`npmScope` might not be defined. It's not a required property of the `nx.json` and we're missing the `/` here.
```suggestion
  "name": "<% if (npmScope) { %><%= npmScope %>/<% } %><%= libFileName %>",
```

2023-03-17 09:49 UTC, leosvelperez commented on packages/angular/src/generators/library/lib/create-files.ts
> +  }
Remove this

2023-03-17 09:49 UTC, leosvelperez commented on packages/angular/src/generators/library/files/lib/README.md__tpl__
Why are we removing the `README`?

2023-03-17 09:49 UTC, leosvelperez commented on packages/angular/src/generators/library/lib/update-project.ts
>    updateNgPackage(host, options);
Do we still need to update `ng-package.json` here? The template should have all that's needed, isn't it?

2023-03-17 09:49 UTC, leosvelperez commented on packages/angular/src/generators/library/lib/update-project.ts
>    updateProjectTsConfig(host, options);
Do we still need to update the tsconfig here? The template should have all that's needed, isn't it?

2023-03-17 16:56 UTC, leosvelperez commented on packages/angular/src/generators/library/files/base/tsconfig.json__tpl__
> +    }<% } %>
I created a PR for the application generator to address this https://github.com/nrwl/nx/pull/15731.

2023-03-20 09:51 UTC, Coly010 commented on packages/angular/src/generators/library/files/lib/README.md__tpl__
bad copy i think

2023-03-20 09:52 UTC, Coly010 commented on packages/angular/src/generators/library/files/lib/README.md__tpl__
actually, it's just been moved

2023-03-20 14:01 UTC, leosvelperez approved these changes

2023-03-20 14:01 UTC, merged