feat(nextjs): update nextjs version to 13.2.3
nrwl/nx pull request #15723
Opened 2023-03-16 20:22 UTC by ndcunningham

2023-03-16 20:36 UTC, FrozenPandaz requested changes

2023-03-16 20:36 UTC, FrozenPandaz commented on packages/next/migrations.json
> +          "version": "13.2.3",
Latest is `13.2.4`. Let's use that.

2023-03-16 20:36 UTC, FrozenPandaz commented on packages/next/migrations.json
> +      "version": "15.8.6-beta.0",
Can you change this to `15.9.0-beta.4` please?

2023-03-16 20:36 UTC, FrozenPandaz commented on packages/next/src/utils/versions.ts
> +export const nextVersion = '13.2.3';
Use `13.2.4`

2023-03-17 23:38 UTC, terrymun commented
I noticed that the [storybook build seems to have stalled at 64%](https://app.circleci.com/pipelines/github/nrwl/nx/29535/workflows/d8f79c38-7292-429a-87a7-9ff0c3505ab2/jobs/299152/parallel-runs/0/steps/0-114) due to an error thrown by webpack:

```
ERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve 'crypto' in '/tmp/nx-e2e--1922-u6fp8WcLr0u2/nx/proj/node_modules/next/dist/shared/lib/bloom-filter'
ERR! 
ERR! BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
ERR! This is no longer the case. Verify if you need this module and configure a polyfill for it.
ERR! 
ERR! If you want to include a polyfill, you need to:
ERR! 	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
ERR! 	- install 'crypto-browserify'
ERR! If you don't want to include a polyfill, you can use an empty module like this:
ERR! 	resolve.fallback: { "crypto": false }
```

I've experienced the same too, and had to remove `crypto` as a fallback in the webpack config on storybook's `main.js` or `main.ts` file:

```ts
webpackFinal: async (config) => {
  if (config.resolve) {
    config.resolve = {
      ...config.resolve,
      fallback: {
        ...config.resolve.fallback,
        crypto: false,
      },
    };
  }
 
  return config;
},
```

2023-03-30 18:45 UTC, closed without merging