feat(react-native): update @react-native-community/cli to 10.2.1
nrwl/nx pull request #15738
Opened 2023-03-17 17:37 UTC by xiongemi

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-03-21 14:56 UTC, jaysoo approved these changes

2023-03-21 14:57 UTC, jaysoo commented on docs/generated/packages/react-native/documents/overview.md
> +To builds IOS app:
typo: `iOS` not `IOS`.

2023-03-21 15:30 UTC, xiongemi commented on docs/generated/packages/react-native/documents/overview.md
> +To builds IOS app:
fixed.

2023-03-21 17:37 UTC, ndcunningham approved these changes

2023-03-24 16:13 UTC, isaacplmann requested changes

2023-03-24 16:13 UTC, isaacplmann commented on docs/shared/packages/react-native/react-native-plugin.md
> +This is a command that will replace the iOS and Android entirely.
Replace the iOS and Android what?

2023-03-24 16:13 UTC, isaacplmann commented on docs/shared/packages/react-native/react-native-plugin.md
> +You can also upgrade React Native iOS and Android code use project [rn-diff-purge](https://react-native-community.github.io/upgrade-helper/).
```suggestion
You can also upgrade React Native iOS and Android code using the [rn-diff-purge](https://react-native-community.github.io/upgrade-helper/) project.
```

2023-03-24 16:13 UTC, isaacplmann commented on docs/shared/packages/react-native/react-native-plugin.md
> +To build your app and starts it on iOS simulator or device:
```suggestion
To build your app and start it on iOS simulator or device:
```

2023-03-24 16:13 UTC, isaacplmann commented on docs/shared/packages/react-native/react-native-plugin.md
> +To build your app and starts it on a connected Android emulator or device:
```suggestion
To build your app and start it on a connected Android emulator or device:
```

2023-03-24 16:13 UTC, isaacplmann commented on docs/shared/packages/react-native/react-native-plugin.md
> +To builds iOS app:
```suggestion
To build an iOS app:
```

2023-03-24 16:13 UTC, isaacplmann commented on docs/shared/packages/react-native/react-native-plugin.md
> +You can specify the build folder by passing option `buildFolder`:
```suggestion
You can specify the build folder by setting the `buildFolder` option:
```

2023-03-24 16:13 UTC, isaacplmann commented on docs/shared/packages/react-native/react-native-plugin.md
> +To build Android app, run:
```suggestion
To build an Android app, run:
```

2023-03-24 16:18 UTC, xiongemi commented on docs/shared/packages/react-native/react-native-plugin.md
> +You can also upgrade React Native iOS and Android code use project [rn-diff-purge](https://react-native-community.github.io/upgrade-helper/).
done.

2023-03-24 16:19 UTC, xiongemi commented on docs/shared/packages/react-native/react-native-plugin.md
> +To build your app and starts it on iOS simulator or device:
changed

2023-03-24 16:19 UTC, xiongemi commented on docs/shared/packages/react-native/react-native-plugin.md
> +To build your app and starts it on a connected Android emulator or device:
changed

2023-03-24 16:20 UTC, xiongemi commented on docs/shared/packages/react-native/react-native-plugin.md
> +To builds iOS app:
changed.

2023-03-24 16:20 UTC, xiongemi commented on docs/shared/packages/react-native/react-native-plugin.md
> +You can specify the build folder by passing option `buildFolder`:
changed.

2023-03-24 16:50 UTC, isaacplmann approved these changes

2023-03-24 16:51 UTC, merged