fix(angular): use @nrwl/web:file-server
nrwl/nx pull request #15849
Opened 2023-03-23 11:49 UTC by Coly010

## Current Behavior

We have a duplicated file-server executor in nrwl/angular

## Expected Behavior

Use the @nrwl/web as the file-server executor

## Related Issue(s)

Fixes #

2023-03-23 14:11 UTC, leosvelperez requested changes
There's the following TODO that was left for when this was done https://github.com/nrwl/nx/blob/master/packages/angular/src/generators/application/lib/add-e2e.ts#L15-L16.

2023-03-23 14:55 UTC, mandarini approved these changes

2023-03-23 15:38 UTC, leosvelperez requested changes

2023-03-23 15:38 UTC, leosvelperez commented on packages/angular/src/migrations/update-15-9-0/update-file-server-executor.ts
> +  }
Sorry, I missed it before, let's format files at the end of the migration.

2023-03-23 16:02 UTC, leosvelperez approved these changes

2023-03-24 19:50 UTC, jaysoo approved these changes

2023-03-24 20:03 UTC, bcabanes approved these changes

2023-03-27 08:42 UTC, merged