fix(storybook): proper user prompts for config generator
nrwl/nx pull request #15860
Opened 2023-03-23 15:30 UTC by mandarini

We should only ask the user what needs to be asked:

1. If user chooses storybook 7 config, ask for v7 framework
2. If user chooses storybook 6, ask for v6 framework
3. Ask for builder only if user chooses react or wc

2023-03-23 16:02 UTC, FrozenPandaz requested changes

2023-03-23 16:03 UTC, mandarini commented on packages/storybook/src/generators/configuration/configuration.ts
> +  getGeneratorConfigurationOptions(rawSchema);
Ohhhhh good call!

2023-03-27 10:51 UTC, Coly010 approved these changes

2023-03-27 12:23 UTC, jaysoo approved these changes

2023-03-27 14:44 UTC, FrozenPandaz approved these changes

2023-03-27 14:44 UTC, merged