feat(nx-plugin): add create-package plugin
nrwl/nx pull request #15872
Opened 2023-03-24 05:43 UTC by xiongemi

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-03-24 15:56 UTC, AgentEnder requested changes
This looks good, there are a few changes

2023-03-24 15:56 UTC, AgentEnder commented on packages/nx-plugin/src/generators/create-package/create-package.ts
> +  addDependenciesToPackageJson(
This task needs to be returned

2023-03-24 15:56 UTC, AgentEnder commented on packages/nx-plugin/src/generators/create-package/schema.json
> +    },
Lets not add this for new generators

2023-03-28 17:44 UTC, xiongemi commented on packages/nx-plugin/src/generators/create-package/create-package.ts
> +  addDependenciesToPackageJson(
changed

2023-04-03 18:47 UTC, closed without merging