chore(react): improve react e2e tests speed
nrwl/nx pull request #15997
Opened 2023-03-31 05:39 UTC by xiongemi

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-04-03 09:35 UTC, mandarini approved these changes

2023-04-04 22:29 UTC, AgentEnder requested changes

2023-04-04 22:29 UTC, AgentEnder commented on e2e/react-core/src/react-module-federation.test.ts
Can you update the CODEOWNERs files for the new paths?

2023-04-05 13:30 UTC, barbados-clemens reviewed
just a small name change so we know which projects we are looking at in the logs.

2023-04-05 13:30 UTC, barbados-clemens commented on e2e/react-extensions/jest.config.ts
> +  displayName: 'e2e-react',
```suggestion
  displayName: 'e2e-react-extensions',
```

2023-04-05 14:58 UTC, xiongemi commented on e2e/react-extensions/jest.config.ts
> +  displayName: 'e2e-react',
changed

2023-04-05 20:08 UTC, xiongemi commented on e2e/react-core/src/react-module-federation.test.ts
in the CODEOWNERS, it points to entire /e2e/**/* folder. but I did update the codeowners in .github/workflows/e2e-matrix.yml

2023-04-05 20:30 UTC, AgentEnder commented on e2e/react-core/src/react-module-federation.test.ts
That's just a fallback - under the react vertical there are specific entries for e2e that need to be updated.

2023-04-05 20:30 UTC, AgentEnder commented on e2e/react-core/src/react-module-federation.test.ts
This line:
```
/e2e/react/** @jaysoo @mandarini @xiongemi @ndcunningham
```
Should change to something like:
```
/e2e/react*/** @jaysoo @mandarini @xiongemi @ndcunningham
```

2023-04-05 22:02 UTC, barbados-clemens approved these changes

2023-04-06 11:35 UTC, meeroslav approved these changes
I have rebased the repo, so the issue with `e2e-react` should no longer appear.

Unfortunately latest master also brings another bug fixed in https://github.com/nrwl/nx/pull/16152

2023-04-06 16:55 UTC, jaysoo approved these changes

2023-04-06 19:32 UTC, xiongemi commented on e2e/react-core/src/react-module-federation.test.ts
changed.

2023-04-14 19:34 UTC, AgentEnder approved these changes

2023-04-14 20:43 UTC, FrozenPandaz approved these changes

2023-04-14 20:43 UTC, merged