docs(node): Add recipe for deploying serverless functions to Netlify
nrwl/nx pull request #16068
Opened 2023-04-03 17:10 UTC by ndcunningham

2023-04-03 18:13 UTC, bcabanes requested changes

2023-04-03 18:13 UTC, bcabanes commented on docs/shared/recipes/deployment/node-serverless-functions-netlify.md
> +```bash
Please use `shell` instead.

2023-04-03 18:28 UTC, jaysoo commented on docs/map.json
> +              "name": "Deploying Node serverless functions to Netlify",
Use `Node.js` over `Node`, and make sure it consistent in the recipe.

2023-04-03 18:28 UTC, jaysoo commented on docs/shared/recipes/deployment/node-serverless-functions-netlify.md
> +## New workspaces
Rename to `Creating the project` for consistency with the other recipe.

2023-04-03 18:29 UTC, jaysoo commented on docs/shared/recipes/deployment/node-serverless-functions-netlify.md
> +## Existing
Update as `### Configure existing projects` for consistency.

2023-04-03 21:36 UTC, jaysoo approved these changes

2023-04-04 17:08 UTC, bcabanes approved these changes

2023-04-04 20:20 UTC, merged