fix(testing): allow removing projects in standalone apps
nrwl/nx pull request #16093
Opened 2023-04-04 18:43 UTC by barbados-clemens

## Current Behavior

error trying to remove e2e project in standalone app
```
 >  NX   Could not remove e2e from projects in /jest.config.ts. Please remove e2e from your projects.

Error: Could not remove e2e from projects in /jest.config.ts. Please remove e2e from your projects.
    at updateJestConfig (/Users/caleb/Work/sandbox/node-app/node_modules/@nrwl/workspace/src/generators/remove/lib/update-jest-config.js:49:11)
    at /Users/caleb/Work/sandbox/node-app/node_modules/@nrwl/workspace/src/generators/remove/remove.js:19:51
    at Generator.next (<anonymous>)
    at fulfilled (/Users/caleb/Work/sandbox/node-app/node_modules/tslib/tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Expected Behavior

remove projects in standalone app

## Related Issue(s)

Fixes #

2023-04-04 22:27 UTC, AgentEnder requested changes
One small nit

2023-04-04 22:27 UTC, AgentEnder commented on packages/workspace/src/generators/remove/lib/update-jest-config.spec.ts
> +        join(__dirname, './test-files/jest-project.config.ts'),
Can we use `__fixtures__` instead of `test-files`?

2023-04-05 14:02 UTC, jaysoo approved these changes

2023-04-06 14:29 UTC, AgentEnder approved these changes

2023-04-06 14:30 UTC, merged