feat(core): allow dependsOn to accept a single project dependency
nrwl/nx pull request #16100
Opened 2023-04-04 21:35 UTC by AgentEnder

## Current Behavior
In its object form, `dependsOn` has a `projects` property. This property takes a string, despite being plural, and only accepts `self` or `dependencies` as its value.

## Expected Behavior
`projects` can be an array of project names, but supports `{self}` and `{dependencies}` as tokens

## Related Issue(s)

Fixes #

2023-04-05 21:19 UTC, FrozenPandaz requested changes

2023-04-05 21:19 UTC, FrozenPandaz commented on docs/shared/reference/project-configuration.md
> +  "dependsOn": [{ "projects": "{dependencies}", "target": "build" }]
Don't update this yet because if people do it in older versions, they will get a warning eventually.

2023-04-05 21:19 UTC, FrozenPandaz commented on packages/nx/src/config/workspace-json-project-json.ts
> +   * - '{dependencies}': This target depends on targets of the projects of it's deps.
Prefer the `{self/dependencies}`

2023-04-05 21:19 UTC, FrozenPandaz commented on packages/nx/src/migrations/update-16-0-0/update-depends-on-to-tokens.ts
> +              : '{dependencies}';
If I run this again, it will change everything to `{dependencies}`

2023-04-06 15:34 UTC, FrozenPandaz requested changes

2023-04-06 15:34 UTC, FrozenPandaz commented on docs/shared/reference/project-configuration.md
We should have separate tabs for the old and new syntax

2023-04-06 17:42 UTC, FrozenPandaz approved these changes

2023-04-10 16:40 UTC, isaacplmann approved these changes
I think the feature is great, but I would restructure the docs a bit.  If you want, you can merge and then I can update the docs section.

I think we should do it like this:
- Full dependsOn syntax structure with tabs for < 16 and 16+
- Examples of usage with tabs for < 16 and 16+
- Specifying individual projects should still be in a tab for 16+ even though there is no corresponding < 16 tab

2023-04-10 16:42 UTC, AgentEnder commented
Sure, that sounds good. Thanks Issac!

2023-04-10 17:12 UTC, merged