chore(core): remove deprecated workspace-lint
nrwl/nx pull request #16212
Opened 2023-04-10 22:33 UTC by AgentEnder

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-04-13 02:55 UTC, puku0x commented
Will Nx provide a way to align the package versions like `workspace-lint` in the future release?

2023-10-07 09:20 UTC, JamesHenry requested changes, later dismissed
This can’t be a chore right, it’s a significant user facing change? chore would cause it to not appear in the changelog

2023-10-12 11:15 UTC, meeroslav commented on packages/nx/project.json
> +    "echo:test": {
This doesn't seem to be related to the PR

2023-10-12 11:15 UTC, meeroslav approved these changes

2023-10-12 15:07 UTC, isaacplmann approved these changes

2023-10-13 17:08 UTC, FrozenPandaz approved these changes

2023-10-13 17:08 UTC, merged