feat(core): add hasher implementation info in `nx report`
nrwl/nx pull request #16261
Opened 2023-04-12 15:16 UTC by Cammisuli

## Current Behavior
There is no way of knowing if the workspace is using the native, git or node hasher. 

## Expected Behavior
Running `nx report` will now have information about the hasher implementation:
```
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.15.0
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                      : 0.0.1
   lerna                   : 6.0.0
   ....
```

## Related Issue(s)

Fixes #

2023-04-12 19:40 UTC, AgentEnder requested changes
Looks good, small formatting nitpick

2023-04-12 19:40 UTC, AgentEnder commented on packages/nx/src/command-line/report.ts
> +    `hasher : ${currentHasherImplementation}`,
```suggestion
    `Hasher : ${currentHasherImplementation}`,
```

2023-04-12 21:27 UTC, AgentEnder approved these changes

2023-04-12 21:28 UTC, AgentEnder commented
@Cammisuli Accepting the suggestion left a bad commit message causing CI checks to fail. Can you rebase + squash locally s.t. the commitlint passes?

2023-04-13 10:53 UTC, Cammisuli commented
dang, thats what I get when I try and be efficient 😅 I **_still_** need to do a checkout and a commit haha

2023-04-13 13:58 UTC, merged