feat(angular): replace usages of @nrwl with @nx
nrwl/nx pull request #16377
Opened 2023-04-18 18:22 UTC by FrozenPandaz

## Current Behavior

The Angular package generates `@nrwl/*`

## Expected Behavior

The Angular package generates `@nx/*`

## Related Issue(s)

Fixes #

2023-04-18 18:47 UTC, barbados-clemens approved these changes

2023-04-19 08:42 UTC, Coly010 requested changes
Everything looks good, but there's one conditional that I believe is incorrect

2023-04-19 08:42 UTC, Coly010 commented on packages/angular/src/generators/convert-to-with-mf/lib/get-webpack-config-path.ts
> +        target.options.customWebpackConfig?.path)
Should this be
```suggestion
      (target.executor === '@nx/angular:webpack-browser' ||
      target.executor === '@nrwl/angular:webpack-browser') &&
        target.options.customWebpackConfig?.path
```

2023-04-19 14:59 UTC, Coly010 approved these changes

2023-04-19 14:59 UTC, merged