docs: nx scope
nrwl/nx pull request #16403
Opened 2023-04-19 13:21 UTC by isaacplmann

- Changes all references in the docs from `@nrwl/` to `@nx/`
- Adds a recipe explaining why the rescope happened and what people need to do
- Adds a note in each of the plugin overview pages referencing the recipe

2023-04-19 13:22 UTC, mandarini approved these changes

2023-04-19 13:31 UTC, leosvelperez approved these changes

2023-04-19 13:36 UTC, juristr commented on docs/shared/recipes/rescope.md
Doesn't really feel like this is a recipe 🤔. Do we really need this docs page or is it enough to mention it in our release blog post, our social channels, the YT video etc. We could even create a dedicated YT video for it.

2023-04-19 14:06 UTC, nartc approved these changes

2023-04-19 15:06 UTC, barbados-clemens approved these changes

2023-04-20 01:54 UTC, isaacplmann commented on docs/shared/recipes/rescope.md
It's closer to a recipe than a concept guide or tutorial.

I don't have strong feelings about keeping this page.  If Jason wants to link out to a blog post instead of a recipe page, that's fine with me.

2023-04-20 14:19 UTC, xiongemi approved these changes

2023-04-20 20:13 UTC, isaacplmann commented
@FrozenPandaz I'll fix these conflicts whenever we're close to the v16 release.  Just let me know.

2023-04-27 20:40 UTC, FrozenPandaz requested changes
I think this is now overboard after we've added the snippet footers. Can we remove these banners?

![image](https://user-images.githubusercontent.com/8104246/234983739-72e4d952-a88c-4406-92d8-da983ae6a402.png)

For the [@nx/devkit page](https://nx-dev-git-fork-isaacplmann-nx-scope-nrwl.vercel.app/packages/devkit/documents/nx_devkit), let's add a banner somehow?

The [`@nx/eslint-plugin`](https://nx-dev-git-fork-isaacplmann-nx-scope-nrwl.vercel.app/packages/eslint-plugin/documents/overview) page has the wrong package name. The contents also have the wrong rule names. It is `@nx/typescript` instead of `@nx/nx/typescript`. [This page](https://nx-dev-git-fork-isaacplmann-nx-scope-nrwl.vercel.app/recipes/other/eslint) as well.

The [`@nx/plugin`](https://nx-dev-git-fork-isaacplmann-nx-scope-nrwl.vercel.app/packages/plugin/documents/overview) page also has issues

2023-04-27 21:41 UTC, FrozenPandaz approved these changes

2023-04-27 22:14 UTC, merged