feat(web): remove deprecated executors
nrwl/nx pull request #16416
Opened 2023-04-19 17:58 UTC by jaysoo

This PR removes executors that we deprecated back in Nx 13 : `@nrwl/web:rollup`,  `@nrwl/web:webpack`, `@nrwl/web:dev-server`. The migrations were applied back in Nx 14 and Nx 15, so people have had enough time to adapt.

Anyone who skipped previous migrations will need to manually update their project configurations.

2023-04-19 17:59 UTC, ndcunningham approved these changes

2023-04-19 18:06 UTC, FrozenPandaz requested changes
Can you take a look at this line please?

https://github.com/nrwl/nx/blob/76dfc6241212a542bb30754c6a60003d9a221cf7/packages/react-native/src/generators/library/library.ts#L87

It's being generated in `@nx/react-native`

2023-04-19 18:06 UTC, FrozenPandaz commented on packages/web/executors.json
Please also remove them from `@nrwl/web` in `packages-legacy`

2023-04-19 18:19 UTC, jaysoo commented
> @jaysoo Can we rerun the migration that moves people to use the new executors?

Sure, we can do it a third time. 😅

2023-04-19 19:54 UTC, AgentEnder approved these changes

2023-04-19 20:12 UTC, barbados-clemens approved these changes

2023-04-19 21:04 UTC, nartc approved these changes

2023-04-19 21:57 UTC, FrozenPandaz reviewed
Sorry, could you also add redirects for nx.dev?

2023-04-20 08:17 UTC, Coly010 approved these changes

2023-04-20 10:38 UTC, mandarini approved these changes

2023-04-20 12:18 UTC, jaysoo commented
@FrozenPandaz done https://github.com/nrwl/nx/compare/e8384dacdd625c2e2b9fbc791d3a9faab7f9a08c..eca3160bc067ab3328a6d6a0e35c55e9a81001c2

2023-04-20 14:21 UTC, xiongemi approved these changes

2023-04-20 15:22 UTC, bcabanes approved these changes

2023-04-20 21:50 UTC, FrozenPandaz approved these changes

2023-04-20 21:50 UTC, merged