feat(testing): add --strict flag for jest-preset-angular test env opts
nrwl/nx pull request #16467
Opened 2023-04-21 17:44 UTC by barbados-clemens

## Current Behavior

jest-preset-angular has options to configure ng TestBed to error on unknown properties and elements but must be manually configured in each test-setup file

## Expected Behavior

when creating an angular project. providing the --strict flag should auto setup jest-preset-angular to fail when unknown properties/elements are used

## Related Issue(s)

Fixes #16352

2023-04-21 17:45 UTC, Coly010 approved these changes

2023-04-28 20:28 UTC, FrozenPandaz requested changes

2023-04-28 20:28 UTC, FrozenPandaz commented on docs/generated/packages/jest/generators/jest-project.json
> +      "strict": {
Can you remove this option and keep it scoped to the Angular generator?

2023-05-09 14:45 UTC, FrozenPandaz approved these changes

2023-05-09 15:07 UTC, merged