feat(core): add skipTypeCheck option to rollup plugin options
nrwl/nx pull request #16710
Opened 2023-05-02 21:20 UTC by marwan38

## Current Behavior
Can't disable the rollup typescript plugin type checker

## Expected Behavior
Allow users to disable it if needed

## Related Issue(s)

Fixes #

2023-05-02 21:22 UTC, marwan38 commented on packages/rollup/src/executors/rollup/lib/normalize.ts
> +    skipTypeCheck: options.skipTypeCheck || false,
Staying consistent with the swc compiler option

2023-05-03 08:40 UTC, mandarini approved these changes

2023-05-03 08:40 UTC, mandarini requested changes
Can you add this extra option to the `schema.json` as well, and then run `pnpm documentation`? Thanks!

2023-05-03 22:39 UTC, marwan38 commented
@mandarini Thanks for getting back to me so quickly. I've added it to the schema and generated the docs. I copied over the exact schema definition from esbuild and swc. No idea what `x-priority` is, but, if both esbuild and swc have it set to `important` I thought that's what I should be doing.

2023-05-04 12:03 UTC, mandarini requested changes
Hi there @marwan38 ! Thanks for updating the code! Can you please squash the commits and remove the `x-priority` attribute? We add this as `important` usually for required values or values we want to bring attention to, so that they are pushed at the top of the executor options list. The new option you added will still show in the list, just not at the top!

I tried to make these changes myself to your repo, but I did not have permission to push :)

2023-05-04 19:55 UTC, marwan38 commented
@mandarini all done. thanks again for walking me through it :)

2023-05-05 09:26 UTC, mandarini approved these changes
All is great now! Thanks! :) However, unfortunately, a new PR got merged and there are some conflicts with your branch, so you need to rebase with latest `master`. I would do it for you, but I don't have permission to push to your fork :( You can "allow edits by maintainers" in your fork, if you want!

2023-05-06 11:10 UTC, marwan38 commented
@mandarini Done!

2023-05-06 11:44 UTC, merged