fix(storybook): ignore nx storybook plugin from sb eslint
nrwl/nx pull request #16725
Opened 2023-05-03 14:41 UTC by mandarini

## Current Behavior
If workspace uses `plugin:storybook/recommended` eslint plugin and `@nx/react/plugins/storybook` storybook addon, then a linting error is thrown, because it cannot see that the plugin is installed. Reference: https://github.com/storybookjs/eslint-plugin-storybook/pull/129

## Expected Behavior
If `@nx/react/plugins/storybook` and workspace uses the `plugin:storybook/recommended` eslint plugin, then ignore our package from the `no-uninstalled-addons` rule.

Also, add this rule to our `.eslintrc.json`.

## Related Issue(s)

https://github.com/nrwl/nx/issues/16629

2023-05-03 15:10 UTC, Coly010 approved these changes

2023-05-03 17:19 UTC, AgentEnder approved these changes

2023-05-03 17:25 UTC, jaysoo requested changes

2023-05-03 17:25 UTC, jaysoo commented on packages/storybook/src/migrations/update-16-1-0/eslint-ignore-react-plugin.ts
> +    console.log('sbConfig', sbConfig);
remove

2023-05-03 17:54 UTC, jaysoo approved these changes

2023-05-03 18:52 UTC, philipjfulcher approved these changes

2023-05-04 10:58 UTC, meeroslav approved these changes
Apart from the leftover console.log, looks good

2023-05-04 10:58 UTC, merged