docs(core): add example of custom/ejected github workflow
nrwl/nx pull request #16739
Opened 2023-05-03 18:49 UTC by meeroslav

## Current Behavior
Our docs suggest using `nrwl/ci` as a default GitHub workflow leading to users believe this is the only way and opening issues with requests we are not willing (or cannot, due to reusable workflow limitations) implement.

## Expected Behavior
We should also have an example of a custom workflow, like we do for other CI providers.

## Related Issue(s)

Fixes #

2023-05-03 18:58 UTC, isaacplmann requested changes

2023-05-03 18:58 UTC, isaacplmann commented on docs/shared/monorepo-ci-github-actions.md
> +          for pid in \${pids[*]}; do
what is this section doing?

2023-05-03 18:58 UTC, isaacplmann commented on docs/shared/monorepo-ci-github-actions.md
> +          fetch-depth: 0
This is great.  I've gotten stuck on this part multiple times trying to set up CI.

2023-05-03 18:58 UTC, isaacplmann commented on docs/shared/monorepo-ci-github-actions.md
> +          for pid in \${pids[*]}; do
it would be nice to add a comment here

2023-05-03 19:35 UTC, meeroslav commented on docs/shared/monorepo-ci-github-actions.md
> +          for pid in \${pids[*]}; do
Added! Please re-review

2023-05-04 10:55 UTC, isaacplmann approved these changes

2023-05-04 10:59 UTC, merged