feat(core): log a note after an interactive migration run where package updates were opted out
nrwl/nx pull request #16802
Opened 2023-05-05 10:34 UTC by leosvelperez

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-05-09 16:33 UTC, isaacplmann requested changes

2023-05-09 16:33 UTC, isaacplmann commented on docs/shared/recipes/advanced-update.md
> +This will update your source code in your workspace in accordance with the implementation of the various migrations which ran and all the changes will be unstaged ready for you to review and commit y
```suggestion
All changes to your source code will be unstaged and ready for you to review and commit yourself.
```

2023-05-15 14:51 UTC, FrozenPandaz approved these changes

2023-05-15 14:56 UTC, isaacplmann approved these changes

2023-05-15 14:56 UTC, merged