fix(misc): always pass project graph to parseTargetString
nrwl/nx pull request #16958
Opened 2023-05-11 16:10 UTC by FrozenPandaz

## Current Behavior

The project graph is not passed to `parseTargetString` in some places.

## Expected Behavior

The project graph is passed to `parseTargetString` in some places.

## Related Issue(s)

Fixes #

2023-05-11 16:18 UTC, mandarini approved these changes

2023-05-11 16:23 UTC, barbados-clemens requested changes
bad import

2023-05-11 16:23 UTC, barbados-clemens commented on packages/cypress/src/generators/cypress-e2e-configuration/cypress-e2e-configuration.ts
> +import { ProjectGraph } from 'nx-cloud/lib/core/models/run-context.model';
imported from the wrong location, should be from nx/devkit?

2023-05-11 16:53 UTC, AgentEnder approved these changes

2023-05-11 20:12 UTC, barbados-clemens approved these changes

2023-06-22 13:50 UTC, jaysoo approved these changes

2023-06-22 15:04 UTC, closed without merging