feat(core): add --affected to show only affected projects
nrwl/nx pull request #16970
Opened 2023-05-11 20:14 UTC by AgentEnder

This PR overhauls `nx show` a bit, to better support future object types and prepare for deprecating print-affected.

The main changes are:
- `nx show` is now a noop, but is built with subcommands
- `nx show projects` is a subcommand, and can take affected arguments
- `pnpm documentation` is equipped to handle subcommands

2023-05-11 21:24 UTC, FrozenPandaz approved these changes

2023-05-11 21:25 UTC, FrozenPandaz requested changes
Please fix e2e tests and add a new one for this.

2023-05-12 22:21 UTC, FrozenPandaz approved these changes

2023-05-12 22:21 UTC, FrozenPandaz commented on docs/generated/cli/show.md
> +### Examples
Add an example for `nx show projects`

2023-05-12 22:21 UTC, FrozenPandaz commented on docs/generated/cli/show.md
> +## Child Commands
```suggestion
## Sub Commands
```

2023-05-12 22:21 UTC, FrozenPandaz commented on packages/nx/src/command-line/examples.ts
> +  ],
```suggestion
  show: {
  projects: [
    {
      command: 'show projects --affected',
      description: 'Show affected projects in the workspace',
    },

    {
      command: 'show projects --affected --exclude *-e2e',
      description:
        'Show affected projects in the workspace, excluding end-to-end projects',
    },
  ]},
```

2023-05-13 01:15 UTC, AgentEnder commented on packages/nx/src/command-line/examples.ts
> +  ],
We'll attack this in follow up :)

2023-05-13 05:48 UTC, merged