feat(nx-dev): add watch to automatically sync docs to nx-dev when developing locally
nrwl/nx pull request #17059
Opened 2023-05-17 06:19 UTC by juristr

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-05-17 12:29 UTC, isaacplmann requested changes

2023-05-17 13:00 UTC, bcabanes approved these changes
Glad this works now!

2023-05-17 19:14 UTC, juristr commented on nx-dev/nx-dev/project.json
> +    "copy-docs": {
Added some inputs/outputs :)

2023-05-19 13:09 UTC, isaacplmann approved these changes

2023-05-19 13:15 UTC, merged