@nx
nrwl/nx pull request #17226
Opened 2023-05-25 19:21 UTC by sir-captainmorgan21

## Current Behavior
Right now if you provide a directory to place your library, it will result in the file name of the library components to include the directory path as a prefix. (IE: MyDirMyLibName.tsx).

## Expected Behavior
Expected behavior would be to allow a way to generate a simple file name only consisting of the name of the lib provided. Just like the `simpleName` option that exists for @nx/angular and was added to @nx/nest

## Related Issue(s)
https://github.com/nrwl/nx/issues/17207

2023-05-25 19:46 UTC, sir-captainmorgan21 commented
@mandarini tagging ya as requested

2023-05-29 13:16 UTC, mandarini requested changes
Just one small comment! Otherwise looks good to me! Thank you @sir-captainmorgan21 !

2023-05-31 07:51 UTC, mandarini commented on .gitignore
> +.pnpm-store
Hmmm I see... I was not getting that on my end, weird...

2023-05-31 13:12 UTC, jaysoo approved these changes

2023-05-31 13:32 UTC, mandarini approved these changes

2023-05-31 13:49 UTC, mandarini approved these changes

2023-05-31 13:59 UTC, isaacplmann approved these changes

2023-05-31 14:02 UTC, jaysoo approved these changes

2023-05-31 14:28 UTC, merged

2023-05-31 15:50 UTC, sir-captainmorgan21 commented
@mandarini thanks! how does the actual release process work in terms of seeing this get published? Do you queue up a small set of features/bug fixes?

2023-06-01 11:03 UTC, christopher-francisco commented
Pure coincidence, I was just looking to see if this existed today, and it was merged yesterday. Where can I get info on the release process?

2023-06-01 11:11 UTC, mandarini commented
Hi there @sir-captainmorgan21 @christopher-francisco ! We usually do patch release whenever there's a good amount of bug-fixes, but that depends. We just released `16.3.0`, I think maybe by the end of the week or sometime early next week? It all depends! :)