feat(core): build project file map with rust
nrwl/nx pull request #17472
Opened 2023-06-07 20:09 UTC by Cammisuli

## Current Behavior
The project file map is done on the Node side of Nx. This means that we had to use a slower glob to gather project configurations. This was inefficient because we already traversed the file system to gather the file hashes.  

## Expected Behavior
The project graph creation is now done with Rust. This means that when we traverse the workspace to gather hashes, we can also find which file is a project configuration and build the project file map from it. 

Calling the native code will give us `{ projectFileMap: ProjectFileMap, configFiles: string[], globalFiles: string[] }` and we can use this information to build out the necessary structures for other parts of Nx. 

## Related Issue(s)

Fixes #

2023-06-09 16:00 UTC, FrozenPandaz requested changes

2023-06-09 16:00 UTC, FrozenPandaz commented on packages/nx/src/daemon/server/project-graph-incremental-recomputation.ts
> +    );
Combine these 2 functions and make sure it is invalidated.

2023-06-09 16:00 UTC, FrozenPandaz commented on packages/nx/src/daemon/server/project-graph-incremental-recomputation.ts
> +      }
Below should be in here

2023-06-09 16:00 UTC, FrozenPandaz commented on packages/nx/src/native/tests/hasher.spec.ts
> +  });
rm

2023-06-09 21:17 UTC, FrozenPandaz requested changes

2023-06-14 07:19 UTC, leosvelperez approved these changes

2023-06-14 15:56 UTC, FrozenPandaz approved these changes

2023-06-14 17:42 UTC, merged