feat(core): use rust utilities for caching operations
nrwl/nx pull request #17638
Opened 2023-06-16 15:27 UTC by Cammisuli

## Current Behavior
Nx cache uses fast-glob, fs, and execSync to manage cache. (Finding what's needed to cache, copy and remove)

## Expected Behavior
Nx cache uses rust utilities to manage these operations

## Related Issue(s)

Fixes #

2023-06-16 15:29 UTC, Cammisuli commented on packages/nx/Cargo.toml
I added `walkdir` and alphabetized the list

2023-06-26 15:11 UTC, FrozenPandaz requested changes

2023-06-26 15:11 UTC, FrozenPandaz commented on packages/nx/Cargo.toml
> +futures = "0.3.28"
Is this used?

2023-06-27 13:45 UTC, Cammisuli commented on packages/nx/src/tasks-runner/cache.ts
> +      await this.remove(tdCommit);
It doesnt use the node remove anymore, and the rust one appears to be faster.

2023-06-27 15:07 UTC, FrozenPandaz approved these changes

2023-06-27 15:08 UTC, merged