feat(nest): add migrations to nest 10 #17681
nrwl/nx pull request #17685
Opened 2023-06-20 09:35 UTC by Coly010

## Current Behavior

We don't currently generate nest projects with version 10

## Expected Behavior

Generate nest with version 10
Add migrations to upgrade Nx workspaces on nest 9 to 10
## Related Issue(s)

Fixes #17681
Fixes #17400

2023-06-20 13:26 UTC, FrozenPandaz requested changes

2023-06-20 13:26 UTC, FrozenPandaz commented on packages/nest/migrations.json
> +      "version": "16.4.0-beta.10",
Can you bump this to `16.4.0-beta.11` please?

2023-06-20 21:23 UTC, FrozenPandaz approved these changes

2023-06-21 17:32 UTC, jaysoo approved these changes

2023-06-21 17:33 UTC, merged