chore(js): fix yarn setup to work with yarn3
nrwl/nx pull request #17716
Opened 2023-06-21 20:40 UTC by FrozenPandaz

## Current Behavior

An error is thrown if using the `verdaccio` executor with yarn 3

```
~/p/nx (master|✔) $ pnpm local-registry

> @nx/nx-source@ local-registry /home/jason/projects/nx
> nx local-registry @nx/nx-source

> nx run @nx/nx-source:local-registry

Cleared local registry storage folder /home/jason/projects/nx/build/local-registry/storage
Set npm registry to http://localhost:4873/
 >  NX   Failed to set yarn registry to http://localhost:4873/: Command failed: yarn config get registry
   Pass --verbose to see the stacktrace.

```

## Expected Behavior

The verdaccio executor works with yarn 3

## Related Issue(s)

Fixes #

2023-06-21 21:49 UTC, fahslaj approved these changes

2023-06-21 21:51 UTC, AgentEnder requested changes

2023-06-21 21:51 UTC, AgentEnder commented on packages/js/src/executors/verdaccio/verdaccio.impl.ts
> +    const yarnV1 = major(execSync('yarn --version').toString().trim()) === 1;
Can we call this `isYarnV1` instead or something similar?

2023-06-21 21:51 UTC, AgentEnder commented on packages/js/src/executors/verdaccio/verdaccio.impl.ts
> +          `yarn config set unsafeHttpWhitelist --json '["localhost"]'` +
This will overwrite the existing value and we don't have a stored value to set it back to, potentially breaking folks.

2023-06-21 21:51 UTC, AgentEnder commented on packages/js/src/executors/verdaccio/verdaccio.impl.ts
> +          `Whitelist http://localhost:${options.port}/ as an unsafe http server`
```suggestion
          `Whitelisted http://localhost:${options.port}/ as an unsafe http server`
```

2023-06-22 14:18 UTC, xiongemi approved these changes

2023-06-22 15:06 UTC, AgentEnder approved these changes

2023-06-22 15:07 UTC, merged