feat(devkit): allow to customize overwrite mode in generateFiles
nrwl/nx pull request #17925
Opened 2023-07-03 12:59 UTC by qortex

Adds a new capability to choose how to handle already existing target files when using a generator.

## Current Behavior
If a target file already exists, `generateFiles` overwrites existing files. It is not always the intended behaviour, forcing to have custom code in generators to check for already existing files.

## Expected Behavior
A new (optional) argument to generateFiles allows to choose the behavior when a target file already exists: overwrite (current & still default behavior), keep, throw.

Note: `nx affected` fails on my setup, so could only check by hand and all tests including new tests pass ok on devkit.

2023-07-22 07:17 UTC, qortex commented
@FrozenPandaz @vsavkin @bcabanes 
Hi, I'm not familiar with the PR review process for Nx. Should this topic be discussed somewhere to get the PR under review? I just submitted it, but maybe I'm missing a step in the process.
Thanks for the amazing work on Nx :)
Best,

2023-07-28 09:36 UTC, qortex commented
Ping
Is there something to do to make sure someone is aware of this PR ?
@FrozenPandaz @vsavkin @bcabanes

2023-09-21 20:22 UTC, AgentEnder approved these changes

2023-09-22 13:05 UTC, isaacplmann approved these changes

2023-09-22 15:04 UTC, qortex commented
Thanks!
Should I resolve the conflicts, or do maintainers prefer to do it?

2023-09-28 21:22 UTC, qortex commented
@AgentEnder @isaacplmann 
Happy to move this forward, how should I proceed?

2023-10-05 13:21 UTC, isaacplmann commented
Go ahead and merge the conflicts

2023-10-12 18:59 UTC, isaacplmann commented
I agree, they look unrelated.  I relaunched the CI pipeline

2023-10-16 11:36 UTC, qortex commented
How should we move forward @isaacplmann ? Now just linux failed, macos passed 🤔

2023-10-16 21:57 UTC, AgentEnder commented
I am unable to rebase + push this up since the fork is on an org account rather than a personal user account. Can you rebase with latest? I think the e2e errors should go away.

2023-10-17 14:51 UTC, qortex commented
Ah bummer

Just did rebase + push 🤞

2023-10-18 10:09 UTC, qortex commented
Looks like it's related to storybook e2e. Should not block this PR right? Or should I do something?
@AgentEnder

2023-10-18 12:38 UTC, isaacplmann commented
No, not your fault.  We're working on fixing that e2e test.

2023-10-24 13:42 UTC, qortex commented
Ok, just rebased and pushed, looks like tests are green now!

2023-10-24 14:11 UTC, isaacplmann approved these changes

2023-10-25 07:32 UTC, qortex commented
@FrozenPandaz @vsavkin  should we merge that before `main` moves ahead again?
That would be great 😄

2023-11-03 07:49 UTC, qortex commented
Test seems to be broken again.
How to get this PR merged?
We actually need this facility in our workflow. I respect if you don't plan to merge, just please let me know so that I take appropriate action and implement that in our project instead of the Nx repo.

Thanks and good luck for the new releases!

2023-11-07 14:06 UTC, qortex commented
@isaacplmann 
What's the way forward?

2023-11-07 14:57 UTC, FrozenPandaz requested changes
Thank you for your contribution! The functionality looks good. Could you please make these implementation changes?

2023-11-07 14:57 UTC, FrozenPandaz commented on packages/devkit/src/generators/generate-files.ts
> +  overwriteStrategy: OverwriteStrategy = OverwriteStrategy.Overwrite
Please add this flag within an `options` object. This will make future flags not a breaking change.

2024-01-30 17:02 UTC, mandarini commented
@qortex thank you so much for your contribution! Will you have time to address the suggested changes, or should I go ahead and fix these, instead?

2024-06-04 14:55 UTC, closed without merging