docs(nx-dev): put all angular recipes together
nrwl/nx pull request #17943
Opened 2023-07-04 13:37 UTC by meeroslav

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-07-05 11:39 UTC, Coly010 reviewed
I think this looks ok, but I think the menu item text should be a bit more clear.

2023-07-05 11:39 UTC, Coly010 commented on docs/shared/reference/sitemap.md
> +    - [Migrating Angular CLI](/recipes/adopting-nx-angular/migration-angular)
```suggestion
    - [Migrating from the Angular CLI](/recipes/adopting-nx-angular/migration-angular)
```

2023-07-05 11:39 UTC, Coly010 commented on docs/shared/reference/sitemap.md
> +    - [Migrating Angular CLI to Integrated](/recipes/adopting-nx-angular/angular-integrated)
```suggestion
    - [Migrating from the Angular CLI to Integrated Monorepo](/recipes/adopting-nx-angular/angular-integrated)
```

2023-07-05 11:39 UTC, Coly010 commented on docs/shared/reference/sitemap.md
> +    - [Migrating Angular Manually](/recipes/adopting-nx-angular/angular-manual)
```suggestion
    - [Migrating from the Angular CLI Manually](/recipes/adopting-nx-angular/angular-manual)
```

2023-07-05 12:07 UTC, Coly010 approved these changes

2023-07-05 12:58 UTC, juristr commented
@meeroslav should this be funneled into the broader discussion on how to reorg some of the stuff we have on the docs page? Like, if we add a section for Angular, we should probably have one for React, Next, Node,...

Right the side-menu organization is kept agnostic from tech but from an Nx focus like migrating etc.. which I agree has its flaws, which is why we should discuss this in general.

As we had already discussed, there are different angles

- Nx specific recipes
- Tech specific recipes related on how to use Nx with <tech-stack> but not necessarily related to any Nx tech specific plugin
- Nx plugin specific recipes

2023-07-05 13:09 UTC, meeroslav commented
We already had segment called `Adopting Nx form Angular CLI` so that's not new.

I believe an Angular user might come to recipes looking for Angular-related content or a framework agnostic one.
There shouldn't be any recipes in the `Other` as each recipe needs to belong somewhere.

Grouping NgRx-related with Angular migration recipes makes sense, in my opinion.

Same should go for React specific recipes.

But we can have a discussion on the topic first.

2023-07-05 14:51 UTC, isaacplmann requested changes
Similar comments to @Coly010 but the changes should be made in map.json rather than sitemap.md.

2023-07-05 14:51 UTC, isaacplmann commented on docs/map.json
> +          "description": "Advanced guides to using Nx with Angular ecosystem",
```suggestion
          "description": "Advanced guides to using Nx within the Angular ecosystem",
```

2023-07-05 14:51 UTC, isaacplmann commented on docs/map.json
> +              "name": "Migrating Angular CLI",
```suggestion
              "name": "Migrating from the Angular CLI",
```

2023-07-05 14:51 UTC, isaacplmann commented on docs/map.json
> +              "name": "Migrating Angular CLI to Integrated",
```suggestion
              "name": "Migrating from the Angular CLI to an Integrated Repo",
```

2023-07-05 14:51 UTC, isaacplmann commented on docs/map.json
> +              "name": "Migrate AngularJS",
```suggestion
              "name": "Migrate an AngularJS Repo",
```

2023-07-19 10:59 UTC, meeroslav commented
Closing as we will refactor the docs further

2023-07-19 10:59 UTC, closed without merging