fix(nx): update workspace to use prettier v1.18.2
nrwl/nx pull request #1809
Opened 2019-09-09 10:41 UTC by wimzyLive

## Current Behavior 

`format:check` with `nx@latest` fails when there is a pair of **()** around async pipes in HTML
Current Behavior
Currently latest nx workspace defaults to prettier version *1.16.2*, whereas latest version of prettier-vscode uses *1.18.x*.
In prettier *1.16.x* prettier adds **()** around async pipes in HTML. i.e.
`<div *ngIf="(isRendered | async)"></div>`
In prettier *1.17* this behaviour was updated to not to have **()** around pipes. i.e.
`<div *ngIf="isRendered | async"></div>`
Current prettier-vscode uses *1.18* so it removes **()** around pipes, but when running `format:check`, nx expects **()** around pipes because of it using prettier *1.16*.

[Reference to prettier issue](https://prettier.io/blog/2019/04/12/1.17.0.html#angular-don-t-add-unnecessary-parentheses-to-pipes-5929-by-voithos) 

## Expected Behavior 

This change updates prettier version to *1.18* same as prettier-vscode to resolve this conflicting behaviour.

2019-09-10 18:34 UTC, kbrilla approved these changes

2019-09-11 03:03 UTC, mehrad-rafigh commented
The commit message is not correct, thus breaking the build. I would recommend renaming your commit to `build(nx): update prettier to v1.18.2`.

Additionaly, the new prettier version should be used, when generating new apps.

2019-09-11 03:05 UTC, mehrad-rafigh requested changes
Please update `packages/workspace/src/utils/versions.ts` accordingly

2019-09-11 22:13 UTC, vsavkin commented
@wimzyLive Thank you very much for your PR! Could you squash the commits and change the message to `chore(nx): update the version of prettier to xxx`.

@mehrad-rafigh Thank you for helping out folks contributing to the repo. Just wanted to say that we use `build` to annotate changes only affecting the nx repo itself (e.g. scripts etc). Updating dependencies used by nx workspace should be chore/feat/fix depending on the nature of the update.

2019-09-12 03:48 UTC, wimzyLive commented
@vsavkin fixed.

2019-09-12 21:19 UTC, mehrad-rafigh approved these changes

2019-09-17 12:46 UTC, merged

2019-09-17 12:46 UTC, vsavkin commented
@wimzyLive Thank you!