feat(core): merge None and TS stacks into one since they are both for TS/JS projects
nrwl/nx pull request #18108
Opened 2023-07-13 18:09 UTC by jaysoo

This PR combines the TS stack into None. The merged stack will allow users to use package-based, integrated, or standalone workspace types.

Before:

```
npx -y create-nx-workspace

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · org6
? Which stack do you want to use? …
None:          Configures a minimal structure without specific frameworks or technologies.
TS/JS:         Configures a TypeScript/JavaScript package without specific frameworks or platforms.
React:         Configures a React app with your framework of choice.
Angular:       Configures a Angular app with modern tooling.
Node:          Configures a Node API with your framework of choice.
```

After (stack):
```
npx -y create-nx-workspace

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · org6
? Which stack do you want to use? …
None:          Configures a TypeScript/JavaScript project with minimal structure.
React:         Configures a React application with your framework of choice.
Angular:       Configures a Angular application with modern tooling.
Node:          Configures a Node API application with your framework of choice.
```

After (workspace type):

```
? Package-based monorepo, integrated monorepo, or standalone project? …
Package-based Monorepo:     Nx makes it fast, but lets you run things your way.
Integrated Monorepo:        Nx creates a monorepo that contains multiple projects.
Standalone:                 Nx creates a single project and makes it fast.
```

2023-07-13 19:18 UTC, isaacplmann approved these changes

2023-07-13 21:19 UTC, isaacplmann approved these changes

2023-07-14 18:49 UTC, FrozenPandaz requested changes

2023-07-14 18:49 UTC, FrozenPandaz commented on packages/create-nx-workspace/bin/create-nx-workspace.ts
> +  workspaceType: 'package-based' | 'integrated' | 'standalone' | 'integrated';
There are 2 integrated here.

What is the difference between `package-based` and `integrated`?

* `package-based` has `packages` directory while `integrated` has `libs`?
* `package-based` has `package.json` projects while `integrated has `project.json` ?
* `package-based` projects do not use executors while `integrated` do?

2023-07-18 13:41 UTC, FrozenPandaz approved these changes

2023-07-18 13:42 UTC, merged