fix(core): migrate old invalid glob syntax in target outputs
nrwl/nx pull request #18191
Opened 2023-07-19 15:53 UTC by Cammisuli

## Current Behavior

Invalid glob syntax in target outputs do not work (ie. `dist/*.(js|map|ts)`. This was because our older glob utility allowed this.

## Expected Behavior

This migrates outputs that have the invalid syntax to `dist/*.{js,map,ts}`. 

## Related Issue(s)

Fixes #18075

2023-07-19 20:25 UTC, AgentEnder approved these changes

2023-07-19 21:06 UTC, FrozenPandaz requested changes

2023-07-19 21:06 UTC, FrozenPandaz commented on packages/nx/src/migrations/update-16-5-4/update-output-globs.ts
> +      projectConfiguration.targets
```suggestion
      projectConfiguration.targets ?? {}
```

2023-07-19 21:06 UTC, FrozenPandaz commented on packages/nx/src/migrations/update-16-5-4/update-output-globs.ts
> +      targetConfiguration.outputs = replaceOutputs(targetConfiguration);
```suggestion
      targetConfiguration.outputs =  targetConfiguration.outputs.map(() => { ... })
```

2023-07-19 21:06 UTC, FrozenPandaz commented on packages/nx/src/migrations/update-16-5-4/update-output-globs.ts
> +        targetConfiguration.outputs = replaceOutputs(targetConfiguration);
```suggestion
      targetConfiguration.outputs =  targetConfiguration.outputs.map(() => { ... })
```

2023-07-20 14:03 UTC, FrozenPandaz approved these changes

2023-07-20 14:04 UTC, merged