feat(linter): add error and warning statistics
nrwl/nx pull request #18313
Opened 2023-07-26 07:23 UTC by SimeonC

Outputs the error and warning count statistics including how many can be auto-fixed, something I found useful before - especially when changing eslint configs which can generate a lot of errors.

## Current Behavior
Linter outputs only whether there are 1 or more errors or warnings.
```
Lint warnings found in the listed files.

Lint errors found in the listed files.
```

## Expected Behavior
We should get the error/warning count and also the number of fixable error/warnings.

```
8 Lint warnings found in the listed files.

2306 Lint errors found in the listed files. (740 are fixable)
```

2024-01-29 17:42 UTC, JamesHenry commented
I'm so sorry for the delay in you receiving a review here @SimeonC! This seems like a good change to me, would it be possible for you to fix up the conflicts please? I'll keep an eye on this one so we can get it merged straight away

2024-01-30 03:41 UTC, SimeonC commented
@JamesHenry I admit I had kinda forgotten about this. Looks like I'm a bit fortunate this time and the "conflicts" are just that git has too many commits and a rebase worked.

2024-01-30 11:32 UTC, JamesHenry requested changes
Thanks!

Sorry to be a pain, but can we align it a bit more with ESLint's own output and mention the --fix flag, as well as not have the `.` before the parens

Their logic looks like this:

```js
 output += chalk[summaryColor].bold([
                "  ", fixableErrorCount, pluralize(" error", fixableErrorCount), " and ",
                fixableWarningCount, pluralize(" warning", fixableWarningCount),
                " potentially fixable with the `--fix` option.\n"
            ].join(""));
```
from https://github.com/eslint/eslint/blob/98b5ab406bac6279eadd84e8a5fd5a01fc586ff1/lib/cli-engine/formatters/stylish.js#L91

It doesn't have to be exactly that (e.g. we don't have the chalk dep in linter I don't think, but ```potentially fixable with the `--fix` option``` is preferable language please

2024-01-31 01:23 UTC, SimeonC commented
@JamesHenry Thanks for the feedback, I went with updating to match the stylish formatted output as much as possible

2024-01-31 02:12 UTC, SimeonC commented
Oh, I see that the success message is used in a lot of other tests. @JamesHenry would you prefer I revert the success message change or update the tests to use the stylish formatted success message?

2024-01-31 08:19 UTC, JamesHenry commented
@SimeonC I think you can just do find an replace on `toContain('All files pass linting.')` with `toContain('All files pass linting')` (i.e. just remove the period at the end, I think that's the only difference)

2024-01-31 09:09 UTC, SimeonC commented
@JamesHenry Thanks, did that.

2024-01-31 11:35 UTC, JamesHenry commented
@SimeonC did you push with `--no-verify`? You have failed CI with a check that would have run automatically prepush

2024-01-31 11:47 UTC, SimeonC commented
Yea I did. My git client was failing with something like “unexpected error” and no further information. I’ll fix it up tomorrow as I thought it’d probably be OK and was running out of time, my bad 😅

Haven’t used a push hook before, we’ve always used a precommit hook for that so was unexpected.

2024-01-31 11:50 UTC, JamesHenry commented
It's your git commit message, you just need to do a commit --amend and add a valid scope to the commit

![image](https://github.com/nrwl/nx/assets/900523/4204a871-72be-4125-80bd-76dfdf0f449b)

The check is way too expensive (it does a lot of things) to apply to a precommit hook, that is why it is done prepush

2024-02-01 01:23 UTC, SimeonC commented
Thanks, my git client just shows "Some refs failed to push", when running `git push` from the command line I get the correct errors and could fix it.

2024-02-01 07:35 UTC, JamesHenry approved these changes
Thanks again @SimeonC!

2024-02-01 13:22 UTC, jaysoo approved these changes

2024-02-01 15:48 UTC, FrozenPandaz approved these changes

2024-02-01 15:48 UTC, merged