feat(core): gather task inputs
nrwl/nx pull request #18407
Opened 2023-07-31 17:38 UTC by Cammisuli

## Current Behavior

Its hard to determine why a task was affected by certain changes. If there are a lot of inputs + their dependencies, it can get overwhelming to mentally map the inputs.

## Expected Behavior

The "task plan" will now be built separately from hashing, and we can check what inputs actually affect our targets/tasks. The UI portion of this will come in a separate PR

## Related Issue(s)

Fixes #

TODO:
-[ ] Add "task plan" information to be consumed for the graph view

2023-08-08 15:28 UTC, FrozenPandaz requested changes

2023-08-08 15:28 UTC, FrozenPandaz commented on packages/nx/src/tasks-runner/run-command.ts
> +  const taskGraph = createTaskGraphWithPlan(
Remove these changes for now.

2023-08-08 15:28 UTC, FrozenPandaz commented on packages/nx/src/tasks-runner/create-task-graph.ts
> +export function createTaskGraphWithPlan(
This should be a function like..

```ts
createHashPlans(
  nxJson,
  projectGraph,
  taskGraph
): HashPlans
```

2023-08-08 15:28 UTC, FrozenPandaz commented on packages/nx/src/tasks-runner/create-task-graph.ts
> +  const taskGraph = createTaskGraph(
Don't create the task graph in this function, take it as an argument.

2023-10-18 11:04 UTC, Cammisuli commented
Closing this as this has been implemented again with #19233

2023-10-18 11:04 UTC, closed without merging