docs(nx-dev): add recipe for yarn pnp
nrwl/nx pull request #18460
Opened 2023-08-03 09:54 UTC by meeroslav

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-08-03 14:27 UTC, isaacplmann requested changes
Grammar fixes.  Looks good otherwise

2023-08-03 14:27 UTC, isaacplmann commented on docs/shared/recipes/yarn-pnp.md
> +Some packages come with broken dependency requirements so using strict `PnP` can lead to broken builds. This results in error similar to one below:
```suggestion
Some packages come with broken dependency requirements so using strict `PnP` can lead to broken builds. This results in errors similar to the one below:
```

2023-08-03 14:27 UTC, isaacplmann commented on docs/shared/recipes/yarn-pnp.md
> +The problem above is something we need to fix by ensuring the requested peer dependency exists as is available:
```suggestion
The problem above is something we need to fix by ensuring the requested peer dependency exists and is available:
```

2023-08-03 14:27 UTC, isaacplmann commented on docs/shared/recipes/yarn-pnp.md
> +Sometimes, simply adding a missing package doesn't work. In those cases the only thing we can do is to contact the author of package causing the issues and notify them of a missing dependency require
```suggestion
Sometimes, simply adding a missing package doesn't work. In those cases the only thing we can do is to contact the author of the package causing the issues and notify them of the missing dependency requirement.
```

2023-08-03 14:27 UTC, isaacplmann commented on docs/shared/recipes/yarn-pnp.md
> +The alternative is to switch back to using `node-modules` node linker.
```suggestion
The alternative is to switch back to using the `node-modules` node linker.
```

2023-08-03 15:46 UTC, isaacplmann commented on docs/shared/recipes/yarn-pnp.md
> +Your `.yarnrc.yml` will now have `nodeLinked` set to a proper method:
This typo needs to be fixed

2023-08-03 18:30 UTC, isaacplmann commented
There are 4 hidden comments that didn't get applied

2023-08-04 10:02 UTC, meeroslav commented
All fixed (+ a few more that my Grammarly found)

2023-08-04 13:05 UTC, isaacplmann approved these changes

2023-08-04 13:09 UTC, merged