fix(nx): check for valid semver version before updating package
nrwl/nx pull request #1846
Opened 2019-09-16 14:15 UTC by brandonroberts

_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#submit-pr)_

> _Please make sure that your commit message follows our format._

> Example: `fix(nx): must begin with lowercase`

## Current Behavior (This is the behavior we have today, before the PR is merged)

Semver check fails if version contains a range, such as `^8.0.0`

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

Valid versions will pass
`x.x.x`
`^x.x.x`
`~x.x.x`

If the version cannot be considered `clean` by `semver`, it will fail
`>=8.0.0`

## Issue

Closes #1831

2019-09-16 15:46 UTC, catfireparty requested changes

2019-09-16 15:46 UTC, jdpearce commented on packages/workspace/src/utils/version-utils.ts
> +  if (!clean(newVersion)) {
You're using `clean` but not actually returning the cleaned result. Did you mean to use `valid` instead?

2019-09-16 15:46 UTC, jdpearce commented on packages/workspace/src/utils/version-utils.ts
> +  if (clean(newVersion)) {
Did you mean to use `valid` here?

2019-09-16 15:46 UTC, jdpearce commented on packages/workspace/src/utils/version-utils.ts
> +      `Unable to validate the provided version against semver - (${version})`
This is a pretty unfriendly error message. Is it worth catching this in the migration and logging out something friendlier like "Your package.json lists a version of @angular/cli that Nx is unable to validate - (${version})"?

2019-09-16 15:46 UTC, jdpearce commented on packages/angular/src/migrations/update-8-5-0/update-8-5-0.spec.ts
> +describe('Update 8.3.0', () => {
TESTS! AWESOME! 🙏

2019-09-17 11:57 UTC, jdpearce commented
Sorry, this looks to be failing on the jest builder spec that I modified. I have no idea how the failing tests managed to get into master... 😞

2019-09-17 14:43 UTC, merged