feat(nx-dev): fetch plugin stats in CI
nrwl/nx pull request #18498
Opened 2023-08-04 17:36 UTC by isaacplmann

- Fetch plugin stats when Vercel deploys the nx-dev site.
- The nx-dev deploy will fail if npm stats or github stats sites are down
- Adds about 4 minutes to the deploy time
- Consolidates all the network calls to fetch github stars into a single network call.  (Couldn't find a graphql endpoint for npm to do the same thing for those network calls)

2023-08-07 15:58 UTC, meeroslav commented on .gitignore
> +/nx-dev/nx-dev/pages/extending-nx/quality-indicators.json
I would leave those in for local testing

2023-08-07 16:00 UTC, meeroslav commented on nx-dev/nx-dev/pages/extending-nx/registry.tsx
> +} catch (ex) {}
We should always have that file, just have `deploy-build` update it with latest data

2023-08-07 16:03 UTC, meeroslav commented on scripts/documentation/plugin-quality-indicators.ts
> +  return data.downloads;
We probably don't want to break our build if npm is down for what ever reason. We can use stale data.

2023-08-07 16:04 UTC, meeroslav requested changes
I don't think we should remove the `quality-indicators.json` from repo nor break the deploy if npm/github api are unavailable.

2023-08-07 18:40 UTC, meeroslav approved these changes

2023-08-08 08:32 UTC, juristr approved these changes

2023-08-08 13:50 UTC, FrozenPandaz approved these changes

2023-08-08 13:50 UTC, merged