feat(nx-dev): types in devkit toc
nrwl/nx pull request #18594
Opened 2023-08-11 19:41 UTC by isaacplmann

Updates the devkit reference:
- Adds types in the toc
- Removes any `@note` tags

2023-08-11 22:12 UTC, FrozenPandaz requested changes
Uh.. Okay, this look worse as is :sweat_smile: This may have been a bad request lol

Is it easy to isolate showing the type for the following to start?
[interface properties](https://nx-dev-git-fork-isaacplmann-docs-types-in-devkit-toc-nrwl.vercel.app/packages/devkit/documents/TargetDependencyConfig)
[class properties](https://nx-dev-git-fork-isaacplmann-docs-types-in-devkit-toc-nrwl.vercel.app/packages/devkit/documents/ProjectGraphBuilder#properties)
[variables](https://nx-dev-git-fork-isaacplmann-docs-types-in-devkit-toc-nrwl.vercel.app/packages/devkit/documents/nx_devkit#variables)

2023-08-14 12:22 UTC, isaacplmann commented
The latest commit should only show types for properties and variables

2023-08-15 19:45 UTC, FrozenPandaz approved these changes
This is looking much better. Can you rebase please?

2023-08-17 15:57 UTC, juristr approved these changes

2023-08-18 15:54 UTC, merged