feat(repo): enable agents
nrwl/nx pull request #18637
Opened 2023-08-15 14:35 UTC by vsavkin

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-08-24 11:32 UTC, mandarini approved these changes

2023-08-29 08:24 UTC, meeroslav commented on .nx/workflows/agents.yaml
> +      nxw cache restore {{nxBranch}}-node_modules node_modules
How does this work between the commits? Will every commit on the same branch use the same cached artifact despite potential dependency changes?

2023-08-29 08:25 UTC, meeroslav commented on .nx/workflows/agents.yaml
> +      echo 123
This should be removed

2023-08-29 08:28 UTC, meeroslav commented on docs/generated/cli/affected-graph.md
> ----
These generated files should not be removed

2023-08-29 08:30 UTC, meeroslav commented on .circleci/config.yml
> -            pnpm nx-cloud record -- nx format:check --base=$NX_BASE --head=$NX_HEAD &
Why are we removing these?

2023-08-29 08:32 UTC, meeroslav requested changes
Left some notes

2023-09-08 16:04 UTC, merged