docs(misc): community slack to official discord
nrwl/nx pull request #18873
Opened 2023-08-29 01:52 UTC by ZackDeRose

## Current Behavior

Points people to the community slack (most of the links are now redirected to discord, but looks like a couple still go straight to the community slack)

## Expected Behavior
Points people to the official discord server.

## Related Issue(s)

Fixes #

2023-08-29 02:09 UTC, ZackDeRose commented on docs/shared/guides/turbo-and-nx.md
> -- There are 5500+ active users in [the community slack.](https://nrwlcommunity.slack.com/join/shared_invite/zt-jba969hz-e5zm1Ou_jiOP1J2h8UTu0w#/shared-invite/email)
I removed this as our numbers now at not very impressive given we just launched today (~150 on day one it looks like)

2023-08-29 02:09 UTC, Moxita33 approved these changes

2023-08-29 02:25 UTC, isaacplmann requested changes
Found a typo

2023-08-29 02:25 UTC, isaacplmann commented on docs/shared/react-standalone-tutorial/react-standalone.md
> +- [Join the Official Nx Server](http://go.nx.dev/community) to ask questions and find out the latest news about Nx.
```suggestion
- [Join the Official Nx Discord Server](http://go.nx.dev/community) to ask questions and find out the latest news about Nx.
```

2023-08-29 08:11 UTC, juristr approved these changes

2023-08-29 13:16 UTC, isaacplmann approved these changes

2023-08-29 14:45 UTC, FrozenPandaz requested changes

2023-08-29 14:45 UTC, FrozenPandaz commented on scripts/readme-fragments/links.md
> +[![Join us on the Official Nx Discord Server](https://simpleicons.org/icons/discord.svg)](http://go.nx.dev/community)
The link here should be `https`

2023-08-29 14:45 UTC, FrozenPandaz commented on README.md
> +[![Join the Official Nx Discord Server](https://img.shields.io/discord/1143497901675401286?label=discord)](http://go.nx.dev/community)
The link here should be `https`

2023-08-29 14:45 UTC, FrozenPandaz commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: http://go.nx.dev/community
The link here should be `https`

2023-08-29 15:01 UTC, ZackDeRose commented
Thanks @FrozenPandaz!! Updated for https

2023-09-06 20:56 UTC, jaysoo approved these changes

2023-09-07 15:01 UTC, FrozenPandaz approved these changes

2023-09-07 15:01 UTC, FrozenPandaz commented on docs/shared/react-standalone-tutorial/react-standalone.md
> +- [Join the Official Nx Discord Server](http://go.nx.dev/community) to ask questions and find out the latest news about Nx.
Missed one.

Could you open a separate PR to change all the `http://` in here please?

2023-09-07 15:01 UTC, merged