docs(core): react-monorepo tutorial
nrwl/nx pull request #18940
Opened 2023-08-31 13:20 UTC by isaacplmann

Creates a react-monorepo tutorial

2023-09-07 13:09 UTC, juristr requested changes

2023-09-07 13:09 UTC, juristr commented on docs/shared/react-tutorial/react-monorepo.md
> +## Visualizing your Project Structure
I would show the entire monorepo. THe graph right now only shows the `myreactapp` but doesn't show the `second-app`. I'd have at least a structure where we have a monorepo with these two apps and some libs that are just used by one app and some by both (e.g. the shared-ui for instance could be used by both). 

Or if we have these two `orders` and `products` we could have a second application `vendors` or `admin` that also imports `products` as a hypothetical app which manages the products on this store.

2023-09-07 13:09 UTC, juristr commented on docs/shared/react-tutorial/react-monorepo.md
> +## Building the App for Deployment
I think we should explain more here, like how we handle deployments for both apps. That is..

- deploy both individually => running the build for both individually
- just run `npx nx run-many -t build -p myreactapp second-app`
- use `affected:build`

for the "affected" to work here, we need to have shown it before. I forgot adding a section for that on the Linear issue, but I'd add that after the "Testing and Linting...." where we show running multiple commands and caching. I'd have a section right after that shows how to only run it for a subset of the monorepo, show the affected part n the graph etc...

2023-09-07 13:09 UTC, juristr commented on docs/shared/react-tutorial/react-monorepo.md
> +## Next Steps
on the linear issue, I also had a section "Setting up CI". Any reason that was skipped here?

2023-09-13 15:13 UTC, juristr requested changes
LGTM, just some minor things. 
Can you also include it in the main intro page. There should already be a tile to uncomment for the React monorepo tutorial; the link just needs to be adjusted afair

Thanks!

2023-09-13 15:13 UTC, juristr commented on docs/shared/react-tutorial/react-monorepo.md
> +- [Speed up CI: Run only tasks for project that got changed](/core-features/run-tasks#run-tasks-affected-by-a-pr)]
there's a `]` too much, same for the next line

2023-09-13 15:13 UTC, juristr commented on docs/shared/react-tutorial/react-monorepo.md
> +### Caching
I think this accidentally finished up in the wrong section. Should have been in the "Testing and Linting ..." section.

2023-09-13 15:58 UTC, isaacplmann commented
I'll wait to add the tutorial to the intro until we have the other 2 tutorials.  It looks bad adding just one on its own row
![Screenshot 2023-09-13 at 11 58 08 AM](https://github.com/nrwl/nx/assets/861504/604089e2-9168-4a7e-8696-ab3368e97f52)

2023-09-13 18:04 UTC, juristr approved these changes

2023-09-13 18:04 UTC, merged