feat(webpack): move module federation utils to webpack
nrwl/nx pull request #18996
Opened 2023-09-05 09:29 UTC by Coly010

## Current Behavior

Our Module Federation utilities currently live in `@nx/devkit`. They were placed here for convenience during the previous effort on MF.

## Expected Behavior

Our Module Federation utilities will live in `@nx/webpack` which makes more sense as we currently, and for the foreseeable future, only support Webpack Module Federation.
This will also remove them from the `@nx/devkit` Public API, usage of which has been deprecated already.

## Related Issue(s)

Fixes #

2023-09-06 14:47 UTC, jaysoo approved these changes

2023-09-06 14:50 UTC, AgentEnder approved these changes

2023-09-07 16:01 UTC, FrozenPandaz requested changes

2023-09-08 14:22 UTC, FrozenPandaz approved these changes

2023-09-08 14:22 UTC, FrozenPandaz commented on packages/webpack/src/utils/module-federation/secondary-entry-points.ts
> +let { readModulePackageJson } = requireNx();
You changed other imports other than this. Can you change this too in a followup please?

This should come from nx directly.

2023-09-08 14:22 UTC, merged