feat(vue): add private Vue plugin
nrwl/nx pull request #19009
Opened 2023-09-05 17:38 UTC by jaysoo

This PR adds an empty vue plugin to start adding generators and executors to. It is marked as `private` for now so we don't publish until it is feature complete.

2023-09-05 17:38 UTC, jaysoo commented on packages/vue/package.json
> +  "private": true,
This will prevent `@nx/vue` from being published (except to local registry).

2023-09-05 17:59 UTC, mandarini approved these changes

2023-09-05 18:00 UTC, AgentEnder commented on CODEOWNERS
> +/e2e/vue/** @nrwl/nx-js-reviewers
Can we go ahead and make this a separate team? I can create it if you update the code

2023-09-05 18:09 UTC, JamesHenry requested changes
Some comments all related to Angular CLI config

2023-09-05 18:09 UTC, JamesHenry commented on packages/vue/package.json
> +  "ng-update": {
I don't think we should use the Angular CLI compat syntax here, it won't ever be used in an Angular CLI workspace context, right?

```suggestion
  "nx-migrations": {
```

2023-09-05 18:09 UTC, JamesHenry commented on packages/vue/package.json
> +  "builders": "./executors.json",
```suggestion
  "executors": "./executors.json",
```

Building on my comment about Angular CLI, do we really want `"builders"` here at all on a package that will never be used in an Angular CLI workspace?

2023-09-05 18:09 UTC, JamesHenry commented on packages/vue/package.json
> +  "schematics": "./generators.json",
```suggestion
  "generators": "./generators.json",
```

Building on my comment about Angular CLI, do we really want "generators" here at all on a package that will never be used in an Angular CLI workspace?

2023-09-05 18:09 UTC, JamesHenry commented on packages/vue/executors.json
> +  "builders": {},
Building on my comment about Angular CLI, do we really want "builders" here on a package that will never be used in an Angular CLI workspace?

2023-09-05 18:28 UTC, JamesHenry commented on packages/vue/generators.json
> +  "schematics": {},
```suggestion
```

Sorry missed this one before, same Angular CLI point

2023-09-05 19:12 UTC, meeroslav commented on packages/vue/.eslintrc.json
> +            "ignoredDependencies": ["nx", "typescript"]
Why is Nx ignored? Shouldn't it be `peerDependency`?

2023-09-05 19:14 UTC, meeroslav commented on tsconfig.base.json
> +      "@nx/vue": ["packages/vue/src/index.ts"],
This path is incorrect. There is no `src/index.ts`.
```suggestion
      "@nx/vue": ["packages/vue"],
```

2023-09-05 19:15 UTC, meeroslav submitted a review, later dismissed
Left two minor notes

2023-09-06 09:54 UTC, JamesHenry approved these changes

2023-09-06 15:05 UTC, AgentEnder approved these changes

2023-09-06 15:23 UTC, FrozenPandaz approved these changes

2023-09-06 17:58 UTC, merged