docs(nx): add more detail to Nx CLI guide
nrwl/nx pull request #1901
Opened 2019-09-30 20:04 UTC by brandonroberts

_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#submit-pr)_

> _Please make sure that your commit message follows our format._

> Example: `fix(nx): must begin with lowercase`

## Current Behavior (This is the behavior we have today, before the PR is merged)

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

## Issue

2019-09-30 21:37 UTC, vsavkin requested changes
I like it. It's much better than before.

There are a few more things I'd like to mention. 
- Configurations. And that any builder invocation involves project/target/configuration.
- defaultCollection. Why `nx g app myapp` can be the same as `nx g @nrwl/react:app myapp`.
- nx g app --help shows the options

And I'd like to mention that it's extensible:
- That folks can add their own targets (maybe use the run-commands builder as an example)

2019-09-30 21:37 UTC, vsavkin commented on docs/react/guides/cli.md
> +### affected
Is it actually printing the list of projects?

2019-09-30 21:37 UTC, vsavkin commented on docs/react/guides/cli.md
> +
Even though you mentioned it, maybe it's worth explicitly showing how to use nx affected --target=lint. Just so folks know that they can run anything with affected

2019-10-04 20:12 UTC, vsavkin requested changes

2019-10-04 20:12 UTC, vsavkin commented on docs/react/guides/cli.md
> +### affected
Does it work for you?

I'm getting "Invalid options provided"

2019-10-04 20:12 UTC, vsavkin commented on docs/react/guides/cli.md
> +You can read more about these commands in the guide about [nly rebuilding and retesting what is affected](react/guides/monorepo-affected).
nly => only

2019-10-10 15:31 UTC, vsavkin commented
@brandonroberts sorry, I think it needs to be rebased.

2019-10-14 13:26 UTC, brandonroberts commented
@vsavkin done

2019-10-15 19:34 UTC, merged