docs(devkit): add link to docs
nrwl/nx pull request #19145
Opened 2023-09-13 12:24 UTC by juristr

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-09-14 12:53 UTC, meeroslav commented on docs/generated/manifests/packages.json
> +    "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, working w
```suggestion
    "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, working with Abstract Syntax Trees(ASTs), and more. Learn more about [extending Nx by leveraging the Nx Devkit](https://nx.dev/extending-nx/intro/getting-started) on our docs.",
```

2023-09-14 12:54 UTC, meeroslav commented on docs/generated/manifests/packages.json
> +        "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, worki
```suggestion
        "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, working with Abstract Syntax Trees(ASTs), and more. Learn more about [extending Nx by leveraging the Nx Devkit](https://nx.dev/extending-nx/intro/getting-started) on our docs..",
```

2023-09-14 12:55 UTC, meeroslav commented on docs/generated/packages-metadata.json
> +    "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, working w
```suggestion
    "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, working with Abstract Syntax Trees(ASTs), and more. Learn more about [extending Nx by leveraging the Nx Devkit](https://nx.dev/extending-nx/intro/getting-started) on our docs.",
```

2023-09-14 12:55 UTC, meeroslav commented on docs/generated/packages-metadata.json
> +        "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, worki
```suggestion
        "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, working with Abstract Syntax Trees(ASTs), and more. Learn more about [extending Nx by leveraging the Nx Devkit](https://nx.dev/extending-nx/intro/getting-started) on our docs.",
```

2023-09-14 12:55 UTC, meeroslav commented on docs/packages.json
> +    "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, working w
```suggestion
    "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, working with Abstract Syntax Trees(ASTs), and more. Learn more about [extending Nx by leveraging the Nx Devkit](https://nx.dev/extending-nx/intro/getting-started) on our docs.",
```

2023-09-14 12:56 UTC, meeroslav commented on packages-legacy/devkit/package.json
> +  "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, working wit
```suggestion
  "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, working with Abstract Syntax Trees(ASTs), and more. Learn more about [extending Nx by leveraging the Nx Devkit](https://nx.dev/extending-nx/intro/getting-started) on our docs.",
```

2023-09-14 12:56 UTC, meeroslav commented on packages/devkit/package.json
> +  "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, working wit
```suggestion
  "description": "The Nx Devkit is used to customize Nx for different technologies and use cases. It contains many utility functions for reading and writing files, updating configuration, working with Abstract Syntax Trees(ASTs), and more. Learn more about [extending Nx by leveraging the Nx Devkit](https://nx.dev/extending-nx/intro/getting-started) on our docs.",
```

2023-09-14 12:57 UTC, meeroslav requested changes
Minor change for more semantical links

2023-09-14 12:59 UTC, isaacplmann approved these changes

2023-10-27 13:35 UTC, meeroslav approved these changes

2023-10-27 13:38 UTC, FrozenPandaz approved these changes

2023-10-27 13:38 UTC, merged