feat(core): include non-project files on fileMap and filesToProcess
nrwl/nx pull request #19217
Opened 2023-09-18 18:16 UTC by AgentEnder

## Current Behavior
`filesToProcess` doesn't include non project files, so there is no indication inside of `createDependencies` if one has changed. This leads to requiring custom caching and hashing behavior on the plugin side to avoid extra work.

## Expected Behavior
`filesToProcess` includes non project files

## Related Issue(s)

Fixes #

2023-09-18 20:25 UTC, FrozenPandaz requested changes

2023-09-18 20:25 UTC, FrozenPandaz commented on packages/nx/src/config/project-graph.ts
> +export interface NonProjectFileData extends BaseFileData {
Make this more similar to the projectFileMap deps.

Add a tuple of `[src, target, type]`

2023-09-19 21:32 UTC, FrozenPandaz approved these changes

2023-09-19 21:32 UTC, FrozenPandaz commented on packages/nx/src/native/workspace/workspace_files.rs
> +
rm

2023-09-19 21:32 UTC, FrozenPandaz commented on packages/nx/src/project-graph/project-graph-builder.ts
> +      fileData ??= getNonProjectFileData(sourceFile, this.allWorkspaceFiles);
```suggestion
      fileData ??= getNonProjectFileData(sourceFile, this.nonProjectFiles);
```

2023-09-19 21:34 UTC, FrozenPandaz requested changes
Double check all of the createDependencies functions

2023-09-19 21:54 UTC, FrozenPandaz approved these changes

2023-09-19 22:31 UTC, ndcunningham approved these changes

2023-09-20 01:46 UTC, merged