feat(misc): use cwd/<project name> as a default for the directory option in project generators
nrwl/nx pull request #19227
Opened 2023-09-19 12:09 UTC by leosvelperez

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-09-19 16:45 UTC, AgentEnder approved these changes

2023-09-20 13:29 UTC, FrozenPandaz requested changes

2023-09-20 13:29 UTC, FrozenPandaz commented on packages/devkit/src/generators/project-name-and-root-utils.ts
> +  } else if (options.rootProject) {
Make even provided `directory` options relative from the cwd.

2023-09-22 12:27 UTC, FrozenPandaz approved these changes

2023-09-22 12:28 UTC, merged