feat(core): creat the task plan in rust
nrwl/nx pull request #19233
Opened 2023-09-19 14:14 UTC by Cammisuli

- feat(core): add WorkspaceContext class
- feat(core): remove FileHasher class
- feat(core): create the task plan in rust

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-10-10 20:55 UTC, FrozenPandaz requested changes

2023-10-10 20:55 UTC, FrozenPandaz commented on packages/nx/src/native/tasks/dep_outputs.rs
> +        println!(
Change to debugLog

2023-10-10 21:03 UTC, FrozenPandaz commented on packages/nx/src/native/tasks/hash_planner.rs
> +    ) -> anyhow::Result<HashMap<String, Vec<String>>> {
Create a separate function which keeps it as a `HashInstruction` which will be easier to work with within Rust.

2023-10-10 21:10 UTC, FrozenPandaz commented on packages/nx/src/native/tasks/hash_planner.rs
> +    ) -> anyhow::Result<HashMap<String, Vec<String>>> {
enum HashInstruction {
  'AllExternalDependencies'
  'ExternalNode'
  'FileSet'
  'EnvironmentVariable'
  'Runtime'
  'ProjectConfiguration'
  'TsConfiguration'
  'TaskOutput'
}

2023-10-11 11:05 UTC, Cammisuli commented on packages/nx/src/native/tasks/inputs.rs
> +    let target_data = project_node
Tests were failing without the `targetDefaults`. I migrated most of the tests from `task-hasher.spec.ts` which specifically has a test called `"should use targetDefaults from nx.json"`

2023-10-12 15:53 UTC, FrozenPandaz approved these changes

2023-10-12 16:59 UTC, merged