feat(core): add NX_ENV_EXPAND environment variable to disable expansion if desired
nrwl/nx pull request #19401
Opened 2023-10-02 06:00 UTC by benpsnyder

## Current Behavior
Nx always expands environment variables using `dotenv-expand`.

## Expected Behavior
The user can disable expansion of variables by setting `NX_ENV_EXPAND=false`

## Related Issue(s)
#19400

2023-11-28 17:55 UTC, Cammisuli commented
Sorry! I've been busy working on something that's taking more time than I would have liked 😅 

I haven't forgot about this, it's on my todos!

2023-11-30 17:00 UTC, Cammisuli commented on packages/nx/src/tasks-runner/task-env.ts
> +  envExpand = process.env.NX_ENV_EXPAND !== undefined
this doesn't need to be a argument to this function. You can remove it and use the logic suggested in the if branch

2023-11-30 17:01 UTC, Cammisuli commented on packages/nx/src/tasks-runner/task-env.ts
> +    if (envExpand) {
```suggestion
    if (process.env.NX_ENV_EXPAND !== 'false') {
```

2023-11-30 17:01 UTC, Cammisuli requested changes
see comments

2023-11-30 19:13 UTC, SmoshySmosh commented
I'm really looking forward to this feature!

2023-12-01 12:52 UTC, Riron commented
If I am not mistaking, the same check should be applied [here](https://github.com/nrwl/nx/blob/master/packages/nx/bin/nx.ts#L119). Otherwise, NX will be comparing expanded & non expanded envs when unloading envs during tasks run [here](https://github.com/nrwl/nx/blob/master/packages/nx/src/tasks-runner/task-env.ts#L192).

2024-05-18 20:32 UTC, closed without merging