docs(core): nx cloud workflows intro
nrwl/nx pull request #19424
Opened 2023-10-03 14:51 UTC by isaacplmann

Adds a page describing nx cloud workflows

2023-10-03 19:30 UTC, juristr requested changes

2023-10-03 19:30 UTC, juristr commented on docs/nx-cloud/intro/nx-cloud-workflows.md
> +## Powerful CI Capabilities Optimized for Nx monorepos
I'm missing a bit the "Why" in this and next section. We describe what Nx Cloud workflow does etc, but not why you want to use it. We still need the latter (e.g. evolution of DTE, automatic scaling etc) but I think if we describe it from the "why beneficial" standpoint it resonates better

Things like
- "legacy" CI is low-level command execution on machines in the cloud
- they don't understand your workspace, just run commands
- Nx Cloud Workflows is task centric, you give it tasks to run and it knows how to split them into lots of fine-grained commands/targets based on your workspace structure
- cost savings due to automated DTE scaling, which before/right now you have to figure out almost on your own; like what number of agents makes most sense at your current monorepo situation to have good parallelism while still not wasting money by spinning up machines

something like this

2023-10-04 17:55 UTC, isaacplmann commented on docs/nx-cloud/intro/nx-cloud-workflows.md
> +{% youtube
waiting on a youtube link

2023-10-04 17:56 UTC, isaacplmann commented on docs/nx-cloud/intro/nx-cloud-workflows.md
> +If you are interested in being one of the first organizations to experience Nx Cloud Workflows, contact [cloud-support@nrwl.io](mailto://cloud-support@nrwl.io).
I'll add the sign up form if it is published before this PR is merged

2023-10-04 18:38 UTC, juristr approved these changes

2023-10-05 12:01 UTC, isaacplmann commented on docs/nx-cloud/intro/nx-cloud-workflows.md
> +{% youtube
removed the video.  I'll add it in a separate PR

2023-10-05 12:07 UTC, merged