Fix custom local angular executors not being transpiled
nrwl/nx pull request #19476
Opened 2023-10-06 11:41 UTC by skrtheboss

Avoid calling createProjectGraphAsync in readMergedWorkspaceConfiguration since it is already available.

## Current Behavior

Custom angular build executor no longer works if used in combination with useDaemonProcess: false.

## Expected Behavior

Custom angular builder should work even if useDaemonProcess: false is set to false.

## Related Issue(s)

Fixes #19475

2023-10-06 22:58 UTC, AgentEnder requested changes
Hey @skrtheboss 🎉 Thanks for taking a stab at this - I think that there may be a slightly different approach that would better suit this, involving making sure that the transpiler is registered when calling the async loader for the builder. This would be after the project graph creation process, so I wouldn't expect it to get shut back down in between the two. I'll take a look into this sometime soon, and make sure I'm not missing something.

2023-10-06 22:58 UTC, AgentEnder commented on docs/generated/devkit/ngcli_adapter/wrapAngularDevkitSchematic.md
> +▸ **wrapAngularDevkitSchematic**(`collectionName`, `generatorName`): (`host`: `Tree`, `projectGraph`: `ProjectGraph`, `generatorOptions`: { `[k: string]`: `any`; }) => `Promise`<`any`\>
This function is public API, we can't add a new required option here.

2023-10-06 22:58 UTC, AgentEnder commented on packages/nx/src/adapter/ngcli-adapter.ts
> +    projectGraph: ProjectGraph,
We can't add this here, as this is public API surface. We may be able to call createProjectGraphAsync inside the body of the returned function, would that help with the issue you are seeing?

2023-10-06 22:58 UTC, AgentEnder commented on packages/nx/src/utils/nx-plugin.ts
I don't think adding reference counts here should be necessary. The builder code is loaded after the graph is registered, so if the transpiler was already unregistered I'd expect us to re-register it when trying to load the .ts files.

2023-10-07 08:27 UTC, skrtheboss commented
Hi @AgentEnder, no worries, i just published what i tried when i was debugging the issue, so maybe it could help understand what was going on. I don't know the code very well, so if you have a better suited solution, just drop this one.
Thank you for the feedback!

2024-06-04 15:17 UTC, AgentEnder commented
Going to close this PR out - we need to take a different route and likely re-evaluate after plugin iso is enabled.

2024-06-04 15:17 UTC, closed without merging