feat(nuxt): storybook generators
nrwl/nx pull request #19529
Opened 2023-10-10 13:31 UTC by mandarini

* `@nx/nuxt:storybook-configuration`
* `@nx/nuxt:stories`

Invoking the `@nx/vue` generators, since Storybook does not officially support any nuxt-specific framework or module at the moment.

2023-10-10 14:14 UTC, isaacplmann approved these changes

2023-10-12 09:30 UTC, Coly010 approved these changes

2023-10-12 13:53 UTC, JamesHenry commented on packages/nuxt/src/generators/stories/schema.json
> +  "$id": "NxVueStorybookStories",
```suggestion
  "$id": "NxNuxtStorybookStories",
```

2023-10-12 13:54 UTC, JamesHenry commented on packages/nuxt/src/generators/stories/schema.json
> +  "title": "Generate Vue Storybook stories",
```suggestion
  "title": "Generate Nuxt Storybook stories",
```

2023-10-12 13:56 UTC, JamesHenry commented on packages/nuxt/src/generators/storybook-configuration/schema.json
> +  "$id": "NxVueStorybookConfigure",
```suggestion
  "$id": "NxNuxtStorybookConfigure",
```

2023-10-12 13:56 UTC, JamesHenry commented on packages/nuxt/src/generators/storybook-configuration/schema.json
> +  "title": "Vue Storybook Configure",
```suggestion
  "title": "Nuxt Storybook Configure",
```

2023-10-12 13:56 UTC, JamesHenry commented on packages/nuxt/src/generators/storybook-configuration/schema.json
> +  "description": "Set up Storybook for a Vue project.",
```suggestion
  "description": "Set up Storybook for a Nuxt project.",
```

2023-10-12 13:57 UTC, JamesHenry requested changes
Mainly copy 🍝 issues and one point around globs, otherwise LGTM

2023-10-12 13:59 UTC, mandarini commented
Fixed!

2023-10-12 14:01 UTC, JamesHenry approved these changes

2023-10-12 14:31 UTC, ndcunningham approved these changes
LGTM

2023-10-12 14:31 UTC, merged