feat(core): add standard way to pass plugin options
nrwl/nx pull request #19589
Opened 2023-10-12 19:46 UTC by AgentEnder

## Current Behavior
There's not a standardized way to provide options for a graph / inference plugin

## Expected Behavior
Plugins can be specified as an object, with options provided.

## Related Issue(s)

Fixes #

2023-10-12 22:46 UTC, FrozenPandaz requested changes

2023-10-12 22:46 UTC, FrozenPandaz commented on packages/nx/src/utils/nx-plugin.ts
> +  plugin.options = options;
Return it alongside the plugin, not on the plugin

2023-10-16 06:23 UTC, leosvelperez approved these changes

2023-10-16 20:31 UTC, FrozenPandaz requested changes

2023-10-16 22:23 UTC, FrozenPandaz approved these changes

2023-10-16 22:24 UTC, merged