feat(vue): support generating components using the path as provided
nrwl/nx pull request #19609
Opened 2023-10-13 19:04 UTC by jaysoo

This PR updates `@nx/vue:component` to support a component path provided as is.

e.g.

```
# this generates at libs/ui/src/button.vue, the path belongs to a project
nx g component libs/ui/src/button
```

2023-10-16 09:13 UTC, leosvelperez requested changes, later dismissed

2023-10-16 09:13 UTC, leosvelperez commented on packages/vue/src/generators/component/schema.json
> +      }
We need to deprecate `--project`.

2023-10-16 09:13 UTC, leosvelperez commented on packages/vue/src/generators/component/schema.d.ts
We need to add the deprecated JSDoc for the deprecated properties here to notify devs using the generator programmatically.

2023-10-16 09:13 UTC, leosvelperez commented on packages/vue/src/generators/component/schema.json
We also need to deprecate `--pascalCaseFiles` and `--pascalCaseDirectory`.

2023-10-16 09:13 UTC, leosvelperez commented on packages/vue/src/generators/component/schema.json
Let's also update the description for `--directory` to match the one we're adding for other generators using both formats.

2023-10-16 09:30 UTC, mandarini approved these changes

2023-10-17 18:11 UTC, FrozenPandaz approved these changes

2023-10-17 18:12 UTC, merged