feat(core): rust task hasher
nrwl/nx pull request #19617
Opened 2023-10-14 20:54 UTC by Cammisuli

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-11-14 08:33 UTC, mandarini approved these changes
Changes in `js` look good to me!

2023-11-14 21:21 UTC, FrozenPandaz requested changes

2023-11-17 16:33 UTC, FrozenPandaz approved these changes

2023-11-17 16:33 UTC, FrozenPandaz commented on packages/nx/src/hasher/native-task-hasher-impl.ts
> +    let tsconfig = readJsonFile(getRootTsConfigPath());
const

2023-11-17 16:33 UTC, FrozenPandaz commented on packages/nx/src/hasher/native-task-hasher-impl.ts
> +    let paths = tsconfig.compilerOptions?.paths ?? {};
const

2023-11-21 13:55 UTC, merged