fix(react): Update error message for invalid remote name
nrwl/nx pull request #19744
Opened 2023-10-19 16:05 UTC by ndcunningham

## Current Behavior

Currently, when you have an invalid remote you only get this error.

```shell
 >  NX   Cannot read properties of undefined (reading 'data')

TypeError: Cannot read properties of undefined (reading 'data')
    at readCachedProjectConfiguration (/private/tmp/projects/react-mfe/node_modules/nx/src/project-graph/project-graph.js:47:17)
    at /private/tmp/projects/react-mfe/node_modules/@nx/react/src/module-federation/utils.js:11:88
    at handleStringRemote (/private/tmp/projects/react-mfe/node_modules/@nx/webpack/src/utils/module-federation/remotes.js:45:30)
    at mapRemotes (/private/tmp/projects/react-mfe/node_modules/@nx/webpack/src/utils/module-federation/remotes.js:20:37)
    at getModuleFederationConfig (/private/tmp/projects/react-mfe/node_modules/@nx/react/src/module-federation/utils.js:62:25)
    at withModuleFederation (/private/tmp/projects/react-mfe/node_modules/@nx/react/src/module-federation/with-module-federation.js:11:112)
    at Object.<anonymous> (/private/tmp/projects/react-mfe/home/webpack.config.js:15:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (/private/tmp/projects/react-mfe/node_modules/ts-node/src/index.ts:1608:43)
```
## Expected Behavior

Have a better error message.
```shell
Cannot find project "remoteDoesNotExists". Check that the name is correct in your module-federation config file.
```
## Related Issue(s)

Fixes #

2023-10-19 18:18 UTC, jaysoo commented on packages/angular/src/utils/mf/utils.ts
> +        `Cannot find remote "${remote}". Check that the remote name is correct in your module-federation.config.js.\n`
It could be `module-configuration.ts`, probably just say `module federation config file`.

2023-10-19 18:18 UTC, jaysoo approved these changes

2023-10-19 18:46 UTC, AgentEnder requested changes

2023-10-19 18:46 UTC, AgentEnder commented on packages/angular/src/utils/mf/utils.ts
> +    }
Its ok to add a bespoke error message here, but can we also update the error messaging in `readCachedProjectConfiguration` s.t. it doens't look so bad in the first place?

2023-10-23 15:09 UTC, AgentEnder approved these changes

2023-10-23 15:09 UTC, merged