fix(vue): do not add @vue/tsconfig dependency
nrwl/nx pull request #19873
Opened 2023-10-26 12:44 UTC by benkroeger

## Current Behavior

@nx/vue:init generator adds a dev dependency for @vue/tsconfig but this package is never used.

## Expected Behavior

do not install @vue/tsconfig when it's not used

## Related Issue(s)
n.a.

2023-10-26 16:31 UTC, ndcunningham requested changes
Hey, thanks for contributing!

However, you need to do some additional updates.
references 
- `packages/vue/src/generators/init`

You need to update test snapshots for `init.spec` and `library.spec`

2024-01-29 17:34 UTC, mandarini approved these changes

2024-01-30 16:37 UTC, jaysoo approved these changes

2024-01-30 16:58 UTC, ndcunningham approved these changes

2024-01-30 16:58 UTC, merged