feat(core): flatten default base config to base
nrwl/nx pull request #19964
Opened 2023-10-31 21:25 UTC by AgentEnder

## Current Behavior
defaultBase is placed inside `affected`

## Expected Behavior
`defaultBase` is specified by `base` at the root of nx.json

## Related Issue(s)

Fixes #

2023-11-02 11:24 UTC, leosvelperez approved these changes

2023-11-28 17:05 UTC, FrozenPandaz requested changes

2023-11-28 17:05 UTC, FrozenPandaz commented on packages/nx/migrations.json
> +      "version": "17.1.0",
Please change the version of this migration

2023-11-28 17:05 UTC, FrozenPandaz commented on packages/workspace/src/generators/ci-workflow/ci-workflow.ts
> +  console.log(base);
rm

2023-11-28 17:05 UTC, FrozenPandaz commented on packages/workspace/src/generators/new/generate-workspace-files.ts
>      delete nxJson.affected;
rm

2023-11-28 17:05 UTC, FrozenPandaz commented on packages/nx/schemas/nx-schema.json
> +      "deprecated": "Use `defaultBase` instead."
Please add when support for this will be dropped.

2024-02-22 21:50 UTC, merged