feat(linter): support yaml for flat config conversion WIP
nrwl/nx pull request #20022
Opened 2023-11-02 22:05 UTC by meeroslav

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-11-19 11:04 UTC, JamesHenry requested changes
Blocker is .yml support, optional for this PR is exploring the newline spacing in converted output

2023-11-19 11:04 UTC, JamesHenry commented on packages/eslint/src/generators/convert-to-flat-config/generator.ts
> +  if (source.endsWith('.yaml')) {
Yaml config can be `.eslintrc.yml` or `.eslintrc.yaml`

2023-11-19 11:04 UTC, JamesHenry commented on packages/eslint/src/generators/convert-to-flat-config/generator.ts
> +  if (/\.base\.(js|json|yaml)$/.test(eslintFile)) {
Yaml config can be .eslintrc.yml or .eslintrc.yaml

2023-11-19 11:04 UTC, JamesHenry commented on packages/eslint/src/generators/convert-to-flat-config/generator.spec.ts
> +  it('should convert yaml successfully', async () => {
Let's add a test for `.yml` too for completeness

2023-11-19 11:04 UTC, JamesHenry commented on packages/eslint/src/generators/convert-to-flat-config/__snapshots__/generator.spec.ts.snap
> +"const baseConfig = require('../../eslint.config.js');
We'd previously discussed improving the newline spacing here in the converted output

2023-11-19 11:04 UTC, JamesHenry commented on packages/eslint/src/generators/convert-to-flat-config/__snapshots__/generator.spec.ts.snap
> +const js = require('@eslint/js');
We'd previously discussed improving the newline spacing here in the converted output

2023-11-22 11:44 UTC, JamesHenry commented
Changes LGTM but triggered re-run of CI to try and get it green first

2023-11-22 12:33 UTC, JamesHenry approved these changes

2023-11-22 12:37 UTC, mandarini approved these changes

2023-11-22 19:37 UTC, merged