feat: add run-many
nrwl/nx pull request #2003
Opened 2019-10-28 19:27 UTC by mbriggs

- want some feedback on this, commented out affected.spec.ts, that still needs to be implemented
 - _think_ it would be a good idea to make `--projects` and `--all` to be exclusive/required
 - add a new command (run-many) that basically is the same as affected, but allows you to specify projects to run
 - re-structure affected.ts so that the bulk of the functionality can be shared

2019-10-31 20:24 UTC, vsavkin approved these changes
It looks good. The only two things are reenabling unit tests and adding some e2e tests.

2019-10-31 20:24 UTC, vsavkin commented on packages/workspace/src/command-line/nx-commands.ts
> +    .option('plain', {
I don't think `affected:apps` and `affected:libs` will work with run-many. And this flag is only used by the two commands.

2019-11-06 21:58 UTC, mbriggs commented
- added --all, made it mutually exclusive with --projects, but required
 - yargs has super weird array input, changed --projects to be comma delimited
 - show warnings when asking to run a project that doesn't have configuration for target
 - show errors when asking to run a project that doesn't exist in the project
 - change the default reporter copy to not say "affected" (think whats there works fine in both cases)
 - rebase on to latest master (includes some bug fixes to affected.ts)

Still need to add tests

2019-11-13 14:13 UTC, vsavkin requested changes
Left some feedback. I think there is an issue with the dep-graph in run-many. The rest looks good.

2019-11-13 14:13 UTC, vsavkin commented on packages/workspace/src/command-line/run-tasks/run-command.ts
> +  projects.forEach(project => {
TaskMap is a set of all possible tasks, so it cannot be derived from the list of projects you are currently running.

2019-11-13 14:13 UTC, vsavkin commented on packages/workspace/src/command-line/run-tasks/run-command.ts
> +  projects.forEach(project => {
In the current version is done like this:

Object.entries(affectedMetadata.dependencyGraph.projects)

So we generate a task map from the list of all possible projects

2019-11-13 14:13 UTC, vsavkin commented on packages/workspace/src/command-line/run-tasks/run-command.ts
> +  projects: ProjectNode[],
I'd rename it to indicate that this isn't list of all possible projects but only the projects are running tasks against this time.

2019-11-13 14:13 UTC, vsavkin commented on packages/workspace/src/command-line/run-tasks/run-many.ts
> +    projects: map,
DependencyGraph must contain all projects. This map is only the projects you are running tasks against.

2019-11-13 14:13 UTC, vsavkin commented on packages/workspace/src/command-line/run-tasks/run-many.ts
> +function projectListToGraph(projects: ProjectNode[]): DependencyGraph {
DependencyGraph describes the workspace. It must contain all projects, all dependenciesd and real roots. This function doesn't do this.

2019-11-13 14:13 UTC, vsavkin commented on packages/workspace/src/command-line/run-tasks/run-command.ts
> +  projectGraph: DependencyGraph,
why not call it dependencyGraph?

2019-11-15 23:59 UTC, merged