feat(vite): add nodes - init commit
nrwl/nx pull request #20086
Opened 2023-11-07 10:40 UTC by mandarini

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-11-09 13:34 UTC, Coly010 approved these changes

2023-11-09 13:38 UTC, jaysoo commented on packages/vite/src/plugins/plugin.ts
> +  getViteConfig(configFilePath, context);
I think you will need to find the output directory. Right now it is hardcoded as `joinPathFragments('dist', projectRoot)` but the user could change it.

2023-11-09 14:55 UTC, jaysoo approved these changes

2023-11-09 14:56 UTC, jaysoo requested changes
We should handle reading output from config. This is blocked on making `CreateNodes` handle async.

2023-11-27 22:53 UTC, FrozenPandaz requested changes

2023-11-27 22:53 UTC, FrozenPandaz commented on packages/vite/src/migrations/update-17-2-0/add-vite-plugin.ts
> +  await replaceProjectConfigurationsWithPlugin(
This won't do much so we should remove it for now.

2023-11-27 22:53 UTC, FrozenPandaz commented on packages/vite/src/migrations/update-17-2-0/add-vite-plugin.ts
> +  // reportsDirectory: '../../coverage/apps/my-app',
Do we need a migration for this?

2023-11-29 15:21 UTC, mandarini commented on packages/vite/src/generators/init/lib/utils.ts
> +  nxJson.targetDefaults['@nx/vite:test'].options ??= {
Yes, I agree, let's not add the target defaults.

I am not sure I understand the meaning of (3). We should not configure jest/vitest at all?

2023-11-30 18:54 UTC, isaacplmann approved these changes

2023-11-30 19:44 UTC, jaysoo approved these changes

2023-11-30 20:56 UTC, FrozenPandaz approved these changes

2023-11-30 20:56 UTC, merged