fix(release): catch 403 when publishing an existing version
nrwl/nx pull request #20155
Opened 2023-11-09 17:03 UTC by fahslaj

## Current Behavior

Publishing fails when the existing version of the package already exists on npm.

## Expected Behavior

Publishing continues when the existing version of the package already exists on npm.

2023-11-09 19:23 UTC, FrozenPandaz requested changes

2023-11-09 19:23 UTC, FrozenPandaz commented on packages/js/src/executors/release-publish/release-publish.impl.ts
> +      console.error(JSON.stringify(stdoutData, null, 2));
Maybe keep the current one but then print this when verbose is true.

2023-11-09 19:37 UTC, FrozenPandaz approved these changes

2023-11-10 06:56 UTC, JamesHenry approved these changes

2023-11-10 06:58 UTC, merged