feat(webpack): add plugin to automatically configure build and serve targets
nrwl/nx pull request #20243
Opened 2023-11-14 21:37 UTC by jaysoo

This PR adds support for projects using `webpack.config.js` files to have their `build` and `serve` targets automatically configured by `@nx/webpack/plugin`.

The plugin will support both `composePlugins` and `NxWebpackPlugin` usages. The former requires a new `isNxWebpackComposablePlugin` function that checks if a `nxWebpackComposablePlugin` exists on the exported function. Otherwise, the function could be a normal [webpack config function](https://webpack.js.org/configuration/configuration-types/#exporting-a-function).

## TODO

- [ ] Update generators to use inferred targets rather than `project.json`
- [ ] Migration for existing projects
- [ ] E2E tests to cover new cases

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-11-27 11:08 UTC, mandarini approved these changes

2023-11-27 15:48 UTC, jaysoo commented on packages/webpack/src/executors/dev-server/lib/get-dev-server-config.ts
> +    host: serveOptions.host ?? 'localhost',
remove these

2023-11-27 20:53 UTC, FrozenPandaz requested changes

2023-11-27 20:53 UTC, FrozenPandaz commented on packages/webpack/src/plugins/plugin.ts
> +      'production' in namedInputs
This should now have an input of the `webpack-cli`.

https://github.com/nrwl/nx/blob/a57122d47c0b9d2ae94facd5a865645093067342/packages/cypress/src/plugins/plugin.ts#L338C41-L338C41

2023-11-27 21:11 UTC, FrozenPandaz approved these changes

2023-11-28 16:58 UTC, ndcunningham approved these changes

2023-11-28 18:01 UTC, merged