feat(core): programmatic API for nx release
nrwl/nx pull request #20371
Opened 2023-11-22 16:41 UTC by JamesHenry

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-11-22 18:47 UTC, JamesHenry commented
Full example of how someone might build on top of this API:

```ts
import { nxReleaseChangelog } from 'nx/src/command-line/release/changelog';
import { nxReleasePublish } from 'nx/src/command-line/release/publish';
import { nxReleaseVersion } from 'nx/src/command-line/release/version';
import * as yargs from 'yargs';

(async () => {
  const options = await yargs
    .version(false) // don't use the default meaning of version in yargs
    .option('version', {
      description:
        'Explicit version specifier to use, if overriding conventional commits',
      type: 'string',
    })
    .option('dryRun', {
      alias: 'd',
      description:
        'Whether or not to perform a dry-run of the release process, defaults to true',
      type: 'boolean',
      default: true,
    })
    .option('verbose', {
      description:
        'Whether or not to enable verbose logging, defaults to false',
      type: 'boolean',
      default: false,
    })
    .parseAsync();

  const { workspaceVersion, projectsVersionData } =
    await nxReleaseVersion({
      specifier: options.version,
      // stage package.json updates to be committed later by the changelog command
      stageChanges: true,
      dryRun: options.dryRun,
      verbose: options.verbose,
    });

  await nxReleaseChangelog({
    versionData: projectsVersionData,
    version: workspaceVersion,
    interactive: 'workspace',
    dryRun: options.dryRun,
    verbose: options.verbose,
  });

  await nxReleasePublish({
    dryRun: options.dryRun,
    verbose: options.verbose,
  });

  process.exit(0);
})();
```

2023-11-22 23:26 UTC, fahslaj approved these changes

2023-11-23 12:56 UTC, meeroslav approved these changes

2023-11-23 16:37 UTC, FrozenPandaz requested changes

2023-11-23 16:37 UTC, FrozenPandaz commented on packages/nx/src/devkit-exports.ts
> +} from './project-graph/file-map-utils';
Don't expose this. import this from nx

2023-11-23 17:05 UTC, FrozenPandaz approved these changes

2023-11-23 20:50 UTC, jaysoo approved these changes

2023-11-23 20:50 UTC, merged