fix(core): small fixes to plugins
nrwl/nx pull request #20528
Opened 2023-12-01 13:02 UTC by mandarini

* fix inputs and cache for eslint
* add test to webpack plugin
* make the way inputs are written in vite plugin same as cypress plugin

2023-12-06 09:53 UTC, meeroslav commented on packages/eslint/src/plugins/plugin.ts
Can you remove these changes as they are already included in the https://github.com/nrwl/nx/pull/20583?

2023-12-07 09:35 UTC, meeroslav requested changes
I think the change to Vite's inputs is not correct.

2023-12-07 09:37 UTC, meeroslav commented on packages/vite/src/plugins/plugin.ts
> +        ? ['default', '^production']
That one might also be incorrect. I see no reason for `build` to depend on non-production files.

2023-12-07 09:38 UTC, mandarini commented
@meeroslav  And in cypress it's the same: https://github.com/nrwl/nx/blob/master/packages/cypress/src/plugins/plugin.ts#L292

Maybe I'm not understanding something correctly though, which is quite possible. 😅

2023-12-07 09:56 UTC, meeroslav approved these changes
Thanks for the fixes. LGTM!

2023-12-07 13:47 UTC, closed without merging