feat(remix): add remix
nrwl/nx pull request #20641
Opened 2023-12-07 15:38 UTC by Coly010

## Current Behavior

Remix support currently lives in `nx-labs`

## Expected Behavior

Remix support should be in `nx`

## Related Issue(s)

Fixes #

2023-12-08 08:55 UTC, Moxita33 approved these changes

2023-12-08 12:28 UTC, isaacplmann approved these changes

2023-12-08 17:24 UTC, FrozenPandaz submitted a review, later dismissed

2023-12-08 19:24 UTC, nartc commented on packages/remix/src/generators/loader/loader.impl.ts
> +  insertImport(tree, routeFilePath, 'LoaderArgs', '@remix-run/node', {
issue/nit: `LoaderArgs` is renamed to `LoaderFunctionArgs` in v2

2023-12-11 14:14 UTC, jaysoo approved these changes

2023-12-11 14:32 UTC, mandarini approved these changes

2023-12-11 16:30 UTC, meeroslav commented on e2e/remix/tests/nx-remix.test.ts
> +    proj = newProject();
You probably would like to follow the convention that @FrozenPandaz recommended on adding just the packages we need for those tests.

2023-12-11 16:36 UTC, meeroslav commented on packages/remix/package.json
> +    "@nx/jest": "file:../jest",
Why are jest, cypress, vite and storybook dependencies of remix? Those should be optional steps using `ensurePackage` when needed.

2023-12-11 16:40 UTC, meeroslav commented on packages/remix/.eslintrc.json
> +              "@nx/storybook"
These are not up to date. For example, `@nx/cypress` is added to `package.json`. I don't see `eslint` here or in `package.json`. How is linting being added?

2023-12-11 16:42 UTC, meeroslav requested changes
Linting seems to be missing for remix application.

Also package.json and .eslintrc don't seem to be optimally configured.

2023-12-12 15:10 UTC, meeroslav commented on packages/remix/project.json
> +      "outputs": ["{options.outputFile}"],
Remove outputs here. This is no longer generated automatically

2023-12-12 15:11 UTC, meeroslav commented on packages/remix/project.json
> +      "outputs": ["{options.outputFile}"],
Actually the entire lint config should be gone, use just `"lint": {}`

2023-12-12 15:11 UTC, meeroslav commented on packages/remix/project.json
> +      "executor": "@nx/jest:jest",
I believe this should also be used from targetDefaults

2023-12-12 15:19 UTC, meeroslav approved these changes
Approved with small comment

2023-12-12 15:19 UTC, meeroslav approved these changes
Approved with small comment

2023-12-13 15:50 UTC, AgentEnder approved these changes

2023-12-13 16:07 UTC, merged