feat(vite): update to vitest v1
nrwl/nx pull request #20747
Opened 2023-12-13 16:38 UTC by mandarini

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-12-13 16:48 UTC, JamesHenry requested changes
The changelog seemed pretty dense when I saw it a few days ago, were there no generated config changes (and associated migrations) necessary?

2023-12-13 16:48 UTC, JamesHenry commented on packages/vite/package.json
> +    "vitest": "<=1.0.0"
```suggestion
    "vitest": ">=1.0.0"
```

Surely?

2023-12-13 16:52 UTC, mandarini commented on packages/vite/package.json
> +    "vitest": "<=1.0.0"
oh lol yes

2023-12-13 16:55 UTC, mandarini commented
@JamesHenry works on my machine :P 
I mean, I tried it on a couple of repos locally and the tests seemed to run ok. For the next cycle, I will look more into any new features they have for monorepos or anything we do want to support. But just for running the tests with our executors, and the bare-minimum we generate, it seems to be working ok?

2023-12-13 17:48 UTC, JamesHenry commented
Ok cool, we can see if CI can pass ok to be sure

2023-12-13 19:54 UTC, jaysoo approved these changes

2023-12-14 14:36 UTC, Coly010 approved these changes

2023-12-14 15:39 UTC, xiongemi approved these changes

2023-12-14 15:55 UTC, JamesHenry approved these changes

2023-12-14 15:55 UTC, merged