Docs/vite nuxt inferred recipe
nrwl/nx pull request #20882
Opened 2023-12-21 10:36 UTC by mandarini

Build on top of https://github.com/nrwl/nx/pull/20868

Not sure if needed, but wanted to give this a shot! @isaacplmann

2023-12-21 13:59 UTC, isaacplmann commented on docs/shared/recipes/nuxt/nuxt-inferred-targets.md
> +| `inputs`  | `production` | Break the cache if any file in the project changes |
Is there no `externalDependencies` entry for `nuxi`?

2023-12-21 14:03 UTC, isaacplmann reviewed
You've got the right idea.  We need to wait to merge these until we know the final form of  the `Debug Inferred Targets` section. And we need to make sure to describe all the options that the plugin infers and where it gets those values from.

2023-12-21 15:05 UTC, mandarini commented
Perfect thanks @isaacplmann ! I just created this as a draft, to know I'm on the right track! I'll update in January!!

2024-01-02 14:50 UTC, mandarini commented
waiting for https://github.com/nrwl/nx/pull/20868 to be merged, then I will update

2024-01-04 18:18 UTC, mandarini commented
@isaacplmann I updated my PR and addressed the comments!

2024-01-04 18:29 UTC, isaacplmann requested changes
A few small changes

2024-01-04 18:29 UTC, isaacplmann commented on docs/shared/recipes/vite/vite-inferred-targets.md
> +| `inputs`  | `production`                           | Break the cache if any file in the project changes                        |
`production` breaks the cache if non-test files change.  `default` would break the cache if any file in the project changes.

2024-01-04 18:29 UTC, isaacplmann commented on docs/shared/recipes/vite/vite-inferred-targets.md
> +| `executor` | `@nx/web:file-server` | Serve statically the build output |
```suggestion
| `executor` | `@nx/web:file-server` | Serve the build output statically |
```

2024-01-04 18:29 UTC, isaacplmann commented on docs/shared/recipes/nuxt/nuxt-inferred-targets.md
> +| `inputs`  | `production`                           | Break the cache if any file in the project changes                        |
`production` breaks the cache if non-test files change. `default` would break the cache if any file in the project changes.

2024-01-04 18:43 UTC, mandarini commented
@isaacplmann done! :D

2024-01-04 20:13 UTC, merged