feat(eslint): make init generator public
nrwl/nx pull request #20890
Opened 2023-12-21 15:33 UTC by jaysoo

We need to call `nx g @nx/eslint:init` for PCv3 so this PR makes it public.

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2023-12-21 15:47 UTC, AgentEnder approved these changes

2023-12-27 20:26 UTC, meeroslav requested changes
Some minor semantical changes needed in title and description

2023-12-27 20:26 UTC, meeroslav commented on docs/generated/packages/eslint/generators/init.json
> +    "title": "Init ESLint Plugin",
Can we change this to Initialize ESLint Plugin?

2023-12-27 20:26 UTC, meeroslav commented on docs/generated/packages/eslint/generators/init.json
> +  "description": "Create the Workspace Lint Rules Project.",
This description sounds cryptic.

How about "Set up ESLint base configuration"

2023-12-28 19:57 UTC, meeroslav approved these changes

2023-12-28 19:58 UTC, merged