docs(storybook): inferred targets
nrwl/nx pull request #21038
Opened 2024-01-08 09:13 UTC by mandarini

Inferred targets docs for storybook

2024-01-08 18:31 UTC, isaacplmann requested changes
Just need to note whether outputs are static or read from a config file

2024-01-08 18:32 UTC, mandarini commented on docs/shared/recipes/storybook/storybook-inferred-targets.md
> +| `outputs` | `["{workspaceRoot}/dist/storybook/{projectRoot}"]`                    | The output directory of the build                                                                 |
It's static unfortunately, until we manage to read args from CLI

2024-01-08 18:32 UTC, mandarini commented on docs/shared/recipes/storybook/storybook-inferred-targets.md
> +| `outputs`  | `["{workspaceRoot}/dist/storybook/{projectRoot}"]`                                          | The output directory of the build
It's static unfortunately, until we manage to read args from CLI

2024-01-08 18:33 UTC, mandarini commented on docs/shared/recipes/storybook/storybook-inferred-targets.md
> +        "command": "storybook build --config-dir my-project/.storybook --output-dir <full path to workspace root>/dist/storybook/my-project"
ohhhhhhh interesting!!!!!!!!!! thanks, let me see if it works well without the full path

2024-01-09 14:05 UTC, isaacplmann approved these changes

2024-01-09 14:05 UTC, merged