docs(core): nx replay rename
nrwl/nx pull request #21053
Opened 2024-01-08 20:08 UTC by isaacplmann

Rename Nx Cache to Nx Replay across all the docs

2024-01-08 20:21 UTC, bcabanes approved these changes

2024-01-08 21:12 UTC, juristr requested changes

2024-01-08 21:12 UTC, juristr commented on docs/generated/manifests/ci.json
> +        "name": "Use Remote Replay",
"Remote Replay" does not make any sense to me. The "marketing term" is "Nx Replay", which replays tasks that are both, cached locally and remotely. But "Remote Replay" sounds weird to me.

Also, we should be cautious to just rename it everywhere. How would people find it searching for "Remote caching", like folks coming from other monorepo solutions?

2024-01-08 21:14 UTC, juristr commented on docs/map.json
> +              "tags": ["replay-task-results"],
What do we do with the title though: "How Caching Works"

Do we leave "caching" here? And how would ppl relate the "replay" feature with the functionality?

2024-01-09 07:37 UTC, juristr commented
Closing this one as discussed. We're going to fix some URL mismatches in another separate PR

2024-01-09 07:37 UTC, closed without merging