fix(vite): only import vite dynamically
nrwl/nx pull request #21050
Opened 2024-01-08 18:23 UTC by mandarini

Only import vite dynamically

2024-01-08 18:24 UTC, ndcunningham approved these changes

2024-01-08 18:26 UTC, jaysoo approved these changes

2024-01-09 08:40 UTC, leosvelperez requested changes

2024-01-09 08:40 UTC, leosvelperez commented on packages/cypress/src/plugins/preprocessor-vite.ts
> -import type { InlineConfig } from 'vite';
A type import doesn't affect runtime. This is only consumed at build time and stripped from the compiled output. Removing this reduces the type-safety we have and doesn't provide any benefits.

Let's revert this change to maintain type safety. We only need to lazy load the runtime code from `vite`.

2024-01-09 14:48 UTC, leosvelperez approved these changes

2024-01-09 14:48 UTC, merged