docs(react-native): add inferred targets for react native
nrwl/nx pull request #21239
Opened 2024-01-19 17:23 UTC by xiongemi

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-01-22 20:58 UTC, isaacplmann requested changes
Some search and replace typos.  Otherwise looks good

2024-01-22 21:08 UTC, xiongemi commented on docs/generated/packages/expo/documents/overview.md
> +Expo is a set of tools built on top of Expo. The Nx Plugin for Expo contains generators for managing Expo applications and libraries within an Nx workspace.
changed

2024-01-22 21:12 UTC, xiongemi commented on docs/shared/packages/expo/expo-plugin.md
> +Expo is a set of tools built on top of Expo. The Nx Plugin for Expo contains generators for managing Expo applications and libraries within an Nx workspace.
changed

2024-01-22 21:13 UTC, xiongemi commented on docs/shared/packages/expo/expo-plugin.md
> +Expo Application Services (EAS) are deeply integrated cloud services for Expo and Expo apps. EAS Build is a hosted service for building app binaries for your Expo and Expo projects.
changed

2024-01-23 01:22 UTC, isaacplmann approved these changes

2024-01-23 01:56 UTC, merged