feat(core): improve nx connect success message
nrwl/nx pull request #21295
Opened 2024-01-24 08:49 UTC by meeroslav

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-01-24 16:13 UTC, bcabanes approved these changes

2024-01-24 17:06 UTC, FrozenPandaz requested changes

2024-01-24 17:06 UTC, FrozenPandaz commented on packages/nx/src/nx-cloud/generators/connect-to-nx-cloud/connect-to-nx-cloud.ts
> +      `with dedicated run UI and analytics. Learn more at https://nx.app`,
```
Enable config free distributed execution for maximum speed,
a dedicated run UI, and analytics.
```

2024-01-30 17:41 UTC, FrozenPandaz approved these changes
Can you make this minor update in a followup PR?

2024-01-30 17:41 UTC, FrozenPandaz commented on packages/nx/src/command-line/connect/connect-to-nx-cloud.ts
> +      title: '✔ This workspace has already Nx Cloud set up',
```suggestion
      title: '✔ This workspace already has Nx Cloud set up',
```

2024-01-30 17:41 UTC, merged