feat(core): remove carret from output headlines
nrwl/nx pull request #21359
Opened 2024-01-26 17:03 UTC by meeroslav

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-02-08 15:46 UTC, FrozenPandaz approved these changes

2024-02-08 15:48 UTC, isaacplmann approved these changes

2024-02-08 15:53 UTC, jaysoo approved these changes

2024-02-13 10:18 UTC, Coly010 approved these changes

2024-02-13 11:40 UTC, JamesHenry requested changes
It hasn't fully taken into account the alignment of things without the carret:

**Current Latest** (aligned)

<img width="653" alt="image" src="https://github.com/nrwl/nx/assets/900523/c025e822-0da0-42da-965a-8ac9748cd7be">

**This PR** (misaligned)

<img width="627" alt="image" src="https://github.com/nrwl/nx/assets/900523/82da8b46-7f39-4fe4-aa7d-e9cb8e7a03ed">

2024-02-13 14:11 UTC, merged