fix(release): use --first-parent to support merged repos
nrwl/nx pull request #21686
Opened 2024-02-07 20:27 UTC by fahslaj

## Related Issue(s)

Fixes #21649

2024-02-08 11:39 UTC, JamesHenry approved these changes

2024-02-08 11:42 UTC, JamesHenry requested changes
Actually on second look, is that correct?

You have HEAD as a positional twice it looks like?

2024-02-08 15:26 UTC, fahslaj commented
> Actually on second look, is that correct?
> 
> 
> 
> You have HEAD as a positional twice it looks like?

The second HEAD is the value being passed for --first-parent. I can use "=" to make it more explicit though.

2024-02-13 13:45 UTC, JamesHenry approved these changes

2024-02-13 13:45 UTC, merged