docs(misc): adding tusky to nx cloud products
nrwl/nx pull request #21738
Opened 2024-02-09 05:01 UTC by ZackDeRose

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-02-13 20:26 UTC, isaacplmann approved these changes

2024-02-13 20:28 UTC, juristr requested changes
The icons are not aligned with what is on nx.app

<img width="1205" alt="image" src="https://github.com/nrwl/nx/assets/542458/86b8ffc0-c1c7-4fd0-957c-7d5a1c721d17">

Ideally I'd also make the tagline shorter

2024-02-13 20:38 UTC, isaacplmann commented
Good catch.  I checked that the text matched, but not the icons.  If you want the tag line to be shorter, that should also be updated on nx.app

2024-02-16 02:03 UTC, ZackDeRose commented
Updated the icons to match the ones on the marketing site.

2024-02-16 16:00 UTC, juristr approved these changes

2024-02-16 16:16 UTC, merged