docs(core): explain NX_ADD_PLUGINS
nrwl/nx pull request #21831
Opened 2024-02-15 19:18 UTC by isaacplmann

Explain NX_ADD_PLUGINS in the Inferred Tasks guide

2024-02-15 19:22 UTC, FrozenPandaz requested changes

2024-02-15 19:22 UTC, FrozenPandaz commented on docs/shared/concepts/inferred-tasks.md
> +When `NX_ADD_PLUGINS` is `true`:
This is the default behavior. So existing workspaces won't need to turn it on persay. And I would also explicitly say that we are working on a migration path for people so they should not worry too much about enabling it at this time.

Workspaces that have their `.env` file gitignored should ensure that everyone sets the variable. Such as adding it to a shared copy of the `.env` file that's not checked in or via adding it to a `.bashrc` script etc.

2024-02-15 19:48 UTC, FrozenPandaz approved these changes

2024-02-16 07:52 UTC, juristr approved these changes
Works for now. 

A couple of notes though, I think this concept page is starting to get bloated and we might want to extract things into separate recipes. Like this one should at a high level explain what Inferred Tasks (and Proj Crystal) is about, why it is beneficial etc..

Things like

- View Inferred Tasks
- Overriding Inferred Task Configuration
- (Opting-out of Inferred Tasks for existing workspaces)

..would almost be a better fit for a recipe and just be linked (via tagging) from the concept page.

2024-02-20 19:13 UTC, merged