fix(vite): update vitest and use parseCLI
nrwl/nx pull request #21890
Opened 2024-02-20 14:44 UTC by mandarini

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-02-21 11:35 UTC, leosvelperez approved these changes

2024-02-21 11:42 UTC, leosvelperez requested changes

2024-02-21 11:42 UTC, leosvelperez commented on packages/vite/src/executors/test/lib/utils.ts
> +  const normalizedExtraArgs = parseCLI(getOptionsAsArgv(options));
CI is failing because the `parseCLI` helper expects the `vitest` as the first argument.

2024-02-21 13:25 UTC, isaacplmann approved these changes

2024-02-21 13:47 UTC, jaysoo approved these changes

2024-02-21 13:56 UTC, leosvelperez approved these changes

2024-02-22 16:03 UTC, AgentEnder approved these changes

2024-02-22 16:03 UTC, merged