docs(core): remove angularjs migration
nrwl/nx pull request #21916
Opened 2024-02-21 14:28 UTC by isaacplmann

Remove angularjs migration guide

2024-02-27 20:15 UTC, Coly010 approved these changes

2024-02-28 08:49 UTC, leosvelperez approved these changes

2024-02-28 11:28 UTC, leosvelperez requested changes
@isaacplmann there are a few other mentions for AngularJS that we should remove:

- https://github.com/nrwl/nx/blob/master/docs/shared/packages/angular/angular-plugin.md?plain=1#L13
- https://github.com/nrwl/nx/blob/master/packages/angular/package.json#L5
- https://github.com/nrwl/nx/blob/master/packages-legacy/angular/package.json#L5
- https://github.com/nrwl/nx/blob/master/docs/shared/mental-model/large-tasks.json#L26182-L26189 (non-important)

2024-02-29 09:02 UTC, leosvelperez approved these changes

2024-02-29 14:17 UTC, jaysoo approved these changes

2024-02-29 20:10 UTC, AgentEnder approved these changes

2024-02-29 20:10 UTC, merged