feat(core): use flag in nx.json for toggling crystal
nrwl/nx pull request #21980
Opened 2024-02-23 22:32 UTC by AgentEnder

## Current Behavior
Users can use NX_ADD_PLUGINS to disable adding plugins

## Expected Behavior
Users can set `useInferencePlugins: false` in nx.json to avoid adding plugins

## Related Issue(s)

Fixes #

2024-02-23 22:43 UTC, jaysoo approved these changes

2024-02-26 09:15 UTC, leosvelperez requested changes

2024-02-26 09:15 UTC, leosvelperez commented on packages/cypress/src/generators/configuration/configuration.ts
> +    nxJson.useInferencePlugins !== false;
This generator receives an `addPlugin` option that can override this. We need to respect the option if provided:
```suggestion
  let addPlugin = options.addPlugin;
  if (addPlugin === undefined) {
    const nxJson = readNxJson(tree);
    addPlugin =
      process.env.NX_ADD_PLUGINS !== 'false' &&
      nxJson.useInferencePlugins !== false;
  }
```

2024-02-26 09:15 UTC, leosvelperez commented on packages/playwright/src/generators/configuration/configuration.ts
> +    nxJson.useInferencePlugins !== false;
Same. We need to respect the provided option.

2024-02-28 09:27 UTC, leosvelperez approved these changes

2024-02-29 20:16 UTC, JamesHenry approved these changes

2024-02-29 20:18 UTC, merged

2024-02-29 20:26 UTC, beeman commented on packages/workspace/src/generators/preset/preset.ts
> +    console.log('Active require');
FYI: There seem to be some left over `console.log`'s here?