feat(node): add compile build target for node libs
nrwl/nx pull request #2226
Opened 2019-12-20 19:16 UTC by Cammisuli

_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#submit-pr)_

> _Please make sure that your commit message follows our format._

> Example: `fix(nx): must begin with lowercase`

## Current Behavior (This is the behavior we have today, before the PR is merged)
Node libs cannot be built independently 
## Expected Behavior (This is the new behavior we can expect after the PR is merged)
Node libs can be built using the `@nwrl/node:compile` build target
## Issue

2019-12-20 22:55 UTC, FrozenPandaz requested changes

2019-12-20 22:55 UTC, FrozenPandaz commented on packages/node/src/builders/compile/compile.impl.ts
> +  const mainFile = relative(dirname(options.main), options.main);
```suggestion
  const mainFile = basename(options.main);
```

2019-12-20 22:55 UTC, FrozenPandaz commented on packages/node/src/builders/compile/compile.impl.ts
> +  packageJson.main = `./${mainJsFile}`;
Consider when someone changes where tsconfig.json root is.. We.shouldn't assume people won't do weird stuff :)

2019-12-20 22:55 UTC, FrozenPandaz commented on packages/node/src/builders/compile/compile.impl.ts
> +    if (typeof asset === 'string') {
Can we support globs as a string?

2019-12-20 22:55 UTC, FrozenPandaz commented on packages/node/src/builders/compile/compile.impl.ts
> +  options.assets.forEach(asset => {
We should normalize this option into 1 data structure

2019-12-20 22:55 UTC, FrozenPandaz commented on packages/node/src/builders/compile/compile.impl.ts
> +  files.forEach(file => {
```
Promise.all(
  files.map(f => copy(f.input, f.output))
)
```

2019-12-20 22:55 UTC, FrozenPandaz commented on packages/node/src/schematics/library/library.ts
> +      options.unitTestRunner === 'jest'
The last one will work when new test runners are added so I don't see a reason to change this.

2019-12-20 22:55 UTC, FrozenPandaz commented on packages/node/src/schematics/library/library.ts
> +          assets: [`${options.projectRoot}/README.md`]
When we support globs.. can we put like...
```
**/*.md
**/*.json
```

2019-12-20 22:55 UTC, FrozenPandaz commented on packages/node/src/builders/compile/compile.impl.ts
> +    })
`context.logger.info('It's done! Here it is: `

2019-12-23 21:55 UTC, FrozenPandaz approved these changes

2019-12-23 21:56 UTC, merged

2019-12-23 22:13 UTC, Hotell reviewed
Amazing! Thanks a lot ❤️