docs(core): editor setup in getting started
nrwl/nx pull request #22416
Opened 2024-03-20 15:22 UTC by isaacplmann

Move the `Integrate with Editors` page to `Getting Started` -> `Editor Setup`

2024-03-20 15:33 UTC, leosvelperez requested changes

2024-03-20 15:33 UTC, leosvelperez commented on nx-dev/nx-dev/redirect-rules.js
> +  '/getting-started/editor-setup': '/getting-started/editor-setup',
```suggestion
  '/features/integrate-with-editors': '/getting-started/editor-setup',
```

2024-03-20 17:44 UTC, leosvelperez approved these changes

2024-04-02 15:54 UTC, AgentEnder approved these changes
`packages/nx` looks fine

2024-04-02 15:56 UTC, merged