docs(gradle): add gradle overview page
nrwl/nx pull request #22552
Opened 2024-03-28 01:18 UTC by xiongemi

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-03-28 09:36 UTC, leosvelperez approved these changes

2024-03-28 14:27 UTC, FrozenPandaz requested changes

2024-03-28 14:27 UTC, FrozenPandaz commented on docs/shared/packages/gradle/gradle-plugin.md
> +The Nx Gradle plugin contains generators and plugins that are useful for Gradle projects in an Nx workspace.
Please add a quick description of Gradle. Most other plugin overview pages also give a quick description of the underlying tool (Gradle).

I also think the main highlight at the moment is the plugin which links gradle tasks to Nx tasks, not generators.

https://nx-dev-git-fork-xiongemi-feature-nxc-544-add-gradle-ce7275-nrwl.vercel.app/nx-api/jest/documents/overview

2024-03-28 14:27 UTC, FrozenPandaz commented on docs/shared/packages/gradle/gradle-plugin.md
> +nx init
This does not match the sentence above. It's already a Nx workspace.

2024-03-28 14:27 UTC, FrozenPandaz commented on docs/shared/packages/gradle/gradle-plugin.md
> +The `@nx/gradle` plugin will create a task for any project that has an app configuration file present. Any of the following files will be recognized as an app configuration file:
```suggestion
The `@nx/gradle` plugin will create an Nx project for each Gradle configuration file present. Any of the following files will be recognized as a Gradle configuration file:
```

2024-03-28 14:27 UTC, FrozenPandaz commented on docs/shared/packages/gradle/gradle-plugin.md
> +To view inferred tasks for a project, open the [project details view](/concepts/inferred-tasks) in Nx Console or run `nx show project my-project --web` in the command line.
```suggestion
To view inferred tasks for a project, open the [project details view](/features/explore-graph#explore-projects-in-your-workspace) in Nx Console or run `nx show project my-project --web` in the command line.
```

2024-03-28 14:27 UTC, FrozenPandaz commented on docs/shared/packages/gradle/gradle-plugin.md
> +## Setting Up @nx/gradle
We should have a section here about setting up a new workspace with gradle + Nx. Like the Nest one: https://nx-dev-git-fork-xiongemi-feature-nxc-544-add-gradle-ce7275-nrwl.vercel.app/nx-api/next/documents/overview

We should have 2 versions:
* Gradle Init
* Spring Initializr

2024-03-28 14:27 UTC, FrozenPandaz commented on docs/shared/packages/gradle/gradle-plugin.md
> +The Nx Gradle plugin contains generators and plugins that are useful for Gradle projects in an Nx workspace.
I also think we need a section on why one would use Nx and Gradle together.

It should include information such as:
* Being able to use the Nx cache on top of the Gradle cache to speed up tasks
* Being able to distribute gradle tasks via Nx Cloud
* Being able to view the project graph via Nx including relationships to non-Gradle projects

2024-04-04 13:59 UTC, xiongemi commented on docs/shared/packages/gradle/gradle-plugin.md
> +To view inferred tasks for a project, open the [project details view](/concepts/inferred-tasks) in Nx Console or run `nx show project my-project --web` in the command line.
changed

2024-04-09 19:51 UTC, FrozenPandaz approved these changes

2024-04-09 19:51 UTC, merged