docs(misc): reorder sidebar menu items
nrwl/nx pull request #22746
Opened 2024-04-09 15:19 UTC by leosvelperez

- Move "Troubleshooting" out of "Recipes" and add it as a top-level menu item
  - Update links across pages from `/recipes/troubleshooting/...` to `/troubleshooting/...`
  - Add/update redirect rules
- Move the "Installation" recipes menu item to be the first menu item under "Recipes"

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-04-09 15:35 UTC, isaacplmann requested changes
Need redirect rules for the troubleshooting recipes

2024-04-09 15:38 UTC, isaacplmann approved these changes

2024-04-09 15:39 UTC, AgentEnder approved these changes

2024-04-10 12:23 UTC, isaacplmann approved these changes

2024-04-11 09:40 UTC, merged