wip
nrwl/nx pull request #22784
Opened 2024-04-11 18:57 UTC by Coly010

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-04-18 16:20 UTC, FrozenPandaz requested changes

2024-04-18 16:20 UTC, FrozenPandaz commented on packages/devkit/src/generators/plugin-migrations/plugin-migration-utils.ts
> +  ) => TargetConfiguration = (targetConfiguration) => targetConfiguration
Update this to your new version with `tree`, etc.

2024-04-18 16:20 UTC, FrozenPandaz commented on packages/devkit/src/generators/plugin-migrations/plugin-migration-utils.ts
> +    delete target.options?.config;
Move this to the `postTargetTransformer`

2024-04-18 16:20 UTC, FrozenPandaz commented on packages/playwright/src/generators/convert-to-inferred/lib/migrate-executor-to-plugin.ts
> +  }
Move this into devkit.

2024-04-18 16:24 UTC, FrozenPandaz commented on packages/playwright/src/generators/convert-to-inferred/convert-to-inferred.ts
> +  }
This should basically look like...

1. Get the graph
2. Call the devkit function
3. Format Files

2024-04-19 16:20 UTC, FrozenPandaz requested changes

2024-04-19 16:20 UTC, FrozenPandaz commented on packages/devkit/src/generators/plugin-migrations/plugin-migration-utils.ts
> +    );
This is weird... keep it for now... we should remove this ideally before we do too many plugins.

Let's get an initial version in.. and start using it.

2024-04-19 16:20 UTC, FrozenPandaz commented on packages/devkit/src/generators/plugin-migrations/plugin-migration-utils.ts
> +  updateNxJson(tree, nxJson);
Let's change this to update the existing plugin to update includes.

At the end check again if include includes every configfile... if it does... we can then remove the include property.

We will need update the playwright init.

2024-04-24 12:39 UTC, isaacplmann approved these changes

2024-04-24 13:06 UTC, FrozenPandaz approved these changes

2024-04-24 13:06 UTC, merged