feat(release): updateDependents generator option for versioning
nrwl/nx pull request #22836
Opened 2024-04-16 11:06 UTC by JamesHenry

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-04-17 13:36 UTC, fahslaj approved these changes

2024-04-19 07:59 UTC, lme-agicap commented
+1

2024-04-22 09:45 UTC, fotopixel commented
@JamesHenry can you please check also the test `transitive updateDependents` with `projects: Object.values(projectGraph.nodes), // version all projects`

I was trying to update your test, But I'm not so sure about all snapshots. 

We are using the `nx release` command with and nx configuration for projects like this `"projects": ["libs/*", "!libs/workspace-extensions"],` and when we do this for an dep. graph like this we will get strange output with your changes. 

![image](https://github.com/nrwl/nx/assets/7202441/e4984197-25c6-49df-bae3-a26ec88ed936)

There is only one change in navigation, but the `nx release` will produce an changelog entry like this. 

```
+ ## 1.0.2 (2024-04-22)
+
+
+ ### 🐞 Bug Fixes
+
+ - **ci:** fix ci ([*****](https://github.com/*****))
+
+
+ ### 🧱 Updated Dependencies
+
+ - Updated styles to null
+ - Updated badge to null
+ - Updated icons to null
+
+
+ ### ❤️  Thank You
+
+ - Matthias Hempel @fotopixel
``` 

I used this settings. 

```
  "updateDependents": {
          "when": "auto",
          "bump": "patch"
        }
```

2024-05-01 14:57 UTC, diosif-cr commented
Hi @JamesHenry this would be a great addition to our setup. Any way I can help with this PR, to get it over the line?

Thank you!

2024-05-01 19:57 UTC, JamesHenry commented
Thanks @fotopixel I don't think using that unit test would help with what you are describing.

I added a filter to remove any dependency bumps where the newVersion is null, I believe that should take care of the issue you saw.

If you get chance to try the PR build again please let me know otherwise I will request final review on this

2024-05-01 20:36 UTC, FrozenPandaz requested changes

2024-05-01 20:36 UTC, FrozenPandaz commented on packages/nx/src/command-line/release/version.ts
> +    when?: 'auto' | 'always';
```suggestion
    when?: 'never' | 'auto';
```

`never` is the current behavior. No dependents are updated. 
`auto` is the new behavior and will remain ambiguous with what we think is best.

We may add more in the future.

2024-05-02 08:18 UTC, ChoSeoHwan commented
I'm really looking forward to this PR being completed.

2024-05-08 18:52 UTC, JamesHenry commented
I'm closing this one in favour of https://github.com/nrwl/nx/pull/23252 which will have enhanced caching for me directly on origin. We will get this merged very soon

2024-05-08 18:52 UTC, closed without merging