chore(js): experimental tsc entrypoint
nrwl/nx pull request #22852
Opened 2024-04-17 10:41 UTC by JamesHenry

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-04-23 18:43 UTC, FrozenPandaz requested changes

2024-04-23 19:13 UTC, JamesHenry commented on packages/js/src/plugins/typescript/plugin.ts
> +        inputs: getInputs(
They are actually a bit different, because they are not always both called and the internal project references can be different, leaving for now

2024-04-23 21:59 UTC, JamesHenry commented on packages/js/src/plugins/typescript/plugin.ts
> +      outputs.add(
Added

2024-04-23 21:59 UTC, JamesHenry commented on packages/js/typescript-plugin.ts
> +export { createNodes } from './src/plugins/typescript/plugin';
Done

2024-04-23 21:59 UTC, JamesHenry commented on packages/js/typescript-plugin.ts
Done

2024-04-23 22:00 UTC, JamesHenry commented on packages/js/src/plugins/typescript/plugin.ts
> +  // Should we consider creating a different optional target for `--clean`?
Will look to add a clean target in a follow up

2024-04-24 14:14 UTC, FrozenPandaz approved these changes

2024-04-24 14:14 UTC, FrozenPandaz commented on packages/js/src/plugins/typescript/plugin.ts
> +        inputs: getInputs(
Really? :eyes: They look the same to me. In fact, the one from typecheck is reused for build if both are called...

2024-04-24 14:14 UTC, merged