docs(cypress): fix code snippet in cypress-setup-node-events.md
nrwl/nx pull request #22977
Opened 2024-04-24 14:32 UTC by chabb

This fixes an example. The outer config variable was shadowed, so this example would fail. By changing the outer variable name, this works

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-04-24 14:40 UTC, FrozenPandaz requested changes

2024-04-24 14:51 UTC, chabb commented on docs/shared/packages/cypress/cypress-setup-node-events.md
> +const nxConfig = nxE2EPreset(__filename, {
No problem, thanks for the quick review. It's done

2024-04-24 16:01 UTC, isaacplmann approved these changes

2024-04-25 03:05 UTC, FrozenPandaz approved these changes

2024-04-25 03:05 UTC, merged