docs(core): restrict plugin inferred tasks
nrwl/nx pull request #22986
Opened 2024-04-24 20:23 UTC by isaacplmann

Add section about restricting plugin inferred tasks

2024-04-24 23:22 UTC, FrozenPandaz requested changes

2024-04-24 23:22 UTC, FrozenPandaz commented on docs/shared/reference/nx-json.md
> +You can limit which projects are processed by Nx plugins to infer tasks using the `include` and `exclude` properties in the plugin configuration object.
```suggestion
You can scope which files are processed by Nx plugins to infer tasks using the `include` and `exclude` properties in the plugin configuration object.
```

I also think the section above can go into a little more details about how plugins work in general.

Specifically that they analyze files. Without that preface, i feel this section is kind of out of the blue talking about files getting processed or not processed and it's confusing.

2024-04-24 23:22 UTC, FrozenPandaz commented on docs/shared/reference/nx-json.md
> +The `include` and `exclude` properties are each file glob patterns that are used to include or exclude the configuration file that the plugin is interpreting. In the example provided, the `@nx/jest`
```suggestion
The `include` and `exclude` properties are each file glob patterns that are used to include or exclude the configuration file that the plugin is interpreting. In the example provided, the `@nx/jest/plugin` plugin will only infer tasks for projects where the `jest.config.ts` file path matches the `packages/**/*` glob but does not match the `**/*-e2e/**/*` glob.
```

2024-04-25 13:43 UTC, leosvelperez approved these changes

2024-04-25 16:52 UTC, FrozenPandaz approved these changes

2024-04-25 16:52 UTC, merged