feat(core): angular library builder to handle buildable libraries
nrwl/nx pull request #2307
Opened 2020-01-13 16:41 UTC by juristr

Adds a new builder `@nrwl/angular:library-build`.

 that makes sure using building buildable (aka publishable) libraries depending on other buildable libraries work as expected, without limiting the current dx with auto-reload when using libraries within apps.

## Current Behavior (This is the behavior we have today, before the PR is merged)

Right now when one buildable (aka) publishable library imports another buildable library, one has to manually fix the `tsconfig` and adjust the `paths` s.t. they point to the `dist` of the depending buildable library. 

That cannot be done statically however, because otherwise running `yarn start` and importing a library in an application won't work (in watch mode). Rather one would have to either rebuild the library manually after each change or run the library with `--watch` independently.

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

This PR introduces a new builder that takes care of

- adjusting the `tsconfig` path at build-time (without writing to the FS) but just by passing them along to ng-packagr
- adding the dependent library (and its according version) to the `package.json`

2020-01-14 14:39 UTC, vsavkin commented
@FrozenPandaz can you take a look at this PR?

2020-01-16 11:37 UTC, juristr commented on packages/angular/src/builders/library/build/build.impl.ts
> +          scope: `@${depNode.data.prefix}/${depNode.name}`,
cannot use `depNode.data.prefix` as that might not exist in other library types (i.e. node or react). updating this soon to read the package.json => name prop which should be already of the form `@wrkspace/mylib`

2020-01-17 19:07 UTC, FrozenPandaz requested changes

2020-01-17 19:07 UTC, FrozenPandaz commented on packages/angular/builders.json
> +    "library-build": {
We're using `bundle` in other projects. That would be an appropriate name for this as well right?

2020-01-17 19:07 UTC, FrozenPandaz commented on packages/angular/src/builders/library/build/build.impl.ts
> +      if (
We can do this higher like on line 234.

```ts
run(options) {
  if (options.withDeps && options.watch) {
    throw new Error('Using --withDeps in combination with --watch is not supported');
  }
}
```

Not completely sure, but I believe throwing an error is more idiomatic for this. Emitting `success: false` also works though.

2020-01-22 06:34 UTC, juristr commented on packages/angular/src/builders/library/build/build.impl.ts
> +  projectDependencies.forEach(libDep => {
👍 discussed this with Victor & we decided to implement this later via the Nx orchestrator. For now the `--withDeps` has been removed. I left some dependency detection in the builder to give users a more meaningful message and suggesting them to try `nx run-many`. That part can be removed again once the orchestrator works and we add `--withDeps`.

2020-01-22 07:04 UTC, juristr commented
@FrozenPandaz implemented the changes. should be good to go now 👍

2020-01-24 02:40 UTC, FrozenPandaz commented
I'm getting this warning when building a library that depends on another:

```
WARNING: No name was provided for external module '@nx-example/lib2' in output.globals – guessing 'lib2'
```

is there something we should do about this? Perhaps apply https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md#resolving-umd-module-identifiers?

2020-01-24 15:19 UTC, FrozenPandaz commented
> I'm getting this warning when building a library that depends on another

Let's address this separately.

2020-01-24 15:19 UTC, FrozenPandaz approved these changes

2020-01-24 15:19 UTC, merged