fix(release): parse NPM output for JSON to prevent JSON.parse from throwing
nrwl/nx pull request #23112
Opened 2024-05-01 11:03 UTC by gutentag2012

closed #22925

## Current Behavior

If the `npm publish` command is run and has any other console output than the JSON, e.g. output from a `prepublishOnly` step, the `pnpm release` command fails.

## Expected Behavior

It should be possible to have a `prepublishOnly` step without this command failing.

## Related Issue(s)

Fixes #22925

2024-05-01 12:48 UTC, JamesHenry commented
You are applying this change (which I am a bit skeptical about) to the `npm view` command which is surely not the intention?

I imagine the npm CLI output is producing only JSON when `--json` is passed but on a specific output channel (e.g. probably the JSON is on stderr and the other output is on stdout (or vice versa)). Please can you verify this? Then we wouldn't need potentially brittle regex parsing of the full output

2024-05-01 12:50 UTC, JamesHenry requested changes
See comment

2024-05-01 13:26 UTC, gutentag2012 commented
Yes, you are completely right, I meant to apply this regex to the stdout of the `npm publish --json` command in line 209.
We would still need pass this output through the regex though since the npm publish output contains output from the `prepublishOnly` steps, so we do have to clean the output somehow.
If you have a different suggestion than using a regex I am open for it

2024-05-21 13:14 UTC, JamesHenry commented
Sorry for the delay @gutentag2012. I have been able to test out my suggestion above and sadly the npm publish output does not behave how I hoped.

I was hoping that npm was going to be consistent around valid JSON output on at least one channel (stdout or stderr) but it does indeed mix the outputs on stdout.

There's a few other things I wanted to cover in this area, so I have gone ahead and opened PR: https://github.com/nrwl/nx/pull/23850

This adds a (hopefully) more robust extraction method, actually prints the output of your lifecycle scripts (and unrelated to this modifies the version in the output in dry-mode, which is a long standing point of potential confusion that I wanted to address).

2024-05-21 13:14 UTC, closed without merging