fix(core): not load env files when NX_LOAD_DOT_ENV_FILES is false
nrwl/nx pull request #23231
Opened 2024-05-08 02:44 UTC by xiongemi

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-05-08 07:54 UTC, leosvelperez approved these changes

2024-05-08 12:34 UTC, jaysoo commented
Tested it locally using the repro from #23090. It is working.

2024-05-08 12:35 UTC, jaysoo approved these changes

2024-05-08 16:05 UTC, FrozenPandaz requested changes

2024-05-08 16:05 UTC, FrozenPandaz commented on packages/nx/src/command-line/run/run-one.ts
> +  extraOptions = {
Can you also update `run-many` and `affected` please?

2024-05-14 17:54 UTC, FrozenPandaz approved these changes

2024-05-14 17:54 UTC, merged