fix(core): addPlugin should not conflict on project.json targets
nrwl/nx pull request #23264
Opened 2024-05-09 11:57 UTC by Coly010

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-05-10 14:32 UTC, AgentEnder requested changes

2024-05-10 14:32 UTC, AgentEnder commented on packages/devkit/src/utils/add-plugin.ts
> +            ))
You don't have to check isCompatible separately from the deep equals imho

```suggestion
          (corePluginsCreatedTarget &&
            !deepEquals(
              corePluginsCreatedTarget,
              mergeTargetConfigurations(
                corePluginsCreatedTarget,
                projConfig.targets[targetName]
              )
            )
```

2024-05-10 14:32 UTC, AgentEnder commented on packages/nx/src/internal-testing-utils/mock-load-nx-plugin.ts
> +        exclude: [],
These are all optional fields right? We could just have this return an empty object.

2024-05-10 14:32 UTC, AgentEnder commented on packages/nx/src/project-graph/plugins/internal-api.ts
> +  }
We still need to normalize to an empty array at minimum, that could either be done in a ternary here or by passing the flag through to normalize plugins, either way.
```suggestion
    plugins =  skipDefaultPlugins ? (plugins ?? []) : await normalizePlugins(plugins, root);
```

2024-05-10 14:32 UTC, AgentEnder commented on packages/nx/src/project-graph/utils/retrieve-workspace-files.ts
> +
Can we keep this in add-plugin, or a similar file next to it in devkit? We shouldn't be using this inside `nx`, so I don't want to put it here.

2024-05-13 14:37 UTC, AgentEnder approved these changes

2024-05-13 14:53 UTC, jaysoo approved these changes

2024-05-13 14:53 UTC, merged