feat(core): default show to web view when in interactive terminal
nrwl/nx pull request #23358
Opened 2024-05-13 22:00 UTC by AgentEnder

## Current Behavior
`nx show projects` shows unformatted json by default

## Expected Behavior
In a TTY we open web view by default

## Related Issue(s)

Fixes #20650

2024-05-13 22:03 UTC, FrozenPandaz requested changes

2024-05-13 22:03 UTC, FrozenPandaz commented on packages/nx/src/command-line/show/command-object.ts
> +        default: process.stdout.isTTY,
rm

2024-05-14 14:23 UTC, isaacplmann approved these changes

2024-05-15 17:32 UTC, FrozenPandaz approved these changes

2024-05-15 17:32 UTC, merged