fix(core): prevent graph output from being truncated
nrwl/nx pull request #23446
Opened 2024-05-16 16:03 UTC by AgentEnder

## Current Behavior
--graph stdout and --file stdout aren't documented.

## Expected Behavior
Existing flags are documented, and `--print` is more discoverable

## Related Issue(s)

Fixes #18689

2024-05-16 16:50 UTC, isaacplmann approved these changes

2024-05-16 20:50 UTC, FrozenPandaz requested changes

2024-05-16 20:50 UTC, FrozenPandaz commented on docs/generated/cli/affected.md
> +Preview the task graph that Nx would run inside a webview.:
```suggestion
Preview the task graph that Nx would run inside a webview:
```

Please fix this everywhere

2024-05-16 21:10 UTC, FrozenPandaz requested changes

2024-05-16 21:10 UTC, FrozenPandaz commented on docs/generated/cli/show.md
>   nx show project my-app
Please make sure this is correct..

2024-05-16 21:10 UTC, FrozenPandaz commented on docs/generated/cli/graph.md
> + nx graph --file=stdout
Only show `--print`

2024-05-27 17:50 UTC, FrozenPandaz requested changes

2024-05-27 17:50 UTC, FrozenPandaz commented on docs/generated/cli/graph.md
> +Output file (e.g. --file=output.json or --file=dep-graph.html). Provide --file=stdout to print the project graph in the terminal.
Let's not recommend this.

2024-05-27 17:50 UTC, FrozenPandaz commented on docs/generated/cli/graph.md
> +Print the project graph in the terminal. (equivalent to --file=stdout)
I don't think we have to mention that it's equivalent?

2024-05-31 22:05 UTC, FrozenPandaz approved these changes

2024-05-31 22:05 UTC, merged