fix(core): mark all projects as affected when npm package is deleted
nrwl/nx pull request #2374
Opened 2020-01-24 18:46 UTC by jaysoo

_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#submit-pr)_

> _Please make sure that your commit message follows our format._

> Example: `fix(nx): must begin with lowercase`

## Current Behavior (This is the behavior we have today, before the PR is merged)

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

## Issue

2020-01-24 18:52 UTC, FrozenPandaz requested changes

2020-01-24 18:52 UTC, FrozenPandaz commented on packages/workspace/src/core/affected-project-graph/locators/npm-packages.ts
> +        touched = Object.keys(nxJson.projects);
```suggestion
      touched = Object.keys({
        ...(packageJson.dependencies || {}),
        ...(packageJson.devDependencies || {})
      });
```

2020-01-24 18:58 UTC, FrozenPandaz approved these changes

2020-01-26 16:20 UTC, vsavkin commented
I'm not sure if this is the right solution. Consider the following:

* Project A depends on NodeModule B and nothing else.
* We removed B without updating A
* A doesn't depend on any other package, so them being touched does nothing to A, but A is broken.

Right?

2020-02-18 22:33 UTC, vsavkin commented
@jaysoo can you explain the rationale for this fix?

Given the example deleting something should probably result in all projects (not packages) marked as affected.

2020-02-19 13:31 UTC, jaysoo commented
@vsavkin Yeah I spoke to Jason about it a while back and it should be all workspace projects -- just hadn't had time to update PR yet.

2020-02-19 17:12 UTC, closed without merging

2020-02-19 17:14 UTC, jaysoo commented
Closed and re-opened as https://github.com/nrwl/nx/pull/2508 (Circle wasn't picking up the unit test fix for some reason).