feat(core): analyze tsconfig changes
nrwl/nx pull request #2376
Opened 2020-01-24 19:53 UTC by FrozenPandaz

# This PR is not done yet

## Current Behavior (This is the behavior we have today, before the PR is merged)

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

## Issue

2020-01-26 21:48 UTC, vsavkin commented
While you are on it, it looks like the json diff handles empty object as no changes.

If I add add something like `"empty": {}` to a project configuration in workspace.json, it won't notice the change. "empty": {"one": "two"}` registers as a change.

I imagine something somewhere is not checking for truthiness correctly.

2020-03-06 20:06 UTC, FrozenPandaz commented
> While you are on it, it looks like the json diff handles empty object as no changes.

This is addressed in #2615

2020-03-12 18:51 UTC, vsavkin requested changes

2020-03-12 18:51 UTC, vsavkin commented on packages/workspace/src/core/affected-project-graph/locators/tsconfig-json-changes.ts
> +export const getTouchedProjectsFromTsConfig: TouchedProjectLocator<
Could you split the function into smaller functions with long names, types, and comments?

The code is very dense. I think it works correctly, but, but it's hard to tell.

2020-03-18 22:00 UTC, merged