fix(angular): storybook config schematic from generating stories when generateStories false
nrwl/nx pull request #2384
Opened 2020-01-27 04:30 UTC by BuckyMaler

## Current Behavior (This is the behavior we have today, before the PR is merged)

Running `ng g @nrwl/angular:storybook-configuration mylib --configure-cypress --generate-cypress-specs false --generate-stories false` for a new lib throws an error.

![Screen Shot 2020-01-26 at 9 00 40 PM](https://user-images.githubusercontent.com/14145352/73150257-124eb000-408b-11ea-89c5-673987bb1577.png)

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

Running `ng g @nrwl/angular:storybook-configuration mylib --configure-cypress --generate-cypress-specs false --generate-stories false` for a new lib completes successfully.

![Screen Shot 2020-01-26 at 9 20 28 PM](https://user-images.githubusercontent.com/14145352/73150279-2c888e00-408b-11ea-9a8d-7349b57bdc62.png)

Now, generating stories is skipped when `--generate-stories` is set to false.

## Issue

Closes #2383

2020-02-07 20:23 UTC, isaacplmann requested changes
This is a helpful change.  Can you add a test for it in `packages/angular/src/schematics/storybook-configuration/configuration.spec.ts`?

2020-02-08 22:03 UTC, BuckyMaler commented
I added a test to ensure only Storybook is configured when all options are false.

2020-02-14 03:31 UTC, BuckyMaler commented
@isaacplmann I think the failing CI build is unrelated to my changes.

2020-02-14 15:07 UTC, isaacplmann commented
@BuckyMaler you're right, it looks like the more recent PRs are passing CI.  Try rebasing against master so CI will run again.

2020-02-19 00:35 UTC, isaacplmann approved these changes
LGTM

2020-02-19 13:18 UTC, merged