feat(graph): add copy button for entire target configuration
nrwl/nx pull request #26284
Opened 2024-05-31 02:54 UTC by xiongemi

## Current Behavior

## Expected Behavior

![Screenshot 2024-05-30 at 6 26 45 PM](https://github.com/nrwl/nx/assets/16211801/5e476cc7-2514-487f-856a-1728f27bccc9)
![Screenshot 2024-05-30 at 6 26 39 PM](https://github.com/nrwl/nx/assets/16211801/ffe713e7-6f97-4c2f-ac79-01178c569a2e)

## Related Issue(s)

Fixes #

2024-06-27 16:50 UTC, jaysoo approved these changes

2024-06-27 18:46 UTC, FrozenPandaz approved these changes

2024-06-27 19:02 UTC, FrozenPandaz requested changes
Whatever gets copied with the `Copy Project` button should be pastable into a `project.json` :thinking: 

Right now it is the project node.. which doesn't really help people.

2024-07-03 18:46 UTC, FrozenPandaz approved these changes
Looks good. Please update the screenshots and merge.

2024-07-04 14:16 UTC, merged