fix(core): handleErrors returns an exit code
nrwl/nx pull request #26343
Opened 2024-06-03 22:04 UTC by AgentEnder

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-06-03 22:12 UTC, FrozenPandaz approved these changes

2024-06-04 12:45 UTC, JamesHenry requested changes
Please could you remove the what would now be redundant handling we have in the release command handlers as well?

2024-06-04 12:46 UTC, JamesHenry commented on packages/nx/src/utils/params.ts
>  export async function handleErrors(isVerbose: boolean, fn: Function) {
(This might require a formatting update)

2024-06-04 22:26 UTC, JamesHenry approved these changes

2024-06-04 22:44 UTC, merged