fix(core): handle `projects` inside `dependsOn` correctly
nrwl/nx pull request #26392
Opened 2024-06-05 16:11 UTC by AgentEnder

## Current Behavior
Each entry in `projects` is handled separately, and a separate invocation to `findMatchingProjects`. This means that negative patterns don't have a chance to work.

Additionally, if only negative patterns are provided anywhere, the result is an empty set.

## Expected Behavior
If only negative patterns are provided, anything that doesn't match those is returned in the result set.  Each entry in `projects` is included in one call to `findMatchingProjects`.

## Related Issue(s)

Fixes #26345

2024-06-05 17:01 UTC, JamesHenry requested changes
Can we add a test in create-task-graph.spec.ts too please?

2024-06-05 18:03 UTC, JamesHenry commented
@AgentEnder looks like we can't remove the handling for lerna, it breaks the smoke tests. What did you think had changed that would allow that to be removed out of interest?

2024-06-05 19:37 UTC, AgentEnder commented
> @AgentEnder looks like we can't remove the handling for lerna, it breaks the smoke tests. What did you think had changed that would allow that to be removed out of interest?

The support for that should have been removed in the release of lerna for Nx 17 support, I guess it may have been missed

2024-06-07 09:01 UTC, JamesHenry approved these changes

2024-06-07 14:38 UTC, merged