fix(core): don't infer scripts as targets if sibling project json declares them
nrwl/nx pull request #26464
Opened 2024-06-07 19:22 UTC by AgentEnder

## Current Behavior
Inferring some scripts during package-json-workspaces causes some thrashing

## Expected Behavior

We only infer a script as a target if its not in project.json

## Related Issue(s)

Fixes #

2024-06-07 20:03 UTC, JamesHenry approved these changes

2024-06-07 21:33 UTC, FrozenPandaz requested changes

2024-06-07 21:33 UTC, FrozenPandaz commented on packages/nx/src/plugins/package-json-workspaces/create-nodes.ts
> +  );
I was confused by what is the `path`, and what is the `root` here.... 

Would this be better if we optionally passed in a parent `project.json`?

2024-06-10 22:19 UTC, FrozenPandaz approved these changes

2024-06-10 22:19 UTC, merged