feat(vite): add createNodesV2 function
nrwl/nx pull request #26484
Opened 2024-06-10 12:37 UTC by Coly010

- chore(vite): move single file processing of plugin to own function
- feat(vite): add CreateNodesV2 function

## Current Behavior

There is no implementation for createNodesV2

## Expected Behavior

There should be an implementation for createNodesV2

## Related Issue(s)

Fixes #

2024-06-10 13:39 UTC, FrozenPandaz requested changes

2024-06-10 13:39 UTC, FrozenPandaz commented on packages/vite/src/plugins/plugin.ts
>  const targetsCache = readTargetsCache();
Don't read this in the moduleScope, there's no point.

2024-06-10 13:39 UTC, FrozenPandaz commented on packages/vite/src/plugins/plugin.ts
>    writeTargetsToCache();
This is not needed anymore.

2024-06-10 13:39 UTC, FrozenPandaz commented on packages/vite/src/plugins/plugin.ts
> +    return createNodesInternal(configFilePath, options, context, targetsCache);
It's okay to use an `{}` here for `targetsCache`.

This function shouldn't really get called unless it's a rare case that someone wrapped our plugin `createNodes` function.

2024-06-11 13:58 UTC, jaysoo approved these changes

2024-06-12 14:09 UTC, FrozenPandaz requested changes

2024-06-12 14:09 UTC, FrozenPandaz commented on packages/vite/src/plugins/plugin.ts
> +    "The 'createDependencies' function is now a no-op. It will be replaced via the 'CreateNodesV2' API."
```suggestion
    "The 'createDependencies' function is now a no-op. This functionality is included in 'createNodesV2'."
```

This has to be moved to a jsDoc.

2024-06-12 22:20 UTC, FrozenPandaz approved these changes

2024-06-12 22:20 UTC, merged