fix(graph): fix search params reload when back to graph
nrwl/nx pull request #26580
Opened 2024-06-17 18:15 UTC by xiongemi

## Current Behavior

- change useIntervalWhen
  - when this function is used, it is mostly calling a fetch request, change it to take a promise
  - wait for the current fetch request to finish before firing the next one
- currently, when going back to graph, it needs to remove the search params expand and sometimes need to add ?project= search params
  - delete expand search params is called after adding the project search params
  
```

 setSearchParams(
        (currentSearchParams) => {
          currentSearchParams.delete('expanded');
          return currentSearchParams;
        },
        { replace: true, preventScrollReset: true }
      );

```

this function does not contain the project search param key, caused the graph page to reload twice

## Expected Behavior

## Related Issue(s)

Fixes #

2024-06-21 18:44 UTC, FrozenPandaz requested changes

2024-06-21 18:44 UTC, FrozenPandaz commented on graph/shared/src/lib/use-interval-when.ts
>  export const useIntervalWhen = (
`usePoll`

2024-06-24 21:45 UTC, jaysoo approved these changes

2024-06-25 14:05 UTC, FrozenPandaz approved these changes

2024-06-25 14:05 UTC, merged