feat(graph): add atomizer label to target groups
nrwl/nx pull request #26622
Opened 2024-06-21 11:56 UTC by MaxKless

- feat(graph): color atomizer as warning when not connected to cloud
- feat(graph): add atomizer label tooltip

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-06-21 12:27 UTC, jaysoo commented on graph/ui-tooltips/src/lib/property-info-tooltip.tsx
> +      'This target has been automatically split into multiple targets by file. We recommend running this only with distribution enabled via Nx Cloud to avoid potential performance overheads.',
The text here appear title-cased, I guess there is styling applied to the tooltip that needs to be fixed.

2024-06-21 12:29 UTC, jaysoo commented on graph/ui-tooltips/src/lib/property-info-tooltip.tsx
> +      'https://nx.dev/ci/features/split-e2e-tasks#automatically-split-e2e-tasks-by-file-atomizer',
Leave out the `#` part, it's not necessary.

2024-06-21 12:39 UTC, jaysoo commented on graph/ui-tooltips/src/lib/property-info-tooltip.tsx
> +      'This target has been automatically split into multiple targets by file. We recommend running this only with distribution enabled via Nx Cloud to avoid potential performance overheads.',
I would not mention the negatives (e.g. avoiding performance overheads). Focus on the value so users can try it a decide for themselves whether it makes sense for them or not. Something like:

```
Nx automatically split this potentially slow target into smaller targets by file that are faster to run. We recommend enabling Nx Cloud to benefit from better distribution, and more granular caching and flaky task re-runs.
```

Maybe @isaacplmann can fix the wording. I think we should mention that atomized targets make the other three features better (distribution, caching and re-runs).

2024-06-25 12:44 UTC, jaysoo approved these changes

2024-06-25 16:48 UTC, FrozenPandaz requested changes

2024-06-25 16:48 UTC, FrozenPandaz commented on packages/jest/src/plugins/plugin.spec.ts
> +                      "atomizedTarget": undefined,
Please get rid of the `undefined`. Only set the property when `options.ciTargetName` is defined. I don't really know why but `jest` sometimes isn't happy with this on different systems :shrug:

2024-06-25 16:48 UTC, FrozenPandaz commented on packages/nx/src/config/workspace-json-project-json.ts
> +  atomizedTarget?: string;
This is not used at the moment as far as I can see? If so, can we remove it?

2024-06-26 14:17 UTC, FrozenPandaz approved these changes

2024-06-26 14:18 UTC, merged