fix(nx-dev): plugin-registry menu
nrwl/nx pull request #26767
Opened 2024-06-29 20:18 UTC by juristr

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-07-01 12:14 UTC, isaacplmann requested changes
I don't think it looks good to have a sidebar menu on that page.  You're just repeating the extending Nx menu.  If you want the plugins to be combined with extending Nx, then we should actually combine the two sections and come up with a design for that.

2024-07-01 12:16 UTC, isaacplmann commented
I realize now that you're trying add the top menu on mobile.  You succeeded at that, but also added a sidebar on desktop - that shouldn't be there.

2024-07-01 18:22 UTC, juristr commented
> I realize now that you're trying add the top menu on mobile. You succeeded at that, but also added a sidebar on desktop - that shouldn't be there.

Ohh...yeah now I understand...that component needs refactoring. I'll fix that.

2024-07-04 12:19 UTC, jaysoo approved these changes

2024-07-04 12:19 UTC, merged