feat(nx-dev): Add Nx Cloud Page
nrwl/nx pull request #26865
Opened 2024-07-08 19:16 UTC by ndcunningham

2024-07-16 11:31 UTC, jaysoo commented
Let's move the page to app router so we don't have to do it in the future. It also allows more optimizations with RSC if needed.

2024-07-16 20:53 UTC, bcabanes commented
Hi @ndcunningham!
Can you rebase your branch please?
With the [merge of the new home page](https://github.com/nrwl/nx/pull/26893), there are some additional libraries available for you to use:
- `ui-icons` for customer, technology, product, social, editor _(etc...)_ icons
- `ui-animations` for animation already used in the home screen

Also, the `ui-common` has been cleaned up, so you have to update the current imports to the right libraries.

2024-07-18 19:10 UTC, bcabanes requested changes

2024-07-18 19:10 UTC, bcabanes commented on nx-dev/ui-cloud/src/lib/call-to-action.tsx
This file already exists in the `ui-common` library, you can directly use it instead. https://github.com/nrwl/nx/blob/master/nx-dev/ui-common/src/lib/call-to-action.tsx

2024-07-18 19:10 UTC, bcabanes commented on nx-dev/ui-cloud/src/lib/enhance-with-ai.tsx
> +            history, Tusky AI can optimize CI resource usage, help resolve
```suggestion
            history, Nx Cloud can optimize CI resource usage, help resolve
```

We won't be introducing Tusky now.

2024-07-18 19:10 UTC, bcabanes commented on nx-dev/ui-cloud/src/lib/faster-and-cheaper.tsx
> +  };
Can you remove the animation altogether on the bars? This will stagger the mobile version otherwise.

2024-07-18 19:10 UTC, bcabanes commented on nx-dev/ui-cloud/src/lib/faster-and-cheaper.tsx
> +                  <Counter value={70}></Counter>%
Can you use the `AnimateValue` component in the `ui-animations` library?
https://github.com/nrwl/nx/blob/master/nx-dev/ui-animations/src/lib/animate-value.tsx

2024-07-18 19:10 UTC, bcabanes commented on nx-dev/ui-cloud/src/lib/faster-and-cheaper.tsx
> +}
Can be remove in profit of `AnimateValue`.

2024-07-19 14:09 UTC, bcabanes approved these changes

2024-07-19 18:53 UTC, jaysoo approved these changes

2024-07-19 18:53 UTC, merged