feat(nx-plugin): add migration schematic
nrwl/nx pull request #2692
Opened 2020-03-19 20:01 UTC by devinshoemaker

This change adds a new schematic that generates a migration for an Nx plugin. The user can specify the version for the migration, and optionally add a custom name, description, and whether or not to include package.json updates.

Examples:

```
nx g @nrwl/nx-plugin:migration --project=ionic-react --version=1.2.0
```

```
nx g @nrwl/nx-plugin:migration fix-files-1.2.0 --project=ionic-react --version=1.2.0
```

2020-03-23 16:35 UTC, devinshoemaker commented
Update: small e2e test improvement, and rebased onto latest master.

2020-03-29 18:25 UTC, Cammisuli requested changes
Thanks @devinshoemaker! Everything looks good, but there's one thing to make sure this works well for everyone.

Since `migrations.json` is a new asset file, you're going to have to modify the `assets` property in the workspace.json to include the migrations file (similar to `builders.json` and `collection.json`).

Also, we removed docs for web, so you might want to rebase on master and regenerate. (Delete the web doc if it doesn't remove it)

2020-03-30 00:11 UTC, devinshoemaker commented
> Since `migrations.json` is a new asset file, you're going to have to modify the `assets` property in the workspace.json to include the migrations file (similar to `builders.json` and `collection.json`).

Do you want the same kind of change to be applied in #2708?

2020-03-30 00:14 UTC, devinshoemaker commented
`migrations.json` is added by default to a generated nx-plugin, so it sounds like you want to support adding migrations to libs that weren't generated with nx-plugin. I'm happy to make the change, but if you want the "schematic" schematic to work the same way then it sounds like I would need to make a similar change over there.

2020-03-30 19:26 UTC, devinshoemaker commented
Requested changes made, rebased, and documentation regenerated.

2020-03-31 14:28 UTC, Cammisuli approved these changes
LGTM!

2020-04-16 19:00 UTC, merged