docs(core): add docs for parallelism
nrwl/nx pull request #26950
Opened 2024-07-16 13:56 UTC by xiongemi

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-07-17 17:25 UTC, FrozenPandaz requested changes

2024-07-17 17:25 UTC, FrozenPandaz commented on docs/shared/reference/project-configuration.md
> +In Nx 19.5.0 and higher, you can configure parallelism for a target by setting `"parallelism": false` in the target's configuration. This ensures that the target will not run in parallel with other t
```suggestion
In Nx 19.5.0+, you can configure parallelism for a target by setting `"parallelism": false` in the target's configuration. This ensures that the target will not run in parallel with other tasks. For example, if you do not want the `e2e` target to alongside any other tasks, you can specify:
```

2024-07-17 17:25 UTC, FrozenPandaz commented on docs/shared/reference/project-configuration.md
> +Parallelism is a feature in Nx that allows multiple tasks to run concurrently. By default, Nx tries to execute as many tasks in parallel as possible to optimize build and test times. However, there a
```suggestion
Parallelism is a feature in Nx that allows multiple tasks to run in parallel. By default, Nx tries to execute tasks in parallel to optimize build and test times. However, there are scenarios where running tasks in parallel is not desirable. For example, tasks that rely on shared resources or have side effects might fail or produce inconsistent results when run alongside other tasks.
```

2024-07-17 17:25 UTC, FrozenPandaz commented on docs/shared/reference/project-configuration.md
> +- `"parallelism": false`: The task will run alone, without any other tasks running concurrently.
Remove

2024-07-22 14:32 UTC, FrozenPandaz commented
This is waiting on Nx Cloud changes

2024-07-22 21:33 UTC, AgentEnder approved these changes

2024-07-22 21:42 UTC, merged