docs(nx-cloud): remova managed saml docs
nrwl/nx pull request #26969
Opened 2024-07-17 16:56 UTC by rarmatei

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-07-19 19:28 UTC, stevepentland approved these changes
Sorry for the wait, I didn't see a notification for the review request

2024-07-23 09:06 UTC, meeroslav commented on nx-dev/nx-dev/redirect-rules.js
> -    '/ci/recipes/enterprise/on-premise/auth-saml-managed',
Please add also redirection from `/ci/recipes/enterprise/on-premise/auth-saml-managed` to `/ci/recipes/enterprise/on-premise/auth-saml`. Same for the above

2024-07-23 09:07 UTC, meeroslav requested changes
Left one minor note

2024-07-23 09:30 UTC, meeroslav approved these changes

2024-07-23 09:43 UTC, merged