feat(nx-dev): Migrate careers from nx.app
nrwl/nx pull request #27020
Opened 2024-07-19 22:11 UTC by ndcunningham

2024-07-22 18:59 UTC, juristr requested changes

2024-07-22 18:59 UTC, juristr commented on nx-dev/data-access-careers/src/index.ts
why do we need this empty file?

2024-07-23 09:28 UTC, juristr approved these changes
LGTM

2024-07-23 12:39 UTC, FrozenPandaz approved these changes

2024-07-23 12:39 UTC, merged