fix(core): format global config files modified by nx migrate
nrwl/nx pull request #27066
Opened 2024-07-23 13:18 UTC by leosvelperez

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #8928

2024-07-23 15:56 UTC, FrozenPandaz requested changes

2024-07-23 15:56 UTC, FrozenPandaz commented on packages/nx/src/command-line/migrate/migrate.ts
> +  let prettier: typeof Prettier;
Can we reuse this logic from the generator util?

2024-07-23 19:52 UTC, FrozenPandaz commented
Is this issue related? https://github.com/nrwl/nx/issues/25122

2024-07-24 06:00 UTC, leosvelperez commented
> Is this issue related? #25122

That one is due to some migration generators not formatting files at the end. I created a separate PR for it: https://github.com/nrwl/nx/pull/27082.

2024-07-25 13:22 UTC, FrozenPandaz approved these changes

2024-07-25 13:22 UTC, merged