fix(nx-dev): clean up heading text
nrwl/nx pull request #27205
Opened 2024-07-30 10:40 UTC by mandarini

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-08-02 14:46 UTC, FrozenPandaz requested changes

2024-08-02 14:46 UTC, FrozenPandaz commented on tools/documentation/create-embeddings/src/main.mts
> +        }
Can this be fixed in `tags.json`?

2024-08-02 15:53 UTC, mandarini commented on tools/documentation/create-embeddings/src/main.mts
> +        }
Yes, I'll do that!

2024-08-05 15:10 UTC, isaacplmann approved these changes

2024-08-06 13:12 UTC, FrozenPandaz approved these changes

2024-08-06 13:13 UTC, merged