fix(core): allow isolated plugins to shut themselves down
nrwl/nx pull request #27317
Opened 2024-08-06 20:04 UTC by AgentEnder

## Current Behavior
Isolated plugin workers are shutdown via `childProcess.kill()` in a `process.on('exit)` handler.

## Expected Behavior
Isolated plugin workers are shutdown via a message sent over their socket, which tells the to clean themselves up

## Related Issue(s)

Fixes #

2024-08-06 20:31 UTC, FrozenPandaz requested changes
Verify that this fixes the windows issue and then, re-enable isolation on Windows in this PR

2024-08-07 16:52 UTC, FrozenPandaz approved these changes

2024-08-08 10:39 UTC, MaxKless approved these changes

2024-08-08 10:40 UTC, MaxKless commented
Works on my windows machine :)

2024-08-09 14:22 UTC, merged