feat(core): Refresh welcome screens based on Nx Cloud
nrwl/nx pull request #27313
Opened 2024-08-06 18:12 UTC by ndcunningham

## Current Behavior

Currently, when you create an app we always show `nx connect` regardless if the workspace has already setup Nx Cloud.

## Expected Behavior

Now, we:
- show `nx connect` if you have no opted into Nx Cloud
- show a CTA to finish your setup if you have setup your workspace on Nx cloud but have yet to claim it
- show a CTA to learn more if your workspace has been claimed in Nx Cloud 

## Related Issue(s)

Fixes #

2024-08-07 14:20 UTC, Coly010 approved these changes

2024-08-07 15:48 UTC, xiongemi approved these changes

2024-08-08 12:30 UTC, jaysoo approved these changes

2024-08-08 17:56 UTC, FrozenPandaz requested changes

2024-08-08 17:56 UTC, FrozenPandaz commented on packages/angular/src/generators/application/application.ts
> +
I don't know if we need to put these onto `options`. Should we move this into `createFiles`?

2024-08-08 17:56 UTC, FrozenPandaz commented on packages/nx/src/nx-cloud/utilities/onboarding.ts
> +    'create-nx-project',
Let's make this `nx-welcome-app`.

Can we make this function name something more clear like `createNxCloudOnboardingURLForWelcomeApp`?

It's currently named basically the same as the `createNxCloudOnboardingURL`

2024-08-08 22:17 UTC, FrozenPandaz approved these changes

2024-08-09 17:23 UTC, merged