Lourw/add nx alias for login
nrwl/nx pull request #27358
Opened 2024-08-09 12:41 UTC by lourw

## Current Behavior

N/A

## Expected Behavior

When running `npx nx login`, a file server should open and take you to Nx Cloud to create a new personall access token.

## Related Issue(s)

Fixes #

2024-08-09 13:08 UTC, lourw commented
I need to add a feature flag to this PR first

2024-08-20 16:24 UTC, AgentEnder approved these changes

2024-08-20 19:14 UTC, isaacplmann approved these changes

2024-08-20 21:16 UTC, FrozenPandaz requested changes

2024-08-20 21:16 UTC, FrozenPandaz commented on packages/nx/src/command-line/login/command-object.ts
> +      .option('verbose', {
We have a helper function, `withVerbose` which will add the `verbose` option.

It includes the middleware to set the environment variable.

You can see it used here: https://github.com/nrwl/nx/blob/c72ba9b50417d7739a3edf9bdae21b74beccc7bd/packages/nx/src/command-line/import/command-object.ts#L41

2024-08-20 21:16 UTC, FrozenPandaz commented on packages/nx/src/command-line/login/login.ts
> +  }
This isn't needed after using `withVerbose`

2024-08-20 21:16 UTC, FrozenPandaz commented on packages/nx/src/command-line/login/login.ts
> +  const isVerbose = process.env.NX_VERBOSE_LOGGING === 'true';
You could either check this.. or `args.verbose`

2024-08-26 17:20 UTC, FrozenPandaz approved these changes

2024-08-26 17:20 UTC, FrozenPandaz commented on packages/nx/src/command-line/logout/logout.ts
> +    (args.verbose as boolean) ?? process.env.NX_VERBOSE_LOGGING === 'true',
This shouldn't be necessary because it's handled in `withVerbose`

2024-08-26 17:20 UTC, FrozenPandaz commented on packages/nx/src/nx-cloud/utilities/axios.ts
> +      `Unable to authenticate. Please connect your workspace to Nx Cloud to define a valid Nx Cloud ID. If you are in a CI context, please set the NX_CLOUD_ACCESS_TOKEN environment variable or define
Should they define an access token or a Nx Cloud ID?

2024-08-26 17:20 UTC, FrozenPandaz commented on packages/nx/src/command-line/logout/command-object.ts
> +    'Logout from Nx Cloud by removing a personal access token from your local machine. The personal access token will be revoked from Nx Cloud and you will need to login again to regain access to Nx
This seems like too much information about the implementation details.

I think we can shorten it to..

```suggestion
    'Logout from Nx Cloud',
```

2024-08-26 17:20 UTC, FrozenPandaz commented on packages/nx/src/command-line/login/command-object.ts
> +    'Login to Nx Cloud by generating a personal access token and saving it to your local machine.',
This seems like too much information about the implementation details.

I think we can shorten it to..
```suggestion
    'Login to Nx Cloud',
```

2024-08-26 18:26 UTC, merged