fix(angular): tests on windows
nrwl/nx pull request #27489
Opened 2024-08-16 19:17 UTC by robertIsaac

## Current Behavior
`nx test angular` fail on windows

## Expected Behavior
`nx test angular` to pass on windows

## notes
in `packages/angular/src/generators/utils/storybook-ast/component-info.ts` file I used `join(moduleFolderPath)` to convert it from always being `/` to be OS separator
there are two other options I can do, but I don't have enough knowledge to take the decision
1. to generate `moduleFolderPath` with OS separator instead of always `/`
2. to make `candidateFile` to always be `/`

2025-01-29 14:21 UTC, leosvelperez requested changes
Thank you for raising this! Hopefully, we can address these issues soon. I left a couple of comments to address.

2025-01-29 14:21 UTC, leosvelperez commented on packages/angular/src/generators/utils/storybook-ast/component-info.ts
> +          candidateFile.lastIndexOf(sep) + 1,
Let's revert this. Generators should work with Unix-based paths. The issue here is that `visitNotIgnoredFiles` is invoking the callback function with OS-dependent paths. So, instead of this change, we can change [line 247](https://github.com/nrwl/nx/pull/27489/files#diff-00a320109b1ece45fa3cc3440d9b6a23b925aa98480f589c43df47254b88c375R247) with:

```ts
componentImportPathChildren.push(normalizePath(filePath));
```

2025-01-29 14:21 UTC, leosvelperez commented on packages/nx/src/generators/tree.ts
> +    return res;
Let's revert this. Most of the time, the children don't "need" to be sorted and this could be a breaking change in some scenarios. So let's avoid it. This is a specific need for a couple of test assertions, so we can just sort the result before asserting in those particular test cases.

2025-01-29 14:21 UTC, leosvelperez commented on packages/nx/src/generators/tree.spec.ts
>          expect(tree.children('parent')).toEqual([
```suggestion
        expect(tree.children('parent').sort()).toEqual([
```

2025-01-29 14:21 UTC, leosvelperez commented on packages/workspace/src/generators/preset/__snapshots__/preset.spec.ts.snap
This file no longer exists. Could you please rebase your changes?

2025-02-02 15:59 UTC, robertIsaac commented on packages/workspace/src/generators/preset/__snapshots__/preset.spec.ts.snap
done

2025-02-02 15:59 UTC, robertIsaac commented on packages/nx/src/generators/tree.ts
> +    return res;
done

2025-02-02 15:59 UTC, robertIsaac commented on packages/angular/src/generators/utils/storybook-ast/component-info.ts
> +          candidateFile.lastIndexOf(sep) + 1,
done

2025-02-02 16:36 UTC, robertIsaac commented
@leosvelperez all comments are addressed now

2025-02-03 09:24 UTC, leosvelperez approved these changes
Thank you!

2025-02-03 09:25 UTC, merged