feat(linter): add option to exclude projects from circular deps check
nrwl/nx pull request #27504
Opened 2024-08-19 09:00 UTC by meeroslav

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-08-20 12:09 UTC, JamesHenry requested changes
Pending a final conclusion to our internal discussion

2024-08-22 19:31 UTC, FrozenPandaz commented
Let's make a PR release for this once it's ready to try.

2024-08-28 14:48 UTC, FrozenPandaz approved these changes

2024-09-03 16:22 UTC, JamesHenry approved these changes

2024-09-03 18:33 UTC, merged