docs(nx-cloud): some improvements based on feedback
nrwl/nx pull request #27615
Opened 2024-08-23 09:09 UTC by juristr

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-08-23 11:54 UTC, isaacplmann approved these changes

2024-08-23 18:51 UTC, FrozenPandaz requested changes

2024-08-23 18:51 UTC, FrozenPandaz commented on docs/shared/using-nx/affected.md
> +As your workspace grows, re-testing, re-building, and re-linting **all projects becomes too slow**. To address this, Nx comes with a so-called "affected" command. Using this command, Nx
Why are we saying `so-called "affected" command`? It's literally an `affected` command...

2024-08-23 18:51 UTC, FrozenPandaz commented on docs/shared/using-nx/affected.md
> -If you aren't using Git, you can pass `--files` to any affected command to indicate what files have been changed.
Was this causing confusion for people?

2024-08-26 14:24 UTC, juristr commented on docs/shared/using-nx/affected.md
> -If you aren't using Git, you can pass `--files` to any affected command to indicate what files have been changed.
🤔 no I think I cut that out by accident

2024-08-26 15:00 UTC, FrozenPandaz approved these changes

2024-08-26 15:00 UTC, merged