Docs/import documentation
nrwl/nx pull request #27859
Opened 2024-09-10 17:01 UTC by isaacplmann

Create an import project recipe
Creates the import command API reference
Adds the import command to the command landing page

2024-09-10 20:35 UTC, jaysoo approved these changes

2024-09-11 14:07 UTC, FrozenPandaz requested changes

2024-09-11 19:10 UTC, FrozenPandaz requested changes

2024-09-11 19:10 UTC, FrozenPandaz commented on docs/shared/reference/commands.md
> +Import part of another repository into this repository, preserving git history.
This wasn't updated. Is this not auto generated? :eyes:

2024-09-11 19:34 UTC, FrozenPandaz approved these changes

2024-09-12 13:12 UTC, merged