cleanup(core): move esbuild to use fdir/picomatch
nrwl/nx pull request #28037
Opened 2024-09-22 05:58 UTC by 43081j

Migrates away from fast-glob to `fdir` and `picomatch`.

this'll improve performance a fair amount (fdir is much faster than fast-glob) and should reduce the install size (picomatch and fdir are both very small).

fast-glob uses micromatch, while this uses picomatch. the difference seems to be that more advanced bash brace expansion isn't supported in picomatch. if that's important to you, its possible we could use micromatch or [zeptomatch](https://github.com/fabiospampinato/zeptomatch)

2024-09-23 11:27 UTC, JamesHenry requested changes
There's a conflict from one of your other PRs, and possibly some legit e2e failures

2024-09-23 19:15 UTC, 43081j commented
No worries, I'll have a look soon 👍

Will catch the branch up too

2024-09-25 13:48 UTC, JamesHenry commented
Please ignore the react rspack module federation error, it will be resolved when you sync with latest master. The others might be legit though

2024-10-01 12:23 UTC, JamesHenry commented
@43081j I pulled in latest again after all the recent merges just in case

2024-10-01 17:49 UTC, 43081j commented
That same test seems to fail locally for me too 

Haven't managed to figure out why yet though. It seems to expect a file to exist which doesn't. That suggests the way we compute the input glob is broken or changed but I'm not sure why/how yet

2024-10-20 03:11 UTC, 43081j commented
Oh wow, whatever got merged in from master seems to have fixed the tests! 

Any chance I can get a re-review? 🙏

2024-10-20 13:34 UTC, JamesHenry commented
@43081j Yeah there was a peer dep issue with the Angular stack that was fixed so I was hoping that would be it. Thanks a lot for your patience in getting this green!

With that said, this is a more significant change than previous ones under this umbrella, so will need some more eyes.

I am also curious about seeing a resolution to this issue I saw when investigating picomatch: https://github.com/micromatch/picomatch/issues/136

2024-10-21 07:19 UTC, 43081j commented
I agree

Other projects we have migrated to picomatch didn't make use of the extra edge cases minimatch supported, so they were fairly easy to move. We also moved a few to zeptomatch which is even smaller and often faster than picomatch, but possibly missing some rarely used pattern types. 

Anyhow, let me know when we have more reviews, if we want to change something 👍

2024-12-10 17:06 UTC, benmccann commented
You might consider `tinyglobby`, which uses `fdir`/`picomatch`, but could be better performing as it does some optimizations to avoid having `fdir` crawl folders that are under the `ignore` pattern. It would also make it so that there are minimal code changes here needing review as `tinyglobby` and `fast-glob` are nearly API compatible. Plus `tinyglobby` is already a dependency via `@nx/js`.

> I am also curious about seeing a resolution to this issue I saw when investigating picomatch: https://github.com/micromatch/picomatch/issues/136

I'm not sure that issue is going to have an effect. `fast-glob` uses `picomatch` and doesn't use `minimatch`, so I don't think anything will change there

2024-12-10 17:56 UTC, 43081j commented
If you want to open a branch which uses tinyglobby instead, I'd be happy to close this

Especially since we already have it in another package of the monorepo. Probably makes sense to use the same one

2025-01-11 13:15 UTC, closed without merging