fix(core): file-utils workspaceFileName now returns proper file name
nrwl/nx pull request #2811
Opened 2020-04-05 20:46 UTC by NathanWalker

This PR picks up where https://github.com/nrwl/nx/pull/2594 left off and fixed all unit tests - thanks to @scallacs original efforts - this one had plagued us for awhile.

## Current Behavior (This is the behavior we have today, before the PR is merged)

workspaceFileName() returns 'angular.json' when @angular/cli is in package.json devDependencies even if workspace.json is used.

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

workspaceFileName() should return 'workspace.json'.

## Issue

closes https://github.com/nrwl/nx/issues/2253

2020-04-09 12:08 UTC, juristr approved these changes
LGTM 👍

2020-04-09 14:30 UTC, FrozenPandaz requested changes

2020-04-09 14:30 UTC, FrozenPandaz commented on packages/workspace/src/core/file-utils.ts
> +  if (fileExists('angular.json')) {
Use `appRootPath` to make sure this works when executing from somewhere other than the root of a workspace.
```suggestion
  if (fileExists(`${appRootPath}/package.json`)) {
```

2020-04-09 14:30 UTC, FrozenPandaz commented
Looks good, just one minor fix :+1:

2020-04-10 05:26 UTC, NathanWalker commented
@FrozenPandaz great catch - updated now 👍

2020-04-11 19:51 UTC, juristr commented
Cool, thx @NathanWalker 👍

2020-04-11 19:51 UTC, merged