fix(core): add try catch around watcher
nrwl/nx pull request #28146
Opened 2024-09-26 18:12 UTC by xiongemi

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-09-26 19:43 UTC, FrozenPandaz requested changes

2024-09-26 19:43 UTC, FrozenPandaz commented on packages/nx/src/command-line/reset/reset.ts
> +      errors.push('Failed to reset the Nx Cloud client.');
Include the error that got thrown.

2024-09-26 19:43 UTC, FrozenPandaz commented on packages/nx/src/command-line/reset/reset.ts
> -import { daemonClient } from '../../daemon/client/client';
This should be fine

2024-09-26 19:43 UTC, FrozenPandaz commented on packages/nx/src/command-line/reset/reset.ts
>    return daemonClient.stop();
```suggestion
  const { daemonClient } = await import('../../daemon/client/client');
  if (daemonClient.enabled()) {
    return daemonClient.stop();
  }
```

2024-09-27 14:36 UTC, FrozenPandaz approved these changes

2024-09-27 16:09 UTC, merged

2024-09-27 16:10 UTC, dunika commented
Thanks!