fix(core): fix package manager determination logic
nrwl/nx pull request #28202
Opened 2024-09-30 17:34 UTC by ThePlenkov

## Current Behavior
Currently create-nx-workspace determines package manager based on the invoker's path and it might be totally misleading if some names are used in the path such as /ubuntu/my_project which is identified as bun command by mistake

## Expected Behavior
It should correctly identify package manager

## Related Issue(s)

Fixes #28201

2024-10-01 13:52 UTC, JamesHenry requested changes
I don't think this is working as intended based on the e2e results.

Based on my own experimentation I believe what we want it to replace the existing logic (and your change) with this:

```ts
let detectedPackageManager: PackageManager = 'npm';

  if (process.env.npm_config_user_agent) {
    for (const pm of packageManagerList) {
      if (process.env.npm_config_user_agent.startsWith(pm)) {
        detectedPackageManager = pm;
      }
    }
  }

  if (process.env.npm_execpath) {
    for (const pm of packageManagerList) {
      if (process.env.npm_execpath.includes(pm)) {
        detectedPackageManager = pm;
      }
    }
  }
  return detectedPackageManager;
```

(Obviously make sure the formatting is fixed before pushing)

Results on my machine:

![image](https://github.com/user-attachments/assets/1dc69350-33f3-4c1c-a4fb-d50610a81a71)

2024-10-01 19:04 UTC, ThePlenkov commented
@JamesHenry indeed - I didn't have intention to say it's a final code. So far I've been trying still to understand what is the functional meaning of this function. Like what is more important - to understand what is running the code or which npm was used during installation because is not the same.

Please note that if the code is run via node or deno directly - npm_config_user_agent is empty.
I've created some command today to prove that: https://www.npmjs.com/package/which-engine which also supports which-pm.

2024-10-01 20:23 UTC, ThePlenkov commented
@JamesHenry is there any way to automate formatting before pushing? like husky + format:write may be?

2024-10-02 07:55 UTC, ThePlenkov commented
OK I see now - seems like we are supposed to use pm used to trigger the call. In case if there is no package manager ( let's say we call globally installed create-nx-workspace or via node programmatically ) - then we just use npm as fallback.

@JamesHenry 
How about this?

I intentionally use / in the startsWith to make sure it's yarn and node something like yarn_alternative.

In the includes script I break path into segments and we search for a segment = npm | yarn | bun. And segments like ubuntu will not be taken into account

```
export function detectInvokedPackageManager(): PackageManager {

  if (env.npm_config_user_agent) {
    for (const pm of packageManagerList) {
      if (env.npm_config_user_agent.startsWith(`${pm}/`)) {
        return pm;
      }
    }
  }

  if (env.npm_execpath) {
    for (const pm of packageManagerList) {
      if (env.npm_execpath.split(sep).includes(pm)) {
        return pm;
      }
    }
  }
  return 'npm';

}
```

2024-10-02 09:31 UTC, JamesHenry commented
@ThePlenkov thanks looks reasonable

2024-10-02 10:42 UTC, ThePlenkov commented
I'm struggling to understand why test is failing. It is failing even locally when I run it on the upstream branch ( without my actual changes ). Can it be because of remote cache?

2024-10-20 14:15 UTC, JamesHenry commented
@ThePlenkov I have brought things up to date with the latest, are you able to reproduce locally?

2024-10-20 14:16 UTC, ThePlenkov commented
I did, but couldn't reproduce failing tests((

2024-10-21 13:21 UTC, JamesHenry commented
@ThePlenkov I think I have traced the issue, however I cannot push directly to the PR because you opened it from your `master` branch. Please open PRs from feature branches in future to allow collaborators to push directly.

Please can you try removing this hardcoded npm reference in the e2e utils, I am not sure why it was done but I believe it could be the cause of the error because based on the logs, the test workspace is getting created with pnpm but then is attempting an `npm install` later:

![image](https://github.com/user-attachments/assets/7ecbfd10-1d64-40f1-821e-171baaaaa725)

cc @FrozenPandaz

2024-10-21 18:48 UTC, closed without merging

2024-10-21 18:49 UTC, ThePlenkov commented
@JamesHenry I'll create another PR better then