Fix package manager determintation
nrwl/nx pull request #28546
Opened 2024-10-21 18:51 UTC by ThePlenkov

Recreated from #28202 

### Current Behavior
Currently create-nx-workspace determines package manager based on the invoker's path and it might be totally misleading if some names are used in the path such as /ubuntu/my_project which is identified as bun command by mistake

### Expected Behavior
It should correctly identify package manager

### Related Issue(s)
Fixes https://github.com/nrwl/nx/issues/28201

2024-10-21 19:05 UTC, ThePlenkov commented
picked up wrong commit - updating the branch now..

2024-10-21 19:22 UTC, ThePlenkov commented
@JamesHenry  let's see if it works now. Is it a right way to create PR?  ( from the fork branch, not from master )

2024-10-22 13:51 UTC, JamesHenry commented
Yes looks good, thank you.

The error still persists. I am working on something else right now, but upon a quick try, it is reproducible locally with:

```sh
pnpm nx run e2e-workspace-create:e2e-ci--src/create-nx-plugin.test.ts --skip-nx-cache
```

Please can you take a look?

You can run with `NX_E2E_EDITOR=` with your code editor of choice's CLI to open the test workspaces in an editor and not tear them down so that further digging is possible.

E.g. for VSCode (as long as you have the `code` command in your PATH):

```sh
NX_E2E_EDITOR=code pnpm nx run e2e-workspace-create:e2e-ci--src/create-nx-plugin.test.ts --skip-nx-cache
```

2024-10-24 15:32 UTC, ThePlenkov commented
Somehow it is still waiting for dependent tasks . Curious how we can run only failing test

![image](https://github.com/user-attachments/assets/14afb802-b120-419e-b1c5-f83b26ea5e68)

2024-10-24 15:38 UTC, JamesHenry commented
You can run without `--skip-nx-cache` to not run everything from scratch, I just gave that to ensure accuracy when isolating this one piece

2024-10-24 15:48 UTC, ThePlenkov commented
```
pnpm exec nx run e2e-workspace-create:e2e-ci--src/create-nx-plugin.test.ts 

   ⠋  Nx is waiting on 68 dependent project tasks before running tasks from e2e-workspace-create...

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target e2e-ci--src/create-nx-plugin.test.ts for project e2e-workspace-create and 68 task(s) they depend on (3s)

   ✖  0/0 failed
   ✔  0/0 succeeded [0 read from cache]

View structured, searchable error logs at https://staging.nx.app/runs/WRfGG8terB


 NX   No such file or directory (os error 2)

Pass --verbose to see the stacktrace.
```

2024-10-24 15:49 UTC, ThePlenkov commented
so somehow `nx run nx:build-native` is failing

2024-10-24 15:57 UTC, JamesHenry commented
Do you have rust installed?

You'll need to follow all steps in the https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md

2024-10-24 15:59 UTC, ThePlenkov commented
I open it via devcontainer - not sure if it's installed indeed

2024-10-24 16:02 UTC, ThePlenkov commented
![image](https://github.com/user-attachments/assets/6a311013-ca1f-4c1e-bfdc-d5cdbce22a8a)
rust is there for sure

2024-10-24 16:11 UTC, ThePlenkov commented
following this guide you mention i was trying to run `nx e2e e2e-workspace-create` and it was not working, but e2e-local ran something. May be guide needs to be updated a bit

2024-10-24 16:15 UTC, ThePlenkov commented
So this command is failing now: `nx e2e-local e2e-workspace-create --verbose` and i cannot figure out from where this `No such file or directory (os error 2)` error comes from

2024-11-04 10:31 UTC, JamesHenry commented
@ThePlenkov I think the side-effect of correctly picking up pnpm was that it was being passed an invalid `--yes` param which doesn't apply to `pnpm exec`, I pushed a commit to try and address this and run CI again

2024-12-02 21:10 UTC, xiongemi commented
i think the plugin fix is also in pr https://github.com/nrwl/nx/pull/28949

2025-01-10 00:47 UTC, xiongemi approved these changes

2025-01-14 14:18 UTC, JamesHenry requested changes
So happy to see this green now, thanks again @ThePlenkov!

Please let's add some simple unit test coverage using realistic values for the relevant process.env properties for each supported package manager.

It will help folks understand how this works and protect against some basic regressions

2025-01-14 14:18 UTC, JamesHenry commented on packages/create-nx-workspace/src/utils/package-manager.ts
> +import { sep } from 'node:path';
Let's not have separate imports to `path`. Please combine this with the import on line 3 (using `node:path` for both `join` and `sep`)

2025-01-14 14:19 UTC, JamesHenry commented on packages/create-nx-workspace/src/utils/package-manager.ts
> +import { sep } from 'node:path';
Ah I see you most recently worked on this @xiongemi maybe you could address my points above please

2025-01-14 16:05 UTC, ThePlenkov commented on packages/create-nx-workspace/src/utils/package-manager.ts
> +import { sep } from 'node:path';
Yes - it's a big thanks to @xiongemi . I was not able to figure out why tests were failing

2025-02-17 15:08 UTC, JamesHenry commented
Looks like this one stalled a little bit, I have folded the changes into a related PR here so that it gets over the line: https://github.com/nrwl/nx/pull/30064

Thanks again for bringing this to our attention @ThePlenkov

2025-02-17 15:08 UTC, closed without merging