Remove duplicate space character in thank you header of generated changelog
nrwl/nx pull request #28664
Opened 2024-10-28 12:15 UTC by thdk

## Current Behavior

The nx release changelog command currently generates a changelog that is not formatted properly. It contains two spaces in the `Thank you` header .

## Expected Behavior
Only once space should be added.

2024-11-04 09:29 UTC, JamesHenry requested changes
Thank you, CI is failing FYI

2024-11-19 21:51 UTC, thdk commented
@JamesHenry seems you have already fixed that isse here: 71715363bf1927b962b41447101fa1c82a4605d0 👍🏼 

I've rebased my PR and now includes only the white space fix.

2024-11-20 13:14 UTC, JamesHenry approved these changes

2024-11-20 13:14 UTC, merged

2024-11-20 13:14 UTC, JamesHenry commented
Thank you @thdk!