fix(core): fix for mulitple level of dependsOn
nrwl/nx pull request #28669
Opened 2024-10-29 01:54 UTC by xiongemi

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes https://github.com/nrwl/nx/issues/28599

2024-10-29 09:10 UTC, JamesHenry requested changes

2024-10-29 16:57 UTC, xiongemi commented on packages/nx/src/tasks-runner/create-task-graph.spec.ts
> +  it('should cycle with multiple level of dependencies', () => {
changed the title

2024-10-31 14:18 UTC, Cammisuli approved these changes

2024-10-31 20:17 UTC, JamesHenry approved these changes

2024-11-01 03:33 UTC, merged