feat(rspack): update withReact plugin for parity with webpack plugin
nrwl/nx pull request #28812
Opened 2024-11-05 22:31 UTC by ndcunningham

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-11-08 19:19 UTC, jaysoo commented on packages/rspack/src/utils/lib/apply-react-config.ts
> +  config.plugins = [
Can't we just do this?

```
if (isDev) {
  config.plugins.push(new ReactRefreshPlugin({ overlay: false }));
}
```

2024-11-08 20:46 UTC, jaysoo approved these changes

2024-11-12 19:19 UTC, Coly010 requested changes
Just a circular dep removal and this should be fine.

Has it been tested with Standard React app and with Module Federation?

2024-11-12 19:19 UTC, Coly010 commented on packages/rspack/src/utils/with-react.ts
> +export interface SvgrOptions {
You'll need to move this out of here and likely into `src/plugins/utils/models.ts`

There's a circular dep now between `with-react` and `apply-react-config`

2024-11-12 19:19 UTC, Coly010 commented on packages/rspack/src/utils/lib/apply-react-config.ts
> +import { SvgrOptions } from '../with-react';
This is part 2 of the circular dep

2024-11-12 20:00 UTC, Coly010 approved these changes

2024-11-12 20:00 UTC, merged