feat(nx-dev): version picker
nrwl/nx pull request #28828
Opened 2024-11-07 03:39 UTC by isaacplmann

Adds a version picker to the footer of nx.dev

2024-11-08 21:55 UTC, ndcunningham commented on nx-dev/ui-common/src/lib/selector.tsx
> +                      <span className={'block truncate font-medium'}>
Could this be an anchor tag instead?

2024-11-08 21:55 UTC, ndcunningham commented on nx-dev/ui-common/src/lib/selector.tsx
> +                {props.items.map((item, personIdx) => (
could this be renamed to `idx` instead of `personIdx`?

2024-11-11 08:12 UTC, juristr requested changes
Couple of comments

- can we stay on the same page when switching version? If the page is not available, ideally we'd just go to /docs if possible (it just happens that we version the entire nx.dev website, but it's the docs which is what the user is interested in
- can we backport this to `website-19` etc? otherwise you switch to v19 and there's no version switcher
- side-note: having the version switcher in the footer is not really super visible. maybe that was intentional

2024-11-11 19:00 UTC, isaacplmann commented
Cleaned up the code.

- If we stay on the same page when you switch versions, you could get a 404.  I updated the link so that it goes to `/docs` instead.
- Yes, I can back port it to the older versions after this merges.
- Yes, the version switcher is intentionally in the footer.  It isn't a high frequency action. Once someone knows that its there, they'll just always open the version of the docs that they're on.  For most people, it just gets in the way if it is at the top.

2024-11-14 14:28 UTC, juristr approved these changes

2024-11-14 15:27 UTC, merged