fix(js): skip tsc batch builds for implicit dependencies
nrwl/nx pull request #28840
Opened 2024-11-08 01:24 UTC by cogwirrel

Implicit dependencies are not referenced in code and therefore TSC incremental builds are not applicable.

## Current Behavior
A project using the `@nx/js:tsc` executor will fail to build if it has implicit dependencies on projects which do not use the `@nx/js:tsc` executor.

To reproduce:
* Clone https://github.com/cogwirrel/nx-tsc-batch-implicit-deps-example
* `pnpm i && pnpm nx run-many --target build --batch --all`

## Expected Behavior
- Implicit dependencies that do not use the `@nx/js:tsc` executor are permitted. For example, a TypeScript project may implicitly depend on a Python project, but the TypeScript project should still be buildable in batch mode.
- Projects using the `@nx/js:tsc` executor will still fail to build if they have explicit dependencies on projects which do not use the `@nx/js:tsc` executor.

Tested by publishing to the local registry, upgrading the [example repo](https://github.com/cogwirrel/nx-tsc-batch-implicit-deps-example) to use my local version, and built successfully in batch mode.

## Related Issue(s)
Fixes #28839

2024-11-13 16:00 UTC, leosvelperez requested changes
Thanks for the contribution!

It looks good to me in general. I just left a comment with a grammar change. Please remember to run `pnpm documentation` to re-generate the docs.

2024-11-13 16:00 UTC, leosvelperez commented on packages/js/docs/tsc-examples.md
> +Building a project with the `@nx/js:tsc` executor in batch mode requires all dependent projects (besides implicit dependencies) to be buildable and built using the `@nx/js:tsc` executor.
```suggestion
Building a project with the `@nx/js:tsc` executor in batch mode requires all dependent projects (excluding implicit dependencies) to be buildable and built using the `@nx/js:tsc` executor.
```

2024-11-14 00:50 UTC, cogwirrel commented
> Thanks for the contribution!
> 
> It looks good to me in general. I just left a comment with a grammar change. Please remember to run `pnpm documentation` to re-generate the docs.

Thanks so much for the review! I've updated the wording in the docs :)

2024-11-14 07:22 UTC, leosvelperez approved these changes
Thank you!

2024-11-14 07:59 UTC, merged