feat(core): Handle when an existing plugin begins to fail with the ne…
nrwl/nx pull request #28893
Opened 2024-11-12 06:37 UTC by xiongemi

…w imported project

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2024-11-15 06:31 UTC, xiongemi commented on packages/nx/src/command-line/import/utils/check-compatible-with-plugins.ts
> +        title: `Plugin ${pluginName} is incompatible`,
changed

2024-11-15 06:34 UTC, xiongemi commented on packages/nx/src/command-line/import/utils/check-compatible-with-plugins.ts
> +    pluginName = (error as AggregateCreateNodesError).pluginName;
changed

2024-12-19 19:05 UTC, FrozenPandaz requested changes

2025-01-15 16:10 UTC, FrozenPandaz approved these changes

2025-01-15 16:10 UTC, FrozenPandaz commented on packages/nx/src/project-graph/error-types.ts
> +    const msg = `The nodes created from ${file} by the "${pluginName}" could not be merged into the project graph.`;
Can you include some information about the `pluginIndex` here?

```suggestion
    const msg = `The nodes created from ${file} by the "${pluginName}" at index ${pluginIndex} in nx.json#plugins could not be merged into the project graph.`;
```

2025-01-17 20:06 UTC, merged