feat(module-federation): consolidate module federation utils into module-federation package
nrwl/nx pull request #28919
Opened 2024-11-13 14:00 UTC by Coly010

- feat(module-federation): consolidate module federation utils into module-federation package
- chore(module-federation): fix tests and linting

## Current Behavior

Our current support for Module Federation relies on utilities that are spread and duplicated across the `@nx/webpack` package and the `@nx/rspack` package.

## Expected Behavior

Now that we have a `@nx/module-federation` package, dedupe the utils and consolidate them into a single package

## Todo
- [x] Migrations for React + Angular to install `@nx/module-federation` and point `ModuleFederationConfig` export to that package from webpack.config and rspack.config files

2024-11-15 09:13 UTC, leosvelperez requested changes

2024-11-15 09:13 UTC, leosvelperez commented on packages/angular/src/migrations/update-20-2-0/migrate-mf-imports-to-new-package.ts
> +    let contents = tree.read(filePath, 'utf-8');
We could avoid reading all files by first checking the `filePath` extension. Additionally, we could also only visit the files of projects that have `@nx/webpack` as a dependency.

2024-11-15 09:13 UTC, leosvelperez commented on packages/react/src/migrations/update-20-2-0/migrate-mf-imports-to-new-package.ts
> +    let contents = tree.read(filePath, 'utf-8');
Same suggestions as the other migration to improve performance.

2024-11-15 09:41 UTC, Coly010 commented on packages/module-federation/src/utils/share.ts
> +import { NormalModuleReplacementPlugin as WebpackNormalModuleReplacementPlugin } from 'webpack';
Unfortunately, we can't. 

`require('@rspack/core')` results in an error where the native binary is not resolved correctly.

2024-11-15 10:56 UTC, Coly010 commented on packages/angular/src/utils/mf/with-module-federation.ts
> +                    '@nx/module-federation/src/utils/plugins/runtime-library-control.plugin.js'
I'm going to vote no for now. It's internal and controlled already via a public api in `withModuleFederation`.
 If we add more, maybe, but don't see the need to pre optimize

2024-11-15 11:12 UTC, leosvelperez approved these changes

2024-11-15 15:50 UTC, FrozenPandaz approved these changes

2024-11-15 15:51 UTC, ndcunningham approved these changes

2024-11-18 19:15 UTC, jaysoo approved these changes

2024-11-18 19:15 UTC, merged