feat(testing): use new test environment function from `jest-preset-angular`
nrwl/nx pull request #29054
Opened 2024-11-25 09:34 UTC by chabb

jest-preset-angular is now using setupZoneTestEnv

## Current Behavior

jest-preset-angular issues a deprecation warning

## Expected Behavior
this MR removes this warning

## Related Issue(s)

Fixes #29165

2024-11-29 17:02 UTC, leosvelperez requested changes
Thanks for the contribution!

The change looks good overall, but we need to support older versions of `jest-preset-angular` where this new setup function doesn't exist.

Can you update the PR to conditionally generate the new or old setup depending on the installed version of the `jest-preset-angular` package? The new setup was made available in version `14.3.0`. Let me know if you need help with it.

2024-12-03 13:19 UTC, leosvelperez approved these changes

2024-12-03 17:14 UTC, leosvelperez commented
Something is messed up with this PR in CI at the moment and no tasks are run. To unblock it I re-created it at https://github.com/nrwl/nx/pull/29169, and I'll close this one.

Thanks a lot for the contribution!

2024-12-03 17:14 UTC, closed without merging

2024-12-04 07:02 UTC, chabb commented
@leosvelperez Thanks for taking care of the MR, I unfortunately had no time to get back at it