fix(nest): Fix generators (guard, interceptor etc...) path to not duplicate when provided
nrwl/nx pull request #29084
Opened 2024-11-26 17:09 UTC by ndcunningham

## Current Behavior

When we run the nest generators (interceptor, resource, guard etc...) it tends to duplicate the path and leads to unexpected folder creations.

## Expected Behavior

It should generate in the path provided.

## Related Issue(s)

Fixes #29076

2024-11-26 17:29 UTC, isaacplmann approved these changes

2024-11-27 10:56 UTC, Coly010 approved these changes

2024-11-27 11:56 UTC, leosvelperez requested changes

2024-11-27 11:56 UTC, leosvelperez commented on packages/nest/src/generators/utils/normalize-options.ts
> +    sourceRoot: options.path,
We should get the `directory` from the `determineArtifactNameAndDirectoryOptions` and assign it to the `sourceRoot`. The received `options.path` also contains the filename, so we don't want to provide that as the source root.

I'm doing a similar change in another PR with more general changes, but I'll rebase this one once merged.

```suggestion
    sourceRoot: directory,
```

2024-11-27 12:06 UTC, leosvelperez requested changes

2024-11-27 15:47 UTC, ndcunningham commented on packages/nest/src/generators/utils/normalize-options.ts
> -    ...options,
Yes I will update this and also the schemas to indicate that `--path` is expecting a file to be included in the given option.

2024-11-27 16:30 UTC, leosvelperez approved these changes

2024-11-27 17:24 UTC, merged