cleanup(core): migrate to picospinner
nrwl/nx pull request #29138
Opened 2024-12-02 01:41 UTC by 43081j

Migrates from `ora` to `picospinner`, a much lighter package.

this should roughly be a drop in replacement and will be faster/lighter. it is maintained by the tinylibs org

2024-12-03 08:53 UTC, JamesHenry commented
@43081j I was thinking we would go for `nanospinner` for this, but found an issue that I linked to from the umbrella cleanup issue: https://github.com/es-tooling/ecosystem-cleanup/issues/117#issuecomment-2456690935

Please could you confirm this library does not have this issue? (Should be able to modify the linked stackblitz) and how the two libraries compare?

2024-12-03 15:51 UTC, 43081j commented
I'll take a look when I can 👍

The two libraries are pretty well aligned, so it comes mostly down to personal preference. picospinner is a bit more customisable

Both maintainers are active in our community too, so you really could just flip a coin here 😅

2024-12-05 17:51 UTC, JamesHenry requested changes
@43081j I added picospinner to my comparison with ora and nanospinner:
https://stackblitz.com/edit/stackblitz-starters-dmnx9n?file=package.json&view=editor

It seems like it doesn't actually allow for the error handling at all. Maybe it is calling process.exit itself?

- ora: works as expected but bloated
- nanospinner: has double printing issue on exit
- picospinner: does not allow for exceptions to be handled

We cannot proceed until one of `nanospinner` or `picospinner` matches the functionality/robustness of ora I'm afraid

2024-12-05 18:06 UTC, 43081j commented
All good, I'll look into this today or tomorrow 👍

I'm mobile at the minute so can't dig into it but I'll figure it out once I'm at a laptop

2025-02-15 09:34 UTC, JamesHenry commented
Hi @43081j, 

Following up on this one:

With the latest versions of `picospinner` and `nanospinner`, it's `nanospinner` that seems to best match `ora` for our usage:

<img width="546" alt="image" src="https://github.com/user-attachments/assets/1a52c924-fe9d-4d9c-b5a7-a363d2a6ee48" />

It's because https://github.com/usmanyunusov/nanospinner/issues/32 was explicitly addressed.

https://github.com/tinylibs/picospinner/pull/5 remains in limbo somewhat. I think we could probably press ahead with `nanospinner` for now,  but remain open to `picospinner` in future?

2025-02-15 11:48 UTC, 43081j commented
its been a while so i forget what the disagreement was, but as far as i remember, it was because none of these spinners should really allow output while they're enabled

when the spinner is enabled, you wouldn't expect output to occur (because we're outputting the spinner frames).

errors are no different and shouldn't output either.

picospinner seems to be doing the right thing here and we're wrong for not stopping the spinner before outputting errors.

however, that does make your try/catch a little more verbose, so i understand why ora and nanospinner would add special behaviour for it.

we should go with nanospinner for that reason

2025-02-15 12:30 UTC, 43081j commented
i've rebased and updated to use nanospinner 👍

2025-02-15 13:57 UTC, JamesHenry commented
Awesome, thanks! Please can we add the usual lint import check to prevent regressions

2025-12-19 18:37 UTC, jaysoo commented
Hey, thanks again for taking the initiative on this and on https://github.com/nrwl/nx/pull/30078.

Unfortunately, both PRs now have many conflicts, and we've been focused on other areas of the tool. There are other places like in `packages/create-nx-workspace` that also use `ora`, so I would suggest on PR to update everything.

If you'd like, opening a discussion on why this is important can also help the team prioritize frequently requested features.

I'm going to close this as it has gone stale.

2025-12-19 18:37 UTC, closed without merging