fix(core): disregard parent .gitignore files when walking workspace
nrwl/nx pull request #29245
Opened 2024-12-06 23:02 UTC by adambiggs

## Current Behavior
When the parent directory of a Nx workspace contains a `.gitignore` file, those ignores can affect file traversal within the workspace. This makes project resolution non-deterministic since it depends on gitignore patterns that exist outside of the workspace's control.

For example, if a workspace is inside a directory with `*` in its .gitignore, Nx fails to properly traverse workspace files.

The root cause is that the `ignore` crate's `WalkBuilder::parents()` method defaults to `true`, causing it to respect parent directory gitignore files.

## Expected Behavior
Nx should only respect .gitignore files that exist within the workspace directory. Parent .gitignore files should have no effect on workspace traversal, ensuring consistent and deterministic project resolution regardless of where the workspace is located.

## Related Issue(s)
Fixes #27368, #28000, #27295, #28123

@nrwl/nx-pipelines-reviewers Given that this fix affects core project resolution behavior, it would be helpful to have a prerelease version so other users can confirm weather it resolves other issues that may or may not be related.

2025-01-21 02:03 UTC, AgentEnder approved these changes

2025-01-21 02:05 UTC, AgentEnder commented
Need to double check some behavior around nested gitignore with this change,  but excited that this may work

2025-01-30 15:12 UTC, Cammisuli commented
This will work with simple workspaces that are just their own repo. But if someone has Nx inside a folder within a repo like so:
```
org/
│
├── .git/
│
├── nx-workspace/
│   └── nx.json
│
└── java-project/
    ├── src/
    ├── pom.xml
    └── README.md
```

Then we want to have parent folders activated. We need to think of a proper solution that will support both cases.

2025-01-30 19:58 UTC, adambiggs commented
@Cammisuli do folks really have multiple Nx workspaces in a single repo? That seems like a pretty niche edge case unless I'm missing something.

If anyone does run into that issue, a quick & easy workaround would be to simply duplicate the root `.gitignore` into the `nx-workspace` subdirectory. To me that seems like a small price to pay for deterministic project graph resolution.

Do you think it would be worth merging this to unblock everyone from upgrading to versions newer than v19.4.4, and then think of a solution for the multi-workspace monorepo scenario if/when it becomes a problem?

2025-01-30 20:29 UTC, adambiggs commented
Was this new behaviour intentional based on a feature request or something? Or was it only introduced because it's the default behaviour of `WalkBuilder`?

I believe this PR restores the same behaviour as before the issue was introduced in 19.5.0. Would your example above have the same problem with 19.4.4?

2025-01-31 02:25 UTC, Cammisuli requested changes
I added some suggestions to satisfy both cases. This will essentially enable parents if the traversal root (aka the nx workspace root) is not the `.git` root. Otherwise it will disable parents if the traversal root is a git root.

2025-01-31 02:25 UTC, Cammisuli commented on packages/nx/src/native/walker.rs
>          walker.add_custom_ignore_filename(".nxignore");
```suggestion
    walker.git_ignore(use_ignores);
    if use_ignores {
        // disable the parent gitignore if the directory is a git repo, otherwise use the parent gitignore
        walker.parents(!directory.join(".git").exists());
        walker.add_custom_ignore_filename(".nxignore");
```

2025-01-31 02:25 UTC, Cammisuli commented on packages/nx/src/native/walker.rs
> +    }
```suggestion
     #[test]
    fn is_unaffected_by_parent_gitignore_if_traversal_root_is_a_git_root() {
        let parent_temp = assert_fs::TempDir::new().unwrap();
        parent_temp.child(".gitignore").write_str("*").unwrap();
        parent_temp.child("workspace/.git").touch().unwrap();
        parent_temp
            .child("workspace/file1.txt")
            .write_str("test")
            .unwrap();
        parent_temp
            .child("workspace/project.json")
            .write_str("test")
            .unwrap();

        let workspace_path = parent_temp.path().join("workspace");
        let mut files: Vec<_> = nx_walker(&workspace_path, true)
            .map(|f| f.normalized_path)
            .collect();
        files.sort();

        assert_eq!(
            files,
            vec!["file1.txt".to_string(), "project.json".to_string()]
        );
    }

    #[test]
    fn is_affected_by_parent_gitignore_if_traversal_root_is_not_a_git_root() {
        let parent_temp = assert_fs::TempDir::new().unwrap();
        parent_temp.child(".gitignore").write_str("*").unwrap();
        parent_temp
            .child("workspace/file1.txt")
            .write_str("test")
            .unwrap();
        parent_temp
            .child("workspace/project.json")
            .write_str("test")
            .unwrap();

        let workspace_path = parent_temp.path().join("workspace");
        let mut files: Vec<_> = nx_walker(&workspace_path, true)
            .map(|f| f.normalized_path)
            .collect();
        files.sort();

        assert!(files.is_empty());
    }
}
```

2025-03-31 15:57 UTC, adamalton commented
> I added some suggestions to satisfy both cases. This will essentially enable parents if the traversal root (aka the nx workspace root) is not the .git root. Otherwise it will disable parents if the traversal root is a git root.

If I'm reading this correctly, your suggested changes will make it so that if the nx workspace root contains a `.git` folder then `.gitignore` files in parent directories will be ignored, but if the nx workspace root does *not* contain a `.git` folder then `.gitignore` files in parent directories will be read.

Assuming that's an accurate description of the behaviour, then it will not correctly handle the case where the nx workspace is inside a subdirectory in a repo _and_ the user has also got a `.gitignore` file higher up the tree somewhere, e.g. in their home directory.

I would suggest that a more desirable behaviour would be that `.gitignore` files in parent directories are taken into account _until_ a `.git` folder is encountered. That `.git` folder might be in the nx workspace root, in which case no parent `.gitignore` files would be read at all. But in the case where the nx workspace is nested, parent `.gitignore` files will be read until we reach the "top" of the git repo under which the nx workspace is controlled, and then no more parent `.gitignore` files will be read.

That would seem like a more desirable behaviour to me.

2025-07-14 15:28 UTC, AgentEnder commented
I'm going to close this PR out in favor of https://github.com/nrwl/nx/pull/31911 which incorporates the various suggested feedbacks

2025-07-14 15:28 UTC, closed without merging