feat(nx-dev): customer videos on customer page
nrwl/nx pull request #29380
Opened 2024-12-16 22:23 UTC by juristr

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2025-01-08 18:18 UTC, bcabanes requested changes

2025-01-08 18:18 UTC, bcabanes commented on nx-dev/ui-customers/src/lib/enterprise-customers.tsx
> +          <div className="grid-cols grid justify-center gap-4 px-2 py-6 md:grid-cols-3">
Please add some breathing room like `my-8` or `my-12`, and same for the cards below like `gap-8` or `gap-12`. 

In addition, now that we have 3 cards on the same row, the shadows are too pronounced, can you make them lighter please?

2025-01-08 18:18 UTC, bcabanes commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +export function CustomerTestimonialCarousel(): JSX.Element {
Can you add the swipe behaviour for mobile?

2025-01-08 18:18 UTC, bcabanes commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +              className={`${logo.height} ${logo.width} transition-transform duration-300`}
Add `flex-shrink-0` to make sure the logo won't shrink in size.
Add `aria-hidden="true"` to make it invisible to screen reader.

2025-01-08 18:18 UTC, bcabanes commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +          <button
With this implementation there is effectively no text describing what is the current logo, which impact accessibility and SEO. Please add the brand name too, can be set with the `sr-only` class.

2025-01-08 18:18 UTC, bcabanes commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +              <ChevronLeftIcon className="h-8 w-8" />
Add `flex-shrink-0` to make sure the icon is not resized,  `aria-hidden="true"` to make it invisible to screen reader.

2025-01-08 18:18 UTC, bcabanes commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +            <button
Add a text to the button describing the action set with `sr-only` for accessibility purpose.

2025-01-08 18:18 UTC, bcabanes commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +              <ChevronRightIcon className="h-8 w-8" />
Add `flex-shrink-0` to make sure the icon is not resized,  `aria-hidden="true"` to make it invisible to screen reader.

2025-01-08 18:18 UTC, bcabanes commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +            <button
Add a text to the button describing the action set with sr-only for accessibility purpose.

2025-01-08 18:18 UTC, bcabanes commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +              title={`See ${testimonials[currentIndex - 1]?.company} again!`}
Remove the `again!`.

2025-01-08 18:18 UTC, bcabanes commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +              title={`Next ${testimonials[currentIndex + 1]?.company}!`}
Remove the `!`.

2025-01-08 18:18 UTC, bcabanes commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +          const nextIndex = (prevIndex + 1) % testimonials.length;
Local variable here is redundant.

2025-01-09 15:26 UTC, ndcunningham commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +export function CustomerTestimonialCarousel(): JSX.Element {
Good question! When I got the changes, the custom implementation was already in place, so I built on top of it to quickly deliver the MVP. That said, I agree that leveraging the existing Carousel component would be a cleaner approach

2025-01-09 16:06 UTC, ndcunningham commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +export function CustomerTestimonialCarousel(): JSX.Element {
Mentioned this to Juri about adding this later if possible reusing the carousel on the enterprise page.

2025-01-09 16:22 UTC, ndcunningham commented on nx-dev/ui-icons/src/lib/customers/rabobank.tsx
> +export const RabobankIcon: FC<SVGProps<SVGSVGElement>> = (props) => (
I think we should keep it so that when we add a few more customers we can always keep the page balanced since it shows a grid of 4.

2025-01-09 16:35 UTC, ndcunningham commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +              className={`${logo.height} ${logo.width} transition-transform duration-300`}
Added aira label the container is not `flex` so `flex-shrink-0` is not needed.

2025-01-09 16:39 UTC, ndcunningham commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +          <button
done

2025-01-09 16:41 UTC, ndcunningham commented on nx-dev/ui-customers/src/lib/enterprise-customers.tsx
> +          <div className="grid-cols grid justify-center gap-4 px-2 py-6 md:grid-cols-3">
done

2025-01-09 16:54 UTC, ndcunningham commented on nx-dev/ui-icons/src/lib/customers/rabobank.tsx
> +export const RabobankIcon: FC<SVGProps<SVGSVGElement>> = (props) => (
Removed

2025-01-09 16:54 UTC, ndcunningham commented on nx-dev/ui-icons/src/lib/customers/rabobank.tsx
> + * Use `#283A93` for a colored version.
Removed

2025-01-09 16:54 UTC, ndcunningham commented on nx-dev/ui-icons/src/lib/customers/rabobank.tsx
> +    viewBox="0 0 24 4.3"
Removed

2025-01-09 17:39 UTC, ndcunningham commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +      <div className="mx-auto grid max-w-7xl grid-cols-2 gap-2 px-4 lg:grid-cols-5 lg:gap-4">
Fixed

2025-01-09 17:40 UTC, ndcunningham commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +            <button
done

2025-01-09 17:40 UTC, ndcunningham commented on nx-dev/ui-customers/src/lib/customer-testimonial-carousel.tsx
> +            <button
done

2025-01-09 20:09 UTC, bcabanes approved these changes

2025-01-09 20:30 UTC, merged