cleanup(core): move esbuild to use tinyglobby
nrwl/nx pull request #29453
Opened 2024-12-21 11:40 UTC by 43081j

An alternative to #28037, switches the esbuild package to use `tinyglobby` instead of `fast-glob`.

This improves performance a fair chunk and reduces install complexity/size.

2024-12-21 13:15 UTC, benmccann approved these changes

2024-12-23 10:34 UTC, JamesHenry requested changes
Please add the eslint entry as usual to avoid regressions

2024-12-31 15:46 UTC, 43081j commented
@JamesHenry this should be all good now

2025-01-14 15:06 UTC, JamesHenry approved these changes
Thanks a lot @43081j!

2025-01-14 15:06 UTC, merged