feat(core): add gradle plugin
nrwl/nx pull request #29464
Opened 2024-12-24 06:11 UTC by xiongemi

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2025-03-20 13:28 UTC, MaxKless reviewed
great job! Left some comments & questions

2025-03-20 13:28 UTC, MaxKless commented on packages/gradle/src/executors/gradlew/gradlew.impl.ts
> +export async function graldewExecutor(
typo

2025-03-20 13:28 UTC, MaxKless commented on packages/gradle/src/executors/gradlew/schema.json
> +  "description": "The GradlewImpl executor is used to run Gradle tasks.",
should we mention that it's basically just runCommands unless in batch mode? Or is that too much implementation detail?

2025-03-20 13:28 UTC, MaxKless commented on packages/gradle/src/plugin/nodes.ts
> +    targetsCache[hash] ??=
super nit but why is this a targetsCache if it contains projects? Shouldn't it be a projectsCache?

2025-03-20 13:28 UTC, MaxKless commented on packages/gradle/src/plugin/nodes.ts
> +      findGraldewFile(gradleFilePath, context.workspaceRoot)
typo

2025-03-20 13:28 UTC, MaxKless commented on packages/gradle/src/plugin/utils/create-ci-targets.ts
> +export function replaceTargetNameWithOptions(
not saying it's wrong but is there a reason we replace the ciTargetName after the fact instead of passing ciTargetName into the gradle task? That way it could set up the correct naming right away

2025-03-20 13:28 UTC, MaxKless commented on packages/gradle/src/plugin/dependencies.ts
> +  const { dependencies: dependenciesFromReport } =
here we just get the project graph report right away without calling `populateProjectGraph`.
I guess there are no cases where `createDependencies` will be called without `createNodes` being called before it?

2025-03-20 13:28 UTC, MaxKless commented on packages/gradle/executors.json
> +      "description": "gradlew.impl executor"
we should add a better description here

2025-03-24 05:21 UTC, xiongemi commented on packages/gradle/src/plugin/nodes.ts
> +    targetsCache[hash] ??=
changed

2025-03-24 05:21 UTC, xiongemi commented on packages/gradle/src/plugin/nodes.ts
> +      findGraldewFile(gradleFilePath, context.workspaceRoot)
changed

2025-03-24 05:24 UTC, xiongemi commented on packages/gradle/src/plugin/dependencies.ts
> +  const { dependencies: dependenciesFromReport } =
yes. plugin v1 has this behaviour, so createNodes will be called first and no need to call `populateProjectGraph`

2025-03-24 05:39 UTC, xiongemi commented on packages/gradle/project-graph-plugin/src/main/kotlin/dev/nx/gradle/NxProjectGraphReportPlugin.kt
> +    val hashProperty = project.findProperty("hash")?.toString() ?: "default-hash"
good idea, add a warning message

2025-03-27 19:10 UTC, xiongemi commented on packages/gradle/project-graph-plugin/src/main/kotlin/dev/nx/gradle/utils/TaskUtils.kt
> +              path.endsWith(".jar") &&
make sense, going to include all extensions

2025-03-28 14:43 UTC, xiongemi commented on packages/gradle/src/plugin/utils/create-ci-targets.ts
> +export function replaceTargetNameWithOptions(
good point, move this logics to plugin

2025-03-28 15:00 UTC, xiongemi commented on packages/gradle/src/executors/gradlew/schema.json
> +  "description": "The GradlewImpl executor is used to run Gradle tasks.",
i am going to remove the gradlew executor for now because native batch runner will change it anyway, since it is not used for now

2025-03-28 15:01 UTC, xiongemi commented on packages/gradle/executors.json
> +      "description": "gradlew.impl executor"
remove executor for now

2025-03-28 15:54 UTC, xiongemi commented
currently pr is blocked because i rename the plugin, however, the plugin portal has not approve my request. https://github.com/gradle/plugin-portal-requests/issues/257

2025-04-14 20:00 UTC, FrozenPandaz requested changes

2025-04-14 20:00 UTC, FrozenPandaz commented on packages/gradle/project-graph/project.json
> +      "command": "./gradlew :project-graph:check",
This is not the right command.

2025-04-15 17:36 UTC, xiongemi commented on build.gradle.kts
> +      plugin("project-report")
removed

2025-04-15 17:36 UTC, xiongemi commented on build.gradle.kts
> +}
removed

2025-04-15 21:15 UTC, xiongemi commented on packages/gradle/project-graph/build.gradle.kts
> +    plugin("project-report")
removed

2025-04-15 21:23 UTC, xiongemi commented on packages/gradle/project-graph/build.gradle.kts
> +    plugin("dev.nx.gradle.project-graph")
removed

2025-04-15 21:23 UTC, xiongemi commented on packages/gradle/project-graph/build.gradle.kts
> +    plugin("com.ncorti.ktfmt.gradle")
removed

2025-04-15 21:27 UTC, xiongemi commented on packages/gradle/project-graph/build.gradle.kts
> +            name.set("The Apache License, Version 2.0")
changed

2025-04-15 21:34 UTC, xiongemi commented on packages/gradle/project-graph/project.json
> +      "command": "./gradlew :project-graph:check",
changed

2025-04-15 22:08 UTC, xiongemi commented on packages/gradle/project-graph/build.gradle.kts
> +    publications.named("nxProjectGraphPluginPluginMarkerMaven", MavenPublication::class) {
i asked ai for this

You need both pluginMaven and nxProjectGraphPluginPluginMarkerMaven because:

pluginMaven is the main artifact that contains your plugin implementation and metadata.

nxProjectGraphPluginPluginMarkerMaven is the marker artifact that tells Gradle:

“This plugin ID maps to this group + artifact.”


Publication Name | What it’s for
-- | --
pluginMaven | The actual plugin JAR + metadata. This contains your plugin class and logic.
nxProjectGraphPluginPluginMarkerMaven | A lightweight artifact that contains only a POM file with plugin ID → implementation class mapping. Used by Gradle's plugin resolution system.

this is the output of build:
<img width="477" alt="Screenshot 2025-04-15 at 6 03 24 PM" src="https://github.com/user-attachments/assets/64644b3d-aa69-4408-a279-e2fa8bdb7397" />

insdie dev/nx/gradle/project-graph, that is the nxProjectGraphPluginPluginMarkerMaven
inside dev/nx/gradle/project-pragh/dev.nx.gradle.project-graph.gradle.plugin, that is pluginMaven

2025-04-15 22:57 UTC, xiongemi commented on packages/gradle/project-graph/project.json
> +    },
added

2025-04-17 19:36 UTC, FrozenPandaz approved these changes

2025-04-17 19:36 UTC, FrozenPandaz commented on packages/gradle/project-graph/src/main/kotlin/dev/nx/gradle/utils/TaskUtils.kt
> +        .filter { it.exists() }
Don't filter if it exists.

2025-04-17 19:36 UTC, FrozenPandaz commented on packages/gradle/project-graph/src/main/kotlin/dev/nx/gradle/utils/TaskUtils.kt
> +      }
We shouldn't have different targets for CI and non-CI.

Let's keep `build` depending on `test` as is.

Let's instruct Gradle users to run `nx affected -t assemble,check-ci` which will not run `test`.. but `test-ci`.

2025-04-17 19:36 UTC, FrozenPandaz commented on packages/gradle/project-graph/src/main/kotlin/dev/nx/gradle/utils/CiTargetsUtils.kt
> +    val targetName = "$ciTargetName--$fileName"
fileName should be className

2025-04-17 19:36 UTC, FrozenPandaz commented on packages/gradle/project.json
> +          },
Remove this

2025-04-17 19:36 UTC, FrozenPandaz commented on packages/gradle/src/plugin/dependencies.ts
> +    try {
Try removing this try catch

2025-04-17 19:36 UTC, FrozenPandaz commented on packages/gradle/src/plugin/dependencies.ts
> +    } catch {} // ignore invalid dependencies
We should at least warn if we really need it.

2025-04-17 19:37 UTC, FrozenPandaz approved these changes

2025-04-17 19:37 UTC, FrozenPandaz commented on packages/gradle/migrations.json
> +      "version": "20.7.0-beta.0",
Change to Nx 21

2025-04-20 02:06 UTC, xiongemi commented on packages/gradle/src/plugin/dependencies.ts
> +    } catch {} // ignore invalid dependencies
changed

2025-04-20 02:06 UTC, xiongemi commented on packages/gradle/src/plugin/dependencies.ts
> +    try {
change to warn in the catch

2025-04-20 02:07 UTC, xiongemi commented on packages/gradle/project.json
> +          },
removed

2025-04-20 02:08 UTC, xiongemi commented on packages/gradle/project-graph/src/main/kotlin/dev/nx/gradle/utils/TaskUtils.kt
> +        .filter { it.exists() }
removed

2025-04-20 06:49 UTC, xiongemi commented on build.gradle.kts
> +    id("dev.nx.gradle.project-graph") version("+")
changed

2025-04-20 06:52 UTC, xiongemi commented on gradle.properties
> +org.gradle.configuration-cache=false
added

2025-04-20 07:16 UTC, xiongemi commented on packages/gradle/project-graph/src/main/kotlin/dev/nx/gradle/utils/TaskUtils.kt
> +      }
changed

2025-04-22 17:41 UTC, xiongemi commented on packages/gradle/migrations.json
> +      "version": "20.7.0-beta.0",
changed

2025-04-22 17:41 UTC, xiongemi commented on packages/gradle/project-graph/src/main/kotlin/dev/nx/gradle/utils/CiTargetsUtils.kt
> +    val targetName = "$ciTargetName--$fileName"
changed

2025-04-23 17:13 UTC, merged