WIP feat(core): switch over to devkit 10-rc.0
nrwl/nx pull request #3056
Opened 2020-05-22 18:23 UTC by FrozenPandaz

# WIP

This is not done yet at all. This is to start testing changes in CI and locally.

*There is no ETA on when this will be released.*

## Current Behavior (This is the behavior we have today, before the PR is merged)

We use angular-devkit 9.1

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

We use angular-devkit 10-rc.0

## Issue

2020-07-06 18:52 UTC, vsavkin requested changes

2020-07-06 18:52 UTC, vsavkin commented on packages/react/src/schematics/application/lib/update-jest-config.ts
> +    : chain([
why was this inlined?

2020-07-06 18:52 UTC, vsavkin commented on packages/web/src/utils/source-root.ts
> +  const projectMeta = await context.getProjectMetadata(context.target.project);
we can remove the workspaces import?

2020-07-06 18:52 UTC, vsavkin commented on packages/workspace/src/migrations/update-10-0-0/solution-tsconfigs.ts
> +export default function (schema: any): Rule {
I'd refactor and split it into mutliple functions with meaningful names. The code is very dense.

2020-07-06 18:52 UTC, vsavkin commented on packages/workspace/src/migrations/update-10-0-0/solution-tsconfigs.ts
> +        if (ig.ignores(join(_dir, file))) {
I think the ignored above should be sufficient. The recursive call will return nothing if it's ignored, right?

2020-07-07 14:58 UTC, FrozenPandaz commented on packages/angular/src/schematics/application/application.ts
> +      updateJsonInTree('tsconfig.json', () => ({
Angular schematics try to modify a `tsconfig.json` solution in the root of the repository. In `10.1.0` they will change it to having a `tsconfig.json` in the project directory.

For now, this is a hack that adds a `tsconfig.json` to the tree for the schematic to modify then deletes it.

2020-07-07 21:02 UTC, merged

2021-01-04 06:13 UTC, royling commented on packages/angular/src/schematics/application/application.ts
> +      updateJsonInTree('tsconfig.json', () => ({
@FrozenPandaz currently this hack is breaking my workspace schematic that is leveraging `@nrwl/angular` to generate a new application in the project, even though angular `10.2.x` is used. The problem is `tsconfig.json` in the repository root got deleted after creating a new app with the workspace schematic. But `tsconfig.json` is still referenced by other existing apps. For now, I cannot upgrade my repo to use Angular/Nx 11 due to some other libs, do you think it's ok to remove this hack in Nx 10.x to support this scenario? Thanks!