docs(docs): workspace builder
nrwl/nx pull request #3057
Opened 2020-05-22 20:24 UTC by ZackDeRose

Adds a doc explaining best practices for creating and running cutom builders to a Nx Workspace.

_[Please make sure you have read the submission guidelines before posting an PR](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#submit-pr)_

> _Please make sure that your commit message follows our format._

> Example: `fix(nx): must begin with lowercase`

## Current Behavior (This is the behavior we have today, before the PR is merged)

## Expected Behavior (This is the new behavior we can expect after the PR is merged)

## Issue

2020-05-22 20:28 UTC, ZackDeRose commented on docs/shared/tools-workspace-builders.md
> +      "$default": {
```suggestion
```

2020-05-22 20:28 UTC, ZackDeRose commented on docs/shared/tools-workspace-builders.md
> +        "$source": "argv",
```suggestion
```

2020-05-22 20:28 UTC, ZackDeRose commented on docs/shared/tools-workspace-builders.md
> +        "index": 0
```suggestion
```

2020-05-22 20:28 UTC, ZackDeRose commented on docs/shared/tools-workspace-builders.md
> +      }
```suggestion
```

2020-05-22 20:29 UTC, ZackDeRose commented on docs/shared/tools-workspace-builders.md
> +      "description": "Text To Echo",
```suggestion
      "description": "Text To Echo"
```

2020-05-25 13:07 UTC, isaacplmann requested changes

2020-05-25 13:07 UTC, isaacplmann commented on docs/shared/tools-workspace-builders.md
> +After your files are created, you can compile your builder with `tsc`:
Maybe add a note here that `tsc` is available if you've installed typescript globally

2020-05-25 13:07 UTC, isaacplmann commented on docs/shared/tools-workspace-builders.md
> +Our last step is to add this builder to a given project’s `architect` object your project's `workspace.json` or `angular.json` file. See the example below for adding this builder to a project named '
```suggestion
Our last step is to add this builder to a given project’s `architect` object in your project's `workspace.json` or `angular.json` file. The example below adds this builder to a project named 'platform':
```

2020-05-25 13:07 UTC, isaacplmann commented on docs/shared/tools-workspace-builders.md
> +Note that the format of the `builder` string here is: `${Path to builder directory}:${builder name}`.
```suggestion
Note that the format of the `builder` string here is: `${Path to directory containing the builder's package.json}:${builder name}`.
```

2020-06-05 14:18 UTC, ZackDeRose commented on docs/shared/tools-workspace-builders.md
> +NOTE:
I'll remove the not for now. Will see about implementing this with Juri

2020-08-14 19:10 UTC, vsavkin commented
Closing this due to inactivity

2020-08-14 19:10 UTC, closed without merging