fix(core): honor workspace layout with workspace move schematic
nrwl/nx pull request #3318
Opened 2020-07-12 15:36 UTC by devinshoemaker

## Current Behavior
The `@nx/workspace:move` schematic does not check the users workspace layout configuration and assumes the `apps/` and `libs/` dir.

If the user manually updates their workspace layout and then attempts to use the `move` schematic then their preferences will be ignored.

If the user the user manually changes their workspace layout, generates a new application or library, and then attempts to use the `move` schematic on the newly generated project then an error is thrown. 

## Expected Behavior
As a user with a custom workspace layout, I should be able to use the `@nrwl/workspace:move` schematic.

2020-07-13 18:33 UTC, jdpearce commented
@devinshoemaker This looks great. Are you able to add an e2e and/or unit test to cover this case? 

(You could pretty much cut and paste one of the ones that exists already)

Btw, you don't have to pay attention to this, but the more I look at the number of times that `getDestination` is called, the more I wonder if it shouldn't just be added on to the options right at the beginning and then never called again... we have precedents for this, cf. various `normalizeOptions` methods...

2020-07-13 18:34 UTC, catfireparty requested changes
Sorry, meant to leave the previous comment as a review 😆 

i.e. e2e/unit test, if poss?

2020-07-14 11:33 UTC, devinshoemaker commented
@jdpearce thanks for taking a look! I'll take a crack at some tests.

As far as the destination goes, are you saying that should be in the normalized options schema? It should be trivial to add it there and remove the need to fetch it multiple times.

2020-07-16 14:22 UTC, jdpearce commented
@devinshoemaker Awesome. If you need help, give me a shout.

Regarding the destination, we've put it in a "normalized" options schema in other schematics yes. If you can do that as well, that would be super amazing, thanks!

2020-07-16 16:24 UTC, devinshoemaker commented
@jdpearce yeah I've very familiar with the normalized options concept at this point. 😁 That should be no issue. I'll try and chip away at it a bit tonight, but I'll be out of town over the weekend so I likely won't be able to wrap it up until early next week.

2020-07-24 10:27 UTC, jdpearce commented
@devinshoemaker I've converted this PR to a draft for now until you're ready to push further changes. Let me know if you need help finishing this off.

2020-07-24 11:21 UTC, devinshoemaker commented
@jdpearce thanks, sorry there's been a lot going on this week. Is there a way to only run workspace e2e changes? The `e2e.sh` script seems to only take what CLI you want to test as an option, and `nx e2e e2e-workspace` results in the error `Error: ENOENT: no such file or directory, stat '/Users/devinshoemaker/code/nx/nx/tsconfig.json'`.

2020-07-24 12:55 UTC, jdpearce commented
@devinshoemaker If you want to run a single set of e2e tests you should be able to run `yarn e2e e2e-workspace -t "test name"`.

`nx e2e e2e-workspace` needs some extra config to run properly which is why it's wrapped in the `e2e.ts` script.

2020-07-24 18:38 UTC, devinshoemaker commented
@jdpearce awesome, that definitely helps. What level of detail would you like from the e2e test? I found the existing e2e tests for the move schematic in `workspace-aux-commands.test.ts` which is pretty extensive so I am considering pulling out most of that logic into a reusable method that I could pass the apps and libs dir that the test Is using.

2020-07-24 18:54 UTC, devinshoemaker commented
Also, the move schematic currently does not have any unit tests, and I'm having trouble getting a basic test to work even on master. If I try to execute these two schematics on master then I get this error:

```
describe('move', () => {
  let appTree: Tree;

  beforeEach(() => {
    appTree = Tree.empty();
    appTree = createEmptyWorkspace(appTree);
  });

  describe('custom workspace layout', () => {
    it('should move library', async () => {
      // appTree = await callRule(
      //   updateJsonInTree<NxJson>('nx.json', (json) => {
      //     json.workspaceLayout = { appsDir: 'e2e', libsDir: 'packages' };
      //     return json;
      //   }),
      //   appTree
      // );

      appTree = await runSchematic('lib', { name: 'myLib' }, appTree);
      appTree = await runSchematic('move', { projectName: 'my-lib', destination: 'subdir/my-lib' }, appTree);
    });
  });
});
```

Error:
```
This should never happen. Path: "/libs/my-lib".

      24 |         });
      25 | 
    > 26 |         tree.delete(project.root);
         |                    ^
      27 | 
      28 |         return tree;
      29 |       })
```

I was able put a breakpoint on that line and my tree object has the folder that's it's trying to delete, and I'm not sure what else to gather from this error. I tried to look for some unit tests for the remove schematic since it would likely be a similar scenario, however, that schematic does not have any unit tests either. I'll keep trying different things, but if something stands out then let me know.

2020-07-31 12:59 UTC, jdpearce commented
@devinshoemaker Apologies for replying late! The "this should never happen" error is actually coming from Angular devkit. I've raised a bug with them, but I don't think it's a high priority to fix.

That bug is why there aren't any full unit tests for that schematic, because you can't use their virtual file system without triggering that error. You _have_ to operate on an existing workspace, hence the e2e tests.

Having said that, there _are_ some unit tests for the rules in the move schematic. You can't test the rule that actually moves the files, but I think the other rules all have tests, e.g. updateWorkspace should be testable?

As to the level of detail... some? As long as there is at least one test that touches on the functionality that's been added/modified then I'm fairly happy. They take a long time to run at the moment, so 100% full coverage isn't something we strive for.

2020-08-04 02:42 UTC, devinshoemaker commented
@jdpearce just wanted to post a quick update. I have some unit and e2e tests working but one of the e2e tests highlighted another area of the `move` schematic that needs to account for the workspace layout. I should have an update within the next day or two.

2020-08-04 12:00 UTC, devinshoemaker commented
So I have run into a small hiccup. The line of code I am having issue with right now is [this](https://github.com/nrwl/nx/blob/master/packages/workspace/src/schematics/move/lib/update-imports.ts#L32). Basically, the `substr(...)` assumes a workspace layout of apps and libs so we need to first figure out the project type and then look up the workspace layout config accordingly. However, it doesn't appear that `WorkspaceDefinition` has this property. I could change this function to read the workspace using the `readJsonInTree(...)` method but that would change the method a bit and I'm not sure if there are any other technical advantages to using the `WorkspaceDefinition`. In this case, should I update the `WorkspaceDefinition` to include this property? Or should I change the function to just read the JSON in a more basic manner?

2020-08-04 16:59 UTC, jdpearce commented
@devinshoemaker Is the layout in the `WorkspaceDefinition`? That's something we're pulling from angular devkit so it's not something you could modify, iirc.

I thought the `workspaceLayout` property was in `nx.json`?

2020-08-05 00:43 UTC, devinshoemaker commented
So that `substr` method I mentioned assumes a specific length of the directory that apps or libs might be in (in the case of a default workspace, both are 4 characters long which is why the `substr` has a parameter of 5). I need to check the `WorkspaceDefinition` for the `projectType` so that I know which property in the `workspaceLayout` that I need to use in order to calculate the proper `substr` length. Hopefully, that makes sense. My main issue is that `WorkspaceDefinition` does not have this `projectType` property so I can't reliably tell whether a project that's being moved is an app or a lib, and therefore cannot reliably determine the `substr` length. If the `WorkspaceDefinition` is an Angular thing then it sounds like the best approach would be to treat the `workspace.json` as a regular JSON instead of a typed variable in order determine the `projectType` of the project being moved.

2020-08-08 15:48 UTC, jdpearce commented
@devinshoemaker That sounds like a good approach to me. I've accessed the `projectType` like that in the Angular extension to the move schematic here - https://github.com/nrwl/nx/blob/86108ae510edbbc0afb87c99ddfca91724b3a57c/packages/angular/src/schematics/move/lib/update-module-name.ts#L24

2020-08-13 23:58 UTC, devinshoemaker commented
@jdpearce let me know what you think of my recent changes. I copied most of the e2e test since it all seemed relevant. I was torn between pulling most of that out into a common method, so let me know if you want me to change anything.

2020-08-15 10:55 UTC, catfireparty approved these changes
This all looks good! Let's get it merged 😁

2020-08-15 10:56 UTC, merged

2020-08-17 14:38 UTC, devinshoemaker commented
Woo! Thanks for your patience @jdpearce