fix(nextjs): add missing references config to tsconfig
nrwl/nx pull request #3472
Opened 2020-08-05 13:46 UTC by hloughrey

## Current Behavior
When you generate a new Next application the tsconfig.json is missing the reference to the tsconfig.lib.json file

## Expected Behavior
tsconfig has a reference property which links the tsconfig with tsconfig.spec.json

2020-08-07 17:48 UTC, jaysoo approved these changes

2020-08-07 18:00 UTC, jaysoo commented on packages/next/src/schematics/application/files/tsconfig.json__tmpl__
> +          "path": "./tsconfig.spec.json"
This `tsconfig.spec.json` file doesn't exist though. Where is it coming from?

2020-08-07 18:01 UTC, jaysoo requested changes

2020-08-07 18:01 UTC, jaysoo commented on packages/next/src/schematics/application/files/tsconfig.json__tmpl__
> +  "include": [],
How come we the includes are empty? Should we be creating a `tsconfig.app.json` file if we're going with solution-style config?

2020-08-07 18:01 UTC, jaysoo commented
Can you describe what this PR fixes? i.e. what was broken, and a link to a reproduction repo if possible? Thanks!

2020-08-07 18:42 UTC, FrozenPandaz commented
Next apps actually intentionally do not have a Solution style `tsconfig.json` due to the fact that (last I checked) the Next build is hard coded to look at `tsconfig.json`. Has that changed?

2020-08-14 15:55 UTC, jaysoo commented
Next doesn't use solution-style configs, as seen in their guide. https://nextjs.org/docs/basic-features/typescript

I'm going to close this PR because I'm not certain what the issue is that the PR is trying to address.

@hloughrey If you are experience a bug do you mind opening up an issue to describe what is happening? Thanks! 

https://github.com/nrwl/nx/issues/new/choose

2020-08-14 15:55 UTC, closed without merging