fix(linter): fix performance issues with boundaries lint checks
nrwl/nx pull request #3478
Opened 2020-08-06 11:59 UTC by maxkoretskyi

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2020-09-16 02:06 UTC, vsavkin requested changes
Left some feedback regarding the impl. Nothing major.

1 extra item:
Your unit tests failed because the error message change. You need to update them. But if you look, the error message is weird. It starts with -> and it shoudl not. Maybe add spaces between ->. And I'd make it such that first and the last node in the chain of -> is the same, so it's clear it's a cycle.

2020-09-16 02:06 UTC, vsavkin commented on packages/workspace/src/utils/runtime-lint-utils.spec.ts
> +function transformGraph(graph) {
should be typed and moved to the bottom of the file

2020-09-16 02:06 UTC, vsavkin commented on packages/workspace/src/utils/runtime-lint-utils.spec.ts
> +function getPath(graph, node) {
should be typed and moved to the bottom of the file

2020-09-16 02:06 UTC, vsavkin commented on packages/workspace/src/utils/runtime-lint-utils.spec.ts
> +      nodes: ['A', 'B', 'C', 'E'],
I think you can probably make it a graph with 2 nodes and 1 edge. Based on the assertion, C & E play no role.

2020-09-16 02:06 UTC, vsavkin commented on packages/workspace/src/utils/runtime-lint-utils.spec.ts
> +    A -> B -> C - > E
There is no E in the graph below

2020-09-16 02:06 UTC, vsavkin commented on packages/workspace/src/utils/runtime-lint-utils.spec.ts
> +      nodes: ['A', 'B', 'C'],
Same. I don't think C is needed, unless you think it changes the test case in a meaningful way

2020-09-22 10:39 UTC, maxkoretskyi commented
One thing that probably will need some refactoring in the future is unit tests assertions. Currently, an assertion expects certain order of nodes in the path, e.g. for a graph:

```
    A
 /    \
B      C
  \   /
    D

```

and path from `A` to `D` both `[A, B, D]` and `[A, C, D]` are correct results. If we define edges for `A` as:

```
A: [B, C]
```

the function `getPath` will follow `B` node first and return `[A, B, D]`. If we swap `B`, and `C`, the function will return `[A, C, D]`. Although both are correct, the test assertion only expects one correct result. 

As an idea, we could probably introduce our own operator to Jest to check for multiple results:

```
expect(path).toEqualOneOf(['A', 'B', 'D'], ['A', 'C', 'D']);
```

2020-09-22 12:26 UTC, vsavkin commented on packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.spec.ts
> +      'Circular dependency between "mylibName" and "badcirclelibName" detected. The path is: mylibName -> badcirclelibName -> anotherlibName -> mylibName'
How about one of these two messages:

Change the message to ... detected: myLibName -> badcirclarLib...

or

Change the message to ... detected. Path: myLibName -> badcirclarLib...

You don't normally put a colon after "is".

2020-09-28 17:20 UTC, vsavkin commented
merged here https://github.com/nrwl/nx/pull/3824

2020-09-28 17:20 UTC, closed without merging