feat(angular): update ngrx to 10.0.0
nrwl/nx pull request #3543
Opened 2020-08-16 17:55 UTC by mehrad-rafigh

ISSUES CLOSED: #3542

## Current Behavior
Ngrx is currently at v9

## Expected Behavior
Ngrx is updated to v10

## Related Issue(s)
#3542

Fixes# #3542

2020-08-26 15:22 UTC, brandonroberts requested changes
Will you update the `10.1.0` migration references to `10.2.0`?

2020-08-27 05:05 UTC, mehrad-rafigh commented
Hi @brandonroberts sure will do and update the PR tonight

2020-08-28 16:38 UTC, mehrad-rafigh commented
Hi @brandonroberts 
Did the changes you requested

2020-08-31 16:20 UTC, brandonroberts commented on packages/angular/migrations.json
> +      "description": "Upgrade Ngrx to 10.0.0",
nit: casing

```suggestion
      "description": "Upgrade NgRx libraries to version 10.0.0 ",
```

2020-08-31 16:45 UTC, mehrad-rafigh commented on packages/angular/migrations.json
> +      "description": "Upgrade Ngrx to 10.0.0",
Done!

2020-08-31 18:28 UTC, brandonroberts approved these changes

2020-08-31 18:28 UTC, merged