feat(core): support globs for file paths in `implicitDependencies`
nrwl/nx pull request #3554
Opened 2020-08-18 14:53 UTC by bekos

Fixes #625

2020-08-18 18:57 UTC, jaysoo commented on packages/workspace/src/core/affected-project-graph/locators/workspace-projects.ts
> +  return [...new Set(touched)];
Can we replace `touched` with `touched = new Set()` and return `Array.from(touched)`? It avoids having to convert twice.

2020-08-18 18:58 UTC, jaysoo requested changes

2020-08-18 18:58 UTC, jaysoo commented on packages/workspace/src/core/affected-project-graph/locators/workspace-projects.ts
> +  return [...new Set(touched)];
Can we replace `touched = []` with `touched = new Set()` and return `Array.from(touched)`? It avoids having to convert twice.

2020-08-19 14:33 UTC, jaysoo approved these changes

2020-08-19 14:36 UTC, merged

2020-08-19 14:40 UTC, zakhenry commented
Wohoo! nice one 🎉