fix(nextjs): add project deps to package.json when building nextjs apps
nrwl/nx pull request #3594
Opened 2020-08-24 16:20 UTC by BigAB

The fix makes the nextjs builder add the project dependencies to the dist package.json file

## Current Behavior
The nextjs project get's built with only next, react and react-dom in the dist `package.json` file, and then fails after deployment because of the missing packages.

## Expected Behavior
The application dependencies are added to the dist `package.json`

## Related Issue(s)

Fixes #3062

2020-08-24 16:21 UTC, BigAB commented
Question, is there anyway to separate out the `devDependencies` from a project in the `ProjectGraph`?

2020-09-04 14:48 UTC, jaysoo commented
@BigAB We currently don't but we can extend the finder to store this info. https://github.com/nrwl/nx/blob/master/packages/workspace/src/core/project-graph/build-nodes/npm-packages.ts#L18-L22

2020-09-08 20:51 UTC, FrozenPandaz commented on packages/next/src/builders/build/lib/create-package-json.ts
> +  const projectNpmDependencies = Object.values(graph.nodes).reduce(
I think it's simpler and more performant to keep mapping the above array to get to the npm projects?

```ts
const projectDependencies = graph.dependencies[context.target.project]
  .map(dep => dep.target)
  .map(nodeName => graph.nodes[nodeName])
  .filter(node => node.type === 'npm')
  .reduce(...)
```

2020-09-08 20:51 UTC, FrozenPandaz commented on packages/next/src/builders/build/lib/create-package-json.ts
> +    outPackageJson.peerDependencies = {
Are there any cases where the `peerDependencies` for 1 application should not be the `peerDependencies` for another application?

2020-09-08 20:56 UTC, jaysoo requested changes

2020-09-08 20:56 UTC, jaysoo commented on packages/next/src/builders/build/lib/create-package-json.ts
> +        if (node.data.isDevDependency) {
I think we can ignore dev and peer dependencies. Peer shouldn't be used for apps so we should just ignore.

Dev dependencies should all go into the root `package.json` so I think they can be ignored as well. Unless there's something I am missing.

2020-09-08 21:49 UTC, BigAB commented
After some discussion, we decided to go with the simpler solution of providing all dependencies to the app, even if the app doesn't specifically use those dependencies.

2020-09-09 02:57 UTC, jaysoo commented on packages/next/src/builders/build/lib/create-package-json.ts
>        next: allWorkspaceDeps.next,
We can remove these deps here since they should already be in the root `package.json`. :)

2020-09-11 08:18 UTC, mvdpoel commented
waiting for this one! 👼

2020-09-11 12:45 UTC, jaysoo approved these changes

2020-09-11 12:45 UTC, merged