feat(storybook): storybook config projectType application (#2382)
nrwl/nx pull request #3611
Opened 2020-08-26 09:30 UTC by webberwang

## Current Behavior

Described in #2382 & #3264 

## Expected Behavior

Described in #2382 & #3264 

## Related Issue(s)

Fixes #2382, #3264

2020-08-26 15:11 UTC, mandarini commented
Hi @webberwang !

Thank you very much for this PR!

As you mentioned, `generateStories` only generates `.stories.*` files in `/lib` directories, and not in `/app` directories! You could fix this issue by checking out the `stories` schematic for `angular` and `react` for example. If you take a look at line 49 in [this file](https://github.com/nrwl/nx/blob/master/packages/react/src/schematics/stories/stories.ts), for example, you will notice that it chooses the `lib` directory. In this place, you can check the `projectType`, just like you did in the `configuration.ts` file you changed, and make it choose the `app` or the `lib` folder, accordingly! If this is fixed in all the projects' `stories` schematics, I think we may have a good result to move forward!

Would you like to try this out?

One more suggestion:
If you take a look at `schema.json` in the `storybook-configuration` schematics, where the prompts for the console are written, you can see that the `"generateStories"` prompt says `Automatically generate story files for components declared in this library?`. If we are to change the schematic to accommodate applications as well, maybe that text could be adjusted, too!

Let me know what you think, and also let me know if you need any help or guidance! I'm happy to help!

Thanks again! 😃

2020-08-28 20:54 UTC, webberwang commented
@mandarini Let me know if everything looks good

2020-09-11 14:27 UTC, juristr requested changes
Tested on a react workspace: when I generate a new react workspace and then run `nx g @nrwl/react:storybook-configuration` on the `demoapp` (or some other arbitrary react app)

✅ it properly handles the fact that Cypress is already set up
✅ it properly generates Cypress specs
✅ it properly generates stories
✅ it properly generates story Cypress specs
❌ doesn't generate a `.storybook` folder in the `demoapp`.

That last issue then causes a run failure if I exec `nx run demoapp:storybook`

![image](https://user-images.githubusercontent.com/542458/92937464-a66b5d00-f44b-11ea-8511-18cef8351c73.png)

2020-09-15 16:44 UTC, mandarini commented
@juristr I cannot seem to fix the failing e2e test, any feedback/tips would be useful!

2020-09-15 16:52 UTC, webberwang commented on package.json
> +  "version": "999.1.1",
is this meant to be committed remotely?

2020-09-15 16:58 UTC, webberwang commented on packages/react/src/schematics/storybook-configuration/schema.json
> +      "description": "Library or application name",
I see I'll take a look

2020-09-15 17:03 UTC, mandarini commented on package.json
> +  "version": "999.1.1",
No, thank you, I will fix it!!

2020-09-15 18:12 UTC, webberwang commented
> @juristr I cannot seem to fix the failing e2e test, any feedback/tips would be useful!
> The whole Storybook e2e suite fails with:
> 
> ```
> ENOENT: no such file or directory, stat 'libs/test-ui-lib-react7659083/.storybook'
> ```
> 
> which is strange because the lib `.storybook` directory seems to be generating correctly, and it also passes the unit tests..

Seems that https://github.com/nrwl/nx/pull/3611/commits/0f1ebc4116150e81e97f53c3589dfea606106ee9 introduced the e2e test errors

2020-09-16 00:39 UTC, webberwang commented
> @juristr I cannot seem to fix the failing e2e test, any feedback/tips would be useful!
> The whole Storybook e2e suite fails with:
> 
> ```
> ENOENT: no such file or directory, stat 'libs/test-ui-lib-react7659083/.storybook'
> ```
> 
> which is strange because the lib `.storybook` directory seems to be generating correctly, and it also passes the unit tests..

To test locally, do I just run `yarn e2e`? It seems to get stuck

2020-09-16 23:01 UTC, webberwang reviewed
@mandarini I ended up replacing the edits you made to fix the e2e errors on circleci (force-pushed)

2020-09-16 23:08 UTC, webberwang commented on packages/storybook/src/schematics/configuration/configuration.ts
This fixes Storybook config not being generated in React application

2020-09-17 05:47 UTC, mandarini commented
@webberwang thanks, that's great! Reviewing now! :)

2020-09-17 06:21 UTC, mandarini commented
> @mandarini I ended up replacing the edits you made to fix the e2e errors on circleci (force-pushed)

So, the e2e errors were fixed, but Nx broke. It has the same issues that it had before I made my changes.
1. Does not find `lib` folder in app
2. Cannot render `svg` due to missing webpack configuration
3. Fails when generating app Storybook, due to existing e2e tests

I will bring back the changes I made to fix these errors, and we should find a way to fix the failing e2e tests! If you can help in any way, that would be great. I will push my reverted fixes in a bit!

2020-09-17 06:23 UTC, webberwang commented
> > @mandarini I ended up replacing the edits you made to fix the e2e errors on circleci (force-pushed)
> 
> Hi again @webberwang !
> 
> So, the e2e errors were fixed, but Nx broke. It has the same issues that it had before I made my changes.
> 
> 1. Does not find `lib` folder in app
> 2. Cannot render `svg` due to missing webpack configuration
> 3. Fails when generating app Storybook, due to existing e2e tests
> 
> I will bring back the changes I made to fix these errors, and we should find a way to fix the failing e2e tests! If you can help in any way, that would be great. I will push my reverted fixes in a bit!

I think our issue is some missing or incorrect tests. So we'll need to identify where that is

2020-09-17 06:46 UTC, mandarini commented
Hi @webberwang !

So, for some reason I cannot find the commits I had made to address the issues I mentioned above, and I'm pretty confused! The commits were made on September 1st. 

In any case, here are the commands I am running:

### Create workspace with React
1. `npx create-nx-workspace@YOUR.LOCAL.VERSION worskpace-name`
2. `cd workspace-name`
3. `yarn add --dev <path_to_your_local_nx>/build/packages/storybook`
4. `yarn nx g @nrwl/react:lib ui-test`
5. `yarn nx g @nrwl/react:component test-lib-component --project=ui-test --export`
6. `yarn nx g @nrwl/react:component test-app-component --project=test-app`
7. `yarn nx g @nrwl/react:storybook-configuration --name=test-app` - error if I say yes to e2e tests, success if I say no to e2e tests
8. `yarn nx g @nrwl/react:storybook-configuration --name=ui-test` success
9. `nx run ui-test:storybook` success
10. `nx run test-app:storybook` error 1 - ` Can't resolve '../src/lib'` (see your Nx lib-files config.js, it's always `lib`, does not check project type). After I manually change config.js to reference `src/app` error: cannot render svg because it's not added in webpack

The thing is, I am pretty positive I had fixed and pushed these in a commit on September 1st - which indeed broke the tests.

Angular issues in next comment

2020-09-17 06:58 UTC, webberwang commented
@mandarini I wasn't sure if you saved the branch locally but I made a backup before force pushing. https://github.com/webberwang/nx/tree/storybook-application-type-backup

Let me give those steps a try

2020-09-17 07:01 UTC, mandarini commented
@webberwang oooh!!! Phew!! Ok, sorry, I panicked there for a moment! I've changed three machines in the past month, so "locally" does not exist for me, lol! Thanks! So, this commit https://github.com/webberwang/nx/commit/0f1ebc4116150e81e97f53c3589dfea606106ee9 fixed all the issues I mentioned above!

2020-09-17 07:04 UTC, webberwang commented
> @webberwang oooh!!! Phew!! Ok, sorry, I panicked there for a moment! I've changed three machines in the past month, so "locally" does not exist for me, lol! Thanks! So, this commit [webberwang@0f1ebc4](https://github.com/webberwang/nx/commit/0f1ebc4116150e81e97f53c3589dfea606106ee9) fixed all the issues I mentioned above!

Great thanks I'll try to cherry pick those commits in there, will work on it tomorrow!

2020-09-17 07:11 UTC, mandarini commented
Yes, we should definitely update the e2e tests... For some reason they are breaking, some .storybook folders are not getting generated... Let me know if you need any help there, I'll try my best!

2020-09-17 17:25 UTC, webberwang commented
> Hi @webberwang !
> 
> So, for some reason I cannot find the commits I had made to address the issues I mentioned above, and I'm pretty confused! The commits were made on September 1st.
> 
> In any case, here are the commands I am running:
> 
> ### Create workspace with React
> 1. `npx create-nx-workspace@YOUR.LOCAL.VERSION worskpace-name`
> 2. `cd workspace-name`
> 3. `yarn add --dev <path_to_your_local_nx>/build/packages/storybook`
> 4. `yarn nx g @nrwl/react:lib ui-test`
> 5. `yarn nx g @nrwl/react:component test-lib-component --project=ui-test --export`
> 6. `yarn nx g @nrwl/react:component test-app-component --project=test-app`
> 7. `yarn nx g @nrwl/react:storybook-configuration --name=test-app` - error if I say yes to e2e tests, success if I say no to e2e tests
> 8. `yarn nx g @nrwl/react:storybook-configuration --name=ui-test` success
> 9. `nx run ui-test:storybook` success
> 10. `nx run test-app:storybook` error 1 - ` Can't resolve '../src/lib'` (see your Nx lib-files config.js, it's always `lib`, does not check project type). After I manually change config.js to reference `src/app` error 2 : cannot render svg because it's not added in webpack
> 
> The thing is, I am pretty positive I had fixed and pushed these in a commit on September 1st - which indeed broke the tests.
> 
> Angular issues in next comment

I'm guessing missing this?
4.5. yarn nx g @nrwl/react:application ui-test

2020-09-18 08:38 UTC, webberwang commented
@mandarini Could I have your slack username in nrwl?

2020-09-18 17:07 UTC, webberwang commented
Hey @mandarini,

This https://github.com/nrwl/nx/pull/3611/commits/f784bc0f650e1cd50d7f217ab4a3ca05760deb8e seems to fix the issue. Renaming the template directory for `./lib-files` to `./project-files` without updating the assets glob pattern was stopping `.storybook` from generating.

It likely worked on the local machine from previously generated artifacts.

2020-09-23 09:23 UTC, mandarini commented
Hi @webberwang ! How is it going? Do you need any help?

2020-09-23 10:46 UTC, webberwang commented
@mandarini It should be fixed in the last commit, let me know if I missed something thanks!

2020-09-23 16:50 UTC, mandarini commented
@juristr I think this looks good, works as expected and we could merge it!

2020-09-24 14:33 UTC, merged

2020-09-27 22:13 UTC, ruslanguns commented
Release date?