docs(docs): expand dependency graph docs
nrwl/nx pull request #3714
Opened 2020-09-11 20:01 UTC by isaacplmann

Expands dependency graph docs
- Explain how dependencies are found
- Talk about resolving circular dependencies

2020-09-12 00:16 UTC, brandonroberts requested changes

2020-09-12 00:16 UTC, brandonroberts commented on docs/shared/workspace/structure/dependency-graph.md
> +A circular dependency is when a project transitively depends on itself. This can cause problems in the design of your software and also makes Nx's affected algorithm less effective. The lint rule, `n
One thing to add is that the lint rule produces an error when running the lint checks

2020-09-18 22:06 UTC, FrozenPandaz commented
I wrote a bit on Circular dependencies here that might be useful for this guide.

As per the organization of the content though, I think visualizing dependencies can be a more full-blown guide to how to use the `dep-graph` command and how to use the interface effectively to navigate your project graph. I think we may want to have a separate guide on what the project graph is, how it's constructed, and how it is used.

What do you think?

Also, if we go forward with this path, we need to add a redirect to nx.dev.

2020-09-25 19:54 UTC, isaacplmann commented
Yes, it would be good to have a full guide on the dep-graph.  Maybe coordinating that with the new cytoscape improvements that Philip is working on.

2020-10-09 18:29 UTC, merged