feat(core): update prettier to v2.1.2
nrwl/nx pull request #3756
Opened 2020-09-17 18:30 UTC by mehrad-rafigh

#3611  Current Behavior
prettier is at v2.0.4

## Expected Behavior
prettier is at v2.1.2

## Related Issues

2020-09-24 14:35 UTC, vsavkin commented
Thank you for your PR!

Could you also update prettier in the root package.json in the Nx repo itself?

2020-09-24 14:37 UTC, vsavkin requested changes

2020-09-24 14:37 UTC, vsavkin commented on packages/workspace/src/migrations/update-10-3-0/update-10-3-0.ts
> +const updatePrettierPackage = updatePackagesInPackageJson(
Can you rename it to updatePackages? Other packages can be updated there as well

2020-09-24 15:20 UTC, mehrad-rafigh commented
Hi @vsavkin 

> Could you also update prettier in the root package.json in the Nx repo itself?
I updated prettier to 2.1.2 in the package.json of the repo itself and renamed the rule to `updatePackages`

2020-10-05 09:21 UTC, mehrad-rafigh commented
Hi @vsavkin Any chance this can get merged?

2020-11-06 20:58 UTC, vsavkin commented
Sorry about the delay. Merged it here: https://github.com/nrwl/nx/commit/e3f318cde33b3dc68c0374af77271d66f6a01af4

Thank you!

2020-11-06 20:58 UTC, closed without merging