chore(nx): 4105 upgrade eslint-plugin-react-hooks
nrwl/nx pull request #4107
Opened 2020-11-18 01:39 UTC by therk

## Current Behavior
Getting warning when running npm install and using eslint@7.12.1:
 WARN eslint-plugin-react-hooks@2.5.1 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

## Expected Behavior
No warning

## Related Issue(s)
Fixes #4105

2020-11-20 14:04 UTC, vsavkin commented
@FrozenPandaz probably related to the work @JamesHenry is doing. Could you review?

2020-11-21 09:45 UTC, JamesHenry requested changes
Upgrades to existing "non-core" plugins was particularly not on my radar, but I don't see any problem with updating this.

Naturally though, this PR is incomplete in its current state, a migration needs to be added, as well as updating the other references to this dependency within the codebase.

I'll let Jason comment further.

2020-11-26 22:49 UTC, BigAB commented
Looks like this may need the same change https://github.com/nrwl/nx/blob/ce993edb007941e25be62c01b33fb3ec8f6a3805/packages/react/package.json#L45
as well

The migrations are actually already in, so this seems to have been left out by accident.

2021-01-07 09:55 UTC, bekos commented
@therk are you still interested to land this? can you address the comment of changing also `nx/packages/react/package.json`?

2021-01-09 01:22 UTC, FrozenPandaz commented
I think we've since then upgraded the version of the react-hooks plugin.

Other than the cypress eslint plugin, I don't think we currently use any eslint plugins in this repo so I'm going to try removing the react hooks plugin as well as the other ones.

2021-01-11 16:57 UTC, closed without merging