fix(linter): Respect the "quiet" option
nrwl/nx pull request #4330
Opened 2020-12-17 18:56 UTC by arabull

## Current Behavior
The eslint plugin doesn't properly respect the "quiet" configuration option, displaying warnings even if "quiet" is `true`.

## Expected Behavior
The eslint plugin should respect the "quiet" configuration option, not displaying errors if it is `true`.

## Related Issue(s)
Fixes #3946

2020-12-22 19:51 UTC, JamesHenry requested changes
Extra console log left in, otherwise I think this is good to go

2020-12-22 19:51 UTC, JamesHenry commented on packages/linter/src/builders/eslint/lint.impl.spec.ts
> +      console.log('FPPP', loggerSpy.mock.calls);
```suggestion

```

2020-12-22 20:19 UTC, arabull commented on packages/linter/src/builders/eslint/lint.impl.spec.ts
> +      console.log('FPPP', loggerSpy.mock.calls);
Well, shoot. That was careless of me!

2021-01-02 10:09 UTC, merged

2021-02-12 19:21 UTC, ahaskell35 commented
should this be working with the **run-many** command as well?
current version I am using (11.2.12) with this command:
```
nx run-many --target=lint -all --quiet
``` 
does not pass the --quiet argument to the child runners.

```
nx lint {project} --quiet
```
does work as described above.

2021-03-25 13:44 UTC, james-wilkinson-thd commented
Any idea when this till be pushed to the project? I ran a fresh install and still have this error.

2021-04-13 12:34 UTC, cakeinpanic commented
also interested

2021-04-16 11:56 UTC, JamesHenry commented
I just had a super quick look at a project which is not on the latest (it's on Nx `11.3.2`) and this change is present in my installed Nx, so I would say make sure you are using a version that was released after this PR was merged (11.3.2 or later for sure) and it should be there.

If you are having issues _in spite of_ this change when using the eslint executor please report them as new issues by following the issue templates

2021-04-20 17:52 UTC, cakeinpanic commented
@JamesHenry 
here is what I'm running
```
> nx lint client --quiet
> nx run client:lint --quiet 
'quiet' is not found in schema
```

```
    "@nrwl/cli": "12.0.7",
    "@nrwl/linter": "12.0.7",
    "@nrwl/nx-cloud": "11.2.0",
    "@nrwl/workspace": "12.0.7",
```

maybe I need to update something else?

2021-04-23 16:54 UTC, dandean commented
The `--quiet` flag doesn't appear to work via `nx affected:lint --quiet`.

```
nx --version
11.6.0
```

2021-04-29 16:03 UTC, JamesHenry commented
@ahaskell35 @cakeinpanic @james-wilkinson-thd @dandean https://github.com/nrwl/nx/issues/5498