feat(schematics): Add ability to ng update from Nx 1.x
nrwl/nx pull request #475
Opened 2018-05-11 20:30 UTC by FrozenPandaz

This adds the new Angular CLI Migrations to Nx!

This allows a user to upgrade from a Nx 1.x workspace to a Nx 6.0 Workspace!

Note:
It might be ugly.

2018-05-12 18:01 UTC, jschwarty commented on packages/schematics/src/command-line/nx.ts
> +// import { patchNg } from './patch-ng';
Should this line just get removed since the `patch-ng` file is deleted?

2018-05-13 20:57 UTC, vsavkin commented
I think we need to create a migration performing all the steps you outlined. So when I run: `yarn add @nrwl/schematics@latest AND yarn update`, it does all of them:

1. creates nx.json
2. installs @angular/cli@6.0.1
3. runs ng update
4. runs update @nrwl/schematics

And it should always reference specific version (e.g., 6.0.1, and not "latest").

This migration isn't moving Nx to the latest version of the CLI, but to CLI 6.0.1. All other updates of the CLI or Nx should be handled elsewhere.

2018-05-13 21:01 UTC, vsavkin requested changes

2018-05-13 21:01 UTC, vsavkin commented on packages/schematics/migrations/migrations.json
> +    "migration-01": {
maybe a better name?

2018-05-13 21:01 UTC, vsavkin commented on packages/schematics/migrations/legacy-migrations/20180507-create-nx-json.ts
> +      json.scripts.postinstall = json.scripts.postinstall || 'echo 1';
I deleted the postinstall hook. So you can set it to undefined.

2018-05-13 21:01 UTC, vsavkin commented on packages/schematics/migrations/update-6-0-0/update-6-0-0.ts
> +function updateKarmaConfigs(host: Tree, context: SchematicContext) {
I don't think we can reuse the karma.conf.js. I would just replace it with the default karma.conf.js CLI generates for apps and libs

2018-05-13 21:06 UTC, vsavkin commented
Make sure the following is true:

```
create-nx-workspace proj // created using nx 1.0.3
ng add myapp --routing --directory=dir
ng add mylib --routing --lazy --parentModule=apps/dir/myapp/src/app/app.module.ts --directory=dir
yarn add @nrwl/schematics@next // or install using local package
yarn install
yarn update
```

and

```
ng new proj --collection=@nrwl/schematics // using schematics 6.0.0-alpha * and cli 6.0.1
ng add myapp --routing --directory=dir
ng add mylib --routing --lazy --parentModule=apps/dir/myapp/src/app/app.module.ts --directory=dir
```

Create same projects, in particular:

1. all tslint.json, package.json, and tsconfig.*.json, angular.json are the same (unless there is a good reason for them not to be)
2. all app.module.ts are the same

One of the limitations of CLI 6 is that project names cannot contain "/". This means that when updating, your should replace / with - in project names.

2018-05-15 16:42 UTC, juristr commented
I need to update my nx workspace to ng6 as soon as possible because I need Angular elements in a project 😄.
Thus I started testing the upgrade, first by generating a new nx workspace using NX v1.

Now  I'm following the above steps to see whether I succeed upgrading the simple workspace for then replicating on my more complex setup.

Currently I'm stuck on the `yarn add @angular/cli@latest -D` step:
```
$ ./node_modules/.bin/nx postinstall
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
```

2018-05-15 23:34 UTC, FrozenPandaz commented
@juristr Sorry, that would be the instructions in the future once it is final. For now, you are correct, you would have to `yarn add @nrwl/schematics@next`.

2018-05-16 12:18 UTC, vsavkin commented
merged here https://github.com/nrwl/nx/commit/8de81d6c16935393239b2d7093bc8e72ab251311

2018-05-16 12:18 UTC, closed without merging