feat(linter): convert-tslint-to-eslint generators
nrwl/nx pull request #4943
Opened 2021-03-04 16:47 UTC by JamesHenry

...Not quite ready for review, opening as draft in order to do an initial CI run...

2021-03-05 14:56 UTC, rmartin-sommset commented
Thanks for all of your work on this @JamesHenry! 👍🏼

2021-03-05 15:21 UTC, pburkindine commented
Awesome sauce!

2021-03-05 19:58 UTC, pburkindine commented
This is huge!  Thanks!

2021-03-09 15:06 UTC, s4m0r4m4 commented
@FrozenPandaz can this be merged in? Looking to use this asap now that it's ready.

2021-03-10 00:01 UTC, FrozenPandaz requested changes
Looking good :smiley:

2021-03-11 10:57 UTC, JamesHenry commented on packages/nest/src/generators/convert-tslint-to-eslint/schema.json
> +      "x-prompt": "Would you like to remove TSLint and its related config if there are no TSLint projects remaining after this conversion?"
I'm not sure what kind of "shared state" you are referring to to achieve (2)? How would you change a default based on user behavior? Literally patch the schema in node_modules after the first run of the schematic?

2021-03-11 10:58 UTC, JamesHenry commented on packages/angular/index.ts
> +export {
Yep good catch!

2021-03-11 10:59 UTC, JamesHenry commented on packages/node/index.ts
> +export { addLintingToApplicationGenerator } from './src/schematics/add-linting-to-application/add-linting-to-application';
Cool will remove it, thanks

2021-03-11 10:59 UTC, JamesHenry commented on packages/linter/src/utils/convert-tslint-to-eslint/project-converter.ts
> +      throw new Error(
Will do

2021-03-11 11:03 UTC, JamesHenry commented on packages/angular/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts
> +    cypressInstallTask = await cypressConversionGenerator(host, {
Will do

2021-03-11 16:26 UTC, FrozenPandaz commented on packages/nest/src/generators/convert-tslint-to-eslint/schema.json
> +      "x-prompt": "Would you like to remove TSLint and its related config if there are no TSLint projects remaining after this conversion?"
You can add the setting to `workspace.json` under `generators`.

```json
{
  ...,
  "generators": {
    "@nrwl/angular:convert-tslint-to-eslint": {
      "removeTSLintIfNoMoreTSLintTargets": options.removeTSLintIfNoMoreTSLintTargets
    }
  }
}
```

Here's an example: https://github.com/nrwl/nx/blob/00516ecd682fd3c58782bc498bdd91a380ed421f/packages/web/src/generators/application/application.ts#L163

Afterward, the setting will be used and the user won't be prompted.

2021-03-12 06:49 UTC, JamesHenry commented on packages/nest/src/generators/convert-tslint-to-eslint/schema.json
> +      "x-prompt": "Would you like to remove TSLint and its related config if there are no TSLint projects remaining after this conversion?"
Ahhh that does makes sense :)

2021-03-16 14:50 UTC, guibeg commented
Hi @FrozenPandaz I wonder if there's an ETA for this pull request ? Thanks ! :)

2021-03-17 14:53 UTC, bopm commented
@vsavkin I know that project has grown and requires a lot of hands and tons of time and I really appreciate all your combined work as a team on this project which saved me a lot of my time and nerves. But this way of interacting with end-users on a really serious problem (obviously given us by the Angular team's decision to postpone it almost to the point of no return but still) starting to revive a lot of memories of dealing with the Angular Core team over the years. Can something be done to improve that. How any of us can help with it?

2021-03-17 15:48 UTC, FrozenPandaz commented
Everyone, thank you for being patient. We definitely understand that TSLint users need a migration path to ESLint.

@JamesHenry has done a wonderful job going through numerous iterations and a lot of exploration around how to accurately handle this very complicated conversion.

This is a priority and we are actively working on it. Rest assured, it _is_ coming. We have a few more things to iron out but I don't think it will be much longer.

As excited as you may be, please refrain from asking for concrete ETAs. Please continue being patient and give us some time and space to work out a _good_ solution. The last thing we want is to migrate users to a state which is hard to continue from.

2021-03-19 17:23 UTC, FrozenPandaz approved these changes

2021-03-19 17:41 UTC, merged

2021-03-20 09:26 UTC, jvandemo commented
Great work, @JamesHenry!! 🎉 🏆