docs(nxdev): rewrite getting started section
nrwl/nx pull request #5139
Opened 2021-03-26 18:27 UTC by isaacplmann

Rewrites the getting started section

Getting Started
- Intro to Nx (Getting Started renamed)
- Nx Setup (Folder Structure content is moved into here)
- Nx CLI (CLI Overview and Nx and CLI content is combined here)
- Nx Editor Plugins (Renamed from Nx Console page)

Getting Started/Configuration is moved to Core Concepts.

Resources page is deleted. (Should we move this somewhere else instead?)

2021-03-29 14:10 UTC, vsavkin commented on docs/angular/getting-started/nx-setup.md
> +`/tsconfig.json` sets up the global TypeScript settings and creates aliases for each library to aid when creating TypeScript imports.
this is tsconfig.base.json

2021-03-29 14:10 UTC, vsavkin commented on docs/angular/getting-started/nx-setup.md
> +└── tsconfig.json
tsconfig.base.json

2021-03-29 17:12 UTC, caitlinthefirst requested changes
My edits/suggestions are here: https://docs.google.com/document/d/1c0vD1TzdicGNbIqNr7oX_ObQ2yjsaWNxnuX_Qhb6wYE/edit?usp=sharing

If I can get permission to make in-line edits, I'm happy to do that as well.

2021-04-01 17:20 UTC, isaacplmann commented
Included @brandonroberts 's edits. And all of @caitlinthefirst 's edits, except the comment about referencing Nx Cloud.

2021-04-01 18:13 UTC, brandonroberts approved these changes

2021-04-01 19:12 UTC, merged