fix(linter): convert tslint:disable comments as part of project conversion
nrwl/nx pull request #5188
Opened 2021-03-31 19:14 UTC by JamesHenry

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2021-03-31 21:03 UTC, FrozenPandaz requested changes

2021-03-31 21:03 UTC, FrozenPandaz commented on packages/linter/src/utils/convert-tslint-to-eslint/convert-to-eslint-config.ts
> +  const allSourceFiles = allFilesInDirInTree(tree, root);
We can use [`visitNotIgnoredFiles`](https://github.com/nrwl/nx/blob/01967f89b1b281750ae74c742ac2be12aa881c5e/packages/devkit/src/generators/visit-not-ignored-files.ts#L10)

2021-03-31 22:16 UTC, FrozenPandaz approved these changes

2021-03-31 22:16 UTC, FrozenPandaz commented on packages/linter/src/utils/convert-tslint-to-eslint/convert-to-eslint-config.ts
> +function allFilesInDirInTree(tree: Tree, dir: string): string[] {
This is unused now and also `join` and `normalizePath`.

2021-03-31 22:53 UTC, merged

2021-04-02 16:01 UTC, pburkindine commented
@FrozenPandaz @JamesHenry are there any special instructions so that this migration will be performed?  I ran `nx migrate latest` this morning and it didn't change anything tslint-wise.

2021-04-06 07:31 UTC, JamesHenry commented
@pburkindine It's not a migration in the sense of `nx migrate`. It is not up to Nx to decide when/if users should move from TSLint to ESLint, it needs to be their choice. Therefore, it is a regular Nx generator which is invoked on demand by users, just like when generating apps, libs etc.

You can either trigger it by searching for `convert-tslint-to-eslint` in Nx Console in VSCode, or by accessing it from the specific package collection. E.g. for Angular projects:

```sh
npx nx g @nrwl/angular:convert-tslint-to-eslint
```

And then follow the prompts from there