DO NOT MERGE: feat(web): environment variables interpolated to index.html
nrwl/nx pull request #5521
Opened 2021-05-01 00:43 UTC by ZackDeRose

## Current Behavior

React and Web executors do not support environment variables interpolated into index.html

## Expected Behavior

Environment variables interpolated into index.html supported

## Related Issue(s)

Fixes #

2021-05-14 18:56 UTC, jaysoo requested changes

2021-05-14 18:56 UTC, jaysoo commented on packages/web/src/utils/interpolate-env-variables-to-index.ts
> +        FAST_REFRESH: process.env.FAST_REFRESH !== 'false',
`FAST_REFRESH` isn't used by us so we can remove here. For CRA they use it to pass to the dev server. When we integrate fast refresh we can add it back if needed. :)

2021-05-14 18:56 UTC, jaysoo commented on packages/web/src/utils/web.config.ts
> +        publicUrl: options.publicUrl,
We have `options.publicUrl` available since it's specific to CRA. Our equivalent would be `deployUrl` for assets.

2021-05-19 16:00 UTC, jaysoo requested changes

2021-05-19 16:00 UTC, jaysoo commented on packages/web/src/utils/interpolate-env-variables-to-index.ts
> +    temp = replaceAll(temp, `%${key}%`, value);
```
temp = temp.replace(new RegExp(`%${key}%`, 'g'), value)
```

This would do a global search and replace using regexp. :)

2021-05-19 18:46 UTC, merged

2021-05-26 10:24 UTC, montogeek commented
@ZackDeRose Was this release?