feat(core): add spinner during node module install
nrwl/nx pull request #5593
Opened 2021-05-07 11:11 UTC by juristr

## Current Behavior

Right now there is no spinner, just a static message informing about multiple installs being done. If you're on a slow connection it looks like the window freezed

## Expected Behavior

Adds a spinner during the npm package install

<img width="858" alt="Screenshot 2021-05-07 at 13 02 33" src="https://user-images.githubusercontent.com/542458/117441446-a87fb000-af35-11eb-8d42-15b6309c9419.png">

## Related Issue(s)

Fixes #

2021-05-07 17:37 UTC, FrozenPandaz requested changes
This adds a spinner but it doesn't spin. I think the spinning happens on the next tick but in this case `execSync` blocks the call stack from emptying and going onto the event loop. We need an asynchronous `exec` here. There's an `execAndWait` and that one records logs so maybe use that one instead.

2021-05-07 20:57 UTC, FrozenPandaz requested changes
For some reason, the spinner lingers now if Nx Cloud is added.

<details>
  <summary>After</summary>
    jason@pop-os ~/p/t/n/temp [1]> pnpx create-nx-workspace@latest --pm npm
✔ Install the following package: create-nx-workspace@latest? (Y/n) · true
Packages: +48
++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/jason/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 48, reused 48, downloaded 0, added 48, done

/home/jason/.npm/_npx/68501/pnpm-global/5:
+ create-nx-workspace 12.99.0
✔ Workspace name (e.g., org name)     · new-aweflnanfl
✔ What to create in the new workspace · express
✔ Application name                    · app1
✔ Use Nx Cloud? (It's free and doesn't require registration.) · Yes

>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.

⠼ Creating your workspace
———————————————————————————————————————————————

UPDATE nx.json

>  NX   NOTE  Nx Cloud has been enabled

  Your workspace is currently public. Anybody with code access can view the workspace on nx.app. 
  You can connect the workspace to your Nx Cloud account at https://nx.app/orgs/workspace-setup?accessToken=NjI2MzI2ZDItNGVlZi00MTFkLTg3MmYtOWQ1ODM3ZGIwNzc3fHJlYWQtd3JpdGU=. (You can do this later.)


>  NX   SUCCESS  Nx has successfully created the workspace.

</details>

<details>
  <summary>Before</summary>
  jason@pop-os ~/p/t/n/temp [SIGINT]> pnpx create-nx-workspace@12.0.8 --pm npm
✔ Install the following package: create-nx-workspace@12.0.8? (Y/n) · true
Packages: +48
++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/jason/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 48, reused 47, downloaded 1, added 48, done

/home/jason/.npm/_npx/69238/pnpm-global/5:
+ create-nx-workspace 12.0.8 (12.99.0 is available)
✔ Workspace name (e.g., org name)     · new-alnwelfan
✔ What to create in the new workspace · react
✔ Application name                    · app1
✔ Default stylesheet format           · css
✔ Use Nx Cloud? (It's free and doesn't require registration.) · Yes

>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.


>  NX   SUCCESS  Nx has successfully created the workspace.


———————————————————————————————————————————————

UPDATE nx.json

>  NX   NOTE  Nx Cloud has been enabled

  Your workspace is currently public. Anybody with code access can view the workspace on nx.app. 
  You can connect the workspace to your Nx Cloud account at https://nx.app/orgs/workspace-setup?accessToken=NmQ3MGU3MDItMzA4OS00NGI4LThhY2YtY2M3Zjc0ODI5M2Q3fHJlYWQtd3JpdGU=. (You can do this later.)


———————————————————————————————————————————————


>  NX   NOTE  First time using Nx? Check out this interactive Nx tutorial.

  https://nx.dev/react/tutorial/01-create-application
  
  Prefer watching videos? Check out this free Nx course on Egghead.io.
  https://egghead.io/playlists/scale-react-development-with-nx-4038
  </details>

2021-05-07 20:57 UTC, FrozenPandaz commented on packages/create-nx-workspace/bin/create-nx-workspace.ts
> -      execSync(`${packageManager} install`, {
This was only to get the logs. Now that we use `execAndWait`, we do not need to try it again.

2021-05-21 13:42 UTC, juristr commented
@FrozenPandaz rebased and fixed merge conflicts. should be ready now

![image](https://user-images.githubusercontent.com/542458/119146616-1904f180-ba4b-11eb-91f0-8e081aa2fe3f.png)

2021-05-21 14:33 UTC, FrozenPandaz approved these changes
Beautiful :smile:

2021-05-21 14:33 UTC, merged