feat(nextjs): improve WithNxOptions typing
nrwl/nx pull request #5903
Opened 2021-06-05 12:28 UTC by puku0x

## Current Behavior

`WithNxOptions` does not extend NextOptions

## Expected Behavior

```ts
import type { NextConfig } from 'next/dist/next-server/server/config';
import { WebpackConfigOptions } from '../src/utils/types';

export interface WithNxOptions extends NextConfig {
  nx?: WebpackConfigOptions;
}
```

```js
// eslint-disable-next-line @typescript-eslint/no-var-requires
const withNx = require('@nrwl/next/plugins/with-nx');

/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  nx: {
    // Set this to false if you do not want to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: true,
  }
};

module.exports = withNx(nextConfig)
```
![image](https://user-images.githubusercontent.com/2607019/120891698-d9422a80-c644-11eb-8d59-0d6af12d6f6a.png)

## Related Issue(s)

Fixes #

2021-06-05 12:31 UTC, puku0x commented on packages/next/plugins/with-nx.ts
> -  [key: string]: any;
This line can be removed because `NextConfig` already has it.

2021-06-20 00:53 UTC, puku0x commented
Do I need to update the docs? I think I should wait for #6073 to be merged.

2021-06-23 15:34 UTC, puku0x commented
@kirjai I added docs changes too. Could you check them too, please?

2021-06-25 11:08 UTC, kirjai requested changes
great improvement, thanks a lot! 

also really appreciate you staying on top of the docs changes as well.

---

i only have one small suggestion, regarding the docs specifically.
i see that you've made changes to both the pages in the `docs` directory, as well as `nx-dev/.../latest` directory. In this particular case, just the `docs` should be enough.

for more info, changes added to the `docs` will be deployed to the documentation on next release. whereas changes to `nx-dev` will show up in the docs "as soon as" this PR is merged. 

so, in this case, wee don't want to change docs in `nx-dev`, since this change to `next.config.js` is not going to be available to users until we do a new release.
does that make sense?

---

other than that, it all LGTM 👍

2021-06-25 11:46 UTC, puku0x commented
Ah, I see. That's why the docs have two similar folders.

@kirjai  Thank you for your clarification. I will change this PR.

2021-06-25 12:07 UTC, kirjai approved these changes

2021-06-25 12:08 UTC, merged