feat(schematics): add an option to build affected libs
nrwl/nx pull request #597
Opened 2018-06-21 17:06 UTC by Cammisuli

`nx affected:lib --base=master` will build only libraries that were affected

Changes to the parameter name or the way things are named can be changed. 

closes #595

2018-06-21 21:42 UTC, FrozenPandaz commented
@Cammisuli Thank you for your contribution.

While this achieves the same functionality as the issue is requesting, the API has changed a bit. I think if a user runs `nx affected:build` publishable libs should be included alongside which is not the case right now.

Hint: I think projects should be filtered for those which have a "build" architect target rather than type.

`nx affected:libs` on the other hand should function similarly to `nx affected:apps` and should only display the libs which are affected.

2018-06-21 21:45 UTC, Cammisuli commented
Thanks! I could update the arguments sometime tomorrow.

2018-06-22 14:21 UTC, Cammisuli commented
@FrozenPandaz I updated the command arguments to better match the expected API. 

`nx affected:libs --base=master` will now print out affected libraries
`nx affected:build --base=master` will now build all projects that have the `build` architype, like you suggested.

2018-06-27 16:02 UTC, FrozenPandaz requested changes
This is looking great! :+1: 

E2E Tests are failing and also new E2E Tests for the new commands would be great!

2018-06-27 16:02 UTC, FrozenPandaz commented on packages/schematics/src/command-line/affected.ts
> +  const projectsToBuild = sortedAffectedProjects.filter(p => {
This function is meant (currently anyways) to build all apps it is passed with no opinions.

This logic is better placed within `shared.ts` where the rest of the logic lives. See other comment.

2018-06-27 16:02 UTC, FrozenPandaz commented on packages/schematics/src/command-line/affected-apps.ts
> +export function affectedLibNames(
This function is great. You can also write a similar function called `affectedBuildableNames` and 
```ts
.filter(p => p.architect.build)
```

2018-06-27 16:02 UTC, FrozenPandaz commented on packages/schematics/src/command-line/nx.ts
> +  .command(
:+1:

2018-06-27 16:02 UTC, FrozenPandaz commented on packages/schematics/src/command-line/nx.ts
> +    'Build applications and publishable libraries affected by changes',
:+1:

2018-06-28 18:49 UTC, Cammisuli commented
@FrozenPandaz I've added the e2e tests and did some reshuffling. I noticed that while doing the e2e, I had to add "affected:libs" to the `package.json` template for new apps. 

I was looking at creating a migration for this, but I saw that you created one in #610. Should I wait for that to be merged before trying to create another migration strategy?

2018-06-29 18:13 UTC, FrozenPandaz requested changes
I tested this and see that it's working. Awesome job! Apart from these slight nitpicks, this LGTM. @vsavkin PTAL

2018-06-29 18:13 UTC, FrozenPandaz commented on e2e/schematics/command-line.test.ts
> +      newLib('mylib2');
These tests are great :+1:

2018-06-29 18:13 UTC, FrozenPandaz commented on packages/schematics/src/command-line/affected-apps.ts
> +    .filter(p => p.type == ProjectType.lib)
Slight nitpick:

Use `===`

```ts
.filter(p => p.type === ProjectType.lib)
```

2018-06-29 18:13 UTC, FrozenPandaz commented on packages/schematics/src/command-line/shared.ts
> +  return projects.filter(p => p.type == ProjectType.lib).map(p => p.name);
Slight nitpick:

Use `===`

```ts
.filter(p => p.type === ProjectType.lib)
```

2018-06-29 18:13 UTC, FrozenPandaz commented on packages/schematics/src/collection/ng-new/files/__directory__/package.json
> +    "affected:libs": "./node_modules/.bin/nx affected:libs",
Could you also take care of `ng-add` please? The same line needs to be added here: https://github.com/nrwl/nx/blob/master/packages/schematics/src/collection/ng-add/index.ts#L62

2018-06-29 18:15 UTC, FrozenPandaz commented
I can take care of the migration afterwards if you want

2018-07-03 13:41 UTC, Cammisuli commented
@FrozenPandaz changes implemented. Thank you!

2018-07-05 21:59 UTC, FrozenPandaz approved these changes

2018-07-09 15:27 UTC, merged