chore(core): nx plugin submission @rxap/plugin-localazy
nrwl/nx pull request #6008
Opened 2021-06-14 15:48 UTC by mmuenker

Add the nx plugin [@rxap/plugin-localazy](https://www.npmjs.com/package/@rxap/plugin-localazy) to the list of approved plugins

2021-06-16 18:11 UTC, vsavkin requested changes
Thank you for the PR. 

Could you fix the description?

2021-06-16 18:11 UTC, vsavkin commented on community/approved-plugins.json
> +    "description": "A Nx plugin for localazy.com upload and download tasks.",
A Nx => An Nx

2021-06-21 08:01 UTC, mmuenker commented
@vsavkin the description is fixed

2021-06-22 20:28 UTC, vsavkin commented
Thank you!

2021-06-22 20:28 UTC, merged