feat(schematics): create global karma conf
nrwl/nx pull request #610
Opened 2018-06-27 22:56 UTC by FrozenPandaz

## Current Behavior

Karma Confs are duplicated for each and every project

## Expected Behavior

A Global Karma Conf is created which can be extended by each project.

New projects should have the global karma config for both `ng new` and `ng add`.

Projects which update should have a global config generated but not currently be used.

`yarn affected:test --all` should still work

2018-07-09 15:18 UTC, vsavkin requested changes
overall, it's pretty good. Two main comments:

1. do not pass config into the base config. Treat it as a value.
2. do not typescriptify karma files. it deviates from the cli, makes our schematics more complex. We also do not have an appropriate tsconfig to compile them.

2018-07-09 15:18 UTC, vsavkin commented on packages/schematics/migrations/update-6-1-1/files/karma.conf.ts__tmpl__
> +export const getBaseKarmaConfig = config => {
Do not pass config to getBaseKarmaConfig. It complicates the interaction.

Just remove logLevel from here and set it in the project tsconfig.

```
const baseConfig = getBaseKarmaConfig(config);
  config.set({
    ...baseConfig,
    logLevel: config.LOG_INFO
    coverageIstanbulReporter: {
      ...baseConfig.coverageIstanbulReporter,
      dir: join(__dirname, '../../coverage/apps/projectName')
    }
  });
```

2018-07-09 15:18 UTC, vsavkin commented on packages/schematics/migrations/update-6-1-1/update-6-1-1.ts
> +  context.logger.warn(stripIndents`
change it to "info". It's not really a warning--it's just a piece of information.

A warning is something folks should act upon. They don't have to do anything in this case.

2018-07-09 15:18 UTC, vsavkin commented on packages/schematics/migrations/update-6-1-1/files/karma.conf.ts__tmpl__
> +import { join } from 'path';
Why is a ts file instead of a js file?

There is no tsconfig that we can use to compile. The root one should only be used for editor support.

2018-07-09 15:18 UTC, vsavkin commented on packages/schematics/migrations/update-6-1-1/update-6-1-1.ts
> +function renameExistingKarmaConfs(host: Tree, context: SchematicContext) {
I think we need to stick JS. 

a) This is what the CLI generates
b) It makes our schematics simpler (no need to update angular.json)
c) we don't have an appropriate tsconfig to compile karma files

2018-07-11 22:54 UTC, FrozenPandaz commented
We sort of have to pass in the config to the base config function because it contains the log level enumeration. :confused:

2018-07-15 17:46 UTC, vsavkin commented
@FrozenPandaz can we import the log level from karma/constants?

2018-07-19 15:56 UTC, FrozenPandaz commented
I imported the constants from 'karma' to keep some type safety. Typescript was able to use `@types/karma` when using `require('karma')` but not `require('karma/constants')`. But the constants property was exported and I got the LOG_INFO from there. Looks like:

```js
const { constants } = require('karma');
logLevel: string = constants.LOG_INFO;
```

2018-07-20 16:00 UTC, merged

2018-07-21 09:49 UTC, ubarevicius commented
Hi guys, I see it's merged to 6.1.1, but couldn't figure out how to run update schematics to get this global karma config to show up in my project. Also if I scaffold a new workspace with latest nrwl, it does not appear. Am I missing something? Thx.

2018-07-21 14:58 UTC, ThomasBurleson commented
@ubarevicius  - The `updateKarmaConf()` is only invoked for new  @nrwl/schematics `app` or `lib`:

```console
ng g app <name> [options]
ng g lib <name> [options]
```

2018-07-21 15:00 UTC, vsavkin commented
@ubarevicius 6.1.1 doesn't include global karma config (see here: https://click.pstmrk.it/2s/freedom.chargebee.com%2Fpages%2Fv3%2FAwwmt0I6G2pRaxB1eE03H4SXfRffwDR3%2F/9qnk2wE/m68y/A9XDlOR2HH). 6.2 will.

2018-07-21 15:42 UTC, ubarevicius commented
Ah, thanks a lot, will wait through for 6.2.0 then.