docs(misc): Install Tailwind for Web/React/Next.js Apps Guide
nrwl/nx pull request #6183
Opened 2021-06-29 20:49 UTC by ZackDeRose

## Current Behavior

No Tailwind web/react/next.js guide

## Expected Behavior

Should have a guide for Tailwind with web/react/next.js.

## Related Issue(s)

Fixes #

2021-07-02 17:59 UTC, jaysoo requested changes

2021-07-02 17:59 UTC, jaysoo commented on docs/react/guides/installing-tailwindcss-in-web-react-nextjs-apps.md
> +This guide will serve as a quickstart to installing TailwindCss in your Web/React/Next.js app.
Should be `Tailwind CSS` not `TailwindCss`. Maybe also link out to `https://tailwindcss.com/`?

2021-07-02 17:59 UTC, jaysoo commented on docs/react/guides/installing-tailwindcss-in-web-react-nextjs-apps.md
> +# Installing TailwindCss in Web/React/Next.js Apps
Should name the guide `Using Tailwind CSS in React`. We can mention that it is for both Next.js and React in the details. Not need to mention Web.

2021-07-06 16:39 UTC, brandonroberts requested changes

2021-07-06 16:39 UTC, brandonroberts commented on docs/react/guides/installing-tailwindcss-in-web-react-nextjs-apps.md
> +This guide will serve as a quickstart to installing TailwindCss in your Web/React/Next.js app.
```suggestion
This guide serves as a quickstart to installing TailwindCss in your Web/React/Next.js app.
```

2021-07-06 16:39 UTC, brandonroberts commented on docs/react/guides/installing-tailwindcss-in-web-react-nextjs-apps.md
> +This will install the requisite tailwind dependencies.
```suggestion
This installs the requisite tailwind dependencies.
```

2021-07-06 16:39 UTC, brandonroberts commented on docs/react/guides/installing-tailwindcss-in-web-react-nextjs-apps.md
> +In this step, we'll create a `postcss.config.js` and a `tailwind.config.js` file specific to the application we'd like to introduce tailwind to.
```suggestion
In this step, create a `postcss.config.js` and a `tailwind.config.js` file specific to the application to introduce Tailwind to.
```

2021-07-06 16:39 UTC, brandonroberts commented on docs/react/guides/installing-tailwindcss-in-web-react-nextjs-apps.md
> +The simplest way to do this uses the Tailwind CLI, and can be done via:
Avoid usage of words like `via`, `etc`, `e.g.` as they aren't common across languages
```suggestion
The simplest way to do this uses the Tailwind CLI, and can be done with:
```

2021-07-06 16:39 UTC, brandonroberts commented on docs/react/guides/installing-tailwindcss-in-web-react-nextjs-apps.md
> +This will create the needed files for you with a general boilerplate implementation.
Avoid usage of `will`
```suggestion
This creates the needed files for you with a general boilerplate implementation.
```

2021-07-12 14:44 UTC, merged