fix(core): target project locator should handle tsconfig paths fully
nrwl/nx pull request #6528
Opened 2021-07-28 12:46 UTC by meeroslav

## Current Behaviour
The `TargetProjectLocator` does not match deep imports (e.g. `@nrwl/tao/src/utils/app-root`) with `tsconfig` wildcard paths (e.g. `@nrwl/tao/*`). 

As a consequence, if we have the same package (e.g. `tao`) locally and installed as an npm dependency, we need to run `typescript resolver` matching before `npm` matching to make sure we target the local one. (See https://github.com/nrwl/nx/pull/6030)

This is an expensive operation, causing slowdowns on `linter`. (See https://github.com/nrwl/nx/pull/5576)

## Expected Behaviour
The `TargetProjectLocator` should match deep imports with `tsconfig` wildcard paths.

NPM package resolving should run before typescript matching, to avoid unnecessary slowdown.

The typescript resolver should probably be removed altogether.

## Related Issue(s)

Fixes #

2021-07-28 12:49 UTC, meeroslav commented on packages/workspace/src/core/target-project-locator.ts
> +    const importedProject = this.sortedWorkspaceProjects.find((p) => {
This makes sense if we want to support JS projects or making sure for imports to be validated even if path is missing in `tsconfig`.

2021-07-28 12:49 UTC, meeroslav commented on packages/workspace/src/core/target-project-locator.ts
> +    // if import cannot be matched using tsconfig `paths` the compilation would fail anyway
After fixing path matcher, I don't see the scenario when this might produce result.

2021-07-29 18:07 UTC, FrozenPandaz requested changes
We found an issue where the paths in `tsconfig.base.json` are not normalized.

2021-07-30 15:37 UTC, meeroslav commented
@FrozenPandaz Please have another check

2021-07-30 16:34 UTC, FrozenPandaz approved these changes
Looks good

2021-07-30 16:34 UTC, merged