feat(node): add debug configuration for serve target
nrwl/nx pull request #6536
Opened 2021-07-29 12:25 UTC by juristr

## Current Behavior

Right now debugging a Nest.js app right from VSCode doesn't work out of the box. One has to make sure to set or pass the `--inspect=inspect --port=9229` to the serve target to get it working.

## Expected Behavior

Generating a default `debug` configuration could help set that up, allowing developers to launch "debug mode" with `nx serve nestapp --configuration=debug`

```
        "serve": {
          "executor": "@nrwl/node:execute",
          "options": {
            "buildTarget": "demo:build"
          },
          "configurations": {
            "debug": {
              "inspect": "inspect",
              "port": 9229
            }
          }
        },
```

## Related Issue(s)

Fixes #

2021-07-29 19:48 UTC, FrozenPandaz requested changes
Isn't this the default configuration? :eyes:

2021-07-30 06:38 UTC, juristr commented
@FrozenPandaz it isn't. the `inspect` flag is not the default and also the port is set to `0` atm, due to another issue @Cammisuli mentioned to me.

We could definitely make it the default, though I've seen NestJS for instance also doesn't serve in debug mode by default, but rather has different options to launch in normal / debug mode. Something that's quite common.

2021-07-30 13:17 UTC, Cammisuli commented
Also, the underlying issue of having the port as `9229` was fixed when we moved to the `@nrwl/devkit`. The previous process is properly killed, and clears the port properly. Having this included is nice now 👍🏼

2021-07-30 13:18 UTC, Cammisuli approved these changes

2021-07-30 17:15 UTC, FrozenPandaz approved these changes

2021-07-30 17:32 UTC, merged

2021-08-03 02:58 UTC, srikanthonl commented
Hi, Is this fix available in v11.6.3 of Nx?

2021-08-13 13:28 UTC, juristr commented
@srikanthonl I'm not sure whether it was merged into 11.6.x as well, but you can set this on your own by providing the `port` in your `serve` target in `angular.json` (or `workspace.json`).

Like

```
"serve": {
  "executor": "@nrwl/node:execute",
  "options": {
    "inspect": "inspect",
    "buildTarget": "demo:build",
	"port": 9229
  }
},
```

2021-08-13 14:05 UTC, srikanthonl commented
> @srikanthonl I'm not sure whether it was merged into 11.6.x as well, but you can set this on your own by providing the `port` in your `serve` target in `angular.json` (or `workspace.json`).
> 
> Like
> 
> ```
> "serve": {
>   "executor": "@nrwl/node:execute",
>   "options": {
>     "inspect": "inspect",
>     "buildTarget": "demo:build",
> 	"port": 9229
>   }
> },
> ```

Thanks @juristr