feat(nx): extract subprocess URL
nrwl/nx pull request #6733
Opened 2021-08-16 07:49 UTC by abarajithan

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2021-08-18 21:55 UTC, FrozenPandaz requested changes

2021-08-18 21:55 UTC, FrozenPandaz commented on packages/node/src/executors/execute/execute.impl.ts
> +process.on('exit', () => {
This should be handled here right?

https://github.com/nrwl/nx/pull/6733/files#diff-8b1daad050dbc745646b89f91cd20c497a23f51caf7eeaddb96a517a80b8f01fL45

It's curious that it's calling `process.exit` and not `subProcess.exit` :thinking: 

@AgentEnder @nartc can you take a look please?

2021-08-18 21:55 UTC, FrozenPandaz commented on packages/node/src/executors/execute/execute.impl.ts
> +    const subProcessMessage = await getSubProcessURL();
What is this for?

It seems like you want the first message or all messages to be propagated up in the build event? Can you open a separate issue describing what the expected behavior is here?

2021-08-31 05:04 UTC, closed without merging

2021-08-31 05:05 UTC, abarajithan commented
opening a separate thread