fix(angular): ensure createProjectGraphAsync is called before readCachedProjectGraph
nrwl/nx pull request #6762
Opened 2021-08-18 16:04 UTC by mattlewis92

## Current Behavior

Building an angular lib fails with:

```
Error reading '/home/circleci/repo/node_modules/.cache/nx/nxdeps.json'. Continue the process without the cache.
Error: UnexpectedEndOfString in JSON at position 1638386
    at Object.parseJson (/home/circleci/repo/node_modules/@nrwl/tao/src/utils/json.js:30:15)
    at Object.readJsonFile (/home/circleci/repo/node_modules/@nrwl/tao/src/utils/fileutils.js:20:19)
    at Object.readCache (/home/circleci/repo/node_modules/@nrwl/workspace/src/core/nx-deps/nx-deps-cache.js:38:32)
    at Object.readCachedProjectGraph (/home/circleci/repo/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:24:47)
    at /home/circleci/repo/node_modules/@nrwl/angular/src/executors/package/package.impl.js:34:114
    at Generator.next (<anonymous>)
    at resume (/home/circleci/repo/node_modules/tslib/tslib.js:221:48)
    at /home/circleci/repo/node_modules/tslib/tslib.js:220:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (/home/circleci/repo/node_modules/tslib/tslib.js:220:67)
    at /home/circleci/repo/node_modules/@nrwl/tao/src/commands/run.js:92:35
    at Generator.next (<anonymous>)
    at /home/circleci/repo/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/circleci/repo/node_modules/tslib/tslib.js:113:16)
    at iteratorToProcessStatusCode (/home/circleci/repo/node_modules/@nrwl/tao/src/commands/run.js:78:20)

      [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

      If you are leveraging `readCachedProjectGraph()` directly then you will need to refactor your usage to first ensure that
      the ProjectGraph is created by calling `await createProjectGraphAsync()` somewhere before attempting to read the data.

      If you encounter this error as part of running standard `nx` commands then please open an issue on https://github.com/nrwl/nx
```

## Expected Behavior

The library compiles without issue

## Related Issue(s)

N/A

2021-08-18 21:47 UTC, FrozenPandaz commented
I don't think this is the solution.. How did you run the library's build?

Did you use `nx build`? 

@mattlewis92 Could you open an issue first so we can understand the issue?

@JamesHenry can you take a look at this please?

2021-08-18 21:47 UTC, FrozenPandaz requested changes
This should not be necessary

2021-08-19 09:27 UTC, JamesHenry requested changes
I agree with @FrozenPandaz this should not be necessary.

@mattlewis92 Please can you provide more information about what ran to get this output?

I have just tried creating an Angular workspace on `12.7.1`, creating a publishable lib to make use of the package executor in question, and running `npx nx build` completed successfully and did not reproduce this error.

Based on the error at the top, this looks like you somehow have a malformed cached ProjectGraph, I think the messaging around `createProjectGraphAsync()` is a red herring

2021-08-19 13:51 UTC, mattlewis92 commented
> I agree with @FrozenPandaz this should not be necessary.
> 
> @mattlewis92 Please can you provide more information about what ran to get this output?
> 
> I have just tried creating an Angular workspace on `12.7.1`, creating a publishable lib to make use of the package executor in question, and running `npx nx build` completed successfully and did not reproduce this error.
> 
> Based on the error at the top, this looks like you somehow have a malformed cached ProjectGraph, I think the messaging around `createProjectGraphAsync()` is a red herring

Oh yes, you're totally right, looking at this with fresh eyes today I realised this doesn't make much sense, the `createProjectGraphAsync()` log is indeed a red herring 😄 The issue is that the `.cache/nx/nxdeps.json'` file is somehow getting cut off, I filed an issue here with more details: https://github.com/nrwl/nx/issues/6770

2021-08-19 13:51 UTC, closed without merging