docs(nxdev): master docs is latest
nrwl/nx pull request #6975
Opened 2021-09-09 20:01 UTC by bcabanes

in progress.

2021-09-10 18:03 UTC, jaysoo requested changes

2021-09-10 18:03 UTC, jaysoo commented on nx-dev/nx-dev/lib/api.ts
>    archiveRoot: join(
I believe we can remove `NX_WORKSPACE_ROOT` altogether somehow since everything is under `public`. Maybe in a follow-up PR.

2021-09-13 13:19 UTC, kirjai commented
LGTM, but i'd still want to wait for @jaysoo's feedback as well

2021-09-13 13:37 UTC, jaysoo requested changes

2021-09-13 13:37 UTC, jaysoo commented on nx-dev/nx-dev/project.json
> +        "buildTarget": "nx-dev:build-nextjs",
This target is missing, should be `nx-dev:build-base`, same with the prod  config.

2021-09-13 13:49 UTC, jaysoo approved these changes

2021-09-13 13:55 UTC, merged