fix(storybook): only match exact component name for Storybook
nrwl/nx pull request #7518
Opened 2021-10-26 10:17 UTC by mandarini

ISSUES CLOSED: #7175

## Current Behavior
In Storybook/Angular, when looking for component classes, it matches both of the following:

```
class KaterinasComponent {
   ...
```
and

```
class KaterinasComponentSomeOtherThing {
   ...
```

## Expected Behavior
Only match exact name of component.

## Related Issue(s)
#7175

Fixes #
#7175

2021-10-29 08:15 UTC, juristr requested changes

2021-11-03 15:43 UTC, mandarini commented on packages/angular/src/generators/stories/lib/component-info.ts
> +        console.log(`Found ${classAndComponentRegex} in ${candidateFile}`);
Remove this console.log

2021-11-05 10:46 UTC, mandarini commented on packages/angular/src/generators/stories/lib/component-info.ts
> +        console.log(`Found ${classAndComponentRegex} in ${candidateFile}`);
Done

2021-11-05 10:46 UTC, mandarini commented on packages/angular/src/generators/stories/lib/component-info.ts
> +      const classAndComponentRegex = new RegExp(
We have the component exact names from parsing the NgModule. Let's keep it like that ,maybe, and once we have the script that takes the import paths from index.js we can use that?

2021-11-10 13:06 UTC, juristr approved these changes
LGTM 👍

2021-11-10 13:07 UTC, merged