feat(core): support eslint v8
nrwl/nx pull request #7800
Opened 2021-11-19 00:31 UTC by JamesHenry

Fixes #6866

2021-11-19 15:57 UTC, FrozenPandaz requested changes

2021-11-19 15:57 UTC, FrozenPandaz commented on packages/linter/src/utils/versions.ts
> +export const eslintVersion = '8.1.0';
It is `8.2.0` in `@nrwl/linter`

Let's change this into re-exports from `@nrwl/linter/src/utils/versions`;

```ts
export {
  typescriptESLintVersion,
  tslintVersion,
  eslintVersion,
  eslintConfigPrettierVersion,
} from '@nrwl/linter/src/utils/versions';
```

2021-11-19 17:02 UTC, FrozenPandaz approved these changes

2021-11-19 17:22 UTC, merged

2021-12-17 08:25 UTC, alfaproject commented
Does eslint need to be pinned to 8.2? Can't it just be a peerDependency for `^8`?