Extend the description of generator schema options
nrwl/nx pull request #7927
Opened 2021-11-28 23:24 UTC by pan93412

WIP, will update this later.

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2021-12-01 01:14 UTC, isaacplmann requested changes
I really like all the examples.  I made some grammar corrections.

You also need to either remove the WIP sections or find out what they do.  Maybe @Cammisuli knows what some of those items do?

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +Only accepts that value that matches one of the condition properties. Example:
```suggestion
Only accepts a value that matches one of the condition properties. Example:
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +In this example, `format` accepts the string including in the `enum` property, or/and the string whose minimum length is larger than 1.
```suggestion
In this example, `format` accepts a string listed in the `enum` property, and/or a string whose minimum length is larger than 1.
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +Only accepts that value that matches all of the condition properties.  Example:
```suggestion
Only accepts a value that matches all of the condition properties.  Example:
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +In this example, `a` only accepts the value that can be divided by 5 **and** 3.
```suggestion
In this example, `a` only accepts a value that can be divided by 5 **and** 3.
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +In this example, the providing value of `prefix` should be formed in the `html-selector` schema.
```suggestion
In this example, the value provided for `prefix` should be formatted using the `html-selector` schema.
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +Indicate that if the property should be visible in the configuration UI. Example:
```suggestion
Indicate whether the property should be visible in the configuration UI. Example:
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +According to the source code: the `path` won't be visible in the configuration UI, and will default to the relative path (if available and users do not provide that property).
```suggestion
In this example, the `path` won't be visible in the configuration UI, and will use a default value
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +Indicate that if the property is deprecated. Can be a `boolean` or a `string`. The `boolean` example:
```suggestion
Indicate whether the property is deprecated. Can be a `boolean` or a `string`. The `boolean` example:
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +It indicates that the property `setupFile` is deprecated without a reason. The `string` example:
```suggestion
This indicates that the property `setupFile` is deprecated without a reason. The `string` example:
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +It indicates that users should use the `tsconfig` property rather than specify this property.
```suggestion
This indicates that users should use the `tsconfig` property rather than specify this property.
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +Make sure that the number is greater than or equal the specified number.
```suggestion
Make sure that the number is greater than or equal to the specified number.
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +In this example, `value` **only** accepts the value that is greater than or equal to 5 (`value >= 5`).
```suggestion
In this example, `value` **only** accepts a value that is greater than or equal to 5 (`value >= 5`).
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +In this example, `value` **only** accepts the value that is greater than 4 (`value > 4`).
```suggestion
In this example, `value` **only** accepts a value that is greater than 4 (`value > 4`).
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +Make sure that the number is less than or equal the specified number.
```suggestion
Make sure that the number is less than or equal to the specified number.
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +In this example, `value` **only** accepts the value that is less than or equal to 200 (`value <= 200`).
```suggestion
In this example, `value` **only** accepts a value that is less than or equal to 200 (`value <= 200`).
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +In this example, `value` **only** accepts the value that is less than 201 (`value < 201`).
```suggestion
In this example, `value` **only** accepts a value that is less than 201 (`value < 201`).
```

2021-12-01 01:14 UTC, isaacplmann commented on docs/shared/generators/generator-options.md
> +In this example, `value` requires the value to match the `^\\d+$` pattern, which is a regular expression that matches the string that contains only digits.
```suggestion
In this example, `value` requires the value to match the `^\\d+$` pattern, which is a regular expression that matches a string that contains only digits.
```

2021-12-01 01:29 UTC, Cammisuli commented
`additionalProperties` and `definitions` are defined in the json schema spec. 

`additionalProperties` allows users to include more properties that are not listed in the schema. Usually generators/executors should have this set to false, because the schema is the api to the generator etc. A use case to have this as true is for setting up an object map similar to how projects are defined in the workspace.json

> https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties

`definitions` are just a place to define some complex schemas, and then they can be referenced from properties with `"$ref": "#/definition/complexProperty"`
> https://cswr.github.io/JsonSchema/spec/definitions_references

2021-12-01 16:39 UTC, pan93412 commented
Self-Proofread again, and checked the basic grammar mistakes with LanguageTool.

r? @Cammisuli 
Thanks a lot!

2021-12-02 22:51 UTC, pan93412 commented
r? @isaacplmann

I'm not sure if GitHub will automatically notify the proofreader after requesting the review. Sorry for annoying :(

2021-12-03 18:24 UTC, isaacplmann commented
The content looks good. We need to get CI to pass though.  I think the `nx format:check` command is failing.  Try running `nx format` locally and committing the changes.

2021-12-04 00:12 UTC, pan93412 commented
@isaacplmann CI passed.

2021-12-14 15:33 UTC, merged

2021-12-14 15:33 UTC, isaacplmann commented
Sorry, this slipped off my todo list.  Thanks for your contribution!