fix(schematics): add lib module to the parent module
nrwl/nx pull request #796
Opened 2018-10-04 03:05 UTC by cristianmartinez

fix #216

2018-10-04 21:00 UTC, FrozenPandaz requested changes
This should only happen if the library is not lazy.

2018-10-04 22:17 UTC, cristianmartinez commented on packages/schematics/src/collection/library/index.ts
> +      insertImport(
You're right, I will make the change tomorrow, sorry!

2018-10-10 19:00 UTC, cristianmartinez commented on packages/schematics/src/collection/library/index.ts
> +      insertImport(
@FrozenPandaz I just pushed the change. Please let me know what do you think about it.

2018-10-18 18:03 UTC, vsavkin commented
@FrozenPandaz any update?

2018-10-22 21:48 UTC, FrozenPandaz commented
@cristianmartinez 

My apologies. I looked into the code more and noticed that this `Rule` is already conditionally being called on being **not** lazy. Sorry for my mistake, your original submission was actually perfect :). Would you mind reverting back to it? It should be good after that!

```sh
git reset HEAD~1 --hard
git push -f
```

2018-10-27 16:14 UTC, closed without merging

2018-11-23 22:38 UTC, FrozenPandaz commented
@cristianmartinez Sorry I'm not really sure what happened. Can you try and remake the PR. Sorry for the delay, did not see this PR since it was closed

2018-12-20 15:09 UTC, cristianmartinez commented
No problem @FrozenPandaz, will try to do it soon!