fix(schematics): check type of tsConfig lint entry (ng-add)
nrwl/nx pull request #814
Opened 2018-10-12 22:02 UTC by skydever

## Current Behavior

The [schema](https://github.com/angular/angular-cli/blob/v6.0.0-rc.8/packages/%40angular/cli/lib/config/schema.json#L1519-L1594) of`angular.json` allows the `tsConfig` entry of `tslint` to be `string` or `array of string`. If you define an array the `ng-add` schematic fails.

## Expected Behavior

The `ng-add` schematic should convert the `tsConfig` path entries for the types `array of string` and `string`.

see #624

2018-10-17 21:48 UTC, FrozenPandaz requested changes

2018-10-17 22:06 UTC, skydever commented on packages/schematics/src/collection/ng-add/index.ts
> +        : [e2eLintConfig.options.tsConfig];
changed to remain a `String`

2018-10-17 22:13 UTC, skydever commented on e2e/schematics/ng-add.test.ts
>      });
I will try to add a separate test

2018-10-19 15:35 UTC, vsavkin commented
@FrozenPandaz could you take another look?

2018-10-19 20:13 UTC, FrozenPandaz approved these changes

2018-10-19 20:14 UTC, FrozenPandaz approved these changes
LGTM! Thank you!

2018-10-22 15:15 UTC, merged