chore(core): use extrapolated ts type in create-nx-workspace & create…
nrwl/nx pull request #8452
Opened 2022-01-10 08:43 UTC by linbudu599

…-nx-plugin

Reduce code below:

```typescript
const packageManagerList = ['npm','pnpm','yarn']

export type PackageManager = 'yarn' | 'pnpm' | 'npm';
```

to be:

```typescript
const packageManagerList = ['npm', 'pnpm', 'yarn'] as const;

export type PackageManager = typeof packageManagerList[number];
```

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2022-01-11 20:17 UTC, FrozenPandaz approved these changes

2022-01-11 20:20 UTC, FrozenPandaz requested changes

2022-01-11 20:20 UTC, FrozenPandaz commented on packages/create-nx-plugin/bin/detect-invoked-package-manager.ts
> +const packageManagerList = ['npm', 'pnpm', 'yarn'] as const;
The order of the list has changed. Can you please ensure the order is:
1. `pnpm`
2. `yarn`
3. `npm`

2022-01-11 20:20 UTC, FrozenPandaz commented on packages/create-nx-workspace/bin/package-manager.ts
> +const packageManagerList = ['npm', 'pnpm', 'yarn'] as const;
The order of the list has changed. Can you please ensure the order is:
1. `pnpm`
2. `yarn`
3. `npm`

2022-01-11 20:21 UTC, FrozenPandaz commented
Thank you for your contribution! Some functionality broke because the order of things had changed. Can you restore the order of the package managers please?

2022-01-12 03:26 UTC, linbudu599 commented
> Thank you for your contribution! Some functionality broke because the order of things had changed. Can you restore the order of the package managers please?

Sorry for the mistakes I have made, the fix has been applied now.

2022-01-12 20:10 UTC, FrozenPandaz approved these changes
> Sorry for the mistakes I have made, the fix has been applied now.

No worries, we all make mistakes! :+1:

Changes look good now. :tada:

2022-01-12 20:10 UTC, merged