fix(schematics): dont let bad .nx-results file prevent test run
nrwl/nx pull request #848
Opened 2018-10-24 21:21 UTC by J-Swift

If the `.nx-results` file got into a bad state, then it caused CLI commands to fail in a cryptic way due to yargs failing JSON parsing. This included having an empty `.nx-results file`. Now we treat this case as if there was no results file in the first place.

I maintained the current code structure, but it might make more sense to add the try/catch and `existsSync` check into the `readJsonFile` utility.

2018-11-12 19:39 UTC, vsavkin commented on packages/schematics/src/command-line/workspace-results.ts
> +        // RESULTS_FILE is likely not valid JSON
Could you print the error message here?

2018-11-12 19:40 UTC, vsavkin requested changes
Do you know what operation results in the file being corrupted?

2018-11-12 20:07 UTC, J-Swift commented
@vsavkin unfortunately no. However, two people on our team ran into it separately. I ran into something similar months ago that may have been the same issue but I didn't look very far into it.

2018-11-18 19:56 UTC, vsavkin commented on packages/schematics/src/command-line/workspace-results.ts
> +        console.error('error parsing previous results');
Sorry, I should have mentioned it in the original comment. Could you use the convention we use?

```
Error: .nx-results file is corrupted.
```

2018-11-18 19:57 UTC, vsavkin commented
@J-Swift One small comment--other than that it looks good. Could you please squash the commits and I'll merge it?

2018-12-02 17:36 UTC, J-Swift commented
@vsavkin - updated, squashed,  and rebased

2018-12-03 16:51 UTC, vsavkin commented
@J-Swift thank you!

2018-12-03 16:51 UTC, merged