fix(web): optimized rollup output logic
nrwl/nx pull request #8526
Opened 2022-01-14 04:08 UTC by xiejay97

ISSUES CLOSED: #8475
ISSUES CLOSED: #8505

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2022-01-27 13:59 UTC, jaysoo requested changes

2022-01-27 13:59 UTC, jaysoo commented on packages/web/src/executors/rollup/rollup.impl.ts
> +  if (!('main' in packageJson)) {
Simple as `!packageJson.main`?

2022-01-27 13:59 UTC, jaysoo commented on packages/web/src/executors/rollup/rollup.impl.ts
> +    for (const format of options.format) {
This is simpler, and prefers `cjs` over `umd` which is more suitable.

```

  if (options.format.includes('cjs')) {
    packageJson.main = entryFileTmpl.replace('<%= extension %>', 'cjs');
  } else if (options.format.includes('umd')) {
    packageJson.main = entryFileTmpl.replace('<%= extension %>', 'umd');
  }
```

2022-04-13 14:25 UTC, AgentEnder commented
@xiejay97 Do you care to run `nx format` and re-push your branch? If we can get CI green on this, it would be good to get merged.

2022-04-22 09:10 UTC, xiejay97 commented
> @xiejay97 Do you care to run `nx format` and re-push your branch? If we can get CI green on this, it would be good to get merged.

OK now

2022-04-22 09:35 UTC, AndyClausen commented
One thing to note here:
If I have a package A with tests that depend on package B, I need to set the `main` field in package B to `index.ts` or the tests in pakcage A will fail.
After this PR is merged, if I set the `main` field, it won't be overwritten when running rollup and I will be "unknowingly" publishing with the incorrect `main` field.
Maybe this is how it should work though, and the problem lies with Jest. I thought it was worth mentioning nonetheless.

2022-05-30 17:43 UTC, jaysoo commented
This is fixed in latest Nx version (14.1.9)

2022-05-30 17:43 UTC, closed without merging