fix(schematics): added skipModulePrefix
nrwl/nx pull request #861
Opened 2018-10-30 09:48 UTC by listepo-alterpost

2018-11-12 19:44 UTC, vsavkin requested changes
It looks good. One thing I am thinking is to change the name of the property from skipModulePrefix to simpleModuleName. The word "skip" implies an _action_ whereas "simple" implies a _choice_.

2018-11-13 00:02 UTC, listepo-alterpost commented
@vsavkin done

2018-11-14 18:15 UTC, FrozenPandaz requested changes

2018-11-14 18:15 UTC, FrozenPandaz commented on packages/schematics/src/collection/library/schema.json
> +      "description": "Skip module prefix when using --directory",
One last remnant.
```suggestion
      "description": "Keep the module name simple (when using --directory)",
```

2018-11-15 11:59 UTC, listepo-alterpost commented
@FrozenPandaz done!

2018-11-16 17:01 UTC, FrozenPandaz approved these changes
LGTM! Thank you for your PR!

2018-11-18 19:48 UTC, merged