docs(storybook): guide for setting up storybook composition
nrwl/nx pull request #8667
Opened 2022-01-24 13:14 UTC by mandarini

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2022-01-28 19:01 UTC, vsavkin commented on docs/shared/guides/storybook/storybook-composition-setup.md
> +command with the parallel flag set to true `--parallel=true`, because you want to run all your Storybooks in parallel. Since the default amount of parallel activities that you can run
Can you change it to `--parallel=3`? We are deprecating --parallel=BOOLEAN and only keeping --parallel=NUMBER

2022-02-01 08:51 UTC, juristr requested changes

2022-02-01 08:51 UTC, juristr commented on docs/map.json
> +            "name": "USetting up Storybook Composition with Nx",
there's a typo in the `name` => "USetting...`

2022-02-01 08:53 UTC, juristr commented on docs/shared/guides/storybook/storybook-composition-setup.md
> +```
Can you add the language flavor to the code embeds? That way it gets syntax highlighted :)

2022-02-01 09:40 UTC, mandarini commented
Updated PR with changes

2022-02-01 13:05 UTC, juristr approved these changes
LGTM

2022-02-01 13:05 UTC, merged