Dark mode changes
nrwl/nx pull request #8712
Opened 2022-01-26 20:25 UTC by Lcarv20

## Current Behavior

Currently there is no possibility to use different themes.

## Expected Behavior

Users can toggle between dark and light themes, or select to dynamically follow the system setting.

## Related Issue(s)

Fixes #

2022-02-01 04:22 UTC, philipjfulcher commented
Please update your PR title to match our commit guidelines, something like "feat(dep-graph): add dark mode"

2022-02-01 04:43 UTC, philipjfulcher commented
This is a good start and takes care of changing our React components to dark mode. I'll work with our designer to determine some colors that fit the Nrwl color palette. 

One more thing we need to figure out is passing the dark mode setting to the graph to be able to alter the colors there. The graph is powered by a library called [Cytoscape](https://js.cytoscape.org/) which uses a canvas to render the graph. So it won't accept our CSS rules to change colors, but it does accept a very similar syntax for styles. You can find the existing styles for nodes and edges in `dep-graph/client/src/app/styles-graph`. 

The style rules accept a function as a setter. So for example, right now the background color on `allNodes` is set using `    backgroundColor: NrwlPalette.white`. This could be changed to a function like `    backgroundColor: () => isDarkMode ? NrwlDarkPalette.white : NrwlPalette.white` so based on the current theme, it can switch between the color from two different palettes. You can probably use one of the existing function you have for selecting the correct class in React here. 

Let me know if that is a good enough starting off point.

2022-02-03 20:39 UTC, Lcarv20 commented
Hey @philipjfulcher, thanks for the hint. I did something like you mention in the previous comment, however the <Tippy /> instances do not update dynamically, and the nodes, edges and arrows will only update after you hover. I didn't quite yet figure a way to dynamically update those. Also, I added my own colour scheme but you can always update them easily, or if you have a pallet in mind just tell me and I can make those changes.

2022-02-14 16:49 UTC, philipjfulcher commented
@Lcarv20 - I pushed up a commit that should refresh the colors on the graph immediately. I also rebased on master to get the latest changes in and ran a format, which I'm hoping should clean-up the e2e failures.

2022-03-02 09:44 UTC, johannesschobel requested changes
found a few typos that should be corrected

2022-03-02 09:44 UTC, johannesschobel commented on dep-graph/client/src/app/dark-theme-styles.tsx
> +// Styling presets for dark mode, defined by agregating styling classes
```suggestion
// Styling presets for dark mode, defined by aggregating styling classes
```

2022-03-31 03:52 UTC, merged