misc(docs): Update getting started docs
nrwl/nx pull request #8730
Opened 2022-01-27 20:25 UTC by barbados-clemens

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2022-01-28 14:47 UTC, isaacplmann reviewed
More than half of the words in the glossary aren't actually linked from anywhere.  Also, almost all the words in the glossary have a full page dedicated to explaining them.  Would it be better to link directly to that full page whenever the word is mentioned?

2022-01-28 14:47 UTC, isaacplmann commented on docs/shared/getting-started/nx-setup.md
> +When creating a workspace, you will have to choose a preset, which will preconfigure a few things for you. If you're unsure se
looks like you didn't finish your sentence here

2022-01-28 14:47 UTC, isaacplmann commented on docs/shared/getting-started/nx-setup.md
> +npx create-nx-workspace --preset=@nrwl/remix
is this released?

2022-01-28 14:47 UTC, isaacplmann commented on docs/shared/getting-started/nx-setup.md
> +Learn more about migrating Create React Apps to Nx via our [Create React App migration guide](/migration/migration-cra)
```suggestion
Learn more about migrating Create React App projects to Nx via our [Create React App migration guide](/migration/migration-cra)
```

2022-01-28 14:47 UTC, isaacplmann commented on docs/shared/glossary.md
> +## Dependency Graph (dep-graph)
```suggestion
## Project Graph
```

2022-01-28 14:47 UTC, isaacplmann commented on docs/shared/glossary.md
> +## Dependency Graph (dep-graph)
We've renamed it elsewhere in the docs

2022-01-28 14:47 UTC, isaacplmann commented on docs/shared/glossary.md
> +A feature of Nx that allows the execution of a task graph across multiple machines instead of locally.
```suggestion
Nx Cloud coordinates executing tasks across multiple machines, balancing out the work load according to the time each task takes to complete.
```

2022-01-28 14:47 UTC, isaacplmann commented on docs/shared/glossary.md
> +Generators provide a way to automate many tasks you regularly perform as part of your development workflow.
```suggestion
Generators automate adding, modifying or deleting code.
```

2022-01-28 14:47 UTC, isaacplmann commented on docs/shared/glossary.md
> +a generic mechanism for expressing constraints
```suggestion
A generic mechanism for expressing constraints between projects.
```

2022-01-28 14:47 UTC, isaacplmann commented on docs/shared/glossary.md
> +streamlining integrations It's important to note that plugins are not required to use Nx. Learn more
```suggestion
streamlining integrations. It's important to note that plugins are not required to use Nx. Learn more
```

2022-01-28 16:49 UTC, barbados-clemens commented
> More than half of the words in the glossary aren't actually linked from anywhere. Also, almost all the words in the glossary have a full page dedicated to explaining them. Would it be better to link directly to that full-page whenever the word is mentioned?

I'm conflicted as I like the idea of having all these terms quickly accessible on a single page with simple straight forward definitions, but the full page for some terms is very handy for a deep dive, which we link to I'm not too sure about (assuming we keep both)

I feel like within a guide linking to the full page as the idea is "if you wanna go deeper you can read these full pages" but from a place that just mentions the term without explaining a link to the glossary. 
BUT this (potentially?) creates a fragmented experience when someone is wanting to learn about a term, as it maybe is a full guide/deep dive or a simple definition. 

I think _ideally_ we could have a tooltip/"what's this" type UI that will display the quick definitions from the glossary, and if a full-page guide exists have a link out to "go deeper" on the topic. but that might require some extra leg work that's probably out of the scope of this PR. (assuming we want to do that)

2022-01-28 17:10 UTC, isaacplmann commented
I'm conflicted too.  Let's open up the question to more people and see what others think.  I'll link this PR in the nx channel.

2022-03-02 09:52 UTC, johannesschobel requested changes
a lot of duplicate text.. can't we just somehow "link" those texts? i.e., move the texts to a library and include them in the different docs?

2022-03-16 15:14 UTC, closed without merging