docs(core): updated jenkinsfile base value for pr requests
nrwl/nx pull request #8852
Opened 2022-02-04 17:13 UTC by echonax

While our team was trying to migrate to Nx, we found out about [this issue](https://github.com/nrwl/nx/issues/2170)
The documentation doesn't mention about this behaviour but in our case setting the --base to origin/{current_branch} fixed it. I've set the env variable accordingly in the md file.
(Also fixed small typo)

Fixes #
https://github.com/nrwl/nx/issues/2170

2022-02-10 17:41 UTC, FrozenPandaz requested changes

2022-02-10 19:43 UTC, echonax commented on docs/shared/monorepo-ci-jenkins.md
> +                        sh "npx nx affected --base origin/${CHANGE_TARGET} --target=build --parallel --max-parallel=3"
`$CHANGE_TARGET` equals to the current branch name in the Jenkins pipeline. I can/should make it `${env.CHANGE_TARGET}` to be more verbose. 

The `origin/main` works if the pipeline runs for the main branch which is already covered in the docs but in the case of a PR request targeted to the `main` branch, you'll get the error mentioned in the ticket. 
[This answer](https://github.com/nrwl/nx/issues/2170#issuecomment-601595383) in that thread has the same approach for github CI.

2022-02-11 20:13 UTC, FrozenPandaz commented on docs/shared/monorepo-ci-jenkins.md
> +                        sh "npx nx affected --base origin/${CHANGE_TARGET} --target=build --parallel --max-parallel=3"
Awesome! Thanks for explaining that. It makes perfect sense.

2022-02-11 20:13 UTC, FrozenPandaz approved these changes

2022-02-11 20:24 UTC, merged