feat(schematics): Add browser option to cypress builder
nrwl/nx pull request #908
Opened 2018-11-16 00:05 UTC by thillmann

Cypress supports running the tests in a user-specified browser. This option was not exposed through
the Cypress builder before. This change will add this option in.

re #906

2018-11-16 16:59 UTC, FrozenPandaz requested changes
Awesome work! Thank you for your PR!

2018-11-16 16:59 UTC, FrozenPandaz commented on packages/builders/src/cypress/schema.json
> +        "Use this to specify the browser to run tests in. The browser needs to be installed on your system."
nitpick:
```suggestion
        "The browser to run tests in."
```

2018-11-16 16:59 UTC, FrozenPandaz commented on packages/builders/src/cypress/schema.json
> +      "type": "string",
Please add an `enum` to list the allowed types of browsers. (Users unfamiliar with Cypress will expect other browsers such as `firefox` and `safari` to be available which is not yet the case.

https://docs.cypress.io/guides/guides/launching-browsers.html#Browsers

```json
"enum": [
  "electron",
  "chrome",
  "chromium",
  "canary"
]
```

2018-11-18 03:58 UTC, thillmann commented
Thanks for the feedback! I've updated the PR accordingly.

Btw, should I change the commit name to feat(builders)? When I created this I looked at your contributing guidelines and it said the scope must be either nx, schematics or bazel. I've seen you guys using builders as scope though...

2018-11-18 19:40 UTC, vsavkin commented
@FrozenPandaz could you take a look and lgtm if you think it looks good?

2018-11-19 15:31 UTC, FrozenPandaz approved these changes

2018-11-19 15:39 UTC, FrozenPandaz commented
LGTM! 👍

2018-11-19 22:29 UTC, merged