fix(misc): support workspaces using a root tsconfig.json instead of tsconfig.base.json
nrwl/nx pull request #9195
Opened 2022-03-04 15:14 UTC by leosvelperez

## Current Behavior

There are several within Nx where it doesn't fall back to locate a root `tsconfig.json` if the expected `tsconfig.base.json` doesn't exist.

Most of the time this should be fine since Nx workspaces by default use `tsconfig.base.json`, but there are still some scenarios where a `tsconfig.json` might still be used (e.g. devs decide to use it, or Angular CLI workspaces migrated using a package like `make-angular-cli-faster` or Angular CLI workspaces migrated using the `--preserve-angular-cli-layout` flag).

## Expected Behavior

The functionality within Nx should look for a root `tsconfig.json` if the `tsconfig.base.json` file doesn't exist. By default, `tsconfig.base.json` should still be used for everything and it's still the recommended file to use, but a fallback should be in place.

## Related Issue(s)

Fixes #

2022-03-07 17:08 UTC, FrozenPandaz requested changes

2022-03-07 17:59 UTC, leosvelperez commented on packages/workspace/src/utilities/typescript.ts
> +  throwIfNotFound: boolean = true
There are actually a couple of places where it's used. In those places it was handled whether the root config exists or not:

https://github.com/nrwl/nx/pull/9195/files#diff-80f4f7ac090c289ee9a0f0d9c3724d3ef2f8140d574c10bde6f27062fdaf0d5dR38

https://github.com/nrwl/nx/pull/9195/files#diff-92965674c07c12510a38d3ece39b524b0682dac8b56e5bcd2469bb19597177afR22

2022-03-07 18:41 UTC, leosvelperez commented on packages/workspace/src/utilities/typescript.ts
> +  throwIfNotFound: boolean = true
Don't mind the above. I'll change this to not throw an error.

2022-03-09 16:30 UTC, FrozenPandaz approved these changes

2022-03-09 16:30 UTC, merged