docs(angular): update angular cli migration docs to reflect the generator relocation to @nrwl/angular
nrwl/nx pull request #9288
Opened 2022-03-11 12:33 UTC by leosvelperez

## Current Behavior

## Expected Behavior

## Related Issue(s)

Fixes #

2022-03-15 11:31 UTC, Coly010 approved these changes
LGTM! 🎉

2022-03-18 21:21 UTC, FrozenPandaz requested changes

2022-03-18 21:21 UTC, FrozenPandaz commented on docs/shared/migration/migration-angular.md
> +This installs the `@nrwl/angular` (or `nrwl/workspace`) package into your workspace and runs a generator (or schematic) to make following changes:
```suggestion
This installs the `@nrwl/angular` (or `@nrwl/workspace`) package into your workspace and runs a generator (or schematic) to make following changes:
```

2022-03-18 21:21 UTC, FrozenPandaz commented on docs/shared/migration/migration-angular.md
> +- Installs the `nx` and `nrwl/workspace` packages.
```suggestion
- Installs the `nx` and `@nrwl/workspace` packages.
```

2022-03-18 21:22 UTC, FrozenPandaz approved these changes

2022-03-18 21:23 UTC, merged