wip feat(schematics): add support for .nxignore
nrwl/nx pull request #943
Opened 2018-12-07 06:09 UTC by FrozenPandaz

## Current Behavior

There is no way to ignore files for affected

## Expected Behavior

`.nxignore` is used to ignore files while performing affected commands and calculating the dep-graph.

`.gitignore` will also be used to ignore files.

Example scenarios:
* Ignore `node_modules` within your projects
* Ignore a readme.md to not trigger builds during editing of documentation

2018-12-10 16:12 UTC, JamesHenry approved these changes

2018-12-13 00:47 UTC, vsavkin requested changes

2018-12-13 00:47 UTC, vsavkin commented on e2e/schematics/ng-add.test.ts
> +import { NxJson } from '../../packages/schematics/src/command-line/shared';
remove the import

2018-12-13 00:47 UTC, vsavkin commented on e2e/schematics/ng-add.test.ts
> +    const nxJson = readJson<NxJson>('nx.json');
remove the type.

2018-12-13 00:47 UTC, vsavkin commented on e2e/schematics/ng-add.test.ts
> +    const nxJson = readJson<NxJson>('nx.json');
or import it from node_modules (when we run e2e tests we first build nx and copy it into node modules), so you should be able to import it

2018-12-13 00:47 UTC, vsavkin commented on packages/schematics/migrations/update-6-0-0/update-6-0-0.ts
> +import { NxJson } from '../..//src/command-line/shared';
//src => /src

2018-12-13 00:47 UTC, vsavkin commented on packages/schematics/src/command-line/shared.ts
> +  .add(readFileIfExisting(appRoot.resolve('.gitignore')))
We don't use `resolve` anywhere else here. For instance, this is how we read nx.json:
```
  const config = readJsonFile(`${appRoot.path}/nx.json`);
```

Could you make it consistent?

2018-12-13 00:47 UTC, vsavkin commented on packages/schematics/src/command-line/shared.ts
> +      files: ig.filter(files)
In this case, the user gave us the file. Do you think we should ignore it?

2018-12-13 00:47 UTC, vsavkin commented on packages/schematics/src/command-line/shared.ts
>    // Ignore files in nested node_modules directories
remove the comment

2018-12-13 00:47 UTC, vsavkin commented on packages/schematics/src/command-line/shared.ts
> +        return res;
replace `return res` with `return`

2018-12-13 00:47 UTC, vsavkin commented on packages/schematics/src/utils/fileutils.ts
> +  return fs.existsSync(path) ? JSON.parse(fs.readFileSync(path, 'utf-8')) : {};
This seem strange. Why do we default to `{}`?

2018-12-18 20:45 UTC, merged