fix(schematics): snapshot not being generated when ran against fixture
nrwl/nx pull request #959
Opened 2018-12-19 06:44 UTC by BuckyMaler

fix #958

## Description

I tested this change in an [example app](https://github.com/BuckyMaler/nx-jest-example). You'll find the relevant changes in `jest.config.js` and `apps/example-app/src/app/app.component.spec.ts`. The motivation is to be able to generate a snapshot against an Angular fixture. This makes it easier to generate a snapshot of an entire template, which I think is common. Also, [documentation](https://github.com/thymikee/jest-preset-angular#snapshot-testing) is written such that this should be possible. More granular snapshots are still possible using `querySelector`. The `snapshotSerializers` added are those used by [jest-preset-angular](https://github.com/thymikee/jest-preset-angular#exposed-configuration).

## Issue

#958

2019-01-07 21:03 UTC, BuckyMaler commented
@FrozenPandaz is there anything in particular keeping this from being merged or have you not had time to review it just yet?

2019-01-18 03:09 UTC, FrozenPandaz requested changes
Sorry for the long delay. Thank you for the contribution!

I would like there to be an option in the `jest-project` schematic so that projects which do not require Angular Serializers do not need to include them.

What do you think?

2019-01-18 20:30 UTC, BuckyMaler commented
I think I can handle that. Before I make the changes though, I'd like to ask what your hesitation is with including the serializers at all times in the root config? My experience is the default serializers don't work well with Angular templates. According to the [docs](https://jestjs.io/docs/en/configuration.html#snapshotserializers-array-string) `jest` includes React serializers by default. In addition to that, `jest-preset-angular` includes the serializers when extending its config. Perhaps your concerned with including the serializers in the root config because not all projects in an Nx Workspace are necessarily Angular projects? In which case I'd recommend that the serializers be included for all Angular projects. Making changes to the `application` schematic so that the serializers are included if `--unit-test-runner` is `jest`. Also, changing the `jest-project` schematic so that the serializers are included if `--skip-setup-file` is `false`.

Let me know what you decide. I look forward to contributing.

2019-01-27 22:13 UTC, BuckyMaler commented
I updated the PR to include an option, `--skip-serializers`.

2019-01-30 21:36 UTC, FrozenPandaz requested changes
Awesome, let's use this option in the following places:

* `ng g lib --no-module`
* `ng g node-app`

2019-01-31 16:30 UTC, FrozenPandaz approved these changes
This looks good! The failing tests are unrelated to your changes.

2019-01-31 19:20 UTC, merged