feat(schematics): --framework nest for node-app
nrwl/nx pull request #974
Opened 2019-01-03 05:42 UTC by FrozenPandaz

## Current Behavior

NestJS is a great choice for enterprises using Angular who are also looking to build backends.

Creating Nest Applications with the nest schematics [has some friction](https://github.com/nestjs/schematics/issues/105#issuecomment-446655741)

## Expected Behavior

A NestJS Application can be created via

```sh
ng g node-app nest-app --framework nestjs
ng g @nestjs/schematics:controller cats --source-root apps/nest-app/src --path app
```

## Notes

This is based off of the work done by @FallenRiteMonk in https://github.com/nrwl/nx/pull/807

@FallenRiteMonk 
Thank you so much for your work. Sorry it was not accepted as is at the time.

2019-01-03 19:15 UTC, FrozenPandaz commented
cc @kamilmysliwiec

2019-01-03 19:24 UTC, vsavkin requested changes
Looks good. A few minor comments.

2019-01-04 10:35 UTC, kamilmysliwiec commented on packages/schematics/src/collection/node-application/files/nestjs/main.ts__tmpl__
> +})();
Why not
```typescript
import { NestFactory } from '@nestjs/core';

import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000, () => console.log('Listening at http://localhost:3333'));
}
bootstrap();
```

2019-01-04 10:42 UTC, kamilmysliwiec commented
@nestjs app initial structure looks good @FrozenPandaz, looking forward to see this feature in Nx :)

2019-01-04 16:47 UTC, FrozenPandaz commented on packages/schematics/src/collection/node-application/files/nestjs/main.ts__tmpl__
> +})();
Looks good, done!

2019-01-04 18:11 UTC, merged